### PR TITLE
[python] Use correct C++ compiler for linking.

### LINKED ISSUE #2952: Python: setup.py: linker and their flags need to be set by Cmake
While there has been some effort to set these, there still seem to be issues.

I guess instead of setting environment variables inside of setup.py, we need to add a custom class deriving from build_ext that sets everything correctly. See e.g. https://shwina.github.io/custom-compiler-linker-extensions/

The problem can be reproduced on Debian using a non-default compiler:
```cmake
set(CMAKE_CXX_COMPILER "/usr/bin/g++-9" CACHE STRING "compiler")
set(CMAKE_C_COMPILER "/usr/bin/gcc-9" CACHE STRING "compiler")
set(OPM_ENABLE_PYTHON ON CACHE STRING "Enable python")
set(OPM_ENABLE_EMBEDDED_PYTHON ON   CACHE STRING "Enable PYACTION")
```

Currently that compiler will be used for compilation
```
ccache /usr/bin/g++-9 -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -UNDEBUG -I/usr/include -I/usr/include/python3.9 -I/home/mblatt/src/dune/opm/opm-common/opm-gcc9 -I/home/mblatt/src/dune/opm/opm-common/opm-gcc9/include -I/home/mblatt/src/dune/opm/opm-common -I/usr/include -I/usr/include/cjson -I/usr/include/python3.9 -c cxx/well.cpp -o build/temp.linux-x86_64-3.9/cxx/well.o -std=c++17 -fopenmp -DFMT_LOCALE -DFMT_SHARED
```
But for linking the default linker is still used:
```
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-z,relro -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.9/cxx/builtin_pybind11.o build/temp.linux-x86_64-3.9/cxx/connection.o build/temp.linux-x86_64-3.9/cxx/converters.o build/temp.linux-x86_64-3.9/cxx/deck.o build/temp.linux-x86_64-3.9/cxx/deck_keyword.o build/temp.linux-x86_64-3.9/cxx/eclipse_config.o build/temp.linux-x86_64-3.9/cxx/eclipse_grid.o build/temp.linux-x86_64-3.9/cxx/eclipse_io.o build/temp.linux-x86_64-3.9/cxx/eclipse_state.o build/temp.linux-x86_64-3.9/cxx/emodel_util.o build/temp.linux-x86_64-3.9/cxx/export.o build/temp.linux-x86_64-3.9/cxx/field_props.o build/temp.linux-x86_64-3.9/cxx/group.o build/temp.linux-x86_64-3.9/cxx/log.o build/temp.linux-x86_64-3.9/cxx/parsecontext.o build/temp.linux-x86_64-3.9/cxx/parser.o build/temp.linux-x86_64-3.9/cxx/schedule.o build/temp.linux-x86_64-3.9/cxx/summary_state.o build/temp.linux-x86_64-3.9/cxx/table_manager.o build/temp.linux-x86_64-3.9/cxx/unit_system.o build/temp.linux-x86_64-3.9/cxx/well.o -L/home/mblatt/src/dune/opm/opm-common/opm-gcc9/lib -lopmcommon -lboost_system -lstdc++fs -o /home/mblatt/src/dune/opm/opm-common/opm-gcc9/python/opm/libopmcommon_python.cpython-39-x86_64-linux-gnu.so -fopenmp /usr/lib/x86_64-linux-gnu/libfmt.so.7.1.3 /usr/lib/x86_64-linux-gnu/libcjson.so
```
See
```sh
x86_64-linux-gnu-g++ --version
x86_64-linux-gnu-g++ (Debian 10.2.1-6) 10.2.1 20210110
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

### PR DESCRIPTION
**Pull request by blattms**
CC is the C compiler. CXX is the C++ compiler. Setuptools will use the C++ compiler for C++ code. Hence it is vital to set that
correctly. If it is not set the default C++ compiler will be used. (LDSHARED will be ignored for C++ as well as the first argument of compiler.linker_so)

Unfortunately it will use the first string as the CXX compiler and hence we need to strip ccache. Fortunately setuptools uses CC for the compilation and that works with gcc as well.

Closes #2952 

I just could not help fixing this for setuptools (for my own sanity which was nearly lost in this embarrassingly long process).

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please.

**Comment by joakim-hove** [comment]
Respect man!

**Comment by bska** [comment]
jenkins build this please

**Comment by blattms** [comment]
I will look into the test failures.

**Comment by blattms** [comment]
The problem was the custom build_ext, which somehow triggered a rebuild for the tests. I have no idea why (maybe some options get skipped because my overwrite was incomplete?)

Anyway, I removed it now and only set the variables correctly. Works on my machine.

**Comment by blattms** [comment]
jenkins build this please

**Pull request merged**
