### PR TITLE
WMCTL is zero for wells with status STOP

### PR DESCRIPTION
**Pull request by GitPaean**

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
I am making it to be draft to have a second checking here.

**Comment by GitPaean** [comment]
I now think it should be fine so I can make it ready for review again.

**Comment by GitPaean** [comment]
@bska , let me know whether this PR is far away from a reasonable solution. From my side, it looks correct and the results look good.

**Review by bska — APPROVED** [review]
Yes, I think this is the correct solution.  Thanks for plugging this hole.

**Pull request merged**
