### PR TITLE
changed: remove the CXX11Features module

### PR DESCRIPTION
**Pull request by akva2**
instead use standard CMake mechanism to set cxx standard to 17

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-material=396 opm-grid=440 opm-models=592 opm-simulators=2330 opm-upscaling=293 please

**Comment by akva2** [comment]
jenkins build this opm-material=396 opm-grid=440 opm-models=592 opm-simulators=2330 opm-upscaling=293 please

**Comment by akva2** [comment]
jenkins build this opm-material=396 opm-grid=440 opm-models=592 opm-simulators=2330 opm-upscaling=293 please

**Comment by akva2** [comment]
jenkins build this opm-material=396 opm-grid=440 opm-models=592 opm-simulators=2330 opm-upscaling=293 please

**Comment by blattms** [comment]
I guess you need to take care of the stuff using the variables of CXX11Features in *config.cmake file as well. I am not sure what [project-config.cmake.in#L73-L76](/OPM/opm-common/blob/01b0dcaedfa390e38ada62d88671754a9815d872/cmake/Templates/opm-project-config.cmake.in#L73-L76) is supposed to do really, but is dangerous to downstream modules.

**Comment by akva2** [comment]
hmm, that seems like something we do not want to retain. abi is ensured in other ways now.

**Comment by akva2** [comment]
jenkins build this opm-material=396 opm-grid=440 opm-models=592 opm-simulators=2330 opm-upscaling=294 please

**Comment by akva2** [comment]
jenkins build this opm-material=396 opm-grid=440 opm-models=592 opm-simulators=2330 opm-upscaling=294 please

**Comment by akva2** [comment]
jenkins build this opm-material=396 opm-grid=440 opm-models=592 opm-simulators=2330 opm-upscaling=294 please

**Comment by akva2** [comment]
jenkins build this opm-material=396 opm-grid=440 opm-models=592 opm-simulators=2330 opm-upscaling=294 please

**Comment by akva2** [comment]
now green.

**Comment by blattms** [comment]
Looked good and made it more KISS. Highly appreciated.

**Pull request merged**
