### PR TITLE
adding unit area

### PR DESCRIPTION
**Pull request by GitPaean**
preparing for a summary output related to area, finding out that we do not have a are dimension.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by bska** [comment]
I'll hold this until we've merged #3471.  That one has been postponed for too long and also changes `UnitSystem.[hc]pp`.  You may need to rebase and resolve a couple of hopefully simple merge conflicts once we bring in #3471.

**Comment by GitPaean** [comment]
> I'll hold this until we've merged https://github.com/OPM/opm-common/pull/3471. That one has been postponed for too long and also changes UnitSystem.[hc]pp. You may need to rebase and resolve a couple of hopefully simple merge conflicts once we bring in https://github.com/OPM/opm-common/pull/3471.

Sure. It is no problem. Especially if you foresee #3471 is going in soon.  Rebasing this PR should be trivial.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
> Rebasing this PR should be trivial.

Actually it will probably give some false merging, as you add a zero to offset tables, and the other PR too, so git will mistakenly think that the change is the same when both extra zeros are needed.

**Comment by bska** [comment]
> > Rebasing this PR should be trivial.
> 
> Actually it will probably give some false merging, as you add a zero to offset tables, and the other PR too, so git will mistakenly think that the change is the same when both extra zeros are needed.

Exactly.  This is the number one challenge when adding new units of measurement to `UnitSystem.cpp`.

**Comment by GitPaean** [comment]
Thanks for the heads up. But it is a small PR, and the situation is different from that you have to understand two sets of code and decide how to combine them or the base code is refactored and reallocated.

**Comment by GitPaean** [comment]
I understand more about the issue mentioned above now. Rebasing did not trigger conflicts, while the compilation got broken.

**Comment by GitPaean** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks a lot for the updates and your patience in getting this in.  This looks good to me now and I'll merge into master.

**Pull request merged**
