### PR TITLE
Store references to EclipseState and Schedule in Summary class

### PR DESCRIPTION
**Pull request by joakim-hove**
To simplify eval and upcoming work.

Downstream: https://github.com/OPM/opm-simulators/pull/2930

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2930 please

**Review by bska — APPROVED** [review]
Looks good to me.  I'll merge once the build check is green.

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2930 please

**Comment by bska** [comment]
jenkins build this opm-models=636 opm-simulators=2930 please

**Comment by bska** [comment]
Build check is green now.  I'll merge into master.  Thanks a lot.

**Comment by akva2** [comment]
and woof! 50 new warnings.. sigh.

**Comment by bska** [comment]
> 50 new warnings.

To be fair, **some** of those (the signed vs. unsigned comparisons) come from OPM/opm-simulators#2882.  I should however have caught the [unused variable](https://github.com/OPM/opm-simulators/blob/433a8f8d99188ab4b61cf437912f7ed92c822e52/ebos/eclwriter.hh#L297) before merging and I'm sorry about that.

**Comment by akva2** [comment]
fixes for both are in https://github.com/OPM/opm-simulators/pull/2929

**Pull request merged**
