### PR TITLE
Rework testing of Schedule exit status

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by blattms** [comment]
Wow, that took a lot of time to understand. So the problem was that `$INPUTCASE` was a full path and the `$SIMULATOR` puts the ouput file next to the `$INPUTCASE`. Hence the fix is in line 12 where you add `basename` in front of it.

You might want to quote all variable in case somebody uses space in files or directories. Or does the expansion `${VAR}` take care of that?

**Comment by joakim-hove** [comment]
> So the problem was that $INPUTCASE was a full path and the $SIMULATOR puts the ouput file next to the $INPUTCASE

That is right.

> You might want to quote all variable in case somebody uses spaces in files or directories.

I guess that is smart - will update

**Comment by joakim-hove** [comment]
I have reworked this test completely; originally the implementation was based on a `std::exit()` in the `Schedule` class - and therefor the testing needed to invoke an extra executable and check status code. Now the final exit is in opm-simulators, and the Schedule object just sets a exit status - that means the testing is quite a lot simpler now.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by blattms** [comment]
Simpler sounds cool. :thumbsup:

Seeing simplified code in the morning makes my day.

**Pull request merged**
