### PR TITLE
fix bug radial

### PR DESCRIPTION
**Pull request by goncalvesmachadoc**

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks.  This is an obvious fix and I'll merge into master.  Whether the volume calculation should assume that the cell is horizontally oriented is a matter for another day.

**Comment by OPMUSER** [comment]
@goncalvesmachadoc  What does this fix?

Also previously when we ran with RADIAL, we got this:

image

Now  I get this for the RADIAL and SPIDER grids with OPM Flow

image

The pressures are not the same for the two OPM Flow cases, why?

Also if  I compare with the commercial simulator the results are significantly different:

image


That is because OPM Flow is not honoring the 1,000 psia WBHP constraint for the well.

image

See also the average reservoir pressure.
image

**Comment by bska** [comment]
> What does this fix?

Zero cell volume.  Due to a bug in the arguments to `calculateCellVolume` we ended up with all radial cells getting zero thickness.  Whatever else may be missing in the radial grid implementation we at least needed to fix that.

**Comment by goncalvesmachadoc** [comment]
@OPMUSER Radial and Spider are supposed to be different, as spider is a corner-point grid (Cartesian coordinates). Even tough they look the same in ResInsight, we are correcting the radial to reflect cylindrical coordinates. The volume of the cells in the radial grid matches with Eclipse radial and not with Spider, which gives difference in pressure and saturation solutions. Radial is only ready for one layered slice of cake, i.e., we haven't "closed the circle" nor correct the well bhp pressure. Considering the well in the cpgrid in opm can only be in one cell, we checked that if in the data file we divide the well IP by the number of slices and make very high permeability in the theta-direction in the first circle, we have very good match with Eclipse for the bhp. For a layered slice of cake, we have excellent match with Eclipse radial grid for all: grid pressure, saturations and well bhp. Note: if want perfect match for transmissibilities, we can correct the transmissibility in the z-direction by multiplying the permeability by theta/sin(theta) (that will correct the area open to the flux). For radial direction, I have derived a correction, but not tested it yet.

**Comment by OPMUSER** [comment]
@goncalvesmachadoc even more confused :-(  

The results presented above compare the commercial simulator radial model with OPM Flow's radial and spider grid results. OPM Flow's results are nearly identical but do not match the commercial simulator. This is because OPM Flow is not honoring the BHP constraint - or I'm missing something, which will not be the first time or even the last. 

If we honor the BHP constraint we should see the decline in oil rate instead of producing on a plateau and then stopping.

**Comment by goncalvesmachadoc** [comment]
Hi @OPMUSER , it seems to be a bug indeed related to well bhp, but don't think is related to radial grid. I have observed the same difference behavior with bhp's when converting my radial model to cartesian grid. Here I have a cartesian grid 5x 1x 3 and BHP constraint of 2000 psi. Blue line is Eclipse and green is Flow. 
image

**Comment by goncalvesmachadoc** [comment]
Here it is a comparison for radial grid of both simulators for a layered slice of cake (without bhp constraint):
image
imageimage

image

**Pull request merged**
