### PR TITLE
Udq set

### PR DESCRIPTION
**Pull request by joakim-hove**
The UDQ expressions work on *sets* - like all wells or all connections. This PR introduces a class `UDQSet` which should represent such sets. Every UDQ value has a notion of defined or not defined, an important part of this implementation is to keep track of the defined property through arithmetic operations.

This is not yet in use - but it is a foundation for this WIP PR: #638

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
A review?

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by totto82** [comment]
I haven't looked at the use case for this, but the code itself looks good.

**Comment by joakim-hove** [comment]
>I haven't looked at the use case for this, but the code itself looks good.

I'll take that as a comprehensive review and merge this!

**Pull request merged**
