### PR TITLE
Travis support

### PR DESCRIPTION
**Pull request by jepebe**

### CODE REVIEW

**Comment by atgeirr** [comment]
While I have no knowledge about Travis configuration, I'll assume that those parts are correct. However, why have the build/test scripts been put here and not in the modules in question? I'd prefer that such things are centralized only if absolutely necessary.

**Comment by jepebe** [comment]
@atgeirr My intention was to "hide" as much as possible of Travis in **opm-common** and not have a `travis` folder in each OPM module. I do not have a very strong opinion of this and will distribute the scripts if you want to.

**Comment by jepebe** [comment]
@atgeirr Distributed scripts implemented.

**Comment by atgeirr** [comment]
Thanks!

**Pull request merged**
