### PR TITLE
data::CellData: add support for integer vectors

### PR DESCRIPTION
**Pull request by akva2**
This in preparation for output of CNV_xx vectors which should be stored as integers.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-simulators=5051 opm-upscaling=383 please

**Review by bska — APPROVED** [review]
It **might** make sense to have a way of accessing the `variant<>` directly, at least in a read-only manner.  That way we can use `std::visit()` to implement the output layer.  I haven't decided yet, so I'm fine with merging this as is and then to add the variant access as needed.

**Comment by akva2** [comment]
Yes i anticipate visitor use but i may not expose but add a member, will see what turns out cleanest.

**Comment by bska** [comment]
> Yes i anticipate visitor use but i may not expose but add a member, will see what turns out cleanest.

Okay.  I look forward to seeing the proposal.  I think I'd prefer not to make `data::Solution` aware of and/or tied to the `EclFile` class hierarchy though.

**Pull request merged**
