### PR TITLE
Silence shadowing warnings

### PR DESCRIPTION
**Pull request by atgeirr**
This silences many, but not all shadowing warnings in opm-common.

Includes minor refactoring of ESMry and AggregateGroupData undertaken with the aid of the original authors to ensure correctness.

### CODE REVIEW

**Comment by atgeirr** [comment]
@joakim-hove or @bska please review.

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
I suggest to enable the `-Wshadow` on Jenkins.  Shadow is a source of bugs and I even encountered one today.

**Comment by joakim-hove** [comment]
Please hold

**Comment by atgeirr** [comment]
> Please hold

No problem. Any particular concern?

**Comment by joakim-hove** [comment]
> No problem. Any particular concern?

We have discussed privately - and in addition to merging this PR I will put forward a suggestion PR which will enable more warnings in the default configuration.

**Pull request merged**
