### PR TITLE
Added support for honoring keyword EDITNNC during deck parsing.

### PR DESCRIPTION
**Pull request by blattms**
If the keyword is present then the transimissibilities of the corresponding NNC
entries will be scalled with the factor specified via EDITNNC. Multiple entries
for the same cell pairs are allowed and will result in multiple scalings.
Cell pairs specified in EDITNNC that are not present in NNC are silently ignored.

Same as #534 but from my fork.

### CODE REVIEW

**Comment by blattms** [comment]
Two comments:
- I am not 100% sure how we write the eclipse files. As I modify NNCs writing will only be valid if EDITNNC is not written. Otherwise we need to rescale the NNCs backwards.
- If a consumer of the Eclipse deck also reads EDITNNC (not sure whether this is possible), and decides to use them for scaling then the scaling will have been done twice and results will be wrong.

To be on the safe side we should probably set the transmissibility multiplyers to 1 once we scalled the NNCs. Opinions?

**Comment by joakim-hove** [comment]
> I am not 100% sure how we write the eclipse files

As I understand your code this should work nicely with the current output implementation.

> If a consumer of the Eclipse deck also reads EDITNNC [...]

In principle the scenario you play out is possible; but direct use of the `Deck` datastructure is strongly discouraged, and *not* something we should give up an immuatable deck for.

**Comment by joakim-hove** [comment]
> Cell pairs specified in EDITNNC that are not present in NNC are silently ignored.

I must admit it is not entirely clear to me whether this is the correct approach; I will browse through the code and get back to you.

**Comment by alfbr** [comment]
> Cell pairs specified in EDITNNC that are not present in NNC are silently ignored.

Providing one informational warning message about all ignored non-present NNCs is the expected behaviour. I believe the main reason is that is that non-existing NNCs are common and difficult for the user to have an overview of. For instance, NNCs with low transmissiblities are simply removed from the model. I believe we should provide an informational warning message though.

**Comment by blattms** [comment]
BTW: There is another semantic change that I should mention. NNCs are now sorted lexicographically (not in the order of addition anymore.

**Comment by joakim-hove** [comment]
> BTW: There is another semantic change that I should mention. NNCs are now sorted lexicographically (not in the order of addition anymore.

That should be ok. In principle there might be third party tools which depend on that ordering - but we are in undocumented territory here anyway.

**Comment by joakim-hove** [comment]
OK; I would like some changes to this PR - the use of templates and lambdas with side-effects was a bit over the top for me. So unless there is a very specific reason which I did not catch I would prefer something simpler like:

1. The original implementation internalizing the `NNC` keyword is retained virtually unchanged.
2. We iterate through the `EDITNNC` records like:
```C++
for (const auto& edit_nnc : editNNCS) {
    auto iter = std::find( nnc.begin(), nnc.end(), [&edit_nnc](nnc_equal));
    if (iter != nnc.end())
         iter->tran *= edit_nnc.tran;
}
```
that will be O(n^2) - and I think we live with that.

**Comment by blattms** [comment]
Well, the reasons are
1. Use templates to prevent code duplications
2. use sorting to prevent O(N^2) complexity. I have no idea how many NNCs/EDITNNCS there usually but my is that it are more then just ten.

I can understand that you see that you do not like using templates/lambdas. But why not use sorting?

**Comment by blattms** [comment]
Added the warning.

I even got rid off the dislike rewrite of adding the nncs to save some lambdas. Lots of duplicate code now.

For the request to search in unsorted vectors I want to hear some numbers first. How many NNCs and EditNNCs are there at the extreme?

**Comment by blattms** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
> For the request to search in unsorted vectors

Sorry - that was not important at all; my argument was just that I did not think it was necessary. But by all means - sorting is best.

It was the use of templates and in particular the lambda to capture return value by side effect - which tickled me the wrong way.

**Comment by joakim-hove** [comment]
Good - I am happy to merge this; my only reservation is this:

>> Cell pairs specified in EDITNNC that are not present in NNC are silently ignored.

> I must admit it is not entirely clear to me whether this is the correct approach; I will browse through the code and get back to you.

Which I am still slightly uncertain about; what worries me slightly is that I fear that we in OPM and Eclipse use the term non-neighbour-connection slightly differently, and that we therefor might interpret the manual incorrectly. 

**OPM**: NNC- cells which should  connected in the simulation graph but do not share any surface area.

**Eclipse**: NNC - cells which are not lexicographical neighbours in the i,j,k, sense, but there should be flow between them. Irrespective of whether the cells actually have shared surface area. 

I will try to deep-read the manual one more time.

**Comment by blattms** [comment]
One should at compile before pushing. I should have learned that one years ago...
Amended last commit to make it compile.

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
OK - I am sorry; this should not have been merged. There is a misunderstanding in the approach used in this PR. The point is that the `EDITNNC` keyword can be applied to both NNCs entered explicitly in the deck - that is correctly handled here, and also NNC inferred implicitly by the grid processing of faults.

In the parsing stage we need to hold on to the `EDITNNC` entries, and then subsequently "apply" them to the grid transmissibilities. Exactly how & where to apply the multipliers is not clear to me, but the code which goes through the Grid and identifies the NNCs which should be written to the `EGRID` file - to generate Eclipse compatible output - is [here](https://github.com/OPM/opm-simulators/blob/58f84d3fb4e14ee5f54130a99f67018782be5177/opm/autodiff/GeoProps.hpp#L374) - so that should at least be something to start from.

**Pull request merged**
