### PR TITLE
fixing ALQ Type IGLR

### PR DESCRIPTION
**Pull request by tskille**
Notice that there are still some issues with summary results for vector WGLIR. This will be addressed in a  separate PR.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
There is one failing test,  ```mpi.ScheduleTests`

It looks like it is exactly what this PR is fixing
```
Running 101 test cases...
/var/lib/jenkins/workspace/opm-common-PR-builder/tests/parser/ScheduleTests.cpp(4139): [NON-XML-CHAR-0x1B][1;31;49merror: in "VFPPROD_SCALING": difference{86399} between v1[i]{0.00057870399999999998} and v2[i]{50} exceeds 0.0001%[NON-XML-CHAR-0x1B][0;39;49m
/var/lib/jenkins/workspace/opm-common-PR-builder/tests/parser/ScheduleTests.cpp(4139): [NON-XML-CHAR-0x1B][1;31;49merror: in "VFPPROD_SCALING": difference{86399} between v1[i]{0.0011574070000000001} and v2[i]{100} exceeds 0.0001%[NON-XML-CHAR-0x1B][0;39;49m
/var/lib/jenkins/workspace/opm-common-PR-builder/tests/parser/ScheduleTests.cpp(4139): [NON-XML-CHAR-0x1B][1;31;49merror: in "VFPPROD_SCALING": difference{86399} between v1[i]{0.001736111} and v2[i]{150} exceeds 0.0001%[NON-XML-CHAR-0x1B][0;39;49m
/var/lib/jenkins/workspace/opm-common-PR-builder/tests/parser/ScheduleTests.cpp(4139): [NON-XML-CHAR-0x1B][1;31;49merror: in "VFPPROD_SCALING": difference{86399} between v1[i]{0.002314815} and v2[i]{200} exceeds 0.0001%[NON-XML-CHAR-0x1B][0;39;49m
```

**Comment by tskille** [comment]
thanks @GitPaean, I forgot to check the test. The test have now been updated and this should now hopefully go through.

**Comment by bska** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
Not sure what is this jenkins failure about
```
mpi.compareECLFiles_flow+ACTIONX_M1
```

```
  CTFAC:WI1:11,6,1 |   CTFAC:WI1:11,6,1
  CTFAC:WI1:11,6,2 |   CTFAC:WI1:11,6,2
  CTFAC:WI1:11,6,3 |   CTFAC:WI1:11,6,3
  CTFAC:WI1:11,6,4 |   CTFAC:WI1:11,6,4
  CTFAC:WI1:11,6,5 |   CTFAC:WI1:11,6,5
               FPR |                FPR
           FUBHPP1 |            FUBHPP1
                   |           FUINJLIM
           FU_INJD |            FU_INJD
                   |          GVIR:TEST
                   |          GVPR:TEST
              TIME |               TIME
           WBHP:P1 |            WBHP:P1
          WBHP:WI1 |           WBHP:WI1
           WGPR:P1 |            WGPR:P1
          WGPR:WI1 |           WGPR:WI1
           WOPR:P1 |            WOPR:P1
            WPI:P1 |             WPI:P1
                   |            WPI:WI1
       WUBHPINI:P1 |        WUBHPINI:P1
      WUBHPINI:WI1 |       WUBHPINI:WI1
        WUDELTA:P1 |         WUDELTA:P1
       WUDELTA:WI1 |        WUDELTA:WI1
        WU_TEST:P1 |         WU_TEST:P1
       WU_TEST:WI1 |        WU_TEST:WI1
          WWIR:WI1 |           WWIR:WI1
          WWPI:WI1 |           WWPI:WI1
           WWPR:P1 |            WWPR:P1
          WWPR:WI1 |           WWPR:WI1
             YEARS |              YEARS
```

@bska , any idea?

**Comment by bska** [comment]
> Not sure what is this jenkins failure about

It's OPM/opm-tests#518 which was not properly updated following OPM/opm-tests#519.  Yet another instance of GitHub becoming confused when updating reference solutions.

**Comment by bska** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=521 please

**Comment by GitPaean** [comment]
It involves the update from the opm-tests side now.  @bska please merge this PR along with the update from opm-tests.  This PR looks good to me.

**Comment by bska** [comment]
> It involves the update from the opm-tests side now.

Not really.  I just abused this PR to update the reference data.  This PR is independent of OPM/opm-tests#521.

> This PR looks good to me.

In that case, I'll merge this anyway.  We already merged the updated reference solutions.

**Pull request merged**
