### PR TITLE
fixed: properly export opm-common_PYTHON_COMMON_DIR

### PR DESCRIPTION
**Pull request by akva2**
this needs to be different for the in-tree and installed config files.

i found the issue you were struggling with @blattms
this fixes it properly.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by blattms** [comment]
I am to dumb for this. Where is it actually exported now? I only see a removed export.

**Comment by akva2** [comment]
https://github.com/OPM/opm-common/blob/master/cmake/Templates/opm-project-config.cmake.in#L118

**Comment by blattms** [comment]
:flushed: For someone who actually worked on that code and added exactly this, I seem to surprisingly little insight into that code. :thinking:

**Comment by blattms** [comment]
thanks a lot for the fix. Always nice to work with smarter people than me.

**Pull request merged**
