### PR TITLE
Fix unit for salt concentration in WSALT

### PR DESCRIPTION
**Pull request by totto82**
The salt concentration has unit density, not identity.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by totto82** [comment]
There is a similar bug in the output layer see OPM/opm-simulators#2727. I will test them together from the simulator side.

**Comment by bska** [comment]
> I will test [this and OPM/opm-simulators#2727] together from the simulator side.

@totto82 : Did you make any progress on this testing?  Is this PR still relevant?

**Comment by totto82** [comment]
I just completely forgot about it. It is still relevant. I just need to check why jenkins fails.

**Comment by totto82** [comment]
jenkins build this opm-simulators=2727 please

**Comment by bska** [comment]
jenkins build this opm-simulators=2727 please

**Comment by akva2** [comment]
i have added @totto82 to whitelist now.

**Comment by bska** [comment]
I guess it's not unreasonable for the [`SPE1CASE1_BRINE`](https://github.com/OPM/opm-tests/blob/affa25fea6554960003f5653333fa55796cae290/spe1_brine/SPE1CASE1_BRINE.DATA) case (FIELD units) results to [change](https://ci.opm-project.org/job/opm-common-PR-builder/2395/testReport/) as a result of changing the unit conversion factors.  If it were METRIC then I would expect the numerical results to be unchanged, but for FIELD units there is no such apriori expectation.

**Comment by GitPaean** [comment]
The dimension of concentration and density are not always the same. 

For FIELD unit system, concentration is `lb/stb` while density is `lb/ft^3`. 

Maybe it is time to introduce a unit `Concentration`?

**Comment by GitPaean** [comment]
It looks like both `PolymerDensity` and `Salinity` might work here.  For WSALT, probably `Salinity` can be proper?

```c++
303         constexpr const double PolymerDensity       = pound/stb;
306         constexpr const double Salinity             = pound/stb;
```

**Comment by totto82** [comment]
Thanks @GitPaean Salinity should to the job. I will update the PRs accordingly.

**Comment by totto82** [comment]
jenkins build this opm-simulators=2727 please

**Comment by totto82** [comment]
The failure for the brine case is expected. I suggest we update the reference data and merge this.

**Comment by bska** [comment]
> The failure for the brine case is expected. I suggest we update the reference data and merge this.

Do we currently output any salt-related summary quantities?  If so, I'd expect some changes to the units of measurement in `Summary.cpp` too.

**Comment by totto82** [comment]
> Do we currently output any salt-related summary quantities? If so, I'd expect some changes to the units of measurement in Summary.cpp too.

Yes. Like WSPR and WSCR. But I think the units are correct for summary.

**Comment by bska** [comment]
> > Do we currently output any salt-related summary quantities? If so, I'd expect some changes to the units of measurement in Summary.cpp too.
> 
> Yes. Like WSPR and WSCR. But I think the units are correct for summary.

Okay, it's just that there are no specific [`rate_unit`s](https://github.com/OPM/opm-common/blob/5557debd9c9ee062cdc1cd15158accee9ab4e9fd/src/opm/output/eclipse/Summary.cpp#L396-L443) for [`brine`](https://github.com/OPM/opm-common/blob/5557debd9c9ee062cdc1cd15158accee9ab4e9fd/opm/output/data/Wells.hpp#L71), so we fall back to the [default](https://github.com/OPM/opm-common/blob/5557debd9c9ee062cdc1cd15158accee9ab4e9fd/src/opm/output/eclipse/Summary.cpp#L396-L397) rate units (i.e., liquid surface volume per time) for these quantities.

**Comment by totto82** [comment]
The summary for brine is handled as polymer. 

`    if( phase == rt::polymer || phase == rt::brine ) return { v, measure::mass_rate };
`
etc.

**Comment by bska** [comment]
> The summary for brine is handled as polymer.
> 
> ```C++
>  if( phase == rt::polymer || phase == rt::brine ) return { v, measure::mass_rate };
> ```

I see.  In that case, I'll put that on my list and generate a new set of reference solutions for the brine model.

**Comment by bska** [comment]
jenkins build this opm-simulators=2727 update_data please

**Comment by bska** [comment]
jenkins build this opm-simulators=2727 opm-tests=373 please

**Comment by bska** [comment]
Reference data update in place from OPM/opm-tests#373.  Merging this now to prepare for also merging the downstream PR OPM/opm-simulators#2727.

**Pull request merged**
