### PR TITLE
internalize StandardConditions

### PR DESCRIPTION
**Pull request by akva2**
To avoid deck usage downstream

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-material=410 opm-simulators=2393 please

**Comment by akva2** [comment]
feel free to tell me to relocate the data if you don't like them being in initconfig.

**Comment by joakim-hove** [comment]
When you are in this part of town I would like to suggest a change/improvement:

1. The `SurfaceCond` class can be initialized with proper defaults (unfortunately there is unit conversion involved ...)
```C++

StandardCond::StandardCond() { 
    using ST = ParserKeywords::STCOND;
    double input_temp = ST::TEMPERATURE::defaultValue;
    double input_pressure = ST::PRESSURE::defaultValue;
    UnitSystem units( UnitSystem::UnitType::UNIT_TYPE_METRIC );
    this->temperature = units.to_si(UnitSystem::measure::temperature, input_temp);
    this->pressure = units.to_si(UnitSystem::measure::pressure, input_pressure);
}
```

2. The book keeping of `inited` can be dropped.
3. Downstream unconditionally uses the `StandardCond` instance from opm-common and avoids the current hardcoded-initialization-and-then-check-if-it-is-set-in-the-deck approach.

I would suggest putting the new `StandardCond` instance in the `TableManager`

**Comment by akva2** [comment]
done.

**Comment by akva2** [comment]
jenkins build this opm-material=410 opm-simulators=2393 please

**Comment by akva2** [comment]
green from downstream.

**Pull request merged**
