### PR TITLE
Parse PYINPUT

### PR DESCRIPTION
**Pull request by stefoss23**
This allows python code to be written in eclipse .DATA files. 
Note: it is not yet possible to embed Python while still running python (e.g. the below example is not possible for the python Parser.).

The syntax is:
```
PYINPUT
import numpy as np
dx = np.array([0.25, 0.25, 0.25, 0.25])
active_unit_system = context.deck.active_unit_system()
default_unit_system = context.deck.default_unit_system()        
kw = context.DeckKeyword( context.parser['DX'], dx, active_unit_system, default_unit_system )
context.deck.add(kw)
<<<
```

Some reading:  https://stackoverflow.com/questions/24656088/static-member-variable-for-class-that-is-dynamically-loaded

### CODE REVIEW

**Comment by stefoss23** [comment]
jenkins build this please

**Comment by stefoss23** [comment]
jenkins build this please

**Comment by stefoss23** [comment]
jenkins build this please

**Comment by stefoss23** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Can you post a message pointing to exactly where it blows?

**Comment by stefoss23** [comment]
It is the use of PythonInstance(). Instead the manual solution has to be used.

**Comment by stefoss23** [comment]
Correction: Py_IsInitialized()

**Comment by stefoss23** [comment]
jenkins build this please

**Pull request merged**
