### PR TITLE
fixed: do not assign value to nonexistent variable

### PR DESCRIPTION
**Pull request by akva2**
Making only the variable declaration and not the assignment conditional was stupid of me.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
i was uncertain. if i do, passing -n becomes an error as per default case so that could possibly break scripts etc.

**Comment by bska** [comment]
>> Would it make sense to just completely remove the `-n` option if OpenMP is unavailable/disabled?
>
> if i do, passing `-n` becomes an error as per default case so that could possibly break scripts etc.

Right, that's a good point.  Maybe we could just add a diagnostic of the form
```C++
#ifdef _OPENMP
    max_threads = ...;
#else
    std::cerr << "OpenMP is disabled-using single thread only\n";
#endif
```

**Comment by akva2** [comment]
done.

**Comment by akva2** [comment]
jenkins build this please

**Pull request merged**
