### PR TITLE
summary support for numerical aquifer keywords

### PR DESCRIPTION
**Pull request by GitPaean**
It is just the support from opm-common side. Downstream PRs from simulators side are not there yet.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
@bska , I am getting numerical aquifers things in piece by piece.  For this PR, do you think we can get it in by iteself, or you think we should wait until the downstream PRs getting in so that the quantities will be updated by the simulator side. 

If you think it can get in by itself, please help to get it in.  If you think it is better to wait, it also works for me. 

Getting it in just provides some convenience for development of other PRs. And before the downstream simulator side is ready, there should be no test cases related to numerical aquifer.

**Comment by joakim-hove** [comment]
The current code looks fine - and can be merged as is; but I am uncertain if it is any point. There are two principle layers before a summary variable is written to the summary file:

1. We need to internalize it in the `SummaryConfig`.
2. We need to implement functionality in `Summary` which based on the node from `SummaryConfig` and simulator results actually creates results for the summary file.

I am quite certain that the `ANxx` keywords you mention here will not be internalized in the `SummaryConfig` implementation, and basically nothing will happen. So - all in all - this PR can be merged, but it will have no effect.

**Comment by GitPaean** [comment]
I have done something related to summary part, it is complex to me. 

From testing with https://github.com/OPM/opm-common/pull/2097 , it does not looks like I need to do anything related to SummaryConfig to let `AN` keywords in. Although I do not have a grasp about why. 

It is running and outputting these keywords properly with the branch associated with https://github.com/OPM/opm-common/pull/2097

**Comment by bska** [comment]
> From testing with #2097 , it does not looks like I need to do anything related to SummaryConfig to let `AN` keywords in. Although I do not have a grasp about why.

You're right.  Our system treats all summary vectors with a leading `A` (other than `ALL`) as [aquifer-related](https://github.com/OPM/opm-common/blob/39720fa3a4117ca6a17cf6ce1c7accd7e364e518/src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp#L283-L286). Since the reader [recognises](https://github.com/OPM/opm-common/blob/39720fa3a4117ca6a17cf6ce1c7accd7e364e518/src/opm/parser/eclipse/share/keywords/000_Eclipse100/A/AQUIFER_PROBE_NUMERIC) the `ANQ*` summary keywords you don't need to do anything to internalise those keywords.  Finally, the [evaluation function](https://github.com/OPM/opm-common/blob/39720fa3a4117ca6a17cf6ce1c7accd7e364e518/src/opm/output/eclipse/Summary.cpp#L2112) will pick up the values from [`data::AquiferData::get()`](https://github.com/OPM/opm-common/blob/39720fa3a4117ca6a17cf6ce1c7accd7e364e518/opm/output/data/Aquifer.hpp#L58) if it exists (name-based lookup from keyword) so this PR is entirely sufficient to transport summary vectors related to numerical aquifers to the summary output file.

The only reason this PR does fail any of the regression tests is that we do not have any of those with numerical aquifers.

**Comment by GitPaean** [comment]
For easy of testing for other PRs, I will merge this PR to https://github.com/OPM/opm-common/pull/2252  for easy to testing with incoming downstream PR from opm-simulators. 

Since this PR is so small and it should be okay. 

This PR is closed now.

**Pull request closed without merging**
