### PR TITLE
Restart: Save/Restore Cumulative Injected Reservoir Volume

### PR DESCRIPTION
**Pull request by bska**
This commit adds support for persisting the `*VIT` cumulative summary vector at the well, group, and field levels in the simulation restart files.  Connection level currently not supported.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Wow - that was fast!

**Comment by joakim-hove** [comment]
jenkins build this update_data please

**Comment by joakim-hove** [comment]
jenkins build this opm-tests=272 please

**Comment by bska** [comment]
jenkins build this opm-tests=272 please

**Pull request merged**
