### PR TITLE
Add std::time start_time argument to SummaryState

### PR DESCRIPTION
**Pull request by joakim-hove**
To be able to keep track of how far the simulation has progressed - in true date. This is ultimately needed in the `ACTIONX` implementation, where you can check the simulation date with statements of the type:
```
...
'MNTH = 6' AND 'YEAR > 2020' ...
```

Downstream: https://github.com/OPM/opm-simulators/pull/2018

### CODE REVIEW

**Comment by bska** [comment]
Would you consider making this a `std::chrono::time_point<std::chrono::system_clock>` instead?  I'd **really** rather prefer that we limit the use of `std::time_t` to internal implentation routines that call into low-level C library functions like `std::gmtime()`.

**Comment by joakim-hove** [comment]
> Would you consider making this a std::chrono::time_point<std::chrono::system_clock> instead

Done

**Comment by bska** [comment]
> > Would you consider making this a `std::chrono::time_point<std::chrono::system_clock>` instead
> 
> Done

Perfect!  Thanks a lot.

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2018 please

**Comment by joakim-hove** [comment]
@jalvestad : This should fix the issue with `DAY/YEAR/MNTH` in the `ACTIONX` conditions. Observe that also the PR in opm-simulators must be merged before you can use this.

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2018 please

**Comment by joakim-hove** [comment]
> I like it. 

Good :-)

> If there are no further changes intended for this PR 

It is ready from my hand.

**Comment by bska** [comment]
> > If there are no further changes intended for this PR
> 
> It is ready from my hand.

Very good.  I'll merge into master.  Thanks a lot for the update.

**Pull request merged**
