### PR TITLE
dont output trapped gas during drainage

### PR DESCRIPTION
**Pull request by totto82**

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
jenkins build this please

**Review by bska — COMMENTED** [review]
This work [changes the simulation results](https://ci.opm-project.org/job/opm-common-PR-builder/6567/testReport/junit/(root)/mpi/compareECLFiles_flow_WAGHYSTR_02/) of the [WAGHYSTR-02](https://github.com/OPM/opm-tests/blob/d5e4ba7718a23d4c680991bbc6fd28237ec4e6dc/waghystr/WAGHYSTR-02.DATA) regression test model.  Are those changes expected?

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
jenkins build this please

**Comment by blattms** [comment]
This has been dormant for some time.  @totto82, are you planning to add tests here before merging or will that be done later?

**Comment by totto82** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by totto82** [comment]
More tests are added and the code approved by Jenkins and @bska. Merging.

**Pull request merged**
