### PR TITLE
Some janitoring

### PR DESCRIPTION
**Pull request by akva2**
When the janitor is away, the hackers dance on the tables.

### CODE REVIEW

**Comment by joakim-hove** [comment]
It was a wonderful 🕺

**Comment by akva2** [comment]
jenkins build this please

**Comment by blattms** [comment]
Tried to backport this in full to the release but we seem to miss some PRs that introduced the warnings.
Might try again after the freeze (if I do not forget).

**Comment by blattms** [comment]
backported all commits but 11462f7 to the release

**Pull request merged**
