### PR TITLE
Avoid headers in headers

### PR DESCRIPTION
**Pull request by akva2**
This avoid including headers in headers. In particular, these are somewhat large, generated headers, and they sit in classes that are pulled in a lot of places.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by bska** [comment]
This appears to [break](https://ci.opm-project.org/job/opm-common/lastCompletedBuild/testReport/(root)/serial/rst_spe1/) opm-common.  Please fix or revert.

**Comment by joakim-hove** [comment]
At my machine it works 50% of the time - hopefully this fixes it: https://github.com/OPM/opm-common/pull/2439

**Comment by joakim-hove** [comment]
> hopefully this fixes it: #2439

it did not - still random failures; I have just removed one check. Will investigate further tomorrow

**Pull request merged**
