### PR TITLE
Python runtime

### PR DESCRIPTION
**Pull request by joakim-hove**
This PR will embed the Python runtime into libopmcommon; that way we can call Python code runtime from the opm/flow C++ codebase. The current PR does nothing, but when this is merged it will be quite simple implement first the 
```
PYINPUT
# Here comes python code - which can manipulate the deck - while 
# it is being assembled
<<<
/
```

and then later 
```
PYACTION
# Here comes Python code which will enable writing the action conditions - 
# and possibly also the action itself - in Python.
<<<

/ 
```    

Embedding the Python interpreter is protected behind the `OPM_ENABLE_EMBEDDED_PYTHON` cmake switch - which defaults to `OFF`.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by akva2** [comment]
apart from a few small things i pr'd to your repo, this looks all fine from a build system perspective.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
This PR will - when the `OPM_ENABLE_EMBEDDED_PYTHON` switch is set to `ON` (defaults to `OFF`) embed the Python interpreter in `libopmcommon` - a not entirely insignificant change. I encourage interested parties to take a look - if this does not ignite I will merge later this week,

**Comment by atgeirr** [comment]
Sounds fun, looking forward to seeing what can be gained from it. Just a few questions:
 - Does this mean that Flow (with this option) becomes more of an attack target? I am in particular thinking of remote running of ensemble jobs on clouds and things like that.
 - Were alternatives considered? I would think that Octave could be a viable option, especially since ResInsight already embeds it, and MRST build on the language. I do not mean to imply that Python is a bad choice, just exploring the possibilities. Could we extend this feature to more languages easily?

**Comment by joakim-hove** [comment]
> Does this mean that Flow (with this option) becomes more of an attack target? I am in particular thinking of remote running of ensemble jobs on clouds and things like that.

I have also thought of that - and I think you have a point. It is not that flow will become an attack target, but rather that it can become *a vector*. In a situation where flow is run as a service, not by the user submitting the job, but rather some shared cluster user the embedded code can be used to trick flow into running arbitrary code as the shared cluster user. We will have to understand this vector better before this is shipped in any way.

> Were alternatives considered?

Not really; Python was suggested at some stage - and the main sponsor was supportive of that. 

> Could we extend this feature to more languages easily?

There are two elements which must be in place for a working solution:

1. The relevant C++ objects must wrapped in the scripting language of choice, so that you can inspect and manipulate the true simulator state through script language objects. This is a quite large job - for Python we have started - largely based on the existing `sunbeam` package from Equinor. To add wrappers for e.g. Matlab/octave would be a new effort - 100% independent of the ongoing Python wrapping.

2. The runtime i.e. `libpython.so` must be embedded in the C++ code, again embedding `libmatlab.so` in the C++ code would be a new effort independent of the ongoing Python effort; however here I think the experience learned from Python would be valuable. Also a quite significant effort which is already merged is changes to the parser to be able to load verbatim code from the deck - that would of course benefit any scripting language.

> I would think that Octave could be a viable option

image

:-)

**Pull request merged**
