### PR TITLE
Udq fixup

### PR DESCRIPTION
**Pull request by joakim-hove**
Ahhh regexps - very powerful - but they come with a price ....

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Looks good to me. Thanks for identifying the missing character. I'll merge into master now.

**Pull request merged**
