### PR TITLE
Suppress GCC 12 Out-of-Bounds Index Warnings in Parameter Caches

### PR DESCRIPTION
**Pull request by bska**

### CODE REVIEW

**Comment by bska** [comment]
This is work in progress and we'll likely have to revise this approach.

**Comment by bska** [comment]
jenkins build this no downstreams please

**Comment by bska** [comment]
jenkins build this no downstreams please

**Comment by bska** [comment]
jenkins build this no downstreams please

**Comment by bska** [comment]
jenkins build this no downstreams please

**Comment by bska** [comment]
Okay, I'm satisfied that the current version does what it's intended to do so I'll mark it as "ready for review" now.

**Comment by bska** [comment]
jenkins build this no downstreams please

**Review by akva2 — APPROVED** [review]

**Comment by bska** [comment]
PR approved and build check is green.  I'll merge into master.

**Pull request merged**
