### PR TITLE
Do not warn if just def'ed HAVE_ vars are set to 1

### PR DESCRIPTION
**Pull request by rolk**
Some configuration scripts probe and just set HAVE_FOO without any
values, whereas others set it explicitly to 1. If these two are mixed,
for instance that the same package is used by two of our prerequisites,
but in different manner, then we get compatibility warnings when we try
to run the configuration script, even though there is no real conflict.

dune-fem, dune-alugrid and dune-localfunctions have this problem (around
release 2018.04).

This patch special-code the test so if the old value was previously
either just defined or explicitly set to the value 1, a warning will not
be issued if then suddenly the other variant is used.

### CODE REVIEW

**Comment by bska** [comment]
Just to be clear here: This is in the context of **CMake** variables named `HAVE_*`, right?  We're not talking about C++ **preprocessor symbols** named `HAVE_*`?

**Comment by rolk** [comment]
@bska Both. The CMake probes will create HAVE_FOO and then export this into config.h. The precursor for this is that if you include dune-fem as a module, you get warnings that HAVE_DUNE was previously defined by some module as "" (defined, but with no value), but has now be defined by someone to be "1". 

I know where you're hinting, and yes I know of the problem with `#define HAVE_FOO 0 #if defined(HAVE_FOO)`, that this test was originally designed to prevent, and the dangers of relaxing it.

Admittedly, this is just a kludge to avoid getting a pagefull of "errors" in the configuration of the application. If I had more time available, I would rather prefer to find the root cause and exterminate it.

I tried to track down why it happens to dune-fem and dune-alugrid, but not to for instance dune-grid, but I couldn't find any thing different in the way these modules were used by the OPM code, so I suspect that it is the *-config.cmake scripts in DUNE that cause this (but then again, I'm not sure).

**Comment by rolk** [comment]
@bska Also note that this test (which is written into opm-snafu-config.cmake) is immediately followed by `set(HAVE_FOO 1)`, which is the probed value in *this* module, so there shouldn't be any case where a previously defined HAVE_FOO (to no explicit value) now "sneaks past" the test, just that the previous definition does not trigger a warning anymore.

**Comment by bska** [comment]
> there shouldn't be any case where a previously defined `HAVE_FOO` (to no explicit value) now "sneaks past" the test, just that the previous definition does not trigger a warning anymore.

Ah, good.  Thanks for the clue-by-four.

**Pull request merged**
