### PR TITLE
Simulation Restart: Restore All Available Injection Control Modes

### PR DESCRIPTION
**Pull request by bska**
In particular, declare that the injection well supports RATE, RESV, and THP limits/targets if such values are available in the SWEL array.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
Note: This PR is necessary to make the regression test
```
compareRestartedSim_flow+SPE9_CP_SHORT
```
go through in the context of existing PR OPM/opm-simulators#2328.

**Comment by bska** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Thanks - merging.

**Pull request merged**
