### PR TITLE
Various static analyzer analytics

### PR DESCRIPTION
**Pull request by akva2**
A mixed bag of static analyzer warnings

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
I did have to look a little closer at the change to ESmry.cpp, but since the `rest` is provably zero in this that's of course fine.  I'll merge into master.

**Comment by akva2** [comment]
dont, build is red

**Comment by bska** [comment]
>>  I'll merge into master.
>
> don't, build is red

Yeah... I noticed **just** as I was about to hit the merge button.

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks a lot for the updates.  This looks good to me now and I'll merge into master.

**Pull request merged**
