### PR TITLE
Adds GuideRateModel

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Sometimes jenkins just won't bite?!

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
@totto: I think this should be ready; the PR contains a model object for calculating the guide rate, in addition there must be some (quite limited) bookkeeping to make sure that the simulator waits `GuideRateModel::update_delay()` before recalculating - that bookkeeping must be managed from the simulator - I have not created any code for that.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by totto82** [comment]
Thanks. I would prefer to have the eval() method in the simulator. i.e. that the guideratemodel just provides the input. And I didn't get the reason for the update_delay method.

**Comment by joakim-hove** [comment]
OK - I have discussed with @totto82 - we agreed to merge this when Jenkins approves, and then see how it works out.

**Pull request merged**
