### PR TITLE
move data serialization objects close to the class code

### PR DESCRIPTION
**Pull request by akva2**
add static method to return a test object for serialization. this allows killing the constructors taking member values.

@joakim-hove as discussed. this is pretty unreviewable but you said yes to the idea.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-simulators=2492 please

**Comment by akva2** [comment]
jenkins build this opm-simulators=2492 please

**Comment by akva2** [comment]
jenkins build this opm-simulators=2492 please

**Comment by akva2** [comment]
is it okay to merge? kinda want to avoid unnecessary rebasing..

**Comment by joakim-hove** [comment]
> is it okay to merge? kinda want to avoid unnecessary rebasing..

Go ahead - cool effort!

**Pull request merged**
