### PR TITLE
Check WELSPECS values

### PR DESCRIPTION
**Pull request by joakim-hove**
This is for reporting; if input is different from default we log a warning and ignore it.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
I'm getting an error in the PVT-table ID code on a model 2 realization:
```
#0  0x00005555587c6528 in Opm::Connection::global_index (this=0x0) at /home/bska/work/opm/src/opm.master/opm-common/src/opm/parser/eclipse/EclipseState/Schedule/Well/Connection.cpp:162
#1  0x00005555587cb75e in Opm::Well::updateConnections (this=0x5555812a9530, connections_arg=std::shared_ptr<Opm::WellConnections> (use count 2, weak count 0) = {...}, grid=..., 
    pvtnum=std::vector of length 338905, capacity 528081 = {...}) at /home/bska/work/opm/src/opm.master/opm-common/src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp:633
#2  0x0000555558755014 in Opm::Schedule::handleCOMPDAT (this=0x5555877a73f0, keyword=..., currentStep=1, grid=..., fp=..., parseContext=..., errors=...)
    at /home/bska/work/opm/src/opm.master/opm-common/src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp:2035
#3  0x0000555558740c32 in Opm::Schedule::handleKeyword (this=0x5555877a73f0, python=std::shared_ptr<const Opm::Python> (use count 6, weak count 0) = {...}, 
    input_path="ANONYMISED", currentStep=1, section=..., keywordIdx=45, keyword=..., parseContext=..., errors=..., grid=..., fp=..., unit_system=..., 
    rftProperties=std::vector of length 0, capacity 0) at /home/bska/work/opm/src/opm.master/opm-common/src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp:383
#4  0x00005555587420e7 in Opm::Schedule::iterateScheduleSection (this=0x5555877a73f0, python=std::shared_ptr<const Opm::Python> (use count 6, weak count 0) = {...}, 
    input_path="ANONYMISED", parseContext=..., errors=..., section=..., grid=..., fp=...)
    at /home/bska/work/opm/src/opm.master/opm-common/src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp:554
#5  0x000055555873da71 in Opm::Schedule::Schedule (this=0x5555877a73f0, deck=..., grid=..., fp=..., runspec=..., parseContext=..., errors=..., 
    python=std::shared_ptr<const Opm::Python> (use count 6, weak count 0) = {...}, rst=0x0) at /home/bska/work/opm/src/opm.master/opm-common/src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp:172
#6  0x000055555873e0c5 in Opm::Schedule::Schedule (this=0x5555877a73f0, deck=..., es=..., parse_context=..., errors=..., python=std::shared_ptr<const Opm::Python> (use count 6, weak count 0) = {...}, rst=0x0)
    at /home/bska/work/opm/src/opm.master/opm-common/src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp:207
#7  0x000055555715c4d8 in Opm::Main::initialize_ (this=0x7fffffffdb50, exitCode=@0x7fffffffdb24: 0) at /home/bska/work/opm/src/opm.master/opm-simulators/opm/simulators/flow/Main.hpp:394
#8  0x000055555715acc5 in Opm::Main::runDynamic (this=0x7fffffffdb50) at /home/bska/work/opm/src/opm.master/opm-simulators/opm/simulators/flow/Main.hpp:147
#9  0x00005555571100d6 in main (argc=6, argv=0x7fffffffdcb8) at /home/bska/work/opm/src/opm.master/opm-simulators/flow/flow.cpp:29
```

Notice `this=0x0` in frame zero.  Going up the call stack to [`Schedule::handleCOMPDAT()`](https://github.com/OPM/opm-common/blob/60e9a9c6b90267ac34693f6e8410d1ab0698f087/src/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp#L2035) I'm seeing that the `connections` object is
```
{
   m_ordering = Opm::Connection::Order::INPUT,
   headI = <Anonymised Positive Value>,
   headJ = <Anonymised Positive Value>,
   m_connections = std::vector of length 0, capacity 0
}
```
meaning the actual list of connections is empty.  I don't know if this is the symptom of a problem that should have been detected earlier or if [`Well::updateConnection()`](https://github.com/OPM/opm-common/blob/60e9a9c6b90267ac34693f6e8410d1ab0698f087/src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp#L629-L638) must be taught how to deal with empty connection lists.

**Comment by joakim-hove** [comment]
> I'm getting an error in the PVT-table ID code on a model 2 realization:

OK - thank you; will look into it.

**Comment by joakim-hove** [comment]
> must be taught how to deal with empty connection lists.

I am quite certain that is the problem; quite involved to test though - would be cool if you could give: #1734 a spin.

**Comment by bska** [comment]
>> must be taught how to deal with empty connection lists.
> 
> [It] would be cool if you could give: #1734 a spin.

It looks promising.  I've gotten past the trouble spot in a debug build.  I'll try again in an optimized/MPI build and if successful then I'll merge the patch.

**Pull request merged**
