### PR TITLE
Add alternative well implementation Well2

### PR DESCRIPTION
**Pull request by joakim-hove**
[This is #674 which was accidentally closed due to some git fat fingering]

This is the first step of an implementation of: #624 - which again is part of the UDQ / UDA work; it should now be ~ready for review. Observe that when this is merged it will have no immediately visible effect - the new well implementation Well2 will exist side by side with the existing implementation Well - and downstream will exclusively use the old Well. As part of this PR an system for well integration testing is integrated into the Schedule constructor - this is briefly described here: #680. When this is merged I encourage all developers to configure opm-common with:
```
bash% cmake .. -DENABLE_WELL_TEST=ON
```
then the automatic "Well ≡ Well2" test will be run as part of Schedule construction; please report any errors you encounter!

When the Well2 implementation has worked silently for some time it is actually time to start using it - that is the subject of this PR: #731 - that is into a moderately distant future.

I quite often preach about the value of small PR's - and I mean it - this PR contains one atomic unit - a new well implementation, and in that sense I feel it is reasonable as one large PR, but to practice as I preach I am willing to split it in subatmoic units to facilitate simpler review.

### CODE REVIEW

**Comment by bska** [comment]
I haven't read this at all, but just out of curiosity: What is the expected lifetime of the `Well2` class name?

**Comment by joakim-hove** [comment]
I am open to suggestions when it comes to lifetime.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
I consider this ~ready now and would like some review comments/testing. In light of recent regressions in the same part of the code it would be very valuable if you could help in with testing this:

1. Check out this branch.
2. Configure opm-common with `-DENABLE_WELL_TEST=ON`
3. Continue your work as normal.

If/when there is a difference between the new and the old well model the `Schedule` constructor should blow up - I am very interested in that error; and of course also a heads up if things work.

This PR is only new code, and apart from the opt in testing as part of the `Schedule` construction it will have no consequences on flow. When this has played nicely for some time the next PR is #731

**Comment by joakim-hove** [comment]
I'll merge this one day in the not-so-distant future.

**Comment by joakim-hove** [comment]
OK - this has been in the baking for a long time - merging.

**Comment by joakim-hove** [comment]
> Does it serve any current purpose in master?

It should of course go - but it is in a code block which is in itself a debugging/testing block (which you have now invoked :+1: ), so yes - it does in my opinion serve a purpose at the moment, but sure I would not object to taking it out either.

**Comment by bska** [comment]
> > Does [the `printf()`] serve any current purpose in master?
> 
> It should of course go - but it is in a code block which is in itself a debugging/testing block (which you have now invoked  ),

I didn't actually invoke anything.  Unless the Jenkins system is running a non-default configuration, this is now part of current master.  As an example, the currently running post-commit build [723](https://ci.opm-project.org/job/opm-simulators/723/consoleText) of opm-simulators emits
```
Sjekker INJ properties ...
```
messages for all injection wells in Norne.  It's not a problem if that's what it's supposed to do.

**Comment by joakim-hove** [comment]
> Unless the Jenkins system is running a non-default configuration

Jenkins configures with: `cmake -DENABLE_WELL_TESTS=ON ...`

**Comment by bska** [comment]
> > Unless the Jenkins system is running a non-default configuration
> 
> Jenkins configures with: `cmake -DENABLE_WELL_TESTS=ON ...`

Ah, I see it now&mdash;introduced in #680.  Thanks for the clue-by-four!

**Pull request merged**
