### PR TITLE
added: error analysis support in compareSummary / compareECL

### PR DESCRIPTION
**Pull request by akva2**
useful for debugging purposes. replaces scripts in opm-simulators.

@alfbr as requested.

### CODE REVIEW

**Comment by alfbr** [comment]
Fantastic, thank you! Please give me a couple of days to give it a spin.

**Comment by alfbr** [comment]
Just finished testing. Works as advertised, and is a significant improvement of the testing framework. Thumbs up from me. Maybe @blattms can have a quick look at the code?

**Comment by blattms** [comment]
Nevermind. I was thinking loud.

**Comment by akva2** [comment]
jenkins build this please

**Pull request merged**
