### PR TITLE
Adding support for LGR related summary vectors

### PR DESCRIPTION
**Pull request by tskille**
Update of class Opn::EclIO::ESmry, now supporting LGR related summary vectors
 - local block data starting with 'LB'
 - local well connections starting with 'LC'
 - local well data starting with 'LW'

This PR is also fixing a bug related to inter-regions summary data.

### CODE REVIEW

**Comment by tskille** [comment]
This PR is now ready for support. Notice that Flow is not yet supporting LGRs, however these updates are needed for program  make_ext_smry (used to convert from smspec/unsmry -> esmry). This program will now av better support for converting summary files generated by eclipse to esmry

This PR is now ready for review.

**Review by bska — COMMENTED** [review]
Looks good to me except for a couple of objects that could be marked as `const` if initialised differently.

**Comment by bska** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
We have all got different axes to grind - one of my favorites is use `std::optional<...>` and not special values like `-1` for objects which might not have a valid. Furthermore the LGR related stuff should be included in the `SummaryNode` class instead of inlining it in the code like in this PR; I would suggest creating a small struct:
```
struct lgr_info {
    std::string name;
    std::array<3, int> ijk;
}
```
and then adding a `std::optional<lgr_info>` to the `SummaryNode` class.

**Comment by tskille** [comment]
Comments from both @bska and @joakim-hove has now been addressed. This can now hopefully be merged.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Good - merging!

**Pull request merged**
