### PR TITLE
fixed: do not open a issue/PR if no tests failed

### PR DESCRIPTION
**Pull request by akva2**
Avoid non-sense issues in opm-tests.

@bska this should take care of it.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-simulators=2251 update_data please

**Comment by bska** [comment]
> this should take care of it.

Looks good to me.  Merge when green

**Comment by akva2** [comment]
jenkins build this opm-simulators=2251 update_data please

**Comment by akva2** [comment]
jenkins build this opm-simulators=2251 update_data please

**Pull request merged**
