### PR TITLE
quell deprecation warnings with boost 1.71

### PR DESCRIPTION
**Pull request by akva2**
header was relocated.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-grid=468 opm-simulators=2579 opm-upscaling=316 please

**Comment by joakim-hove** [comment]
Are you sure we need to include the header at all? At least there are many other tests which invoke `BOOST_CHECK_CLOSE()` without inlcuding the `floating_point_comparison.hpp` header.

**Comment by akva2** [comment]
no, i didn't think about that, i just want to quell my ocd.

**Comment by joakim-hove** [comment]
Merged #1767  instead

**Pull request closed without merging**
