### PR TITLE
WPIMULT: directly multiply the connection transmissibility factor

### PR DESCRIPTION
**Pull request by joakim-hove**
Do not handle WellPI as a separate entity in the Connection class - just multiply with the transmissibility factor right away.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2511 please

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2511 please

**Comment by atgeirr** [comment]
Sounds good, unless we need the "raw" CTF for some reason (output perhaps). I assume this has been checked?

**Comment by joakim-hove** [comment]
> unless we need the "raw" CTF for some reason (output perhaps). I assume this has been checked?

Yes it is kind of opposite - output only uses the scaled CTF.

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2511 please

**Pull request merged**
