### PR TITLE
Internal serialization in EclipseState - part 1

### PR DESCRIPTION
**Pull request by akva2**
More internal serialization support.

### CODE REVIEW

**Comment by akva2** [comment]
@joakim-hove you might want to check if there are accessors in BCConfig and RockConfig that you want to kill (those were added after serialization started, so maybe there are things there you don't want now).

**Comment by blattms** [comment]
jenkins build this opm-simulators=2461 please

**Comment by akva2** [comment]
it has a prerequisite, the build will fail.

**Comment by joakim-hove** [comment]
>  you might want to check if there are accessors in BCConfig and RockConfig that you want to kill (those were added after serialization started, so maybe there are things there you don't want now).

Thanks - I'll try to remember when the dust has settled.

**Comment by akva2** [comment]
jenkins build this opm-simulators=2461 please

**Comment by blattms** [comment]
I was not expecting a struct like RockComp to be a pod, but I guess my understanding is to limited.
Seems like the static_assert is wrong, but catched an issue anyway (which would have been catched anyway?).

Hence your original approach without the assert and a (hopefully) meaningful compiler error was better.

What I am wondering is, why do we need to actively choose how a vector is serialized? Is that because for some vectors (with pods) we only send parts of the data of the entries?

**Comment by akva2** [comment]
because we do not have pack/unpack/packSize methods for these types any more. we only have type.serializeOp(). so we need to handle them at the eclmpiserializer level, not in the underlying serializer. eventually the serializer itself will (return to) only supporting primitive data + std::string.

**Comment by akva2** [comment]
jenkins build this opm-simulators=2461 please

**Comment by akva2** [comment]
I removed the static_assert for now. I'm fairly certain we can do some sfinae to avoid the explicit vector method later, but i need the complete overview before i do so.

**Comment by akva2** [comment]
jenkins build this opm-simulators=2461 please

**Pull request merged**
