### PR TITLE
GuideRate: avoid pointer semantics

### PR DESCRIPTION
**Pull request by akva2**
As far as I can tell there is no reason to use pointer semantics here. Since it causes grief for my serialization efforts, I chose to simply remove them. If I missed something, do make fun of me..

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
i don't quite understand why the size of the map matters, but okay then, I will have to find a more complicated solution.

**Comment by atgeirr** [comment]
> The [`GudeRateValue`](https://github.com/OPM/opm-common/blob/b034c914832073df696c3dc1631b51dc95fc3649/opm/output/data/GuideRateValue.hpp#L32) object is rather large so storing pointers instead reduces the size of the containing map.

I did not understand this (and also prefer avoiding pointers...)?

**Comment by bska** [comment]
> > The [`GudeRateValue`](https://github.com/OPM/opm-common/blob/b034c914832073df696c3dc1631b51dc95fc3649/opm/output/data/GuideRateValue.hpp#L32) object is rather large so storing pointers instead reduces the size of the containing map.
> 
> I did not understand this

You mean apart from the obvious, I take it, that
```C++
sizeof(GuideRateValue) > sizeof(std::unique_ptr<GuideRateValue>)
```
(the latter is typically equal to `sizeof(GuideRateValue*)`.) Otherwise, it's not clear to me how to respond.

**Comment by atgeirr** [comment]
Sure, the pointer object is smaller, but is there a reason to avoid large value objects in maps? (The total memory used is not any less.)

**Comment by akva2** [comment]
Obviously the map will reduce in size as such, but the amount of memory in use is still the same, it's just "manually" managed through pointers, rather than letting the map handle that. We are not copying this thing since these are unique_ptr's. So the only rationale I can see is that there are lots of nullptr entries in there for some reason, but looking at the  usage it seems to me that an instance is immediately created so no, I don't get it.

**Comment by bska** [comment]
> So the only rationale I can see is that there are lots of nullptr

There are not, but `map<key, small_and_movable>` is easier to move than `map<key, large_and_non_movable>`.

**Comment by bska** [comment]
> is there a reason to avoid large value objects in maps

Typically yes.  Every operation becomes more expensive when the value type is large since the map **typically** stores collections of something like
```C++
struct _Map_node { std::pair<const _Key, _Value> _x; /* other members */ };
```
internally.

**Comment by atgeirr** [comment]
> Typically yes. Every operation becomes more expensive when the value type is large since the map **typically** stores collections of something like

Thanks for your explanation, it is a good point.

However, in this case the GRValState is just 40 bytes AFAICT, so @akva2 if this makes life easier for you, and avoids worse hacks, then I am in favour of this change.

**Comment by akva2** [comment]
https://github.com/OPM/opm-common/pull/3393/commits/7c3c0016b13a1fce684684060a70dcb9a273b817#diff-11b16a4fb4c321a41c3b84e397316e78185546e23065cd63c39db8d6858434a3R153

it's not too bad as such so it's not very crucial.

**Comment by blattms** [comment]
Funny discussion. I especially like the argumentation about map / _Map_node. But don't you use an unordered_map, which might have a linked list for each bucket? I'll better shut up...

**Comment by bska** [comment]
> But don't you use an unordered_map, which might have a linked list for each bucket?

Kinda.  I'm sure they do something more clever, but as a mental model, GCC's implementation of `unordered_map<>` looks like this
```C++
template <typename _Key, typename _Value, /* ... */>
class unordered_map
{
public:
    // Interface mandated by C++ standard...

    pair<iterator, bool> insert(const pair<const _Key, _Value>& x)
    {
        size_t __hash_code = hash{}(x);
        _Node* __n = _Get_New_Node(__hash_code, x);
        auto __b = _Get_Bucket(__hash_code);
        _Node* __start = __buckets[__b];
        _Node* __end = __buckets[_Get_Next_Bucket(__hash_code)];
        while (__start != __end) {
            if (__start->__value == x) {
                return { iterator(__start), false };
            }
            if (_Can_Insert_At(__start, x)) {
                _Insert(__start, __n);
                return { iterator(__start), true };
            };
            ++__start;
        }
        _Insert(__end, __n);
        return { iterator(__end), true };
    }

   // Other members

private:
    struct _Node {
        size_t __hash_code;
        pair<const _Key, _Value> __value;
        _Node* __next;
        // Other members
    };

    _Node* __first;
    vector<_Node*> __buckets;
};
```
In other words, GCC's `unordered_map<>` is, at least conceptually, a huge linked list of `_Node`s, but with a bucket-like accelerator structure based on hash codes.

**Pull request closed without merging**
