### PR TITLE
New keywords

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
@akva2 : I guess you know already  - but it looks like jenkins needs an :ambulance: 

For your effort: :bouquet:

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
yes, it's a mess. i cannot figure out why, all hell broke lose when i updated to the newest version provided by debian :/

**Pull request merged**
