### PR TITLE
fixed: avoid unused parameters when built without embedded python

### PR DESCRIPTION
**Pull request by akva2**

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Fine by me.  Another option is to tag the parameters as `[[maybe_unused]]` instead.

**Comment by akva2** [comment]
i don't like to use maybe_unused in code paths where things are definitely not used but i can do that if you prefer of course.

**Comment by akva2** [comment]
jenkins build this please

**Comment by bska** [comment]
> i don't like to use maybe_unused in code paths where things are definitely not used

I appreciate that, but I think I prefer the tag in this situation.  I find it to be slightly more maintainable than having to use the preprocessor to generate two different function headers and making sure the braces match up.

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks a lot for the updates.  Please merge when green.

**Pull request merged**
