### PR TITLE
update redhat packaging

### PR DESCRIPTION
**Pull request by akva2**
new boost::filesystem usage requires a newer boost.

### CODE REVIEW

**Comment by blattms** [comment]
Looks like black-magic because of taking boost from mariadb

**Comment by akva2** [comment]
i know but it's the only packaged version available. it does the job..

**Comment by blattms** [comment]
backported to release via #1172

**Comment by bska** [comment]
> new `boost::filesystem` usage requires a newer boost.

Just out of curiosity.  were you able to determine the kind of Boost.Filesystem usage in our code that requires linking to more recent versions of Boost?

On a related note, I see that we're still looking for [Boost 1.44](https://github.com/OPM/opm-common/blob/e9367d5116583bce7a57de08d78877bed2940911/opm-common-prereqs.cmake#L19-L20) in our `*-prereqs.cmake` files.  Maybe we should update these to reflect the actual requirements?  On my own development box I have Boost Versions 1.63 and 1.70 and I usually use the latter for my primary day-to-day work.

**Comment by akva2** [comment]
well, 1.48 is too old, causing a lot of build errors due to a missing implicit std::string constructor. on the other hand, the 1.53 in centos7 built fine, but it failed during linking (likely an abi issue) - so 1.53 should have been enough as such. bumping to 1.58 worked. as 1.58 is also the version in ubuntu xenial, that seems like a sane minimum.

**Comment by bska** [comment]
> so 1.53 should have been enough as such. bumping to 1.58 worked. as 1.58 is also the version in ubuntu xenial, that seems like a sane minimum.

Thanks for the information.  I agree with your assessment.  We should raise the minimum Boost version to 1.58 (or C++17 with `std::filesystem` 😉 ).  Boost 1.58 was [released](https://www.boost.org/users/history/) in April of 2015 and it's not entirely unreasonable to expect OPM users to have that.

**Comment by akva2** [comment]
Yes, in fact updating to a newer c++ revision would make it easier to support the old rhels.

**Pull request merged**
