### PR TITLE
WIP: include ewoms in travis build testing

### PR DESCRIPTION
**Pull request by joakim-hove**
Comments appreciated. This will include ewoms building in the general build chain; if/when this is merged I will add the necesary .travis.yml file to the ewoms repository.

### CODE REVIEW

**Comment by joakim-hove** [comment]
Some of the ewoms test fails:
```txt
Unable to find executable: skip_test_dummy
55/56 Test #55: test_stokes .........................***Not Run   0.00 sec
      Start 56: tutorial1
56/56 Test #56: tutorial1 ...........................   Passed    0.74 sec
79% tests passed, 12 tests failed out of 56
Total Test time (real) = 1272.53 sec
The following tests FAILED:
	  6 - finger_immiscible_ecfv (Not Run)
	  7 - finger_immiscible_vcfv (Not Run)
	  8 - finger_immiscible_ecfv_adaptive (Not Run)
	  9 - test_navierstokes (Not Run)
	 10 - test_stokes2c (Not Run)
	 11 - test_stokesni (Not Run)
	 46 - fracture_discretefracture (Not Run)
	 49 - co2injection_ncp_ni_ecfv_parallel (Not Run)
	 50 - obstacle_immiscible_parallel (Not Run)
	 51 - lens_immiscible_vcfv_parallel (Not Run)
	 52 - lens_immiscible_ecfv_parallel (Not Run)
	 55 - test_stokes (Not Run)
Errors while running CTest
```
all failures are because it can not find the executable `skip_test_dummy`. The configuration only includes `dune-localfunctions` - not the optional dune dependencies: `dune-fem` and `dune-alugrid`.

**Comment by akva2** [comment]
that is expected. andreas insists on marking the tests as not run instead of silently not adding them to the list of tests and there is no smooth way to do this in cmake < 3.3 or thereabout. in the jenkins scripts there is specific code to "handle" this (ignore exit status 8 iirc).

**Comment by joakim-hove** [comment]
> that is expected. andreas insists on marking the tests as not run instead of silently not adding them to the list of tests

Hmmm - that was unfortunate; this seems like a complete show-stopper to me?!

**Comment by akva2** [comment]
well, not if you can bypass the exit code and return 0 to the shell nontheless as done for jenkins.

**Comment by joakim-hove** [comment]
> well, not if you can bypass the exit code and return 0 to the shell nontheless as done for jenkins.

That is of course in principle right; but why-oohh-why start creating separate executables to run ctest and then special case non-zero exit codes there. Without knowing @andlaus reason for this particular setup I would strongly suggest just not adding the tests in the configuration phase. What are the conditions for adding / not adding the tests?

**Comment by akva2** [comment]
lacking optional dependencies. i've had this discussion with andreas, and as i said, he insists. we just have to deal with it.

**Comment by joakim-hove** [comment]
> lacking optional dependencies

OK- maybe the dependencies (`dune-fem` and `dune-alugrid` ??) should be marked as `REQUIRED` then?

**Comment by akva2** [comment]
@andlaus you argue your case.

**Comment by andlaus** [comment]
> That is of course in principle right; but why-oohh-why start creating separate executables to run ctest and then special case non-zero exit codes there. Without knowing @andlaus reason for this particular setup I would strongly suggest just not adding the tests in the configuration phase. What are the conditions for adding / not adding the tests?

as @akva2 wrote: the `not run` tests are due to missing optional dependencies. IMO it is very useful to know that a test is present but was not run and I definitively like to keep that feature. (Note that it would be much simpler not to add the test at configure time than the current solution.) Further, the reason for the `skip_test_dummy` hack is that when I originally wrote this macro, the only way  cmake (version 2.8, I think) would display such a test as "(not run)" was to point it to a non-existent binary. more modern cmake versions can use a special exit code for this, but I suppose that the oldest cmake version which we need to support doesn't.

 > OK- maybe the dependencies (dune-fem and dune-alugrid ??) should be marked as REQUIRED then?

For your own benefit, I'd strongly prefer to keep optional dependencies non-mandatory because they are not required in many contexts that are relevant in practice, i.e., I don't want to cause more pain to people than strictly necessary. I suppose they would (rightfully) complain otherwise:

- dune-alugrid is only required if the test uses an unstructured grid (e.g., the test for the discrete fracture model). In particular ECL simulators like OPM *don't* need it.
- dune-fem is only needed if grid adaptivity is to be used. (and even if dune-fem is available, grid refinement is only enabled for simulations if `--enable-grid-adaptation=true` is passed to the binary
- the opm-{parser,core,grid} dependencies are only required for people who want to do ECL simulations
- there are some optional dependencies like quadruple precision math, superLU or UMFPack which you don't want to install on your system or which you want/need to disable for other reasons: e.g., libquadmath is only available on GCC and it slows down the tests which use it by a factor of 10.

note that IMO it would be beneficial to move the ECL simulation stuff into its own module which has hard dependencies on everything required for that. The main reason I did not push this more aggressively so far is that I've heard rumours that some people are generally opposed to adding new modules...

**Comment by joakim-hove** [comment]
OK:

>IMO it is very useful to know that a test is present but was not run and I definitively like to keep that feature.

Well - the test is actually *not* present; due to the missing dependencies it has not even been compiled. The fact that there is some - for this particular configuration - dead test code lying around is in my opinion not interesting enough to make special case hoops for it. If you have suggestions for simple modifications to the Travis build setup which will give 'normal' test behavior I would be happy to merge/implement it, otherwise this PR will be closed.

**Comment by andlaus** [comment]
how about adding a "-DSHOW_DISABLED_CTESTS={YES,NO}"  cmake option for travis? that would be pretty simple to implement I guess...

**Comment by joakim-hove** [comment]
> how about adding a "-DSHOW_DISABLED_CTESTS={YES,NO}" cmake option for travis? that would be pretty simple to implement I guess...

Yes - that would  be possible; but it is not about *showing* the disabled tests, but rather whether they should be added to ctest setup at all. So - the `-DADD_DISABLED_TESTS=OFF` must be passed at *configure* time; depending on how the intricate the "add_test" macros are in ewoms that should be quite doable.

**Comment by andlaus** [comment]
does #164 work for you?

**Comment by joakim-hove** [comment]
OK - this is continued in #165 - closing.

**Pull request closed without merging**
