### PR TITLE
Segment sorting - check if already in order

### PR DESCRIPTION
**Pull request by joakim-hove**
Fixup to: https://github.com/OPM/opm-common/pull/1731#issuecomment-618028278

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
Thanks.  This does indeed make my checked-iterator build go through.  It looks good to me so I'll merge into master.

**Comment by joakim-hove** [comment]
> This does indeed make my checked-iterator build go through. It looks good to me so I'll merge into master.

Thanks for the help with testing.

**Pull request merged**
