### PR TITLE
Determine Python include directory to fix docker pypi builds

### PR DESCRIPTION
**Pull request by blattms**
Whenever OPM_ENABLE_PYTHON is on we need to set PYTHON_INCLUDE_DIRS as it is needed to find Python.h (shouldn't we even need to link the library?). This could (in theory) be done by using by issuing `find_package(Python3 REQUIRED COMPONENTS Interpreter Development)` or `find_package(PythonLibs REQUIRED)`.

Unfortunately, both do not work (for yet unknown reasons) when we build pypi packages in docker (even with setting the PYTHON_EXECUTABLE or Python3_EXECUTABLE correctly).

Hence we now use python manually to determine these. Additionally we skip using the Python3 library as an impoted target directly and use the full path.

### CODE REVIEW

**Comment by blattms** [comment]
There might still some skeletons in Python closet. 

Why on earth don't we always need to link to the python library if we use Python?

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
Concerning skeletons I am seeing this in the docker images:
```
In file included from /usr/include/boost169/boost/python/detail/is_xxx.hpp:8,
                 from /usr/include/boost169/boost/python/detail/is_auto_ptr.hpp:9,
                 from /usr/include/boost169/boost/python/detail/copy_ctor_mutates_rhs.hpp:8,
                 from /usr/include/boost169/boost/python/detail/value_arg.hpp:7,
                 from /usr/include/boost169/boost/python/object/forward.hpp:10,
                 from /usr/include/boost169/boost/python/object/pointer_holder.hpp:16,
                 from /usr/include/boost169/boost/python/to_python_indirect.hpp:10,
                 from /usr/include/boost169/boost/python/converter/arg_to_python.hpp:10,
                 from /usr/include/boost169/boost/python/call.hpp:15,
                 from /usr/include/boost169/boost/python/object_core.hpp:14,
                 from /usr/include/boost169/boost/python/object/class.hpp:9,
                 from /usr/include/boost169/boost/python/class.hpp:13,
                 from /usr/include/boost169/boost/python/suite/indexing/indexing_suite.hpp:9,
                 from /usr/include/boost169/boost/python/suite/indexing/vector_indexing_suite.hpp:9,
                 from cxx/deck_keyword.cpp:1:
/usr/include/boost169/boost/python/detail/is_auto_ptr.hpp:17:40: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   17 | BOOST_PYTHON_IS_XXX_DEF(auto_ptr, std::auto_ptr, 1)
      |                                        ^~~~~~~~
/usr/include/boost169/boost/detail/is_xxx.hpp:20:4: note: in definition of macro ‘BOOST_DETAIL_IS_XXX_DEF’
   20 |    qualified_name< BOOST_PP_ENUM_PARAMS_Z(1, nargs, T) >        \
      |    ^~~~~~~~~~~~~~
/usr/include/boost169/boost/python/detail/is_auto_ptr.hpp:17:1: note: in expansion of macro ‘BOOST_PYTHON_IS_XXX_DEF’
   17 | BOOST_PYTHON_IS_XXX_DEF(auto_ptr, std::auto_ptr, 1)
      | ^~~~~~~~~~~~~~~~~~~~~~~
```

So we are using boost-python, too? :fearful:

**Comment by blattms** [comment]
Tested with the pypi-docker stuffs. Warnings are a bit scary, but building succeeds.

**Comment by blattms** [comment]
@akva2 Pypi failed in docker with recent CMake 3.17.5

**Comment by akva2** [comment]
pybind11 is a reimplementation/simplification/extraction of boost::python.

**Comment by blattms** [comment]
shameless self merge to restore nightly builds.

**Comment by blattms** [comment]
And indeed pypi nightly builds work again.

It just would put my mind add ease to know why CMake's Python library detection does not work with the docker images. Any insight is highly appreciated.

**Pull request merged**
