### PR TITLE
store temperature for all wells not just injectors

### PR DESCRIPTION
**Pull request by totto82**
See OPM/opm-simulators#4263

### CODE REVIEW

**Review by bska — COMMENTED** [review]
I guess it's fine to **store** the temperature value for all wells, but we should be very careful not to **use** the value in the case of production wells.  In other words, every call to `Well::temperature()` must be preceded by a check for whether or not the well is an injector.

**Comment by totto82** [comment]
> I guess it's fine to store the temperature value for all wells, but we should be very careful not to use the value in the case of production wells. In other words, every call to Well::temperature() must be preceded by a check for whether or not the well is an injector.

I can add the "throw std::runtime_error("Can not ask for temperature in a producer");" back to the well->temperature() method that will make it safer and force usage only after it is labeled an injector. 

The main reason for storing the temperature unconditionally is that you may have a workflow that sets WTEMP first and later WCONINJE when the injection starts. With the current code this will lead to injection with default temperature i.e. approx 15C.

**Comment by bska** [comment]
> > I guess it's fine to **store** the temperature value for all wells, but we should be very careful not to **use** the value in the case of production wells. In other words, every call to `Well::temperature()` must be preceded by a check for whether or not the well is an injector.
> 
> I can add the `throw std::runtime_error("Cannot ask for temperature in a producer")` back to the `Well::temperature()` method that will make it safer and force usage only after it is labeled an injector.

Yes please.

> The main reason for storing the temperature unconditionally is that you may have a workflow that sets WTEMP first and later WCONINJE when the injection starts.

This is an extension compared to what the commercial simulator offers as far as I can tell, and I'm fine with relaxing restrictions as long as we don't end up doing something that will prevent us from adding other features later.  For what it's worth, the other simulator requires that a well already be an injector before assigning injection fluid temperature through `WTEMP`.

**Comment by bska** [comment]
jenkins build this opm-simulators=4263 please

**Comment by blattms** [comment]
Review comments seem to be  addressed and jenkins is green. Merging.

**Pull request merged**
