### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by andlaus**
this fixes two smaller issues I ran into on a freshly installed ubuntu 16.04 system. Although it seems to Work for Me (TM), the second patch may cause some trouble on systems with newish cmake versions and should thus be further tested before it is merged.

@akva2: can I trigger jenkins builds for this module?

### CODE REVIEW

**Comment by andlaus** [comment]
jenkins build this with downstreams please

**Comment by andlaus** [comment]
@akva2: did you have time to look at this? it's kind of inconvenient having to patch the build system if blas is not installed...

**Comment by akva2** [comment]
first is fine, second is more scary. are you certain there we do not depend on the old policy anywhere?

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Comment by andlaus** [comment]
> are you certain that we do not depend on the old policy anywhere?

no I'm not sure, but it Works for Me (TM). Giving Jenkins a good shake and doing some local testing is thus probably a good idea. ;)

**Comment by akva2** [comment]
sigh. the build chain is broken again. if i was king heads would be rolling by now.

will look into this again as soon as integrity is restored.

**Comment by andlaus** [comment]
ok. thanks.

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Comment by andlaus** [comment]
seems like jenkins is happy, too? (on the other hand, I might have just misinterpreted it ...)

**Comment by akva2** [comment]
looks fine. merging.

**Pull request merged**
