### PR TITLE
Restore Explicit THP Control Options from Restart File

### PR DESCRIPTION
**Pull request by bska**
In particular, this PR restores all `WVFPEXP`-related items from the restart file's `IWEL` array.

### CODE REVIEW

**Comment by bska** [comment]
This PR depends on, and contains, PR #3110 and must not be merged until that PR is installed on the master branch.  I'm therefore creating this PR in "draft" mode.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
Upstream PR #3110 has been merged into the master branch.  Marking this as "ready for review" now.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
I think I'd like to get this PR into the master branch now.  Unless anyone objects I intend to merge it no later than noon CEST on Tuesday the 4th of October 2022.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by blattms** [comment]
Looks good (given my non-existing knowledge of this). Merging.

**Pull request merged**
