### PR TITLE
Implement support for GECON keyword

### PR DESCRIPTION
**Pull request by hakonhagland**
Implements support for the GECON keyword. Note that restart IO support has not been added yet. See also companion PR https://github.com/OPM/opm-simulators/pull/4819 in opm-simulators for more information.

### CODE REVIEW

**Comment by hakonhagland** [comment]
jenkins build this opm-simulators=4819 please

**Comment by hakonhagland** [comment]
jenkins build this opm-simulators=4819 please

**Comment by hakonhagland** [comment]
jenkins build this opm-simulators=4819 please

**Comment by hakonhagland** [comment]
Hmm the [jenkins build](https://ci.opm-project.org/job/opm-common-PR-builder/6108/console) seems to have problems with linking `bin/test_equil`:
```
/usr/bin/ld: lib/libopmsimulators.a(ParallelSerialization.cpp.o): in function `void Opm::Schedule::pack_unpack<Opm::GroupEconProductionLimits, Opm::Serializer<Opm::Mpi::Packer> >(Opm::Serializer<Opm::Mpi::Packer>&)':
ParallelSerialization.cpp:(.text._ZN3Opm8Schedule11pack_unpackINS_25GroupEconProductionLimitsENS_10SerializerINS_3Mpi6PackerEEEEEvRT0_[_ZN3Opm8Schedule11pack_unpackINS_25GroupEconProductionLimitsENS_10SerializerINS_3Mpi6PackerEEEEEvRT0_]+0x3c7): undefined reference to `void Opm::GroupEconProductionLimits::serializeOp<Opm::Serializer<Opm::Mpi::Packer> >(Opm::Serializer<Opm::Mpi::Packer>&) const'
/usr/bin/ld: ParallelSerialization.cpp:(.text._ZN3Opm8Schedule11pack_unpackINS_25GroupEconProductionLimitsENS_10SerializerINS_3Mpi6PackerEEEEEvRT0_[_ZN3Opm8Schedule11pack_unpackINS_25GroupEconProductionLimitsENS_10SerializerINS_3Mpi6PackerEEEEEvRT0_]+0x54f): undefined reference to `void Opm::GroupEconProductionLimits::serializeOp<Opm::Serializer<Opm::Mpi::Packer> >(Opm::Serializer<Opm::Mpi::Packer>&) const'
collect2: error: ld returned 1 exit status
```
This file links fine on my laptop, so I cannot reproduce. I had a similar problem when linking `test_Serialization.cpp` in opm-common see:

https://github.com/OPM/opm-common/blob/bec10dbfbe7c9e691c6a3f60932248b3a6756412/src/opm/input/eclipse/Schedule/Group/GroupEconProductionLimits.cpp#L105

this was fixed by including the template specialization into the .cpp file as shown there. Any idea how to fix this?

**Comment by akva2** [comment]
serializeOp implementation should be kept in the header, that's how it is designed. simply don't put that in the cpp file for the class.

**Comment by hakonhagland** [comment]
> serializeOp implementation should be kept in the header

@akva2 Thanks!

**Comment by hakonhagland** [comment]
jenkins build this opm-simulators=4819 please

**Comment by hakonhagland** [comment]
jenkins build this opm-simulators=4819 please

**Pull request merged**
