### PR TITLE
Fix output of LET curves by taken into account the connate saturations

### PR DESCRIPTION
**Pull request by totto82**

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
The test failure is expected. I have compared the output in ResInsight and the endpoints that where negative(with swmin) are now correct.

**Review by bska — APPROVED** [review]
Looks good to me.  I'll update the reference solutions and merge this into the master branch.

**Comment by bska** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=1176 please

**Comment by bska** [comment]
The updated reference solutions have been installed on the CI system.  I'll merge this into master now to activate the new logic.

**Pull request merged**
