### PR TITLE
RSEG: Index Results by Segment Number

### PR DESCRIPTION
**Pull request by bska**
This commit switches the segment result reload code to indexing the RSEG vector primarily by the segment number from the input file. The original scheme of using the linear index and extracting the segment number from ISEG was based on a terrible misunderstanding [%].

This is the second half of commit 0a730d94 (PR #697)

[%] Pointy Hat: @bska

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
> The original scheme of using the linear index and extracting the segment number from ISEG was based on a terrible misunderstanding [%].

Not correctly differentiating between a plain runnning index, and an actual quantity in the Eclipse domain is a classic; I fear there might be other such misunderstandings in the code.

**Comment by joakim-hove** [comment]
I guess this should be considering for merging together with https://github.com/OPM/opm-simulators/pull/1592 - when the test failures there are clarified I have no objections to merging this.

**Comment by bska** [comment]
> I guess this should be considering for merging together with [OPM/opm-simulators#1592](https://github.com/OPM/opm-simulators/pull/1592)

Yes, that's the intention of this PR.

> > The original scheme of using the linear index and extracting the segment number from ISEG was based on a terrible misunderstanding.
> 
> Not correctly differentiating between a plain running index, and an actual quantity in the Eclipse domain is a classic; I fear there might be other such misunderstandings in the code.

True.  I will definitely keep my eye out for similar inconsistencies.

**Pull request merged**
