### PR TITLE
also compile tests marked `ONLY_COMPILE` on `make test-suite`

### PR DESCRIPTION
**Pull request by andlaus**
this surfaced while doing OPM/ewoms#220.

### CODE REVIEW

**Comment by atgeirr** [comment]
Looks fine, will merge when green.

**Comment by atgeirr** [comment]
jenkins build this with downstreams please

**Comment by atgeirr** [comment]
@andlaus please investigate why Jenkins fails, to see if there is an error in the PR or a Jenkins hiccup.

**Comment by akva2** [comment]
virtual memory exhausted: Cannot allocate memory

**Comment by atgeirr** [comment]
> virtual memory exhausted: Cannot allocate memory

So it's a Jenkins problem? What to do?

**Comment by akva2** [comment]
until compiler is bumped i see no other solution than to build with less threads. the ewoms derived simulators eats 4 gb a pop and when 2 jobs run in parallel, we can only afford about 4 build threads. (currently 4 per job).

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Pull request merged**
