### PR TITLE
Create library in opm-common

### PR DESCRIPTION
**Pull request by joakim-hove**
The main purpose of this PR is to tickle the build system into creating a new library `libopmcommon`, and ensure that the full build chain still works.

The actual content - `class DataContainer` - is meant to be used as a base class for / replacment for the `class ReservoirState` in opm-core - but that is somewhat into the future.

### CODE REVIEW

**Comment by joakim-hove** [comment]
Ahhh - sorry; the `testDataContainer.cpp` file should not be included. Update coming.

**Comment by akva2** [comment]
buildsystem side is fine.

**Comment by joakim-hove** [comment]
> buildsystem side is fine.

Since this was for all practical purposes mostly a build system fix; I will merge now.

**Comment by atgeirr** [comment]
> Since this was for all practical purposes mostly a build system fix; I will merge now.

That is fine. For the actual DataContainer class (whose role here is just to ensure things actually work) we should agree on its interfaces before starting to change the state classes, for example I think that we should make it possible to use it for well states, too.

**Comment by andlaus** [comment]
I'd like to have it renamed to `BigDataContainer` just to have a buzzword ;)

seriously: I think the name of that class is much too generic since it is intented to store scalar fields (or vector fields if you assume some ordering) on grids and not for general data (and even for that it would be too generic, because it does not say what approach it uses internally: is it an associative container, is it a list, an array, ...?)

**Comment by joakim-hove** [comment]
> I think the name of that class is much too generic since it is intented to store scalar fields (or vector fields if you assume some ordering)

I am more than happy to change the name, the reason `DataContainer` was chosen instead of e.g. `FieldContainer` was to be ready for well data in addition to the current scalar fields.

**Comment by andlaus** [comment]
how about `GridDataContainer`?

**Comment by atgeirr** [comment]
> how about GridDataContainer?

If we want to store well data there, that name is not quite good either. What about SimulationDataContainer?

**Comment by joakim-hove** [comment]
> SimulationDataContainer?

I like that; changing name will be simple anyway.

**Comment by GitPaean** [comment]
From my side, this PR causes the building error in OPM/opm-material#116. 

The observation shows that `opm-common_INCLUDE_DIR` is not included in the `opm-material_INCLUDE_DIRS` for unclear reason.

**Pull request merged**
