### PR TITLE
Deck refactor2

### PR DESCRIPTION
**Pull request by joakim-hove**
This is a contunation of: #2850

Downstream:
https://github.com/OPM/opm-material/pull/485
https://github.com/OPM/opm-grid/pull/559
https://github.com/OPM/opm-simulators/pull/3704
https://github.com/OPM/opm-upscaling/pull/350

### CODE REVIEW

**Comment by joakim-hove** [comment]
Original comment copied from: https://github.com/OPM/opm-common/pull/2850#issuecomment-971710907
```C++
#include<iostream>
#include<tuple>
struct A{
    static constexpr int id = 0;
    double data;
};

struct B{
    static constexpr int id = 1;
    double data;
};


struct Cont
{
    template<class T>
    auto& operator()(const T&, int) 
    {
        return std::get<T::id>(data);
    }
    template<class T>
    auto& operator[](const T&){
        return std::get<T::id>(data);
    }
    std::tuple<A,B> data;
};

int main(){
    Cont c;
    c[A()].data=10.0;
    std::cout << c[A()].data << " "<< c(A(), 0).data <<std::endl;
}
```

**Comment by joakim-hove** [comment]
Original comment copied from: https://github.com/OPM/opm-common/pull/2850#issuecomment-971743574

> maybe we should prevent specifying template parameters and even use operator() as a shortcut

For what it's worth, the following overload set allows dispatching on whether or not a data member named name exists

```C++
#include <iostream>
#include <string>
#include <type_traits>
#include <utility>

namespace {
    template <typename, class = void>
    struct has_name : std::false_type {};

    template <typename T>
    struct has_name<T, std::void_t<decltype(T::name)>> : std::true_type{};

    struct S {
        std::string name{};
    };

    struct D {
        std::string operator[](const std::string& name) const
        {
            std::cout << "S::operator[const string&]\n";
            return name;
        }

        template <typename KW, std::enable_if_t<has_name<KW>::value, void**> = nullptr>
        std::string operator[](const KW& kw) const
        {
            std::cout << "S::operator[const KW&]\n";
            return (*this)[kw.name];
        }
    };
}

int main()
{
    const auto d = D{};
    const auto x1 = d["hello"];
    const auto x2 = d[S{}];

    std::cout << "x1 = |" << x1 << "|, x2 = |" << x2 << "|\n";
}
```

**Comment by joakim-hove** [comment]
Thank you for interesting suggestions; I really do not manage to see through what is best. My wishes can be summarized as:

1. Shorter and less typing than the current `getKeyword()` - this PR has the super short `[]`.
2. Make more (100%) use of the `ParserKeywords::XX` classes for lookup.

The suggestion from @blattms and @bska look interesting, what rubs me slightly the wrong way is that in both cases you actually need to create an instance of class  `ParserKeyword::XX`? The member we are differentiating on (i.e. `std::string name`) is `static` - would that help? Could also make use of a `static int id = ??` as suggested by @blattms.

The current PR does not change anyway when it comes to `"PORO"` &leftrightarrow; `ParserKeywords::PORO` but it solves/addresses consistency aspects. So I am tempted to merge this now - and then come back to a variety of the alternatives presented by @blattms / @bska. 

In addition it has been a goal to have a more explicit behavior when it comes to keywords which have multiple occurences in the deck (current master just takes the last). With this PR you must excplicitly use `back()`

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
> in both cases you actually need to create an instance of class `ParserKeyword::XX`?

No way to avoid that if you're going to use `operator[]()` as the main accessor.

**Comment by joakim-hove** [comment]
jenkins build this opm-material=485 opm-grid=559 opm-simulators=3704 please

**Comment by joakim-hove** [comment]
jenkins build this opm-material=485 opm-grid=559 opm-simulators=3704 opm-upscaling=350 please

**Comment by joakim-hove** [comment]
jenkins build this opm-material=485 opm-grid=559 opm-simulators=3704 opm-upscaling=350 please

**Comment by joakim-hove** [comment]
jenkins build this opm-material=485 opm-grid=559 opm-simulators=3704 opm-upscaling=350 please

**Comment by joakim-hove** [comment]
jenkins build this opm-material=485 opm-grid=559 opm-simulators=3704 opm-upscaling=350 please

**Comment by joakim-hove** [comment]
jenkins build this opm-material=485 opm-grid=559 opm-simulators=3704 opm-upscaling=350 please

**Comment by joakim-hove** [comment]
jenkins build this opm-material=485 opm-grid=559 opm-simulators=3704 opm-upscaling=350 please

**Comment by joakim-hove** [comment]
OK - this is not perfect; but it is an improvement - IMHO. I'll merge

**Pull request merged**
