### PR TITLE
Fix Dimension of D-Factor Correlation 'A' Coefficient

### PR DESCRIPTION
**Pull request by bska**
We were missing the `Area` component.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by totto82** [comment]
Thanks for noticing. I did all the testing on metric so I didn't notice this. Please merge when green.

**Comment by bska** [comment]
> Please merge when green.

Build check is green.  Merging this now.

**Pull request merged**
