### PR TITLE
Module renaming

### PR DESCRIPTION
**Pull request by atgeirr**
Rename dune-cornerpoint to opm-grid.

Follow-up pull requests do appear in downstream modules.

### CODE REVIEW

**Comment by atgeirr** [comment]
That should be it. I'll try to pull off Jenkins builds of these.

**Comment by atgeirr** [comment]
It would be good if one of @akva2, @joakim-hove, @andlaus, @bska or @dr-robertk would volunteer to test this I'd feel confident that it is good. The Jenkins builds succeded (and that is a great feature, thanks a lot Arne Morten).

**Comment by akva2** [comment]
i'm on it.

**Comment by akva2** [comment]
1) sibling builds pass fine
2) sibling-with-build-dir-as-siblings pass to the extent it used to pass. there's still the limitation of no ERT sibling in this mode and that you have to set OPM_COMMON_ROOT explicitly.
3) dunecontrol pass fine-ish, there's still the problem with the explicit setting of the _DIR variable for opm-common but that is not caused by these PRs. i did not test using the .. let me constrain myself to a simple 'hacky' .. configure wrappers if you run dunecontrol without --use-cmake.
4) install builds pass fine as evident on jenkins.

all good (or at least no new issues introduced by this work). great work. merge!

**Comment by atgeirr** [comment]
Thanks, I'll merge the entire chain and send a message to the mailing list.

**Pull request merged**
