### PR TITLE
Activate GRUPTREE, WGRUPCON and WELSPECS for use in PYACTION, tests a…

### PR DESCRIPTION
**Pull request by lisajulia**
…re in opm-tests

### CODE REVIEW

**Comment by lisajulia** [comment]
jenkins build this opm-simulators=5345 opm-tests=1157 please

**Comment by lisajulia** [comment]
After this is merged, PR1157 of opm-tests can be merged as well and then as the last one PR5345 of opm-simulators.
Thanks!

**Comment by lisajulia** [comment]
jenkins build this opm-simulators=5345 opm-tests=1157 please

**Review by akva2 — APPROVED** [review]
I See nothing to review here ;)

**Comment by lisajulia** [comment]
jenkins build this opm-simulators=5345 opm-tests=1157 please

**Comment by lisajulia** [comment]
@akva2 or @bska: Can have a look and merge or tell me what I still need to change here?
This PR activates the keywords GRUPTREE, WGRUPCON and WELSPECS for use in PYACTION, the tests are in opm-tests https://github.com/OPM/opm-tests/pull/1157 and they get compared to the respective ACTIONX files with the changes in https://github.com/OPM/opm-simulators/pull/5345, so no wild changes :)

**Pull request merged**
