### PR TITLE
Execute tests in parallel for the 'check' target

### PR DESCRIPTION
**Pull request by akva2**
I was tasked with enabling parallel test execution by default. Sadly CMake does not allow use to customize the built-in test target.

You can run tests in parallel using 'make test ARGS=-jN' , or equivalently using 'ctest -jN'. But you cannot set a default value for the ARGS environment variable for the test target.

The 'check' target, however, is our custom target to build and execute tests. Here I can enable this by default. This is the closest I can get to automated parallel execution.

@alfbr

### CODE REVIEW

**Comment by alfbr** [comment]
Thanks for the fix and clarification! If I understand correctly, with this patch I can run make check instead of make test to enable parallel execution of tests?

The ProcessorCount function from cmake simplifies nicely the code, but it does not allow us to extract physical cores (instead of logical cores). Hence, ideally we should divide the number of CPUs from ProcessorCount by two when running the tests.

**Comment by akva2** [comment]
that's the idea. the ProcesorCount.cmake claims it returns the number of physical cores. i'll double check a little.

**Comment by akva2** [comment]
which indeed is a lie. using another call now that is supposed to give physical.

**Comment by alfbr** [comment]
Excellent, this is perfect from my end.

**Comment by akva2** [comment]
no protests? self-merge in 2h if i hear nothing.

**Pull request merged**
