### PR TITLE
Multregt edit

### PR DESCRIPTION
**Pull request by joakim-hove**
Comment from second commit:

        /*
          This is a quite contrived piece of code to work around a peculiarity
          in Eclipse: If the MULTREGT keyword is present in the EDIT section it
          will *only* be taken into account if the EDIT section also contains
          the keywords TRANX, TRANZ and TRANZ - otherwise it will be ignored.
        */

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by totto82** [comment]
Thanks. Testing in progress.....

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by totto82** [comment]
Flow now gives a warning but when I compare TRANZ it seems like MULTREGT is still applied.

**Comment by joakim-hove** [comment]
This turnded out to not be required; will make a micro PR with a warning.

**Pull request closed without merging**
