### PR TITLE
added: use cmake mechanisms to enable c++11 with cmake >= 3.1

### PR DESCRIPTION
**Pull request by akva2**
as a bonus it makes it easy to experiment with c++14

### CODE REVIEW

**Comment by pgdr** [comment]
Just adding a minor remark that, as far as I know, `cmake 3.1` is not (and won't be?) available on Redhat 6.

I would be _very_ happy if someone corrected me on that belief.

**Comment by akva2** [comment]
hence the fallback to old behavior.

**Comment by akva2** [comment]
travis timed out, using jenkins.

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Comment by atgeirr** [comment]
Looks very reasonable (adding `?w=1' to the URL in the files changed view is a lifesaver), will merge when green.

**Comment by atgeirr** [comment]
> travis timed out, using jenkins.

I notice that is seems to have stopped at the same place here as in #185. Could it be indicating a problem?

**Comment by jokva** [comment]
Maybe, but both local builds and jenkins succeed with no problems.

**Pull request merged**
