### PR TITLE
add the S[WG]LPC and IS[WG]LPC keywords

### PR DESCRIPTION
**Pull request by andlaus**
they are just like their non-PC postfixed counterparts, except that they only apply to capillary pressures, not to the relperms and they seem to overwrite the values specified via S[WG]L for the capillary pressures but not for relperms.

### CODE REVIEW

**Comment by andlaus** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
> except that they only apply to capillary pressures, not to the relperms and they seem to overwrite the values specified via S[WG]L

you just got to love the consistency ... :-)

**Comment by andlaus** [comment]
yeah, ECL is fun...

**Comment by bska** [comment]
> > except that they only apply to capillary pressures, not to the relperms and they seem to overwrite the values specified via S[WG]L

That's only partly true.  The `S{W,G}LPC` keywords do indeed apply to the capillary pressure curves, but if the value is defaulted/unspecified in a cell then the connate saturation defaults to that of the `S{W,G}L` keyword.  If that is **also** defaulted/unspecified in the cell, then the connate saturation is that of the unscaled table for the cell's region.

**Comment by bska** [comment]
By the way, this actually matters a lot if we're ever going to write out scaled end-points to the `.INIT` file.  Unspecified/defaulted scaled saturation values are supposed to be output as `-1.0E+20` so if we're ever going to write these, then we'll need to know which values were defaulted.

**Comment by andlaus** [comment]
> The S{W,G}LPC keywords do indeed apply to the capillary pressure curves, but if the value is defaulted/unspecified in a cell then the connate saturation defaults to that of the S{W,G}L keyword. 

yes, but this is done like this already?!

**Comment by andlaus** [comment]
is there any good reason not to merge this?

yes, the default initializer for these grid properties could use the values of the non-*PC variants but this would either require access to the eclipse state object in the initializer (last time I tried this, the patch was rejected due to the cyclical dependency of the eclipse state and the property) or **a lot** of copy and paste with almost the guarantee that these two keyword families will drift apart in the future. Also, if the SWLPC keyword is specified, there hopefully will never be many cells that are defaulted and that are explicitly specified by SWL.

**Comment by joakim-hove** [comment]
No - there is probably not a good reason not to merge it, but I must admit I have not really understood the situation yet. I will look properly into tomorrow.

**Comment by joakim-hove** [comment]
> yes, the default initializer for these grid properties could use the values of the non-*PC variants but [...]

yes - I agree that the 3D properties system has not aged very well, it is on the list for improvements .... in particular that includes more fine grained control over what has been defaulted and not.

For now I suggest you add Bård's comment as a comment in the code, and I will merge this.

**Comment by andlaus** [comment]
jenkins build this please

**Comment by andlaus** [comment]
quite verbose comments added. (I would like to enter them into the "longest comments in opm-common" competition ;))

**Comment by andlaus** [comment]
jenkins build this please

**Comment by andlaus** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
This has been green on Jenkins several times already?

**Comment by andlaus** [comment]
yes, but the commit ID has changed because of the change of message requested by @bska, so I figured that it does not hurt to jenkins it again...

**Comment by joakim-hove** [comment]
OK - I'll push Green when Jenkins is in the green

**Pull request merged**
