### PR TITLE
Co2BrinePvt: encapsulate EclipseState w/ friends

### PR DESCRIPTION
**Pull request by akva2**
And move some logging to OpmLog instead of cerr.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks.  I'll merge into master.

**Comment by bska** [comment]
> Thanks. I'll merge into master.

Just a quick heads-up following this PR: This makes OPM-Common depend on Dune and we'll need to link our main library to dune lest we get build failures like
```
/home/bska/work/opm/src/opm.kdev/opm-common/src/opm/material/fluidsystems/blackoilpvt/BrineCo2Pvt.cpp
In file included from /home/bska/work/opm/src/opm.kdev/opm-common/opm/material/components/SimpleHuDuanH2O.hpp:36,
                 from /home/bska/work/opm/src/opm.kdev/opm-common/opm/material/fluidsystems/blackoilpvt/BrineCo2Pvt.hpp:33,
                 from /home/bska/work/opm/src/opm.kdev/opm-common/src/opm/material/fluidsystems/blackoilpvt/BrineCo2Pvt.cpp:25:
/home/bska/work/opm/src/opm.kdev/opm-common/opm/material/common/Exceptions.hpp:32:10: fatal error: dune/common/exceptions.hh: No such file or directory
   32 | #include <dune/common/exceptions.hh>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
```
on systems that don't have the Dune headers in a system directory.

**Comment by akva2** [comment]
Okay, I wanted to address the exception NIH, I guess I should do that now.

**Pull request merged**
