### PR TITLE
Convert UDA in GCONSALE and GCONSUMP 

### PR DESCRIPTION
**Pull request by totto82**

### CODE REVIEW

**Comment by joakim-hove** [comment]
This looks very good - I am glad to see others navigate the 'UDx' mess.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
>Copying shared_ptrs is expensive enough that we want to avoid it if possible.

OK - I have now read about the topic and realized that shared pointers are more expensive than I thought.

**Comment by totto82** [comment]
Thanks for the review.

**Pull request merged**
