### PR TITLE
Unit tests for writing of multisegment well (MSW) data to Eclipse Compatible restart file.

### PR DESCRIPTION
**Pull request by jalvestad**
Added unit tests for writing of multisegment well (MSW) data to Eclipse Compatible restart file. Added changes to allow for more general MSW structure allowing for discontinuous segment numbering.

### CODE REVIEW

**Comment by joakim-hove** [comment]
I will look into this later today/tomorrow. 

Just a minor tip: Your git commit messages will look nicer if you try to adhere the principles outlined here: https://chris.beams.io/posts/git-commit/

**Comment by jalvestad** [comment]
I consider this development as finished and the code is ready for final review and merging.

**Comment by joakim-hove** [comment]
Ok - I have looked at it already and had no significant comments, will merge quite soon.

You could remove the WIP marker.

**Comment by bska** [comment]
> I consider this development as finished and the code is ready for final review and merging.

Much appreciated!  Let's launch a Jenkins build first just to ensure that all tests pass.

**Comment by bska** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
OK - this needs a rebase after merging #653

**Comment by jalvestad** [comment]
I have now rebased this branch/pullrequest after the merge of #653.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Hmmm - this fails on jenkins; the PR seems to be a mix of new tests and some changes in MSW output code? Would it be advisable to split it in one test-only part, and one part which requires `update_data`? Anyway - @jalvestad / @bska probably know the best way forward.

**Comment by bska** [comment]
> Hmmm - this fails on jenkins

To be honest, I don't really see how this PR could be the cause of that failure, but I'll go through it carefully tonight.

That said, while I haven't looked at all of the tests yet, most seem to be of the general form "Something changed in well- or group-related summary and/or restart quantities".  This PR does indeed alter the code that creates segment and branch output (restart vectors `{I,R}SEG` and `ILB{R,S}`) and so could conceivably be the root cause of the [3D_MSW failure](https://ci.opm-project.org/job/opm-common-PR-builder/771/testReport/junit/(root)/mpi/compareECLFiles_flow_3D_MSW/), but that appears to be unrelated to segment/branch output&mdash;at least on the face of it.

**Comment by bska** [comment]
> I'll go through the failure list carefully tonight.

For reference: Here's the [permanent link to the failures of build 771](https://ci.opm-project.org/job/opm-common-PR-builder/771/#showFailuresLink)

Having read through all of those failures I don't see any symptom that points directly to this PR (#649) being the root cause.  Instead, my initial impression that 

> most seem to be of the general form "Something changed in well- or group-related summary and/or restart quantities".

is borne out by more thorough analysis.  All of the items that get flagged when comparing the restart files are rates and cumulatives at the connection/well/group/field levels. or the suggested next timestep (i.e., `DOUBHEAD[1]`) changes too much between the runs.

More speculatively, there was an update to the reference solutions (OPM/opm-tests#101, for OPM/opm-simulators#1743) that almost coincided with the [previous Jenkins run](https://github.com/OPM/opm-common/pull/649#issuecomment-470086416) so there **may** have been a race condition between this PR and that update.  I suggest we try to rerun Jenkins in the current state and if the symptom persists, then we need to do even more careful analysis.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
> jenkins build this please

That [passed](https://ci.opm-project.org/job/opm-common-PR-builder/774/).  Is there anything else we need to do here?

**Pull request merged**
