### PR TITLE
Add json file for OPTIONS3, E300.

### PR DESCRIPTION
**Pull request by berland**
Need to be able to have the schedule section manipulation  code support the E300 keyword OPTIONS3. Maybe adding this file is sufficient?

```python
import json
from collections import OrderedDict
keyw =  OrderedDict()
keyw["name"] = "OPTIONS3"
keyw["sections"] = ["RUNSPEC", "SCHEDULE"]
keyw["size"] = 1
keyw["items"] = []
for a in range(288):
    keyw["items"].append(OrderedDict(name="ITEM"+str(a+1), value_type="INT", default=0))
open('OPTIONS3.dirty', 'w').write(json.dumps(keyw))
```

```bash
jq . < OPTIONS3.dirty > OPTIONS3
```

### CODE REVIEW

**Comment by joakim-hove** [comment]
Close - you also need to add it the kewywordlust file two directories up

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins - get your act together - please

**Comment by bska** [comment]
jenkins build this please

**Pull request merged**
