### PR TITLE
Add UnitSystem functionality to handle eclipse integer id

### PR DESCRIPTION
**Pull request by joakim-hove**
To enable instantiating the unit system from a restart/init file. Writing of INTEHEAD keyword uses `UnitSystem` class instead of intermediate enum `RestartIO::UnitSystem` which has been removed.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
Will merge if/when green.

**Comment by joakim-hove** [comment]
Looks like there was a jenkins race - will try again

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this opm-upscaling=292 please

**Comment by bska** [comment]
All checks pass. Merging as advertised.

**Pull request merged**
