### PR TITLE
Remove #define INVALID_GROUP_RATE - just use 0

### PR DESCRIPTION
**Pull request by joakim-hove**
Minor preparation for Group2

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
I am sure nothing is broken by this, but do we need to distinguish an invalid rate from a zero rate?

**Comment by joakim-hove** [comment]
> I am sure nothing is broken by this, but do we need to distinguish an invalid rate from a zero rate?

I don't know - and all tests pass is good enough for me. The previous construction was a bit in the way of the `Group` &rightarrow; `Group2`refactoring.

**Pull request merged**
