### PR TITLE
Changes in schedule iterate section for restarts

### PR DESCRIPTION
**Pull request by joakim-hove**
**Changes in restart TimeMap and Schedule::iterateSection**

This commit changes two aspects of restarts where well and group information is
assembled from the restart file:

- We require the restart date to be present in the Schedule file as a DATES keyword.

- SKIPREST behavior is implemented unconditionally for restarts with restart files, even if the SKIPREST keyword is not present.

These changes came about when trying to fix the test failures in #1971

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by alfbr** [comment]
A more descriptive PR would be great :-)

**Comment by joakim-hove** [comment]
> A more descriptive PR would be great :-)

:-)

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Comments?

**Pull request merged**
