### PR TITLE
Delete GRUPRIG from OPM Flow Keyword List

### PR DESCRIPTION
**Pull request by OPMUSER**
GRUPRIG was both in the E100 and the OPM Flow keyword definitions. So delete the OPM Flow version. Need to run Jenkins, just in case

### CODE REVIEW

**Comment by joakim-hove** [comment]
The `GRUPRIG` keyword also occurs twice in the keyword list: https://github.com/OPM/opm-common/blob/master/src/opm/input/eclipse/share/keywords/keyword_list.cmake#L1095

**Comment by OPMUSER** [comment]
@joakim-hove why have it in one place when you can it in two :-). 

Will fix this as well.

**Comment by bska** [comment]
> GRUPRIG was both in the E100 and the OPM Flow keyword definitions. So delete the OPM Flow version.

Note that the two definitions are not exactly equal.  In particular, they have differing item names.  I don't **think** it matters in the current Flow development sources, but we need to be sure that any existing uses keep working when one of the definitions is removed.

**Comment by OPMUSER** [comment]
> Note that the two definitions are not exactly equal. In particular, they have differing item names. I don't think it matters in the current Flow development sources, but we need to be sure that any existing uses keep working when one of the definitions is removed.

Yes I know, Jenkins should trap any errors, correct? Also the E100 has a bit more descriptive variable names and it is in the correct place where people would check. I also have the keyword as being inactive, so we should be okay.

**Comment by OPMUSER** [comment]
PYEND keyword JSON definition is missing and also in : https://github.com/OPM/opm-common/blob/master/src/opm/input/eclipse/share/keywords/keyword_list.cmake#L1095

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
> Yes I know, Jenkins should trap any errors, correct?

Well - only to the extent that the code is tested.For this particualar topic the use of compiled names like `ParserKeywords::GRUPRIG::GROUP` will help catch errors.

**Comment by joakim-hove** [comment]
> PYEND keyword JSON definition is missing and also in

Well - there is no `PYEND` keyword?

**Pull request merged**
