### PR TITLE
Group uda

### PR DESCRIPTION
**Pull request by joakim-hove**
Evaluate UDA variables in GCONPROD and GCONINJE

Downstream: https://github.com/OPM/opm-simulators/pull/1959

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=1959 please

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=1959 please

**Comment by joakim-hove** [comment]
This is the final step in enabling UDA for groups; will merge tomorrow unless .... :-)

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=1959 please

**Comment by joakim-hove** [comment]
@totto82 : can you use this?

**Comment by totto82** [comment]
Great. Looks promising. Both this and the downstream PR looks fine. Please merge if its ready.

**Pull request merged**
