### PR TITLE
removing potential keywords from ALL in SUMMARY (attempt no. 2)

### PR DESCRIPTION
**Pull request by GitPaean**
most of the related information is in #914, #919 and #920 .

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by GitPaean** [comment]
jenkins build this opm-tests=154 please

**Comment by joakim-hove** [comment]
I am looking into this.

**Comment by joakim-hove** [comment]
I am sorry Kai - but this still does not cut it - looking at the opm-tests PR many restart files are updated, and they should be unmodified by this. I will call you shortly.

**Comment by GitPaean** [comment]
> I am sorry Kai - but this still does not cut it - looking at the opm-tests PR many restart files are updated, and they should be unmodified by this. I will call you shortly.

Please call me soon. I am leaving office soon. As commented in #914, https://github.com/OPM/opm-common/pull/914#issuecomment-519519502 , they should be updated. 

Basically, for these cases, there is not ALL in the SUMMARY section in the deck, and in the master branch, their well potentials values are not output to the RESTART files. 

With this PR, with the second commit, the well potentials values will be unconditionally output to the RESTART files no matter whether we have ALL in the SUMMARY section.

**Comment by GitPaean** [comment]
The only exception is the example 3D_WECON, it is explained in the comment https://github.com/OPM/opm-common/pull/914#issuecomment-519558130 and  https://github.com/OPM/opm-common/pull/914#issuecomment-519561086 . 

It is because in 3D_WCON, we put the RPTRST in the SCHEDULE section not in the SOLUTION section. 

AS a result, there is no request for outputting the RESTART file in the 0th report step.

**Comment by joakim-hove** [comment]
OK - thank your persisitence; even I understand this now. Merging!

**Pull request merged**
