### PR TITLE
Timestep fix

### PR DESCRIPTION
**Pull request by joakim-hove**
This is the work of @lars-petter-hauge : #343  - but due to some minor f.. I have completed it with one final micro commit.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this update_data please

**Comment by joakim-hove** [comment]
jenkins build this opm-data=354 please

**Comment by atgeirr** [comment]
@akva2 could we user this PR as an opportunity to test the opm-test functionality?

In any case, should we hold back merging data-updating PRs or are we good to go?

**Comment by akva2** [comment]
we could. also it's trivial to re-copy the data so no reason to let that hold anything back as such.

**Comment by joakim-hove** [comment]
> @akva2 could we user this PR as an opportunity to test the opm-test functionality?

I'll leave this PR open; feel free to (ab)use it as you like and merge when you see fit.

**Comment by totto82** [comment]
I have a colleague that is  waiting for this fix. I would prefer if this could be merged asap. (But of-course not before it is ready)

**Comment by joakim-hove** [comment]
From my side this is ready, I'll leave it to @akva2 to determine if the system changes are ready.

**Pull request merged**
