### PR TITLE
Adding support for DATES with time (HH:MM:SS.MICROSEC) in python/opm/utils/time_vector.py

### PR DESCRIPTION
**Pull request by vkip**

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by akva2** [comment]
need to add python3-pandas to debian/control

**Comment by vkip** [comment]
jenkins build this please

**Comment by notspiff** [comment]
pandas installed on ci box.

**Comment by notspiff** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
OK - this was a quite large dependency to pull in for one single function. Is it an option to inline the function in question?

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by vkip** [comment]
> OK - this was a quite large dependency to pull in for one single function. Is it an option to inline the function in question?

No problem getting around the dependency with a few extra lines of code, but: i) pandas is becoming a fairly standard package - likely to be useful elsewhere and might enter at some point anyway. ii) I'm lazy. 

Just insist and I'll fix it!

**Comment by joakim-hove** [comment]
> Just insist and I'll fix it!

I insist ;-)

**Comment by joakim-hove** [comment]
Apart from the pandas dependency this is fine.

**Comment by vkip** [comment]
> > Just insist and I'll fix it!
> 
> I insist ;-)

Was afraid of that.. :) Fixed.

**Comment by joakim-hove** [comment]
> Was afraid of that.. :) Fixed.

Mohahah - I just love the power ;-)

Thanks for the update - I'll kick Jenkins and merge.

**Comment by joakim-hove** [comment]
jenkins build this please

**Review by joakim-hove — APPROVED** [review]

**Pull request merged**
