### PR TITLE
Remove unused class SimulationDataContainer

### PR DESCRIPTION
**Pull request by joakim-hove**
Maybe it was a good idea - and also a good implementation(??) - but it is not used.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2795 please

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2795 please

**Comment by atgeirr** [comment]
While I could argue in favour of the original idea, at this point we should remove it. If we need to reinstate it we will.

**Comment by atgeirr** [comment]
In other words: Merge when green!

**Pull request merged**
