### PR TITLE
Release/2024.04 fix opm embedded

### PR DESCRIPTION
**Pull request by lisajulia**

### CODE REVIEW

**Comment by lisajulia** [comment]
jenkins build this please

**Comment by lisajulia** [comment]
jenkins build this please

**Comment by blattms** [comment]
To bad. I am still getting the same error on Ubuntu 2024.04:
```
193: Working Directory: /build/opm-common-2024.04~rc1+ds/obj-x86_64-linux-gnu/python
193: Test timeout computed to be: 1500
193: Fatal Python error: PyImport_AppendInittab: PyImport_AppendInittab() may not be called after Py_Initialize()
193: Python runtime state: initialized
193: 
193: Current thread 0x00007efdeb10a740 (most recent call first):
193:   File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
193:   File "<frozen importlib._bootstrap_external>", line 1289 in create_module
193:   File "<frozen importlib._bootstrap>", line 813 in module_from_spec
193:   File "<frozen importlib._bootstrap>", line 921 in _load_unlocked
193:   File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
193:   File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
193:   File "/build/opm-common-2024.04~rc1+ds/obj-x86_64-linux-gnu/python/opm/_common.py", line 12 in <module>
193:   File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
193:   File "<frozen importlib._bootstrap_external>", line 995 in exec_module
193:   File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
193:   File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
193:   File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
193:   File "/build/opm-common-2024.04~rc1+ds/obj-x86_64-linux-gnu/python/opm/io/parser/__init__.py", line 1 in <module>
193:   File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
193:   File "<frozen importlib._bootstrap_external>", line 995 in exec_module
193:   File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
193:   File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
193:   File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
193:   File "/build/opm-common-2024.04~rc1+ds/obj-x86_64-linux-gnu/python/opm/io/__init__.py", line 1 in <module>
193:   File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
193:   File "<frozen importlib._bootstrap_external>", line 995 in exec_module
193:   File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
193:   File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
193:   File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
193:   File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
193:   File "<frozen importlib._bootstrap>", line 1310 in _find_and_load_unlocked
193:   File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
193:   File "/build/opm-common-2024.04~rc1+ds/obj-x86_64-linux-gnu/python/tests/test_connection.py", line 3 in <module>
193:   File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
193:   File "<frozen importlib._bootstrap_external>", line 995 in exec_module
193:   File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
193:   File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
193:   File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
193:   File "/usr/lib/python3.12/unittest/loader.py", line 337 in _get_module_from_name
193:   File "/usr/lib/python3.12/unittest/loader.py", line 394 in _find_test_path
193:   File "/usr/lib/python3.12/unittest/loader.py", line 364 in _find_tests
193:   File "/usr/lib/python3.12/unittest/loader.py", line 372 in _find_tests
193:   File "/usr/lib/python3.12/unittest/loader.py", line 309 in discover
193:   File "/usr/lib/python3.12/unittest/main.py", line 160 in createTests
193:   File "/usr/lib/python3.12/unittest/main.py", line 253 in _do_discovery
193:   File "/usr/lib/python3.12/unittest/main.py", line 130 in parseArgs
193:   File "/usr/lib/python3.12/unittest/main.py", line 104 in __init__
193:   File "/usr/lib/python3.12/unittest/__main__.py", line 18 in <module>
193:   File "<frozen runpy>", line 88 in _run_code
193:   File "<frozen runpy>", line 198 in _run_module_as_main
193: Subprocess aborted
1/1 Test #193: python_tests .....................***Failed    0.04 sec
```

**Comment by blattms** [comment]
Not sure whether this helps, but I can trigger the same problem by just importing opm_embedded:
```
root@frau-mahlzahn:/build/opm-common-2024.04~rc1+ds/obj-x86_64-linux-gnu/python# ipython3 
/usr/lib/python3/dist-packages/IPython/paths.py:69: UserWarning: IPython parent '/home/mblatt' is not a writable location, using a temp directory.
  warn("IPython parent '{0}' is not a writable location,"
Python 3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.20.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import opm_embedded
Fatal Python error: PyImport_AppendInittab: PyImport_AppendInittab() may not be called after Py_Initialize()
Python runtime state: initialized

Thread 0x00007ff897f026c0 (most recent call first):
  File "/usr/lib/python3/dist-packages/IPython/core/history.py", line 827 in _writeout_input_cache
  File "/usr/lib/python3/dist-packages/IPython/core/history.py", line 844 in writeout_cache
  File "/usr/lib/python3/dist-packages/IPython/core/history.py", line 60 in only_when_enabled
  File "/usr/lib/python3/dist-packages/decorator.py", line 232 in fun
  File "/usr/lib/python3/dist-packages/IPython/core/history.py", line 899 in run
  File "/usr/lib/python3/dist-packages/IPython/core/history.py", line 60 in only_when_enabled
  File "/usr/lib/python3/dist-packages/decorator.py", line 232 in fun
  File "/usr/lib/python3.12/threading.py", line 1073 in _bootstrap_inner
  File "/usr/lib/python3.12/threading.py", line 1030 in _bootstrap

Current thread 0x00007ff89a1da740 (most recent call first):
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1289 in create_module
  File "<frozen importlib._bootstrap>", line 813 in module_from_spec
  File "<frozen importlib._bootstrap>", line 921 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "<ipython-input-1-82368e23dd9f>", line 1 in <module>
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 3553 in run_code
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 3493 in run_ast_nodes
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 3311 in run_cell_async
  File "/usr/lib/python3/dist-packages/IPython/core/async_helpers.py", line 129 in _pseudo_sync_runner
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 3106 in _run_cell
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 3051 in run_cell
  File "/usr/lib/python3/dist-packages/IPython/terminal/interactiveshell.py", line 904 in interact
  File "/usr/lib/python3/dist-packages/IPython/terminal/interactiveshell.py", line 911 in mainloop
  File "/usr/lib/python3/dist-packages/IPython/terminal/ipapp.py", line 317 in start
  File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 982 in launch_instance
  File "/usr/lib/python3/dist-packages/IPython/__init__.py", line 130 in start_ipython
  File "/usr/bin/ipython3", line 8 in <module>
Aborted
```

**Comment by blattms** [comment]
Same picture if I do `from opm.io.parser import Parser`

**Comment by lisajulia** [comment]
Hm.. I think that this problem has been there for longer, yet we did not see it because the manual check had been removed: https://github.com/OPM/opm-common/pull/4027/commits/b620f3ddb1e695ab45d9e3d47c50566995cc9c02#diff-50fef50151ea5817c0c49606693aeac2f11d9e809efc1f6bc426338ca413c2bfR38

**Pull request closed without merging**
