### PR TITLE
Indentation changes

### PR DESCRIPTION
**Pull request by joakim-hove**
The files `AggregateGroupData.cpp` and `AggregateGroupData.hpp` have slightly inconsistent indentation. As part of the `Group2` changes I need to make many - small changes to these files, and it is difficult to without affecting the indentation significantly - I have tried. Have therefor made this PR with only white space changes, when this is merged the real `Group2`related changes should not create additional white-space noise.

I have no strong feelings about this, and if someone else wants to submit a PR which makes the indentation in these files consistent that is fine by me. I will self merge this PR quite soon - morning of 24.th of July, because it is currently holding back the `Group2` changes.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Not to start a long discussion on the topic - do we have anything close to an agreement on the question of whether to indent inside namespaces, i.e.
```C++
namespace indent {
       
      double add(double x, double y) {
             return x + y;
      }

}
```
or
```C++
namespace no_indent {

double add(double x, double y) {
      return x + y;
 }

}
```

the current PR uses `no_indent` - I think our codebase as a whole is close to 50% of each?

**Comment by blattms** [comment]
I do not think we ever agreed on a coding standard. Yet there are at least some comments in the [wiki]( https://wiki.opm-project.org/index.php?title=Suggested_coding_standard). The example uses indentation for namespace. My emacs does not and it does what it wants and not want I want. But in this case I do not think that indentation gives us anything besides longer lines.

**Comment by bska** [comment]
I'm not going to drag out the discussion here, but I will say that this patch appears to have been generated by Emacs's `format-region` function.  That is the wrong tool for this job.  It doesn't really know about templates, lambdas, braced initializer lists or namespaces and therefore usually does a terrible job for C++.  If you wanted to convert the tabs to spaces and still stay within Emacs there is the `whitespace-cleanup` function which is a much more targeted approach.

**Comment by magnesj** [comment]
In resinsight er have used clang-format for a while om new code. We plan to auto format on save in the near future. Relevant for other opm modules? I can give a short demo if anyone is interested.

**Comment by bska** [comment]
> In resinsight we have used clang-format for a while om new code. [...] Relevant for other opm modules?

It is definitely relevant.  Clang-format is the right answer to this problem.  I suspect we will start implementing clang-format in the second half of this year.

**Comment by atgeirr** [comment]
There is no reason to wait: I have (sneakily...?) added a `.clang-format` file to opm-simulators that encapsulates what I think is good practice, of course we do not all agree on everything, but it should serve as a starting point. On the particular issue of outer namespace indentation I have come to think that we should drop the indentation for the outermost namespace (and the clang-format specification above does this). Only issue with using clang-format is getting emacs (or other editors) to format according to the spec without having to run clang-format separately. I am willing to switch editors if I find one that does this well! (Perhaps not vi though...)

**Comment by joakim-hove** [comment]
> I have (sneakily...?) added a .clang-format file to opm-simulators 

That sounds like a good start - are there also usage instructions there?

**Comment by atgeirr** [comment]
> usage instructions

(with .clang-format file in current dir or parent dirs, put it in ~/ to apply universally)
```
clang-format file.cpp # Sends formatted version to cout, file is unchanged.
clang-format -i file.cpp # Formats inline, modifying file.
```

**Comment by joakim-hove** [comment]
> Only issue with using clang-format is getting emacs (or other editors) to format according to the spec

For those of us to are addicted to the emacs poison there is `clang-format.el` package which has a `clang-format-region` function.

**Comment by atgeirr** [comment]
> For those of us to are addicted to the emacs poison there is `clang-format.el` package which has a `clang-format-region` function.

Thanks a lot!

**Comment by akva2** [comment]
Cluestick: use git-clang-format

**Comment by atgeirr** [comment]
> Cluestick: use git-clang-format

...but that requires maintainers to agree on using such a hook and what it should do, just using clang-format locally is a good starting point I think.

**Comment by akva2** [comment]
git clang-format is not a hook, it is purely a local helper. Allows running on working tree, for a set of comnits, etc.

**Comment by magnesj** [comment]
Here is a good article based on introduction of clang-format into an organization
https://engineering.mongodb.com/post/succeeding-with-clangformat-part-1-pitfalls-and-planning

**Comment by blattms** [comment]
On Wed, Jul 24, 2019 at 02:06:26AM -0700, Atgeirr Flø Rasmussen wrote:
> There is no reason to wait: I have (sneakily...?) added a
> `.clang-format` file to opm-simulators that encapsulates what I think
> is good practice,

That one does not work on my system:

clang-format failed with code 1: YAML:10:42: error: invalid boolean

**Comment by atgeirr** [comment]
> clang-format failed with code 1: YAML:10:42: error: invalid boolean

I think the AlwaysBreakTemplateDeclarations argument has changed from being a bool to taking the arguments {Yes, No, MultiLine}, see https://clang.llvm.org/docs/ClangFormatStyleOptions.html

Older clang-format used a bool: https://releases.llvm.org/5.0.2/tools/clang/docs/ClangFormatStyleOptions.html

So I think you must either update your clang-format to a newer version, or replace the 'Yes' with a 'true'.

**Pull request merged**
