### PR TITLE
Add keywords starting with R

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by blattms** [comment]
Just double checking: Marked for the release are Keywords with R and M, but not anothers. That means all other letters merged to master after PR 1091 (7 seven days ago) should not be in the release (I, J, K, L it seems)

**Comment by blattms** [comment]
backported to release via #1136

**Pull request merged**
