### PR TITLE
GroupTests: use raw string literals

### PR DESCRIPTION
**Pull request by akva2**
I noticed this while reading https://github.com/OPM/opm-common/pull/3609 

I'm fine with that going in first.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — COMMENTED** [review]
This is okay, I guess, but the two versions are not completely equivalent. The raw string literals have whitespace at the beginning of each line whereas the original version does not. Leading whitespace is strictly speaking not allowed, but our parser happens to accept that nonetheless.

**Comment by akva2** [comment]
Yeah I am aware the strings are not equivalent. I can nuke the whitespace if you prefer, just code looks slightly better with the indent.

**Comment by bska** [comment]
> I can nuke the whitespace if you prefer

Yes please.  As alluded to earlier, this PR in its current form switches valid input into an input string which is, **strictly speaking** invalid.  The format requires that keywords not be preceded by blanks on the same line.  The fact that our parser happens to accept leading blanks in this way is an accident and we should not depend on that behaviour.

> should I also update the existing strings?

If they have leading blanks on keyword lines then yes.  Otherwise, we can deal with those when we're making/preparing other changes.

**Comment by akva2** [comment]
done.

**Review by bska — APPROVED** [review]
Thanks a lot for the updates.  This looks very good to me now and I'll merge into master.

**Pull request merged**
