### PR TITLE
Add test revealing strange behavior when opening an initially shut well

### PR DESCRIPTION
**Pull request by lisajulia**
All connections to the well appear to be shut and therefore its closed in the 'end_report' function of the Schedule class
Is this supposed to be like this?

### CODE REVIEW

**Comment by GitPaean** [comment]
> All connections to the well appear to be shut and therefore its closed in the 'end_report' function of the Schedule class Is this supposed to be like this?

It might be a problem if in a later report step that you specify more COMPDAT keyword to add or change  connections. Did not check the detail code, it is possible that the later `COMPDAT` keyword will not be able to revive the well from being `SHUT`.

**Comment by lisajulia** [comment]
> > All connections to the well appear to be shut and therefore its closed in the 'end_report' function of the Schedule class Is this supposed to be like this?
> 
> It might be a problem if in a later report step that you specify more COMPDAT keyword to add or change connections. Did not check the detail code, it is possible that the later `COMPDAT` keyword will not be able to revive the well from being `SHUT`.

Thanks for the reply, I've removed the `COMPDAT` keyword now, but the problem is still there: the well remains shut.
What else could be the problem? :)

**Comment by GitPaean** [comment]
> Thanks for the reply! I've removed the COMPDAT keyword now, but the problem is still there: the well remains shut.
Was that what you meant? What else could be the problem? :)

Do you have more information regarding this? Without saying the actual DATA input, I can not understand the issue.

**Comment by lisajulia** [comment]
> > Thanks for the reply! I've removed the COMPDAT keyword now, but the problem is still there: the well remains shut.
> > Was that what you meant? What else could be the problem? :)
> 
> Do you have more information regarding this? Without saying the actual DATA input, I can not understand the issue.

Do you mean sth. other than this file? tests/msim/MSIM_ACTIONX.DATA

**Comment by GitPaean** [comment]
> Do you mean sth. other than this file? [tests/msim/MSIM_ACTIONX.DATA](https://github.com/OPM/opm-common/pull/3991/files#diff-ba4de264bd1d894690764b8f09a8f58652d74b824e597ba5965e29e75bfb9efc)

I mean the file. 

I am not familiar with ACTION, but from the view point of 

for this file, since there is no connection specified for the well `P1`, `WELOPEN` should not be able to open the well under any circumstances.

What do you want to achieve?

**Comment by GitPaean** [comment]
If the well has some valid connection initially, while its status is `SHUT`,
`WELOPEN` will be able to `OPEN` it with no problem.

**Comment by lisajulia** [comment]
Ok :) Thanks! This answers my question; I came across this when looking at tests opening and closing wells using an ACTIONX and PYACTION.

**Pull request closed without merging**
