### PR TITLE
Boost remove

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by atgeirr** [comment]
This looks ok. Un-WIP, test and merge? Or will you add more?

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by akva2** [comment]
you could probably pick and squash https://github.com/akva2/opm-common/commit/c38bef1f5518c31357d81f06551e254f225d7d2f

**Comment by joakim-hove** [comment]
> you could probably pick and squash akva2@c38bef1

Done

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Pull request merged**
