### PR TITLE
Add get method for LIFTOPT item 4.

### PR DESCRIPTION
**Pull request by hakonhagland**

### CODE REVIEW

**Comment by hakonhagland** [comment]
jenkins build this please

**Review by joakim-hove — APPROVED** [review]

**Comment by bska** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
That looks like a race condition - I'll rerun

**Comment by joakim-hove** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Build check succeeds.  Merging per prior approval.

**Pull request merged**
