### PR TITLE
Fix DeckItem Diagnostic Message

### PR DESCRIPTION
**Pull request by bska**
We would previously issue a message of the form

> No dimension has been set for item'X'; can not ask for SI data

This PR adds a space between the word "item" and the beginning quote of the item name.  We also rephrase the message slightly to read

> No dimension defined for item 'X'; cannot request SI data.

instead.  Finally, while here, also reduce code duplication.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Review by akva2 — APPROVED** [review]

**Comment by bska** [comment]
Oops&ndash;I merged #4101 too quickly.  I didn't notice that there were test failures.  I'll update the reference solutions from here...

**Comment by bska** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
jenkins build this please

**Comment by bska** [comment]
Merging per prior approval.

**Pull request merged**
