### PR TITLE
changed: output last log entry in branches for jenkins builds

### PR DESCRIPTION
**Pull request by akva2**
can help identifying issues with builds

### CODE REVIEW

**Comment by andlaus** [comment]
I want this!

**Comment by atgeirr** [comment]
Let's test it!

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by andlaus** [comment]
probably it is better to change this to

```
git log HEAD -1 | cat
```

because `git log` might go into interactive mode if it thinks to be run on a TTY.

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by andlaus** [comment]
I just verified that the git log entry of the last commit appears in the jenkins output. the printing ID seems to be a bit indirectly because for this PR it says

```
Checking out Revision 06d112f5f8b6dddc773d776e6ee245fe2806253d (refs/remotes/origin/pr/333/merge)
Commit message: "Merge e8ae254c0b32bcf24ee9978276bc6d7dc64f6e0c into 7d5aa7992282920629a152c5e6d37dde16d38887"
```

anyway, nice! @akva2: can this script still be manually invoked from the command line?

**Comment by akva2** [comment]
yes, local usage is described in the wiki. that's the only thing i can give you so you will have to stomach the indirections. it uses shallow clones from github.

**Comment by andlaus** [comment]
okay. if one does not need to manually quit a pager after `git log`, there are no issues which I can can come up with. Please merge.

**Comment by akva2** [comment]
you are right that in principle it can invoke a pager. the chance of a single log message being that long is small but not zero so i will change it.

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
All green, merging!

**Pull request merged**
