### PR TITLE
add group events

### PR DESCRIPTION
**Pull request by totto82**

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
This is very similar to the existing well based code and can be merged as is - but some suggestions to think of:

1. Instead of throwing an exception if a well/group does not exist you could introduce a "NULL_EVENT" and return that?

2. Since wells and groups are in the same namespace it is not strictly necessary to introduce a new map. Could just introduce the new enum values and use `WellGroup` instead of only `Well` in the existing api?

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by totto82** [comment]
1) Shouldn't there always be a group? Will not a "NULL_EVENT" just move the handling away from the problem?
2) Good point. That will minimize lines of code. Then we trust that well names and group names are different. I think that is assumed other places in the code as well.

**Comment by joakim-hove** [comment]
>Shouldn't there always be a group? Will not a "NULL_EVENT" just move the handling away from the problem?

At least one of us misunderstands here, but the situation I consider is when you ask for the events related to a well/group which does not have any events registered, although the well/group itself might be perfectly legitimate. In that case throwing might be a bit aggressive? (I know that is what the existing code does).

**Comment by totto82** [comment]
> At least one of us misunderstands here

I thought it was the "missing group" throw. Then I agree, but I don't think such a change belongs to this PR. I will fix point 2.

**Comment by joakim-hove** [comment]
Merge this when jenkins is green and you are ready with respect to downstream++

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by totto82** [comment]
Jenkins is green i opm-simulators. I will merge this.

**Pull request merged**
