### PR TITLE
Fix compile error when using clang.

### LINKED ISSUE #769: Linking error with  compareECL
I got the following linking error when compiling with `-DCMAKE_BUILD_TYPE=Release -DUSE_MPI=1`.
```
[ 50%] Linking CXX executable bin/compareECL
Undefined symbols for architecture x86_64:
  "void ECLFilesComparator::printValuesForCell<std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long, unsigned long, EGrid*, std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > > const&, std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > > const&) const", referenced from:
      void ECLRegressionTest::deviationsForNonFloatingPoints<std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > > >(std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > >, std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long) in libtestutil.a(EclRegressionTest.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/compareECL] Error 1
make[1]: *** [CMakeFiles/compareECL.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 50%] Building CXX object CMakeFiles/mocksim.dir/msim/src/msim.cpp.o
[ 50%] Linking CXX static library lib/libmocksim.a
[ 50%] Built target mocksim
make: *** [all] Error 2
```
I use clang version: 
```
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Am I missing something to compile it?

### PR DESCRIPTION
**Pull request by atgeirr**
This closes #769.

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
Note that this fix can hurt performance of the comparison program when comparing strings, I would be surprised if it was noticable in any way!

**Comment by atgeirr** [comment]
@akva2 there seems to be something wrong with Jenkins, still.

**Comment by bska** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
I do not understand the test failure, it seems to have something to do with Jenkins and/or GitHub but I am not sure.

**Comment by bska** [comment]
> I do not understand the test failure, it seems to have something to do with Jenkins and/or GitHub but I am not sure.

It is **possibly** the result of a race condition.  We should rerun the build check, but please hold while [build 930](https://ci.opm-project.org/job/opm-common-PR-builder/930/) is running.

**Comment by bska** [comment]
> > do not understand the test failure, it seems to have something to do with Jenkins and/or GitHub but I am not sure.
> 
> It is **possibly** the result of a race condition.

On second thought it might be a Jenkins system issue (out of memory? out of disk space?).  The failure mode of build 930, quoted below, doesn't make any sense in light of the changes in #724.

---

```
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
CMakeFiles/upscale_relperm_benchmark.dir/build.make:62: recipe for target 'CMakeFiles/upscale_relperm_benchmark.dir/benchmarks/upscale_relperm_benchmark.cpp.o' failed
make[2]: *** [CMakeFiles/upscale_relperm_benchmark.dir/benchmarks/upscale_relperm_benchmark.cpp.o] Error 4
make[2]: *** Deleting file 'CMakeFiles/upscale_relperm_benchmark.dir/benchmarks/upscale_relperm_benchmark.cpp.o'
CMakeFiles/Makefile2:2667: recipe for target 'CMakeFiles/upscale_relperm_benchmark.dir/all' failed
make[1]: *** [CMakeFiles/upscale_relperm_benchmark.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
c++: internal compiler error: Killed (program cc1plus)
```

**Comment by blattms** [comment]
Sorry couldn't help and made an alternative PR #772 that should have the same performance as the original but might add some compile time.

**Comment by joakim-hove** [comment]
I have no opinion on #771 versus #772 - suggest a duel Galaois style, since @mblatt is the challenger I suggest @atgeirr can choose weapon?!

**Comment by bska** [comment]
jenkins build this please

**Comment by blattms** [comment]
I do not care either which one gets merged. I just did mine to have some
template fun before I saw @atgeirr's proposal

**Pull request closed without merging**
