### PR TITLE
fixing -x option for compareECL program

### PR DESCRIPTION
**Pull request by tskille**
-x options should not have any arguments.

### CODE REVIEW

**Comment by tskille** [comment]
Example below comparing summary files. 6 extra summary vectors in second case. These are ignored when using this option. With this option we can make sure that all other summary vectors are within tolerances.

This option is working for SMRY, INIT, UNRST and RFT  

```
tskille@anfield:~/programming/opm/test_2112$ ../opm-common/build/bin/compareECL TEST1 TEST2 1e-5 1e-5 -t SMRY -x
Comparing 'TEST1' to 'TEST2'.

Loading EGrid TEST1.EGRID  ....  done.
Loading EGrid TEST2.EGRID  ....  done.

Loading summary file TEST1.SMSPEC  .... done

Loading summary file TEST2.SMSPEC  .... done

Comparing summary files 

Extra keywords (6) accepted in second file 

Checking 20  vectors  ...  done.

Program finished 
```

**Review by blattms — APPROVED** [review]
Just checked the code and this indeed is an option without arguments. Will just fire up jenkins

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
Thanks a lot for the fix.

**Pull request merged**
