### PR TITLE
Dynamicstate update equal

### PR DESCRIPTION
**Pull request by joakim-hove**
Small changes to support the atrocity `UDQ` in `ACTIONX`

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
opinions on this?

**Review by bska — COMMENTED** [review]
> Small changes to support the atrocity `UDQ` in `ACTIONX`

Sure, but what **are** those changes?  This PR changes a number of member functions to return `std::optional<>` objects which may make the interface harder to reason about.  What semantics are you trying to model and why is this a reasonable representation of those semantics?

**Comment by joakim-hove** [comment]
> Sure, but what are those changes? 

You are right - it is not much of a change; it turned out that most of the functionality which I intended to implement was already there. The return value of `update_equal()`has changed from `void` to `std::optional<std::size_t>`.

> This PR changes a number of member functions to return std::optional<> objects which may make the interface harder to reason about. What semantics are you trying to model and why is this a reasonable representation of those semantics?

These were drive by changes; I personally like `std::optional<T>` quite a lot. These functions are varieties of `find` which return an index - or an empty `std::optional<std::size_t>` if a matching index can not be found. Previously an `int` was used - and `-1` was used to signify "No such element" - I really prefer `std::optional<std::size_t>` to `int` and `-1`.

**Comment by bska** [comment]
> Previously an `int` was used - and `-1` was used to signify "No such element" - I really prefer `std::optional<std::size_t>` to `int` and `-1`.

Agreed, that's better.  Alternatively these functions could follow the STL's lead and return iterators with a return value of `end()` meaning "no such element`.  I'll merge into master.

**Pull request merged**
