### PR TITLE
Suggestion: Remove unsupported E300 keywords

### PR DESCRIPTION
**Pull request by joakim-hove**
See: https://github.com/OPM/opm-simulators/issues/2560#issuecomment-619741727

We now parse all(?) Eclipse100 keywords, and those not supported further than just loading into the deck are assembled in the `MissingFeatures` list in opm-simulators.

We support some E300 keywords, but that is very much on a need-to-support basis, and specifically we do *not* maintain a `MissingFeatures` list for the E300 keywords. This PR removes two E300 keywords which only have a json scheme but absolutely no further use/support. 

Feels a bit awkward to remove keywords - what do you say?

### CODE REVIEW

**Comment by joakim-hove** [comment]
Just a heads up: I am very uncertain about this one and will *not* merge myself unless someone clearly offers support in that direction.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by totto82** [comment]
If I remember correctly these keywords where added in the context of making a blackoil thermal simulator that does a bit more then the e100 version. Therefore E300 results was used for reference. At that time it was convenient to be able to run the same input file in e300 and flow. 

Maybe adding a supported e300 list for Flow that gives a warning to the user that Flow has encountered a e300 keyword and are fine with it is an option. But I am also fine with just merging this. Should not take much time to add them when(if) we need them.

**Comment by OPMUSER** [comment]
I think we just add them to MissingFeatures, like all the other keywords we ignore. I don't think having separate MissingFeatures list for E100 and E300 is a sensible approach, just combine them as one list. But this is just my two cents

**Comment by joakim-hove** [comment]
Mixed signals - I'll merge this.

**Pull request merged**
