### PR TITLE
removing SPECIAL from WPOLYMER definition

### PR DESCRIPTION
**Pull request by GitPaean**
it does not look like it is needed.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
it does not looks like the jenkins failure is related to this PR, 
```
######################
# Running test 'test_quadrature'
######################
executing "./bin/test_quadrature "
testing identity mapping...
WARNING (ignored): Could not open file 'alugrid.cfg', using default values 0 < [balance] < 1.2, partitioning method 'ALUGRID_SpaceFillingCurve(9)'.

You are using DUNE-ALUGrid, please don't forget to cite the paper:
Alkaemper, Dedner, Kloefkorn, Nolte. The DUNE-ALUGrid Module, 2016.

Created parallel ALUGrid<3,3,simplex,nonconforming> from input stream. 

/var/lib/jenkins/workspace/opm-common-PR-builder/deps/opm-models/bin/runtest.sh: line 82: 626237 Segmentation fault      "$TEST_BINARY" $TEST_ARGS
```

**Comment by akva2** [comment]
it's not, it's alugrid enablement which is stuck in review..

**Comment by bska** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks for cleaning up this left-over.  I'll merge into master.

**Pull request merged**
