### PR TITLE
[test] test the first commit of PR #914 

### PR DESCRIPTION
**Pull request by GitPaean**

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this opm-tests=146 please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by joakim-hove** [comment]
This one commit PR should not work.

**Comment by GitPaean** [comment]
> This one commit PR should not work.

It helps to check the problem. The things are not working as designed.

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
With this first commit, the following cases complained about the XGRP difference in RESTART files. 

```
mpi.compareECLFiles_flow+2D_H__
mpi.compareECLFiles_flow+3D_MSW
mpi.compareECLFiles_flow+2D_OILWATER_POLYMER
mpi.compareECLFiles_flow+2D_THREEPHASE_POLY_HETER
mpi.compareECLFiles_flow+3D_WECON
```

Other failures only complain about the missing keywords in the SUMMARY files, which is expected.

**Comment by GitPaean** [comment]
Checked all the UNRST files that complain, they are all due to zero values output probably related to well potentials.

It means, the options in SUMMARY can affects the output to the RESTART files. 

The decks that complains the XGRP in RESTART files all have `ALL` in `SUMMARY`, while not all the cases that have `ALL` complain.  It is not easy to tell why. 

The well potential values are all computed no matter we request it in the SUMMARY setup.

**Comment by bska** [comment]
Sorry to be blunt, but we're not going to get any further just looking at the final output files.

The content of those is directed by the values in the `SummaryState` object that gets passed into [`RestartIO::save()`](https://github.com/OPM/opm-common/blob/9875d5fbd8c3cc6a403a4db5f9fb20d41ee22ec2/opm/output/eclipse/RestartIO.hpp#L72-L80).  Specifically, the group-related quantities are [just copied](https://github.com/OPM/opm-common/blob/9875d5fbd8c3cc6a403a4db5f9fb20d41ee22ec2/src/opm/output/eclipse/AggregateGroupData.cpp#L389-L403) from `SummaryState` and directly into the `XGRP` vector (with `keys` being the [explicit list](https://github.com/OPM/opm-common/blob/9875d5fbd8c3cc6a403a4db5f9fb20d41ee22ec2/opm/output/eclipse/AggregateGroupData.hpp#L85-L97) from `AggregateGroupData.hpp`).

Therefore, the only thing that matters for the restart file is whether or not `SummaryState` changes between current master and the proposed PR #914.  If there are changes, then we need to track down their origins.  Chances are those changes come from one of two sources

  1. The actual potential rates reported from [`WellStateFullyImplicitBlackoil::report()`](https://github.com/OPM/opm-simulators/blob/0e309fc254a7d20016f1dc211ac54f5e0ca23954/opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp#L501)

  2. Incomplete potential rate handling in `Summary.cpp`, perhaps because we never actually call [`potential_rate()`](https://github.com/OPM/opm-common/blob/9875d5fbd8c3cc6a403a4db5f9fb20d41ee22ec2/src/opm/output/eclipse/Summary.cpp#L1007-L1012) for the affected wells and/or groups.

Before we have a reasonable explanation&mdash;and preferably a plan to correct it&mdash;I am opposed to merging #914.

**Comment by GitPaean** [comment]
I am not only checking the output files, while the output files are the starting points. 

And the information within WellStateFullyImplicitBlackoil::report() are same with this pull request. 

I just had a bad time in checking the content in `SummaryState`, my software is having problems in showing me what is inside `SummaryState`. And I had to turn to other business. 

About #914, it is just the correct thing to do to give the ALL option more correct interpretation, while it is surprising that the RESTART facility has some dependence on it.

**Comment by GitPaean** [comment]
Just putting information for later record. This PR is for testing purpose. 

With the case 2D_H__, with this PR, 

The data::wells has the same content from the WellState***:report(). 

The SummaryState contains less content in the group_values and well_values.

**Comment by GitPaean** [comment]
there are a few cases, having ALL in the summary and  reporting missing keywords in the summary files, while not complaining mismatching in the RESTART files, 

for example, 2D_POLYMER_INJECTIVITY and 2D_OW_CTAQUIFER . 

Although the well potential values are output to the SUMMARY files with the master branch, they are zero.  As a result, it does not make a difference that whether we output the well potential values to the RESTART files.

For example 2D_OW_CTAQUIFER, it has the E100 refernece. In the E100 reference, there is no well potential values output to the SUMMARY file, which is good and justifies the motivation of removing well potential values to the `ALL` in `SUMMARY`.

**Comment by GitPaean** [comment]
For the case, 2D_POLYMER_INJECTIVITY, 

Due to the big injection rate under BHP limit,  an exception is thrown in `IntervalTabulated2DFunction`, while it is never caught anywhere. But as a result, the well potential value calculation can not be finished, so that is why the well potential values are all zero. 

```
    template <typename Evaluation>
    Evaluation eval(const Evaluation& x, const Evaluation& y) const
    {
        if ((!xExtrapolate_ && !appliesX(x)) || (!yExtrapolate_ && !appliesY(y))) {
            std::ostringstream oss;
            oss << "Attempt to get undefined table value (" << x << ", " << y << ")";
            throw NumericalIssue(oss.str());
        };
```

**Comment by GitPaean** [comment]
For the case, 2D_FETKOVICHAQUIFER, 

the well potential calculation never gets converged, as a result, they are also all zero values.

**Comment by GitPaean** [comment]
So far, for this commit, the things look like working as expected (No detailed checking for all the cases.)

It removes the output of the well potential values to the SUMMARY files. 

RESTART outputting looks  like depending on the setup in the SUMMARY, not sure whether it should be the correct behavoir from the viewopoint of the deck setup or it is something that the implementation has to do this.

But it does increases significantly the complexity of the issue of cleaning up the content of ALL in SUMMARY.

**Comment by GitPaean** [comment]
jenkins build this please

**Pull request closed without merging**
