### PR TITLE
Some janitoring

### PR DESCRIPTION
**Pull request by akva2**
- Remove unused function
- Add missing initializers
- Remove unused variable

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks.  I'll merge once build check is successful.

**Comment by akva2** [comment]
jenkins build this please

**Comment by bska** [comment]
> I'll merge once build check is successful.

Build check is successful.  Thanks a lot.  I'll merge into master now.

**Pull request merged**
