### PR TITLE
Rebuild opm-common with Python3 on jenkins

### PR DESCRIPTION
**Pull request by joakim-hove**
This is not a real PR - rather a support request from the Jenkins master.

### CODE REVIEW

**Comment by akva2** [comment]
you want two builds, or just one build using python3 ?

**Comment by akva2** [comment]
imho a sane approach is we do two builds for the post-builder, but just one build up front, and for that target python 3. ie only post builder builds against python 2.7.

my existing the tooling is much better suited for this approach.

**Comment by joakim-hove** [comment]
> mho a sane approach is we do two builds for the post-builder, but just one build up front, and for that target python 3. ie only post builder builds against python 2.7.

Perfect!

**Comment by akva2** [comment]
Done. As a bonus, you can include 'python2' in trigger if you want to build a pr against py2.

**Comment by joakim-hove** [comment]
Thank you!

**Pull request closed without merging**
