### PR TITLE
Remove old well

### PR DESCRIPTION
**Pull request by joakim-hove**
This PR will remove the old Well implementation in opm-common, and base everythoing on the new `Well2` - is ready for review now.

Context: https://github.com/OPM/opm-common/pull/740, https://github.com/OPM/opm-common/pull/674

Downstream: 
https://github.com/OPM/opm-grid/pull/365
https://github.com/OPM/opm-simulators/pull/1815

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=365 opm-simulators=1815 please

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=365 opm-simulators=1815 please

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=365 opm-simulators=1815 please

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=365 opm-simulators=1815 please

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=365 opm-simulators=1815 please

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=365 opm-simulators=1815 please

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=365 opm-simulators=1815 please

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=365 opm-simulators=1815 please

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=365 opm-simulators=1815 please

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=365 opm-simulators=1815 please

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=365 opm-simulators=1815 please

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=365 opm-simulators=1815 please

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=365 opm-simulators=1815 please

**Comment by joakim-hove** [comment]
Look ma - jenkins approves; in only ... attempts!

**Comment by andlaus** [comment]
Based on recent experience, the big models should be run and the results should be checked manually before this is merged. (I'm about indifferent about the change itself, but it has a high potential for regressions?!)

**Comment by joakim-hove** [comment]
>Based on recent experience, the big models should be run and the results should be checked manually before this is merged. (I'm about indifferent about the change itself, but it has a high potential for regressions?!)

Absolutely - first #740 should be merged, and then somewhere down the line this is ready.

**Comment by joakim-hove** [comment]
OK - this has been in the working for a long time, and I am now keen to merge it. The main body of changes were merged in #740 - but this PR will actually start using the new well model. The current status of testing is:

- The normal test-suite works with the full new well model.
- For a relatively short list of proprietary models I have verified that the `checkWells()` test passes, but not actually simulated.

I will run through the proprietary models I have access to, but after that it is my intention to merge this ~ middle of next week.

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=365 opm-simulators=1815 please

**Comment by joakim-hove** [comment]
```
[ 84%] Building CXX object CMakeFiles/diffusion_pvs.dir/tests/diffusion_pvs.cc.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
```

I'll just try again - and hope that Heisenberg teams up?

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=365 opm-simulators=1815 please

**Comment by joakim-hove** [comment]
> I will run through the proprietary models I have access to, but after that it is my intention to merge this ~ middle of next week.

:heavy_check_mark:

**Comment by joakim-hove** [comment]
```
28 keywords exhibit failures
	FOPP: Summary file
		Fails for 49 entries
		Largest absolute error: 1.2160034e+00
		Largest relative error: 2.1551463e-03
        ....
```
it works on my machine ...

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=365 opm-simulators=1815 please

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=365 opm-simulators=1815 please

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=365 opm-simulators=1815 please

**Comment by akva2** [comment]
jenkins build this opm-grid=365 opm-simulators=1815 please

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=365 opm-simulators=1815 please

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=365 opm-simulators=1815 please

**Comment by joakim-hove** [comment]
Ok - this has been in the making for a long time. It passes all the jenkins tests, and also manual testing on the proprietary models I have access to.

I'll merge it now. But the well ode is complex and I will not exactly give up an arm and a leg if there is a regression.

**Pull request merged**
