### PR TITLE
Dimension string does not accept space

### PR DESCRIPTION
**Pull request by joakim-hove**
The code for parsing the dimensions string is not particularly robust or anything .... ;-)

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
@alfbr : can you confirm that this fixes your problem?

**Comment by alfbr** [comment]
Yes, this fixes my problem, thanks!

**Comment by joakim-hove** [comment]
> Yes, this fixes my problem, thanks!

Cool - merging

**Pull request merged**
