### PR TITLE
Add method WellSegments::segmentDepthChange()

### PR DESCRIPTION
**Pull request by joakim-hove**
Add utility function to calculate depth change of one segment

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
I'm getting a test failure in a checked iterator build (GDB backtrace below):
```
./bin/MultisegmentWellTests --run_test=MSW_BRANCH_SEGMENTS
...
/usr/include/c++/7/debug/safe_container.h:83:
Error: attempt to self move assign.

Objects involved in the operation:
    sequence "this" @ 0x0x5555570c9800 {
      type = __gnu_debug::_Safe_container<std::__debug::vector<int, std::allocator<int> >, std::allocator<int>, __gnu_debug::_Safe_sequence, true>;
    }
```
This comes from [swapping](https://github.com/OPM/opm-common/blob/cd8b32acac219d384f10f8bb0a20512aae6bee7b/src/opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.cpp#L491) a segment with itself. We must not do that, but I haven't tried to analyse whether this is common in a real case or just happens in the [test code](https://github.com/OPM/opm-common/blob/cd8b32acac219d384f10f8bb0a20512aae6bee7b/tests/parser/MultisegmentWellTests.cpp#L479).  That said, the arguments to [`find_if`](https://github.com/OPM/opm-common/blob/cd8b32acac219d384f10f8bb0a20512aae6bee7b/src/opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.cpp#L484) look a little suspicious.  While I haven't analysed the algorithm completely, I might possibly expect
```C++
segments.begin() + head_index + 1
```
as the first argument.

--- 

```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff68a3801 in __GI_abort () at abort.c:79
#2  0x00007ffff76e6789 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x000055555606a2d5 in __gnu_debug::_Safe_container<std::__debug::vector<int, std::allocator<int> >, std::allocator<int>, __gnu_debug::_Safe_sequence, true>::operator= (this=0x5555570c9800, __x=...)
    at /usr/include/c++/7/debug/safe_container.h:83
#4  0x000055555606798f in std::__debug::vector<int, std::allocator<int> >::operator= (this=0x5555570c9800) at /usr/include/c++/7/debug/vector:113
#5  0x0000555556067a1f in Opm::Segment::operator= (this=0x5555570c97f0) at /home/bska/work/opm/src/opm.kdev/opm-common/opm/parser/eclipse/EclipseState/Schedule/MSW/Segment.hpp:37
#6  0x0000555556067b5c in std::swap<Opm::Segment> (__a=..., __b=...) at /usr/include/c++/7/bits/move.h:199
#7  0x0000555556064be9 in Opm::WellSegments::branchSegments (this=0x5555570564f0, branch=1) at /home/bska/work/opm/src/opm.kdev/opm-common/src/opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.cpp:491
#8  0x0000555555f93c12 in MSW_BRANCH_SEGMENTS::test_method (this=0x7fffffffbb2e) at /home/bska/work/opm/src/opm.kdev/opm-common/tests/parser/MultisegmentWellTests.cpp:479

... Test Framework Functions Omitted ...
```

**Comment by joakim-hove** [comment]
> I'm getting a test failure in a checked iterator build (GDB backtrace below):

Thank you for the detailed testing - a possible fix is here: #1735 

>This comes from swapping a segment with itself. 

I did not know that was illegal; it can certainly happen in real life.

**Pull request merged**
