### PR TITLE
Enable 3D props testing in opm-simulators and opm-grid

### PR DESCRIPTION
**Pull request by joakim-hove**
This testing flag spreads all over the place; maybe not an entirely good approach after all ;-(

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this opm-material=376 please

**Comment by blattms** [comment]
Can someone enlighten me what the changes mean? Does it jenkins now only check with `-DENABLE_3DPROPS_TESTING=ON`?

Should we use `-DENABLE_3DPROPS_TESTING=ON` in production?

**Comment by joakim-hove** [comment]
> Does it mean that jenkins now only checks with -DENABLE_3DPROPS_TESTING=ON?

yes

> Should we use -DENABLE_3DPROPS_TESTING=ON in production?

no

More details here: https://github.com/OPM/opm-common/pull/1056

**Comment by blattms** [comment]
> > Does it mean that jenkins now only checks with -DENABLE_3DPROPS_TESTING=ON?
> 
> yes
> 
> > Should we use -DENABLE_3DPROPS_TESTING=ON in production?
> 
> no
> 
Sounds like a contradiction to me.
How am I supposed to work on something that uses the eclipse properties? Should I really do it twice?

**Pull request merged**
