### PR TITLE
fix path written to in-tree config file

### PR DESCRIPTION
**Pull request by akva2**
caused issues with dune-control based builds.

### CODE REVIEW

**Comment by atgeirr** [comment]
I am unsure how to test this in a good way. Travis got as far as opm-simulators before timeout, so we did not really get to exercise the path stuff. I guess a Jenkins run would detect harmful side effects so I'll start it, but that would not show any dune-control benefits.

**Comment by atgeirr** [comment]
jenkins build this with downstreams please

**Comment by akva2** [comment]
you cannot test this on either ci system, you have to either trust me or use dunecontrol locally.

**Comment by atgeirr** [comment]
OK, I'll trust you, then! (And deque the Jenkins job.)

**Pull request merged**
