### PR TITLE
changed: remove extra flags for ebos

### PR DESCRIPTION
**Pull request by akva2**
ebos is no more

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
This is great; now maybe we can resurrect: https://github.com/OPM/opm-common/issues/1127

**Comment by totto82** [comment]
> This is great; now maybe we can resurrect: #1127

That's another discussion. Even though we don't use ebos anymore we use the various compositional simulators in opm-models that don't use ecl input/output.

**Comment by joakim-hove** [comment]
> That's another discussion. Even though we don't use ebos anymore we use the various compositional simulators in opm-models that don't use ecl input/output.

OK - I understand

**Pull request merged**
