### PR TITLE
Add names to the arguments of the python functions of the EclipseState, Schedule, ScheduleState and Summary State

### PR DESCRIPTION
**Pull request by lisajulia**
And update the `python/opm_embedded/__init__.py` file

### CODE REVIEW

**Comment by lisajulia** [comment]
jenkins build this please

**Comment by lisajulia** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Review by blattms — APPROVED** [review]
Looks good to me and I would normally merge. I am holding back as you might have requested other reviews for a reason.

**Pull request merged**
