### PR TITLE
Uda value reset

### PR DESCRIPTION
**Pull request by joakim-hove**
The system for units does not really play nicely with the `UDAValue` class. This is a band aid fix.

The proper fix is to pass the dimension object along when constructing the UDAValue, but that will require quite invasive low-level changes to the deck construction code; will come back to that.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
> is a little too developer centred though. Hopefully a user will never actually see it, but if they do the word UDAValue won't make a lot of sense to them.

OK; I have tried to update the message slightly; I have opted not to add `ParseContext / ErrorGuard` handling of this - for several reasons:

1. This is a bug/limitation in opm/flow - and not really something the user has done wrong.
2. It is *impossible* to recover from.
3. It should eventually become irrelevant as the UDA support is expanded.

**Comment by bska** [comment]
> OK; I have tried to update the message slightly;

Much appreciated.  I'll merge the updated version.

> I have opted not to add `ParseContext` / `ErrorGuard` handling of this - for several reasons:

I didn't mean to suggest we should hook this up to that machinery, only that if there's even a slightest chance a user would see the message, then the message should preferably refer to entities in the user's context rather than an implementation classes. In this instance, I like that we acknowledge this as a limitation in OPM's support for UDAs.

**Pull request merged**
