### PR TITLE
Reduce g++-12 resource consumptions for generated parser files.

### LINKED ISSUE #3401: Long compile time with g++-12
Somehow compilation time skyrocketed (e.g. on Debian) with the move to g++12. Especially the ParserInit.cpp et al files take forever (4 times slower) and consumes up to 2 GB.

I have already started the process of refactoring (Not including all generated headers there but splitting ParserInit into multiple files ParserInitA, ..., there is another candidate). Let's see how far that gets us. But this is low priority for now.

Workaround would be to use ccache to compile these not to often.

### PR DESCRIPTION
**Pull request by blattms**
Compiling the generated sources (ParserInit.cpp and anything including Builtin.hpp) literally to an hour and more while eating up >>1 GB RAM.

The reason was that ParserInit.* and Builtin.hpp included all the generated headers and had code that used and even instantiated the all ParserKeywords in them. Now we split the functionality by the first character of the keywords and moved those to separate source files (ParserInitA.cpp, BuiltinA.cpp, ...) and headers (ParserInitA.hpp, ...). Also we removed the static members for each Keyword in Builtin. One can still get one with `Builtin::get_KEYWORD_NAME()`.
This reduced compile time quite drastically (tested on Debian testing).

Closes #3401

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
jenkins build this please

**Comment by bska** [comment]
I haven't looked at the details here in any way.  I just notice that we get [one new warning](https://ci.opm-project.org/job/opm-common-PR-builder/5574/gcc/new/) for each new `Builtin<K>.cpp` file added here.  All of them appear to be [using the parameter name `keywords`](https://github.com/OPM/opm-common/blob/995ec609e3d0dc357ffb10b06a00641894acca9e/src/opm/input/eclipse/Generator/KeywordGenerator.cpp#L141) which [shadows a member of `Builtin`](https://github.com/OPM/opm-common/blob/a407f57df13a181b25e6c0b06f5cc2dcf4eb7e2b/src/opm/input/eclipse/Generator/KeywordGenerator.cpp#L133).  Would you mind renaming one of those?  Possibly the data member (e.g., `keywords` :arrow_right: `keywords_` with a trailing underscore)?

**Comment by bska** [comment]
> Would you mind renaming one of those? Possibly the data member (e.g., `keywords` :arrow_right: `keywords_` with a trailing underscore)?

Come to think of it, since we're adding new member functions of class `Builtin`, we don't actually need the parameter at all.  Every `emplace<X>()` member function could just be generated along the lines of
```C++
void Builtin::emplaceA()
{
    this->keywords.emplace("AKEYWRD", AKEYWRD{});
    // ...
}
```
statements.

**Comment by blattms** [comment]
> Come to think of it, since we're adding new member functions of class `Builtin`, we don't actually need the parameter at all.

Brilliant idea. Done.

**Comment by blattms** [comment]
> Is there something particular about GCC 12 that causes this? I have not observed on clang at least (assuming you also refer to building in parallel here).

Yes, that is why the title says "g++-12".
BTW: This has nothing to do with parallel builds (except that we have more parallelism now). Basically ParserInit and Builtin were compiled after each other and because this took so long it was always only one make process at the end.

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
For those interested: in the build history of [Debian's buildd](https://buildd.debian.org/status/logs.php?pkg=opm-common&arch=amd64) you can see the jump up in compile time for 2022.04+ds-2+b1 when they rebuild with g++12 and down with this patch in 2022.10+ds-6.

**Review by akva2 — APPROVED** [review]
Looks good to me. A potential follow-up would be to de-interleave some of the raw strings to make the code more readable.

**Pull request merged**
