### PR TITLE
Refactor Deck to use a call to operator[] instead of method getKeyword()

### PR DESCRIPTION
**Pull request by daniepin**
Call to `operator[std::string].back()` replaces `Deck::getKeyword(std::string)`, 
`operator[size_t]` replaces  `Deck::getKeyword(size_t)` and  
`deck[std::string][size_t]` replaces  `deck.getKeyword(std::string, size_t)`

### CODE REVIEW

**Comment by bska** [comment]
I'd really prefer that we switch to using
```C++
Deck::getKeyword<KW>()
```
where possible instead.  E.g., to use
```C++
deck.getKeyword<ParserKeywords::PVTO>()
```
instead of
```C++
deck["PVTO"]
```
On the other hand, if we can make
```C++
deck[ParserKeywords::PVTO]
```
work then that's better still.

**Comment by joakim-hove** [comment]
>On the other hand, if we can make

We agree on the goal - and this is a step in that direction.

**Comment by joakim-hove** [comment]
Hmm - I am sorry to say that I had not crossed all t's and dotted all the i's (OK - I seldom do) in my mental model here. I can not see how the ideal solution:
```
deck[ParserKeywords::PVTO]
```
can be attained (happy to be proven wrong though). The alternative I suggest is: Stay with a function call ala `::getKeyword()` - but I would prefer to shorten to just `::get()` - and also stay with the change in semantics in this PR - i.e. the function returns a `DeckView` and let calling scope calls `back()`.

Opinions @bska

**Comment by blattms** [comment]
maybe we should prevent specifying template parameters and even use operator() as a shorcut along of the following lines:
```
#include<iostream>
#include<tuple>
struct A{
    static constexpr int id = 0;
    double data;
};

struct B{
    static constexpr int id = 1;
    double data;
};


struct Cont
{
    template<class T>
    auto& operator()(const T&, int) 
    {
        return std::get<T::id>(data);
    }
    template<class T>
    auto& operator[](const T&){
        return std::get<T::id>(data);
    }
    std::tuple<A,B> data;
};

int main(){
    Cont c;
    c[A()].data=10.0;
    std::cout << c[A()].data << " "<< c(A(), 0).data <<std::endl;
}
```

**Comment by joakim-hove** [comment]
>maybe we should prevent specifying template parameters and even use operator() as a shorcut along of the following lines:

Interesting!

**Comment by bska** [comment]
> maybe we should prevent specifying template parameters and even use `operator()` as a shortcut

For what it's worth, the following overload set allows dispatching on whether or not a data member named `name` exists
```C++
#include <iostream>
#include <string>
#include <string_view>
#include <type_traits>
#include <utility>

namespace {
    template <typename, class = void>
    struct has_name : std::false_type {};

    template <typename T>
    struct has_name<T, std::void_t<decltype(T::name)>> : std::true_type{};

    struct S {
        std::string name{};
    };

    struct D {
        std::string operator[](const std::string& name) const
        {
            std::cout << "S::operator[const string&]\n";
            return name;
        }

        template <typename KW, std::enable_if_t<has_name<KW>::value, void**> = nullptr>
        std::string operator[](const KW& kw) const
        {
            std::cout << "S::operator[const KW&]\n";
            return (*this)[kw.name];
        }
    };
}

int main()
{
    const auto d = D{};
    const auto x1 = d["hello"];
    const auto x2 = d[S{}];

    std::cout << "x1 = |" << x1 << "|, x2 = |" << x2 << "|\n";
}
```

**Comment by joakim-hove** [comment]
This is continued here: #2856

**Pull request closed without merging**
