### PR TITLE
Actionx

### PR DESCRIPTION
**Pull request by joakim-hove**
Add some basic initial functionality for the ACTIONX keyword. There is a long way left for a working ACTIONX implementation, but I will focus elswehere now.

This should be innocent to merge as is.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by akva2** [comment]
contains a merge.

**Comment by joakim-hove** [comment]
> contains a merge.

Fixed

**Comment by akva2** [comment]
the irony of a typo in the typo fix commit description is not lost on me ;)

**Comment by akva2** [comment]
other than that it looks fine to me.

**Comment by bska** [comment]
> the irony of a typo in the typo fix commit description is not lost on me ;)

https://en.wikipedia.org/wiki/Muphry%27s_law

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by akva2** [comment]
'Fix typo in keyword defintion' strike 2.

**Comment by joakim-hove** [comment]
jenkins build this please

**Pull request merged**
