### PR TITLE
Add Restart Support for Known Well Level Economic Limits

### PR DESCRIPTION
**Pull request by bska**
Notably missing are

  - Maximum gas-liquid ratio
  - Maximum temperature
  - Minimum reservoir fluid flow rate
  - Follow-on well

We do not currently write those items to the restart file but will extend the support as need arises.

### CODE REVIEW

**Comment by bska** [comment]
Note: I'm creating this in "draft" mode since the PR depends on, and initially contains, #3095 and must not be reviewed or merged before that PR is installed on the master branch.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
The upstream PR has been merged into master.  I'm marking this as "ready for review" and running a build check.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Review by akva2 — APPROVED** [review]
Can't say much about correctness of implementation, but code wise it looks good to me.

**Comment by bska** [comment]
Merging per approval.

**Pull request merged**
