### PR TITLE
FLOWS and FLORES support

### PR DESCRIPTION
**Pull request by daavid00**
See https://github.com/OPM/opm-simulators/pull/4275 and https://github.com/OPM/opm-models/pull/758 for rationale.

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this opm-models=758 opm-simulators=4275 please

**Comment by totto82** [comment]
jenkins build this opm-models=758 opm-simulators=4275 please

**Comment by totto82** [comment]
jenkins build this opm-models=758 opm-simulators=4275 please

**Comment by totto82** [comment]
jenkins build this opm-grid=607 opm-models=758 opm-simulators=4275 please

**Comment by blattms** [comment]
Please add some information and tests. Like this it seems rather opaque what nncid is and why it is needed.

**Comment by daavid00** [comment]
> Please add some information and tests. Like this it seems rather opaque what nncid is and why it is needed.

Thanks for the comment. In fact the extra entry for the non-neighboring connection id is not needed, I have modified the scripts accordingly. I will later add a test in opm-tests.

**Comment by totto82** [comment]
jenkins build this opm-models=758 opm-simulators=4275 please

**Comment by totto82** [comment]
jenkins build this opm-models=758 opm-simulators=4275 please

**Comment by totto82** [comment]
jenkins build this opm-models=758 opm-simulators=4275 please

**Comment by totto82** [comment]
benchmark opm-models=758 opm-simulators=4275 please

**Comment by totto82** [comment]
> benchmark opm-models=758 opm-simulators=4275 please

We did this not work?

**Comment by akva2** [comment]
For some reason please goes beforw specifiers.

**Comment by akva2** [comment]
benchmark please opm-models=758 opm-simulators=4275

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                              | Relative |
| ------- | ------------------------------------------ | -------- |
| opm-git | OPM Benchmark: drogon - Threads: 1         | 0.997    |
| opm-git | OPM Benchmark: drogon - Threads: 8         | 1.003    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 | 0.984    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 | 1.003    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 | 0.997    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 | 0.996    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1935

**Comment by totto82** [comment]
jenkins build this opm-models=758 opm-simulators=4275 please

**Comment by totto82** [comment]
@atgeirr @bska Can we merge this now?

**Comment by atgeirr** [comment]
> Can we merge this now?

I assume you mean the whole set of PRs? Given the comments by @vkip I think we are very close. I will just do a readthrough of the collect to io rank part, which I have not looked at yet.

**Comment by bska** [comment]
jenkins build this opm-models=758 opm-simulators=4275 please

**Comment by bska** [comment]
I'm going to start merging this PR sequence now.  Thanks a lot for your efforts and for responding to review!

**Pull request merged**
