### PR TITLE
bump version to 2019.10-rc2

### PR DESCRIPTION
**Pull request by akva2**
This was forgotten for rc1.

### CODE REVIEW

**Comment by blattms** [comment]
Indeed.

**Comment by OPMUSER** [comment]
Is there a binary available for the "C++ challenged" users :-)

**Comment by OPMUSER** [comment]
I get this, is this me?

`flow: symbol lookup error: flow: undefined symbol: _ZNK3Opm8DeckItem3getINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEERKT_m`

Ubuntu 18-04

**Comment by akva2** [comment]
Remove libecl1. Reinstall libopm-simulators-bin. It have tested bionic, they worked fine for me.

**Comment by blattms** [comment]
Maybe we should mark libecl1 as a confict/collission?

**Comment by akva2** [comment]
it's not really libecl causing anything. it was just a easy way to nuke all old opm packages, plus you don't need it anymore anyways..

**Comment by OPMUSER** [comment]
I have this now:

`This is flow 2019.10-pre`

And the package manager says` 2019.10-rc-1` so am good go?  If so many thanks.

**Comment by OPMUSER** [comment]
Typo

`Warning: Expected the kewyord: TABDIMS to infer the number of records in: PVTW`

Should be keyword not  kewyord :-)

**Comment by akva2** [comment]
Yes version bump was forgotten in rc1.

**Comment by blattms** [comment]
That one I missed. Will fix.

**Comment by akva2** [comment]
The equivalent of this pr is lacking in all modules, this pr was meant to point this out.

**Comment by blattms** [comment]
@akva2 I am aware of that and intend to do that for the other modules,
buit probably not today.

**Pull request merged**
