### PR TITLE
Add temperature as optional input for Source

### PR DESCRIPTION
**Pull request by totto82**
For thermal runs with Source you can either specify the enthalpy or the temperature. If temperature is given, the simulator will compute the enthalpy from the temperature given and the pressure in the cell.

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this opm-simulators=5107 please

**Comment by totto82** [comment]
jenkins build this opm-simulators=5107 please

**Comment by daavid00** [comment]
I have tested it on the spe11b (both enthalpy and temperature) and the results look fine, thanks for this.

**Comment by totto82** [comment]
Thanks for the testing. If no further comments, I plan to merge this (and the corresponding PR i simulators) later today.

**Pull request merged**
