### PR TITLE
[WIP] adding support for WSEGSICD

### PR DESCRIPTION
**Pull request by GitPaean**
Migrated from OPM/opm-parser#1194. please refer to the discussion there for more information. 

It has not been tested against the major targeting case with details. Will do that when information is available later. So it is marked as [WIP] for now.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins buid this opm-simulator=1389 please

**Comment by GitPaean** [comment]
jenkins build this opm-simulators=1389 please

**Comment by bska** [comment]
How much work do you think it will be to get this back up and running along with OPM/opm-simulators#1389?

**Comment by GitPaean** [comment]
> How much work do you think it will be to get this back up and running along with OPM/opm-simulators#1389?

I am doing it when I get time. I have a WIP branch.

**Comment by GitPaean** [comment]
closed by #1251

**Pull request closed without merging**
