### PR TITLE
Some more SCA warning cleanup

### PR DESCRIPTION
**Pull request by akva2**
These might be slightly more controversial as they actually require some small code changes.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by bska** [comment]
> cppcheck gets confused

Get a better checker.

**Comment by akva2** [comment]
dropped the workarounds for cppcheck parser.

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Looks good to me.  I'll merge into master.

**Pull request merged**
