### PR TITLE
Fixed defect in ESmry constructor. 

### PR DESCRIPTION
**Pull request by tskille**
This fixes issue found when using this class with summary files generated from the commercial simulator.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
I am not familiar with the details of the `ESmry` implementation; so I can not really judge this PR from the diff, but if it works for you locally I guess it is ok. You could add a test which loaded the ECL100 reference data from the opm-tests repository, that way you would have basic regression test. I would add the test conditionally if the opm-tests repo is found - as [here](https://github.com/OPM/opm-common/blob/master/ExtraTests.cmake#L72) - or you could copy the summary files in to the opm-common repository

**Comment by akva2** [comment]
there's a huge private test suite so while joakim is right, i trust this has been thoroughly tested.

**Pull request merged**
