### PR TITLE
Improve Simple Table errros messages

### PR DESCRIPTION
**Pull request by goncalvesmachadoc**

### CODE REVIEW

**Comment by goncalvesmachadoc** [comment]
jenkins build this please

**Review by bska — COMMENTED** [review]
This looks good to me and will be a clear benefit to the users if there happen to be small mistakes in their input files.  I just noticed one minor issue concerning parameter passing.  Once you fix that and mark this as "ready for review" I'll be happy to merge this.

**Comment by goncalvesmachadoc** [comment]
image

**Comment by alfbr** [comment]
I would really like to see these messages similarly formatted as the convention used for other warnings and errors. Something like this:

Error: Non-monotonic values values in keyword SWOF
In /path/to/file/SWOF.INC line 7
Water saturations need to be entered in strictly increasing order.

**Comment by goncalvesmachadoc** [comment]
I propose we print the table name and order schema in this PR, and leave filename and line number for following-up one:
image

**Comment by goncalvesmachadoc** [comment]
jenkins build this please

**Comment by goncalvesmachadoc** [comment]
We have  also added keyword name on error throw in SimpleTable.cpp in this current PR
image

**Comment by alfbr** [comment]
> I propose we print the table name and order schema in this PR, and leave filename and line number for following-up 

Sounds like a plan :+1:

**Review by bska — APPROVED** [review]
Thanks a lot for the updates.  I'll merge this now and then we can do follow-up work concerning file/line and other formatting later.

**Comment by OPMUSER** [comment]
I'm confused in what has changed with this PR.

For the 2022-10 release I get this as the error message:

```
Error: Problem with keyword SWOF
In SWOF-ERROR.DATA line 321.
Internal error: For table with ID 1: Number of input table elements (59) is not a multiple of table's specified number of columns (4)

Error: Unrecoverable errors while loading input: Problem with keyword SWOF
In SWOF-ERROR.DATA line 321.
Internal error: For table with ID 1: Number of input table elements (59) is not a multiple of table's specified number of columns (4)
```

If I run the same deck with master, I get this:

```
Error: Problem with keyword SWOF
In SWOF-ERROR.DATA line 321.
Internal error: For table SWOF with ID 1: Number of input table elements (59) is not a multiple of table's specified number of columns (4)

Error: Unrecoverable errors while loading input: Problem with keyword SWOF
In SWOF-ERROR.DATA line 321.
Internal error: For table SWOF with ID 1: Number of input table elements (59) is not a multiple of table's specified number of columns (4)
```

So what has changed, or have I done something wrong?

**Comment by goncalvesmachadoc** [comment]
For the error message you just checked the message was already ok (i.e., for the number of elements in the table check), but if you have for example twos rows in SWOF with same saturation value, then you get more informative error message.  Before the error would not say which table was wrong, neither that the error was related to monotonicity.

**Pull request merged**
