### PR TITLE
fix build with gcc7

### PR DESCRIPTION
**Pull request by akva2**
the filesystem TS did not include proximate. implement
a poor man's version and use this when necessary

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by alfbr** [comment]
Still failing with GCC7 here, similar error related to filesystem::relative.

**Comment by akva2** [comment]
arf. back to the drawing board then. stupid TS.

**Comment by joakim-hove** [comment]
Can the hack in opmpack be relevant?

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
copied and modified from libstdc++. this should work.

**Comment by alfbr** [comment]
It works!

**Comment by bska** [comment]
I think this looks good and if it fixes GCC 7 then we should clearly merge it.  Sorry for not picking up on `proximate()` whilst reviewing the first PR.  On the other hand, maybe we should add a tiny bit of source-level attribution to the bits extracted from libstdc++?

**Comment by akva2** [comment]
agreed, and done.

**Comment by akva2** [comment]
jenkins build this please

**Comment by bska** [comment]
Thanks for the updates.  I'll merge into master.

**Pull request merged**
