### PR TITLE
fixed unset return value causing segfault in release build on ubuntu …

### PR DESCRIPTION
**Pull request by hnil**
unset return value made strange behavoir.
flow segfault before parsing ends on all builds except debug on  18.10

### CODE REVIEW

**Comment by hnil** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
@akva2 should probably be in the release

**Comment by akva2** [comment]
nah, does not apply to the release.

**Comment by atgeirr** [comment]
> nah, does not apply to the release.

I see, my mistake.

**Pull request merged**
