### PR TITLE
Add PyAction skeleton code

### PR DESCRIPTION
**Pull request by joakim-hove**
Not very much here ...

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
Any chance you could rebase this onto current master?

**Comment by joakim-hove** [comment]
I'll rebase - in the end

**Comment by joakim-hove** [comment]
OK - rebased

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Pull request merged**
