### PR TITLE
Add boost subset

### PR DESCRIPTION
**Pull request by akva2**
As promised on dev-meeting;

This is the subset of boost required to build opm-common, assuming we disable tests.

It is in fact header only. Spirit pulls most of these files. The iterator range is the other usage we cannot (easily) kill, that one isn't too bad.

My opinion is that since there is no library dependencies for the boost usage, this is not really worth the costs.

### CODE REVIEW

**Comment by atgeirr** [comment]
> My opinion is that since there is no library dependencies for the boost usage, this is not really worth the costs.

I agree. Header-only dependencies are an order of magnitude less troublesome than those involving linking to third-party libraries, it is great to be there!

**Comment by magnesj** [comment]
We plan to use opm-common in ResInsight for reading VFP tables.  This PR will ease the work on our side. We will very much appreciate if this PR is merged. Any plans for when this will be merged?

**Comment by atgeirr** [comment]
> Any plans for when this will be merged?

I think it should not... Do you need to avoid even header-only boost libs?

**Comment by joakim-hove** [comment]
Hmmm - it has been lying around for some time, it has not been widely discussed but I think the loose consensus has been that this should not be merged.

I would certainly like to facilitate use of opm-common in Resinsight, but merging this feels like a high price. Hopefully we can find another solution which everyone can be happy with.

**Comment by magnesj** [comment]
Thanks for the feedback.

In ResInsight we also link NRlib, and this library is using Boost, including some features that not are header-only. So I think the boost-subset files in this PR can be merged with the requirements of NRlib to make both NRlib and opm-common compile.

https://github.com/CRAVA/crava/tree/master/libs/nrlib

**Comment by magnesj** [comment]
Ok for me if this PR is closed to avoid confusion on if this is intended to be merged.

**Comment by magnesj** [comment]
@akva2 How did you extract the boost subset files in this PR? I tried to do similar using

`bcp.exe spirit filesystem `

but ended up with 6000 files, much more than you have here.

**Comment by joakim-hove** [comment]
You should not need filesystem.

**Comment by akva2** [comment]
Started with bcp, then compared and stripped down using gcc output of included headers while building opm-common.

**Comment by joakim-hove** [comment]
Agreement has been this will not be merged - closing.

**Pull request closed without merging**
