### PR TITLE
Group level report

### PR DESCRIPTION
**Pull request by joakim-hove**
Rebased version of #1761

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
this PR breaks the running of our current example due to segmentation fault.
```
#0  Opm::GTNode::level (this=0x7fffb405a150) at /home/kaib/OPM-master-test/debug/opm-common/src/opm/parser/eclipse/EclipseState/Schedule/Group/GTNode.cpp:76
#1  0x00005555572f93f5 in (anonymous namespace)::GroupWrapper::group_level (this=<optimized out>)
    at /home/kaib/OPM-master-test/debug/opm-common/src/opm/output/eclipse/report/WELSPECS.cpp:391
#2  0x00005555572f6a44 in std::__invoke_impl<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> ((anonymous namespace)::GroupWrapper::*&)((anonymous namespace)::context const&, unsigned long, unsigned long) const, (anonymous namespace)::GroupWrapper const&, (anonymous namespace)::context const&, unsigned long, unsigned long> (__f=<optimized out>, __f=<optimized out>, __t=...) at /usr/include/c++/9/bits/invoke.h:89
#3  std::__invoke<std::__cxx11::basic_string<char> ((anonymous namespace)::GroupWrapper::*&)((anonymous namespace)::context const&, unsigned long, unsigned long) const, (anonymous namespace)::GroupWrapper const&, (anonymous namespace)::context const&, unsigned long, unsigned long> (__fn=<optimized out>)
    at /usr/include/c++/9/bits/invoke.h:96
#4  std::_Function_handler<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >(const (anonymous namespace)::GroupWrapper&, const (anonymous namespace)::context&, long unsigned int, long unsigned int), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > ((anonymous namespace)::GroupWrapper::*)(const (anonymous namespace)::context&, long unsigned int, long unsigned int) const>::_M_invoke(const std::_Any_data &, const (anonymous namespace)::GroupWrapper &, const (anonymous namespace)::context &, unsigned long &&, unsigned long &&) (__functor=..., __args#0=..., 
    __args#1=..., __args#2=<optimized out>, __args#3=<optimized out>) at /usr/include/c++/9/bits/std_function.h:318
#5  0x00005555572fd7f8 in std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >(const (anonymous namespace)::GroupWrapper&, const (anonymous namespace)::context&, long unsigned int, long unsigned int)>::operator() (__args#3=<optimized out>, __args#2=<optimized out>, 
    __args#1=..., __args#0=..., this=0x7fffb40aa528) at /usr/include/c++/9/bits/std_function.h:685
#6  (anonymous namespace)::column<(anonymous namespace)::GroupWrapper, 2>::print (sub_report=0, line_number=2, ctx=..., data=..., os=..., 
    this=0x7fffb40aa4e0) at /home/kaib/OPM-master-test/debug/opm-common/src/opm/output/eclipse/report/WELSPECS.cpp:109
#7  (anonymous namespace)::table<(anonymous namespace)::GroupWrapper, 2>::print_data (sub_report=0, ctx=..., Python Exception <class 'gdb.error'> value has been optimized out: 
lines=<synthetic pointer>, os=..., 
    this=0x7fffbfea4dd0) at /home/kaib/OPM-master-test/debug/opm-common/src/opm/output/eclipse/report/WELSPECS.cpp:172
#8  (anonymous namespace)::report<Opm::GTNode, (anonymous namespace)::GroupWrapper, 2>::print_data (bottom_border=45 '-', sub_report=0, Python Exception <class 'gdb.error'> value has been optimized out: 
    data=<synthetic pointer>, os=..., this=0x7fffbfea4d90) at /home/kaib/OPM-master-test/debug/opm-common/src/opm/output/eclipse/report/WELSPECS.cpp:209
#9  (anonymous namespace)::report_group_levels_data (os=..., ctx=..., report_step=<optimized out>)
    at /home/kaib/OPM-master-test/debug/opm-common/src/opm/output/eclipse/report/WELSPECS.cpp:415
#10 0x00005555572ff888 in Opm::RptIO::workers::write_WELSPECS (os=..., schedule=..., grid=..., unit_system=..., report_step=<optimized out>)
    at /home/kaib/OPM-master-test/debug/opm-common/src/opm/output/eclipse/report/WELSPECS.cpp:850
#11 0x00005555572f6217 in std::function<void (std::ostream&, unsigned int, Opm::Schedule const&, Opm::EclipseGrid const&, Opm::UnitSystem const&, unsigned long)>::operator()(std::ostream&, unsigned int, Opm::Schedule const&, Opm::EclipseGrid const&, Opm::UnitSystem const&, unsigned long) const (
    __args#5=<optimized out>, __args#4=..., __args#3=..., __args#2=..., __args#1=<optimized out>, __args#0=..., this=<optimized out>)
    at /usr/include/c++/9/bits/std_function.h:685
#12 Opm::RptIO::write_report (os=..., report="WELSPECS", value=1, schedule=..., grid=..., unit_system=..., report_step=0)
    at /home/kaib/OPM-master-test/debug/opm-common/src/opm/output/eclipse/WriteRPT.cpp:44
#13 0x00005555572c52b9 in Opm::EclipseIO::writeTimeStep (this=this@entry=0x555557d9c4d0, st=..., report_step=0, isSubstep=<optimized out>, 
    secs_elapsed=<optimized out>, value=..., write_double=write_double@entry=false)
    at /home/kaib/OPM-master-test/debug/opm-common/src/opm/output/eclipse/EclipseIO.cpp:268
#14 0x0000555556067840 in Opm::EclWriter<Opm::Properties::TTag::EclFlowProblem>::EclWriteTasklet::run (this=0x5555b5ca9760)
    at /home/kaib/OPM-master-test/debug/opm-simulators/ebos/eclwriter.hh:716
#15 0x0000555555f2e3c6 in Opm::TaskletRunner::run_ (this=0x555557c26db0) at /home/kaib/OPM-master-test/debug/opm-models/opm/models/parallel/tasklets.hh:330
#16 0x00007ffff7a25f74 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#17 0x00007ffff77cc669 in start_thread (arg=<optimized out>) at pthread_create.c:479
#18 0x00007ffff76f2323 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by joakim-hove** [comment]
OK - will look into it tomorrow; can the model be shared?

**Comment by GitPaean** [comment]
No. But I can try to give some information about the graph tree.

**Comment by joakim-hove** [comment]
@GitPaean: I have looked briefly on this; difficult to proceed without data. Good if you contact me when you are for some conversation.

**Comment by GitPaean** [comment]
Sure. I will contact you sometime later today with some more information hopefully helpful to you.

**Comment by GitPaean** [comment]
I am having a bad time to create a smaller deck to reproduce the problem. Will try to get back to you as soon as possible. I might comment out my findings hopefully can give you some clues.

**Comment by GitPaean** [comment]
@joakim-hove , I managed to make a small case that can reproduce the problem. I have sent the data file to you.  Please let me know if you receive it.

**Comment by blattms** [comment]
Souldn't that test move to opm-tests also?

**Pull request merged**
