### PR TITLE
Keyword location

### PR DESCRIPTION
**Pull request by joakim-hove**
A small step in the work of improving error messages

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2789 please

**Review by bska — APPROVED** [review]
Looks good to me.  A purely mechanical type renaming.  I'll merge this and the downstream follow-up PR into master.

**Pull request merged**
