### PR TITLE
Prepare for UDT support

### PR DESCRIPTION
**Pull request by akva2**
This adds the container for UDTs and adds slots for them in UDQConfig and UDQContext.

Note this is limited to 1D UDTs only.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by blattms** [comment]
I did take a look. Looks good. I am just wondering what happens if someone specifies a UDT with more than 1 dimension.

**Comment by akva2** [comment]
see next PR, it will throw in the parsing.

**Comment by blattms** [comment]
jenkins build this please

**Review by blattms — APPROVED** [review]

**Pull request merged**
