### PR TITLE
Adding python bindings for class ExtESmry

### PR DESCRIPTION
**Pull request by tskille**
- Used for loading data from summary file ESMRY

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Is it necessary to have two separate classes in Python? As I see it the point of the `ExtESmry` class is to work as a drop in replacement for the `ESmry` - then I would assume it should be possible to only have one - i.e. `ESmry` class in Python?

**Comment by tskille** [comment]
I'm not sure what you mean by 

> as a drop in replacement for the `ESmry`

There are two separate C++ classes in opm-common 
```
Opm::EclIO::ESmry and Opm::EclIO::ExtESmry
```
ESmry is used to access data from SMSPEC/UNSMRY files and ExtESmry is used to access data in ESMRY files. 

Would you like med to add one extra layer of python which should handle both input files (SMSPEC/UNSMRY and ESMRY) ?

**Comment by joakim-hove** [comment]
> There are two separate C++ classes in opm-common

Yes - but the user does not care; she just want's her summary data.

> Would you like med to add one extra layer of python which should handle both input files (SMSPEC/UNSMRY and ESMRY) ?

That is one option, or maybe even in C++

**Comment by tskille** [comment]
Modified as we talked about on the phone. Python bindings to new c++ class ESmryBind which supports both ESMRY and SMSPEC/UNSRM files. User of API doesn't need to relate to a new python class for loading data from ESMRY file.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Good updates  - in she goes

**Pull request merged**
