### PR TITLE
Support MINPORV

### PR DESCRIPTION
**Pull request by OPMUSER**
Add support for MINPORV, which is an alias for MINPV. Also added additional checks, such that only one of MINPV, MINPORV and MINPVFIL can be active in the deck

### CODE REVIEW

**Comment by OPMUSER** [comment]
Ready for review with https://github.com/OPM/opm-simulators/pull/3975

**Comment by bska** [comment]
jenkins build this opm-simulators=3975 please

**Comment by OPMUSER** [comment]
Failure is due to the error message being move from the C++ code into the parser code, and thus changing the error message format.

**Comment by blattms** [comment]
I guess that is not 100% correct. It has nothing to do with formatting. We do not check that. With the movement of code you added an additional check  to the constructor that has not been there before. This makes the EclGridTest fail. Hence your will need to fix this in [tests/parser/EclipseGridTests.cpp](https://github.com/OPM/opm-common/blob/bad915fdf511a1e2268ab25eb290ef4d04d9c45b/tests/parser/EclipseGridTests.cpp), test ConstructorMINPV. While at it you should probably also add a test there for the new alias.

**Comment by bska** [comment]
> With the movement of code you added an additional check to the constructor that has not been there before. This makes the EclGridTest fail. Hence your will need to fix this in [tests/parser/EclipseGridTests.cpp](https://github.com/OPM/opm-common/blob/bad915fdf511a1e2268ab25eb290ef4d04d9c45b/tests/parser/EclipseGridTests.cpp), test ConstructorMINPV

@blattms is correct.  The [existing test](https://github.com/OPM/opm-common/blob/bad915fdf511a1e2268ab25eb290ef4d04d9c45b/tests/parser/EclipseGridTests.cpp#L846), which now [fails](https://ci.opm-project.org/job/opm-common-PR-builder/4927/testReport/junit/(root)/mpi/EclipseGridTests/), expects the existence of `MINPVFIL` in the same input as `MINPV` to throw an exception of [type `std::invalid_argument`](https://github.com/OPM/opm-common/blob/bad915fdf511a1e2268ab25eb290ef4d04d9c45b/tests/parser/EclipseGridTests.cpp#L852), but adding [`prohibits : [ "MINPV", "MINPORV" ]`](https://github.com/OPM/opm-common/blob/4fe559ba3ca0c8d8b0fb5ead13499fa8b5002828/src/opm/input/eclipse/share/keywords/900_OPM/M/MINPVFIL#L6) turns this condition into an `OpmInputError` instead.  These two types are unrelated so the test assertion does not protect the execution path.

The current master sources [raise `std::invalid_argument`](https://github.com/OPM/opm-common/blob/bad915fdf511a1e2268ab25eb290ef4d04d9c45b/src/opm/input/eclipse/EclipseState/Grid/EclipseGrid.cpp#L347-L349) through an explicit check in the source code, but this PR removes that check.  Tangentially, it's not clear to me what `MINPVFIL` actually does or if it even does anything at all.  The only reference I can find to this keyword is in that explicit check and the keyword, which moreover is OPM specific, is not documented anywhere.

Unless anyone can give a convincing argument for why we should continue to support that keyword I'd be in favour of removing its definition entirely in early September.

**Comment by OPMUSER** [comment]
@bska thanks for the clear explanation of the failure - hopefully I have fixed this now.

I do have a preference of placing these type of checks whenever possible in the JSON files, as I think this results in a "cleaner" work flow.

**Comment by bska** [comment]
jenkins build this please

**Comment by OPMUSER** [comment]
Please merge. 

I'll submit another PR to remove MINPVFIL and the checks, that can sit there for a month or so as a reminder us that we should remove this keyword. We also have the MINPVV that is marked as active and sets the minimum pore volume by cell, I think that MINPVFIL was replaced by MINPVV, but that is just a guess.

**Pull request merged**
