### PR TITLE
Remove unused CMake find_package macros Eigen3

### PR DESCRIPTION
**Pull request by blattms**
My assumption is that nobody uses these. Please double check.

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by akva2** [comment]
the petsc one used to be implicitly required by dune-fem but  but I think they have cleaned up their act and provide the rules they require now. eigen3 is no longer used, it was used by the old autodiff code.

**Comment by blattms** [comment]
Thanks. Then I will probably leave that in.

**Comment by blattms** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Much appreciated.  I'll merge into master.

**Pull request merged**
