### PR TITLE
Update regexp to allow for digits in UDQ name

### PR DESCRIPTION
**Pull request by joakim-hove**
Should fix: https://github.com/OPM/opm-simulators/issues/2581

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
This definitely fixes a problem and brings in new summary vectors for summary vectors `WUPR1` and `WUPR3`:
```
  > 'WUPR1:OPL01'
  > 'WUPR1:OPL02'
  > 'WUPR1:OPU01'
  > 'WUPR1:OPU02'
  > 'WUPR3:OPL01'
  > 'WUPR3:OPL02'
  > 'WUPR3:OPU01'
  > 'WUPR3:OPU02'
```
I'll launch a data-update run.

**Comment by bska** [comment]
jenkins build this opm-tests=312 please

**Comment by bska** [comment]
Build check is green with updated reference data.  I'm merging this into master to correct the problem.  Thanks a lot for the quick analysis and turn-around.

**Pull request merged**
