### PR TITLE
Small Changes in restart <-> Schedule interaction

### PR DESCRIPTION
**Pull request by joakim-hove**
Small trivial commits in the restart saga

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
These changes will be properly tested with #1991 / #1992

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Comments to this?

**Review by bska — APPROVED** [review]
Looks good to me.  I'll merge into master.

**Pull request merged**
