### PR TITLE
Improved parsing of individual sections

### PR DESCRIPTION
**Pull request by tskille**
* Supporting that EDIT, REGIONS and SUMMARY section is optional
* RUNSPEC needed for parsing, but keywords removed from deck after parsing if not needed

### CODE REVIEW

**Comment by tskille** [comment]
This PR is addressing  issue [3855](https://github.com/OPM/opm-common/issues/3855)

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Pull request merged**
