### PR TITLE
Clean up item names in json for WCONHIST

### PR DESCRIPTION
**Pull request by berland**
Consistency with other keywords

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
I think there are a few c++ code places need to update to use these names.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by berland** [comment]
Correct, there was one C++ file that had this included as a string  - now added to the PR. I have searched through the rest of the repositories and not found more usage.

**Comment by akva2** [comment]
jenkins build this please

**Pull request merged**
