### PR TITLE
Simplify dune/opm module search by relying on cmake package config files

### PR DESCRIPTION
**Pull request by blattms**
We use ${module}_DIR to set the correct path when sibling search is activated. The package configuration files set all the necessary variables and we save us a lot of CMake magic.

Note that we previously used PkgConfig to find system installed DUNE and OPM packages. The paths found ended up as first hints in the find_* calls. Therefore the semantics might have been changed here. Previously system installed stuffed might have had higher priority than package found via sibling search.

We use the sibling search logic here as in the other modules.

This is at least a first step in simplifying our CMake scripts.

### CODE REVIEW

**Comment by blattms** [comment]
Red might become the color of the season. :)

**Comment by akva2** [comment]
first fallout: opm-grid now lacks the DUNE_GRID_EXPERIMENTAL_GRID_EXTENSIONS (and some more) in config.h which breaks the polyhedralgrid test, ref cmake/Modules/Finddune-grid.cmake

**Comment by blattms** [comment]
Thanks for the testing. That proves that I still do not get all the magic. I added a fix for this (which I actually did not deem needed).

**Comment by akva2** [comment]
i think it's better to find issues and fix using magic you understand, than trying to decode so it's all good.

**Comment by blattms** [comment]
I guess I need to test one more thing here. If  I use the sibling search and install the modules, then I am not sure whether the installed modules depend only on installed ones.

**Comment by akva2** [comment]
don't worry, i'm thorough so if that breaks you will hear from me! ;)

**Comment by akva2** [comment]
opm-parser needs some love regarding its simplified sibling search (it always picks the build folder).

**Comment by akva2** [comment]
and installation of sibling-based builds is problematic as you suspected, it will link against sibling dirs.

**Comment by blattms** [comment]
Opened PR OPM/opm-parser#1141 to adjust its sibling search to the customs of the rest of OPM.

Corncerning the second issue I must admit that I underestimated this a bit. I was tempted to reply "just deactivate sibling search" when I realized that the cmake package config files that we install are not fit for it. They do contain references to the build directory. (This excludes opm-parser which has its own way and quirks). I will fix this but that might take a while.

**Comment by akva2** [comment]
the turning off is only mandatory if you store things in an "evil" layout i assume?

**Comment by blattms** [comment]
Well I do not consider my layout evil:
Source are src/opm-common, src/opm-core, build directories are test-build/opm-common-build, test-build/opm-core-build. libopmcore.so from the install tree links libcommon.so from the build tree.

There must be some extra magic in OPM that bites us here, because with dune the paths in the shjared libs get rewritten automatically.

**Comment by akva2** [comment]
sorry, by evil i mean you have things in a sibling layout in the first place. ie this does not interfer with packaging.

**Comment by blattms** [comment]
Correct. Then my layout is evil.

**Comment by akva2** [comment]
```
$ pwd
/home/akva/kode/opm/sibling/opm-parser/build-debug
$ls ../.. -1
...
libecl/
...

$ cmake .. -DCMAKE_BUILD_TYPE=Debug
CMake Warning at CMakeLists.txt:81 (find_package):
  Could not find a package configuration file provided by "ecl" with any of
  the following names:

    eclConfig.cmake
    ecl-config.cmake

  Add the installation prefix of "ecl" to CMAKE_PREFIX_PATH or set "ecl_DIR"
  to a directory containing one of the above files.  If "ecl" provides a
  separate development package or SDK, be sure it has been installed.


-- Found ecl library: /home/akva/kode/opm/sibling/opm-common/serial/build-libecl
```
where the resolved path is some random test build i did at some point which it dug out of the cache.

reason is i use the repo name (libecl), not ecl for the sibling dir. i'd argue that should be supported (yes, i should have caught that before i merged in the other repo :/). 

it think it would be helpful if you suppressed the 'Finding package xxx using module mode' output, if we already have read a config file.

i have tested everything sibling related again and it's all good apart from these two things. jenkins will be used to test the install builds once these are addressed. then it's ready for merge as far as i am concerned.

**Comment by blattms** [comment]
Well, ecl seems special. Somehow I assumed that I manually did use libecl as the clone directory.

**Comment by blattms** [comment]
The first issue is fixed in OPM/opm-parser#1146 as it uses its own build system. Same fix is applied here in case we ever search for ecl, which like it seems we currently do not. ecl is always search implicitly when searching for opm-parser (that search is broken for installed opm-parser, fix coming).

**Comment by akva2** [comment]
final sanity check.

**Comment by akva2** [comment]
jenkins build this with downstreams dune 2.4 please

**Comment by akva2** [comment]
you have to give the code in Findopm-output.cmake which locates compareECL etc some love i think.

**Comment by blattms** [comment]
I guess you are right. Give me some minutes.

One question though:
Is [`${project}_VERDIR`](/OPM/opm-common/blob/352b5a371d32da51c1c9a57383db1a3015687452/cmake/Modules/OpmInit.cmake#L63-L73) used by you? It seems it is not used consistently across OPM.

**Comment by blattms** [comment]
This now needs OPM/opm-output#209 for the comare commands-

**Comment by blattms** [comment]
jenkins build this with downstreams opm-output=209 dune 2.4 please

**Comment by blattms** [comment]
testing my jenkins foo.

**Comment by akva2** [comment]
foo was almost okay, you copied my typo (it's dune2.4 in one word). however, commenting after the trigger breaks things. stupid bug in the pr builder. i will cancel, then you can trigger again. i need to dig into java code to fix that bug i guess :/

**Comment by blattms** [comment]
Sorry, I did a mistake. There were commits in this branch that should not have been there. I fixed this and force pushed. Let's try jenkins again.

**Comment by blattms** [comment]
jenkins build this with downstreams opm-output=209 dune2.4 please

**Comment by akva2** [comment]
sorry, you probably despise me by now but;

```
CMake Warning at /var/lib/jenkins/workspace/opm-common-PR-builder/mpi-dune2.4/install/share/cmake/opm-material/opm-material-config.cmake:107 (message):
  Incompatible value "1" of variable "HAVE_DUNE_BOOST"
Call Stack (most recent call first):
  /var/lib/jenkins/workspace/opm-common-PR-builder/mpi-dune2.4/install/share/opm/cmake/Modules/OpmPackage.cmake:78 (find_package)
  /var/lib/jenkins/workspace/opm-common-PR-builder/mpi-dune2.4/install/share/opm/cmake/Modules/Findopm-material.cmake:16 (find_opm_package)
  /var/lib/jenkins/workspace/opm-common-PR-builder/mpi-dune2.4/install/share/opm/cmake/Modules/OpmFind.cmake:160 (find_package)
  /var/lib/jenkins/workspace/opm-common-PR-builder/mpi-dune2.4/install/share/opm/cmake/Modules/OpmPackage.cmake:92 (find_and_append_package_to)
  /var/lib/jenkins/workspace/opm-common-PR-builder/mpi-dune2.4/install/share/opm/cmake/Modules/Findopm-core.cmake:16 (find_opm_package)
  /var/lib/jenkins/workspace/opm-common-PR-builder/mpi-dune2.4/install/share/opm/cmake/Modules/OpmFind.cmake:160 (find_package)
  /var/lib/jenkins/workspace/opm-common-PR-builder/mpi-dune2.4/install/share/opm/cmake/Modules/OpmFind.cmake:224 (find_and_append_package_to)
  /var/lib/jenkins/workspace/opm-common-PR-builder/mpi-dune2.4/install/share/opm/cmake/Modules/OpmLibMain.cmake:122 (find_and_append_package_list_to)
  CMakeLists.txt:109 (include)
```
happens with both dune 2.4 and 2.5. in the config file. from opm-material-config.cmake
```
if (DEFINED HAVE_DUNE_BOOST AND NOT "${HAVE_DUNE_BOOST}" STREQUAL "")
  message (WARNING "Incompatible value \"${HAVE_DUNE_BOOST}\" of variable \"HAVE_DUNE_BOOST\"")
endif ()
set (HAVE_DUNE_BOOST)
```
and its config.h;
```
/* #undef HAVE_DUNE_BOOST */
```
while we get a
```
#define HAVE_DUNE_BOOST 1
```
in opm-simulators config.h

**Comment by blattms** [comment]
No I do not. I am just sorry for abusing you for such a lot of testing.
I will look into it tommorrow.

**Comment by blattms** [comment]
The problem was that opm-common is already found using config mode in the top level CMakeLists.cmake and never searched again using find_opm_package. Therefore the Boost stuff was not defined for modules that did not include another opm module that needed Boost.

BTW: The issue must have been in master already.

**Comment by blattms** [comment]
and is hopefully fixed here now.

**Comment by akva2** [comment]
Yes we are pulling in a intricate web of threads which worked by chance at times :) now we get it under control

**Comment by akva2** [comment]
jenkins build this with downstreams dune2.4 please

**Comment by akva2** [comment]
in she goes. thx for patience.

**Comment by blattms** [comment]
Cool. Thanks.

**Pull request merged**
