### PR TITLE
Remove dead serialization code

### PR DESCRIPTION
**Pull request by akva2**
This removes unused and replaced serialization code, and consequently the serialization class in opm-common.

Also includes a serializeObject (yes, @bska, i will fix the naming) method for enabling a trancalculator test that was supposed to go in an earlier PR.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this serial opm-simulators=4085 please

**Comment by akva2** [comment]
jenkins build this serial opm-simulators=4085 please

**Comment by akva2** [comment]
jenkins build this serial opm-simulators=4085 please

**Review by bska — APPROVED** [review]
Really happy to see the number of serialization methods go down.  I'll merge this and its downstream companion into the master branch.

**Pull request merged**
