### PR TITLE
Time keyword info logging

### PR DESCRIPTION
**Pull request by joakim-hove**
This a continunation of #1971

### CODE REVIEW

**Comment by joakim-hove** [comment]
With this PR we print a log message for every DATES and TSTEP while we are assembling the Schedule object (i.e. this is in addition to the message which is printed when the keyword is read initially). Currently the messages will look like this:
```

Complete report step  242: 2006-10-10 - 2006-10-15 5.0 DAYS /home/hove/work/OPM/opm-tests/norne/INCLUDE/BC0407_HIST01122006.SCH line 9412
Complete report step  243: 2006-10-15 - 2006-11-01 17.0 DAYS /home/hove/work/OPM/opm-tests/norne/INCLUDE/BC0407_HIST01122006.SCH line 9447
Complete report step  244: 2006-11-01 - 2006-11-09 8.0 DAYS /home/hove/work/OPM/opm-tests/norne/INCLUDE/BC0407_HIST01122006.SCH line 9474
Complete report step  245: 2006-11-09 - 2006-11-11 2.0 DAYS /home/hove/work/OPM/opm-tests/norne/INCLUDE/BC0407_HIST01122006.SCH line 9505
Complete report step  246: 2006-11-11 - 2006-11-17 6.0 DAYS /home/hove/work/OPM/opm-tests/norne/INCLUDE/BC0407_HIST01122006.SCH line 9532

```
Not particularly nice yet - **input more than welcome**. The pieces of information I consider relevant are:

1. The start of the report step (that is the value of the *previous* `DATES` keyword).
2. The end of the report step - corresponding to the `DATES` keyword we are looking at.
3. The report step number this is.
4. The length of the report step.
5. File and line of the `DATES` keyword

Then - if the assembly of e.g. a WCONHIST keyword fails we will get something like
```
Complete report step  246: 2006-11-11 - 2006-11-17 6.0 DAYS /home/hove/work/OPM/opm-tests/norne/INCLUDE/BC0407_HIST01122006.SCH line 9532

Error: Problem with keyword WCONHIST
In /path/to/file line 278
Internal error: Phase OL not recognized
```

For `TSTEP` it looks like this:
```
TSTEP  114 30.0 DAYS -> 2024-06-28
TSTEP  115 31.0 DAYS -> 2024-07-29
TSTEP  116 31.0 DAYS -> 2024-08-29
TSTEP  117 30.0 DAYS -> 2024-09-28
```

**Comment by atgeirr** [comment]
Sounds good, will this replace the current printout? Current print from Norne:
```
...
  728 Reading DATES    in file /Users/atgeirr/opm/src/opm-tests/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3605
  729 Reading WCONHIST in file /Users/atgeirr/opm/src/opm-tests/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3609
  730 Reading WCONINJE in file /Users/atgeirr/opm/src/opm-tests/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3621
  731 Reading WTRACER  in file /Users/atgeirr/opm/src/opm-tests/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3630
  732 Reading DATES    in file /Users/atgeirr/opm/src/opm-tests/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3637
  733 Reading WCONHIST in file /Users/atgeirr/opm/src/opm-tests/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3641
  734 Reading WCONINJE in file /Users/atgeirr/opm/src/opm-tests/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3653
  735 Reading DATES    in file /Users/atgeirr/opm/src/opm-tests/norne/INCLUDE/BC0407_HIST01122006.SCH, line 3663
...
```
How would that be after this?

**Comment by joakim-hove** [comment]
> [...] will this replace the current printout? Current print from Norne:

No - the current printout comes from the initial phase reading the deck; that will be unchanged. This is new output which comes from the `Schedule` construction. Current situation is that reading of the `Deck` is quite verbose, but then afterwards there is complete silence - this PR will change that a bit.

**Comment by atgeirr** [comment]
> Current situation is that reading of the `Deck` is quite verbose, but then afterwards there is complete silence - this PR will change that a bit.

Sounds fine. I hope we can make it uniform with respect to TSTEP vs DATES?

**Comment by bska** [comment]
> > Current situation is that reading of the `Deck` is quite verbose, but then afterwards there is complete silence - this PR will change that a bit.
> 
> Sounds fine. I hope we can make it uniform with respect to TSTEP vs DATES?

Also, do we get 50 log lines if the input file has
```
TSTEP
  50*30 /
```
?

Finally, as a possible aesthetic issue, does the log say
```
DAYS
```
(plural) if the report step size is exactly one (1) day?

**Comment by atgeirr** [comment]
> Also, do we get 50 log lines if the input file has
> 
> ```
> TSTEP
>   50*30 /
> ```

I think that would be the best, for uniformity.

**Comment by joakim-hove** [comment]
>  I hope we can make it uniform with respect to TSTEP vs DATES?

We can make it uniform for TSTEP / DATES; the log line should have some indication of which keyword is in action though.

**Comment by joakim-hove** [comment]
> Also, do we get 50 log lines if the input file has

yes

**Comment by joakim-hove** [comment]
> (plural) if the report step size is exactly one (1) day?

It is `DAYS` even if it is exactly one day.

**Comment by OPMUSER** [comment]
I have a suggestion, based on that the data is all coming from the same file:

```
Reading: /home/hove/work/OPM/opm-tests/norne/INCLUDE/BC0407_HIST01122006.SCH
Report step  242: 2006-10-10 - 2006-10-15  5.0 DAYS line 9412
Report step  243: 2006-10-15 - 2006-11-01 17.0 DAYS line 9447
Report step  244: 2006-11-01 - 2006-11-09  8.0 DAYS line 9474
Report step  245: 2006-11-09 - 2006-11-11  2.0 DAYS line 9505
End Reading: /home/hove/work/OPM/opm-tests/norne/INCLUDE/BC0407_HIST01122006.SCH 
```

This makes the output shorter for the terminal and avoids duplication of the file being read. Also notice how I aligned the data for greater readability. You could also indent to get something like this.

```
Reading: /home/hove/work/OPM/opm-tests/norne/INCLUDE/BC0407_HIST01122006.SCH
   Report step  242: 2006-10-10 - 2006-10-15  5.0 DAYS line 9412
   Report step  243: 2006-10-15 - 2006-11-01 17.0 DAYS line 9447
   Report step  244: 2006-11-01 - 2006-11-09  8.0 DAYS line 9474
   Report step  245: 2006-11-09 - 2006-11-11  2.0 DAYS line 9505
End Reading: /home/hove/work/OPM/opm-tests/norne/INCLUDE/BC0407_HIST01122006.SCH 
```

**Comment by joakim-hove** [comment]
> I have a suggestion, based on that the data is all coming from the same file:

I think that is a good idea; yes the output will be better aligned - that was already on my list of planned improvements.

**Comment by OPMUSER** [comment]
I would not bother about DAY/DAYS, but if some people are, you could us use DAY(S) instead and forget about it.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
@alfbr : This works on my machine - fingers crossed Jenkins also approves.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
I'll merge this quite soon - to get more feedback on the messages++ - and then revisit with updated format string.

**Comment by joakim-hove** [comment]
jenkins build this please

**Pull request merged**
