### PR TITLE
changed: hide the templated 'has' and 'get' interfaces in FieldPropsManager

### PR DESCRIPTION
**Pull request by akva2**
motivation: an upcoming parallel frontend to the field props manager.
templated functions cannot be virtualized, and thus having these exposed
would give a great chance of confusing the users in the downstream
code, where properties would be caught from the (potentially) empty
backend instead of from the frontend.

i realize this isn't necessarily the most popular change, but i cannot get around it without complicating matters a lot in the downstreams. this is the smallest cost in my opinion.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-material=389 opm-simulators=2304 please

**Comment by joakim-hove** [comment]
> i realize this isn't necessarily the most popular change, 

Ehhh no - that is correct. I was intending to remove the `get_int()` and `get_double()`frontends - but they suddenly became canonical.

**Comment by joakim-hove** [comment]
Test and Python code wrapper needs to be updated.

**Comment by akva2** [comment]
jenkins build this opm-material=389 opm-simulators=2304 please

**Comment by akva2** [comment]
self-merging as it has been approved.

**Pull request merged**
