### PR TITLE
Import opm-parser and opm-output

### PR DESCRIPTION
**Pull request by akva2**
This imports opm-parser and opm-output into this repo (with history).

Two new options are added -DENABLE_ECL_(INPUT|OUTPUT), both of which defaults to true.

Probably some issues left but I need pr's to test jenkins etc.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-material=290 opm-grid=313 ewoms=293 opm-simulators=1424 opm-upscaling=251 please

**Comment by akva2** [comment]
jenkins build this opm-material=290 opm-grid=313 ewoms=293 opm-simulators=1424 opm-upscaling=251 please

**Comment by akva2** [comment]
jenkins build this opm-material=290 opm-grid=313 ewoms=293 opm-simulators=1424 opm-upscaling=251 please

**Comment by andlaus** [comment]
while I suppose that the actual code changes are all good, the downstream PRs are missing the removal of opm-{parser,output} from the dependencies of `dune.module` (as usual ;)

Anyway, thanks for the work!

**Comment by joakim-hove** [comment]
When opm-output and opm-parser have been imported into opm-common *the* dominating part of opm-common is made up of Eclipse related IO, making the bulk of library optional seems weird to me?

**Comment by akva2** [comment]
i have no opinion, only did what i was told to do.

**Comment by joakim-hove** [comment]
Sure - I clearly have an opinion, we will see what the others say.

**Comment by andlaus** [comment]
I agree with @joakim-hove that the module should be renamed to something more concise. maybe `opm-eclio` or `opm-eclcommon`? I do not consider this to be an urgent issue, though.

**Comment by alfbr** [comment]
> When opm-output and opm-parser have been imported into opm-common the dominating part of opm-common is made up of Eclipse related IO, making the bulk of library optional seems weird to me?

Yes, I agree. The option caters to developers who want the reservoir simulation implementation, but are not interested in Eclipse file formats. Currently, this is common in the academic realm. I do think it is a pity, simply because I believe a well supported format has huge benefits also for research tasks. Especially when we provide a back-end like Resinsight to handle the formats, not to forget the libecl python bindings.

**Comment by atgeirr** [comment]
About naming: I suggest we leave that alone (i.e. keep opm-common) until after the 2018.04 release, and then open the discussion. Ok with everyone?

**Comment by atgeirr** [comment]
> while I suppose that the actual code changes are all good, the downstream PRs are missing the removal of opm-{parser,output} from the dependencies of dune.module (as usual ;)

I take that to mean that you successfully compiled with this PR (after removing those dependencies)?

**Comment by andlaus** [comment]
> I do think it is a pity, simply because I believe a well supported format has huge benefits also for research tasks.

I won't waste too many words about the merits of the ECL file format for anything other than cell-centered TPFA finite-volume discretizations with cornerpoint grids here, but consider that e.g. #336 and friends have been mainly caused by stuff which is not needed by the numeric and thermodynamic frameworks, so only having to deal with the stuff that you actually want is a good thing. Posing this matter differently: would you like your `flow` build to break just because compilation of e.g. the comsol file format parsing library fails?

**Comment by andlaus** [comment]
> I take that to mean that you successfully compiled with this PR (after removing those dependencies)?

almost: I did not bother with the default build system yet and the one which I use still needs a few adjustments. Besides that it seems to work fine if the opm-{parser,output} directories are removed.

**Comment by alfbr** [comment]
> I won't waste too many words about the merits of the ECL file format for anything other than cell-centered TPFA finite-volume discretizations with cornerpoint grids here,

None of those are file format limitations.

> but consider that e.g. #336 and friends have been mainly caused by stuff which is not needed by the numeric and thermodynamic frameworks

I would say they are mostly caused by an excessive dependency matrix. In that particular case Boost seems to be the culprit. Let's not go down that road again though, I have an E300 case here I need to run for the thermal stuff ;-)

**Comment by andlaus** [comment]
>> I won't waste too many words about the merits of the ECL file format for anything other than cell-centered TPFA finite-volume discretizations with cornerpoint grids here,
>
> None of those are file format limitations.

true in principle, but that is a mood point if you have to use a deck with all-custom keywords.

>> but consider that e.g. #336 and friends have been mainly caused by stuff which is not needed by the numeric and thermodynamic frameworks
>
> I would say they are mostly caused by an excessive dependency matrix.

that's exactly the point: stuff which does not get used cannot break! forcing users to always compile the code for a somewhat esoteric file format that comes with somewhat uncommon dependencies and that is essentially proprietary is not a good idea.

**Comment by atgeirr** [comment]
After testing I can say that for me, this PR (and its companions) works great with both regular building, and using a super-module build.

**Comment by alfbr** [comment]
> true in principle, but that is a mood point if you have to use a deck with all-custom keywords.

I think you misunderstand. The file format already caters to unstructured grids in both input and output side without custom keywords. MPFA is not a custom keyword, and you will find finite element stuff for the geomechanics. For tracers you will find a second order scheme. Catering to various needs is not the big deal you make it out to be. Choose your poison, but I do think well supported, well documented and feature rich file formats on both input and output is very valuable.

**Comment by andlaus** [comment]
> I do think well supported, well documented and feature rich file formats on both input and output is very valuable.

I suppose this means that you want us add support for the FLOTRAN and the comsol file formats as well as HDF-5 to opm-common?

**Comment by alfbr** [comment]
Not sure about FLOTRAN, but I would love to see HDF-5 support in opm-common. A lot of work went into trying to make parts of the input and output code generic, so I do hope that reuse of at least parts of it is beneficial if we ever have the resources to implement other file formats.

**Comment by totto82** [comment]
> When opm-output and opm-parser have been imported into opm-common the dominating part of opm-common is made up of Eclipse related IO, making the bulk of library optional seems weird to me?

Wasn't this what we agreed on as a compromise in the hangout. If nobody uses the optional feature to  build without eclipse stuff we can remove the options later if it becomes a problem. For now I suggest to get this merged as is, and leave the discussions to a pub in Oslo.

**Comment by joakim-hove** [comment]
> Wasn't this what we agreed on as a compromise in the hangout. 

I wasn't there - but I have come to realize such an agreement had already been reached by the relevant parties.

**Comment by atgeirr** [comment]
We are ready to merge this! Just a final jenkins run since there were some tiny adjustments.

**Comment by atgeirr** [comment]
jenkins build this opm-material=290 opm-grid=313 ewoms=293 opm-simulators=1424 opm-upscaling=251 please

**Comment by atgeirr** [comment]
@akva2 please merge the chain of PRs, when green.

**Comment by GitPaean** [comment]
Maybe the super cmake file also need to be updated after this. 

https://github.com/OPM/opm-utilities/blob/master/opm-super/CMakeLists.txt

**Comment by atgeirr** [comment]
> Maybe the super cmake file also need to be updated

Yes, and I already edited and tested it, so I'll make a PR.

**Pull request merged**
