### PR TITLE
Add method to get only wells that have been active during the simulation

### PR DESCRIPTION
**Pull request by vkip**

### CODE REVIEW

**Comment by vkip** [comment]
jenkins build this opm-simulators=5609 please

**Comment by vkip** [comment]
jenkins build this opm-simulators=5609 please

**Comment by vkip** [comment]
jenkins build this opm-simulators=5609 please

**Comment by vkip** [comment]
jenkins build this opm-simulators=5609 please

**Review by blattms — COMMENTED** [review]
Sorry. I reviewed this yesterday but never pressed the button.

Looks great. Just two nitpicks.

**Comment by vkip** [comment]
jenkins build this please

**Review by blattms — APPROVED** [review]

**Pull request merged**
