### PR TITLE
Add Restart Support for Item 2 of GEFAC

### PR DESCRIPTION
**Pull request by bska**
That is, save and restore the group efficiency factor value to/from the `SGRP` array in the restart file.

### CODE REVIEW

**Comment by tskille** [comment]
I have tested this and results are good. I've tested both eclipse restart (from flow) and flow restart from flow restart file.

**Comment by bska** [comment]
> I have tested this

Thank you!  This is greatly appreciated.  Then I'm marking this as "ready for review".  Note that we will need to update the reference solutions of a few regression tests due to no longer writing the constant `1.0` to the `GEFAC` item of `SGRP`.

**Comment by bska** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this update_date please

**Comment by bska** [comment]
> jenkins build this update_date please

Did you mean update_dat**A**?

**Comment by joakim-hove** [comment]
>Did you mean update_datA?

Ehh yes ...

**Comment by joakim-hove** [comment]
jenkins build this update_data please

**Pull request merged**
