### PR TITLE
fixing bug in Opm::EclIO::ESmry constructor

### PR DESCRIPTION
**Pull request by tskille**
- changed behaviour when opening summary file from restart run
 - will now work with loadBaseRunData=false and original base run folder
   not found.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by tskille** [comment]
Small fix of class ESmry.  Use case that is fixed is the following. 

One restart simulation is moved away from its original location. Hence relative path in restart keyword (smspec file) will no longer be valid. However, should still be possible to open the smspec file with loadBaseRun=false. 

This is ready for review.

**Comment by tskille** [comment]
Sorry forgot to update python bindings code. Fixed now

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
I agree that this use-case makes a lot of sense.  I'll merge into master.

**Pull request merged**
