### PR TITLE
Support polymer keys

### PR DESCRIPTION
**Pull request by lars-petter-hauge**
Fix: https://github.com/OPM/opm-simulators/issues/1507

Depends on: https://github.com/Statoil/libecl/pull/423

### CODE REVIEW

**Comment by lars-petter-hauge** [comment]
jenkins build this please

**Comment by lars-petter-hauge** [comment]
(just want to test that I'm allowed to initiate jenkins.. )

**Comment by lars-petter-hauge** [comment]
So.. It appears that I was a bit too quick.. After some discussion with @GitPaean (thanks by the way), it seems that `rt:polymer` is used in flow_legacy, while the current implementation regards polymer as part of the water rate. I've added the injection rate and total, however the concentration is not yet populated from the simulator side so production will have to wait a bit.

I'll add field and group as well before this one is finished.

**Comment by lars-petter-hauge** [comment]
I believe this should be ready now.

Verified that all commits pass all tests locally.

**Comment by lars-petter-hauge** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
I'll merge this now; observe that this requires: Statoil/libecl#423 - otherwise the newly added `xCIT` keys will not be recognized as *totals* and you will get test errors.

**Pull request merged**
