### PR TITLE
Handle RPTSCHED keywords in a time-sensitive manner

### PR DESCRIPTION
**Pull request by wito**
This feature adds the handling of `RPTSCHED` keywords in a time-sensitive (i.e. `DynamicState<T>`-based) manner. It expands the interface of `Opm::Schedule` as follows:

1. Adds `report_config(std::size_t timeStep)`: Gets the report configuration at `timeStep`.

It also adds `Opm::RPTConfig: public std::unordered_map<std::string,unsigned>`, a container for report settings, with the following interface (in addition to its normal `unsigned_map` interface):

1. `RPTConfig::RPTConfig(const DeckKeyword&)`: Creates a new config entry based on the passed keyword and its arguments.

### CODE REVIEW

**Comment by wito** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
> RPTConfig(const DeckKeyword&)

I don't think that is checked in yet?

**Comment by wito** [comment]
> > RPTConfig(const DeckKeyword&)
> 
> I don't think that is checked in yet?

It should be.

**Comment by wito** [comment]
@joakim-hove Any comments on this?

**Comment by joakim-hove** [comment]
> Any comments on this?

This looks good; I generally prefer "has a" to "is a"; but that is OK.

**Pull request merged**
