### PR TITLE
jenkins: build all ebos extensions

### PR DESCRIPTION
**Pull request by andlaus**
while these are not relevant during normal development, it should be assured that they build fine before a PR is merged. (note that this does not mean that it is assured that the results they produce are still correct, just that they build.)

@akva2: I guess that this PR is for you.

### CODE REVIEW

**Comment by andlaus** [comment]
jenkins build this please

**Comment by andlaus** [comment]
jenkins build this please

**Comment by andlaus** [comment]
jenkins build this please

**Comment by andlaus** [comment]
@joakim-hove: the test failure here seems to be related to your recent well events removal work?

**Comment by andlaus** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
> @joakim-hove: the test failure here seems to be related to your recent well events removal work?

yes - I agree; but I hope it is only due to a merge-race. I'll keep an eye on this.

**Comment by dhan16** [comment]
1. would it be possible to avoid the code duplication below

if test "$1" = "opm-simulators"; then
....	      
CMAKE_ARGS="$CMAKE_ARGS -DBUILD_EBOS_EXTENSIONS=TRUE -DBUILD_EBOS_DEBUG_EXTENSIONS=TRUE"
	  fi

2. we can set -DBUILD_EBOS_EXTENSIONS=TRUE -DBUILD_EBOS_DEBUG_EXTENSIONS=TRUE for all modules right not just opm-simulators? it won't be use but overall would be simpler as the flags would simply be set at the top level instead of per module.

**Comment by andlaus** [comment]
> - would it be possible to avoid the code duplication below

I can't see how: the `build_module()` function does not know the module name and if these arguments get passed unconditionally, one gets ugly cmake "variable-defined-but-unused" warnings for everything but opm-simulators.

> - we can set -DBUILD_EBOS_EXTENSIONS=TRUE -DBUILD_EBOS_DEBUG_EXTENSIONS=TRUE for all modules right not just opm-simulators?

yes, but that results in ugly cmake warnings which are false positives.

**Comment by dhan16** [comment]
ack. thanks

**Comment by andlaus** [comment]
@akva2: any objections to merging this before the April release?

(If jenkins performance is a relevant factor, think it would be more sensible to either disable the tests of the eWoms module, or to get even beefier hardware for the Jenkins instance.)

**Comment by andlaus** [comment]
this is superseeded by #698. closing.

**Pull request closed without merging**
