### PR TITLE
Remove test check for number of items in record

### PR DESCRIPTION
**Pull request by joakim-hove**
Remove minor test statement which creates complication for: #2549

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by akva2** [comment]
https://ci.opm-project.org/job/opm-common-PR-builder/3915/gcc/new/source.8576ed0c-2325-4b0e-a09e-4a795250c93c/#152

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Pull request merged**
