### PR TITLE
Aggregate conn data

### PR DESCRIPTION
**Pull request by joakim-hove**
ACTIONX - a feature that just gives and gives. The restart files should contain the rates which were active when the restart file is written. If the well is closed at the end of a report step current flow will write zero rates to the restart file, whereas the correct is to write the rates for the time just-before-closing. This PR should fix that.

### CODE REVIEW

**Comment by bska** [comment]
Please ensure that you don't break the sign convention here.  Production rates are supposed to be output as positive values in `XCON` while injection rates are supposed to be output as negative values.   It is also not clear to me what you gain by using `SummaryState` instead of `data::Rates` here.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Looks good to me and I appreciate the complications that ACTIONX bring and that necessitate this.  I'll merge into master.

**Pull request merged**
