### PR TITLE
added enum class FuncType for ASTNode.

### PR DESCRIPTION
**Pull request by stefoss23**
This is response to issues https://github.com/OPM/opm-common/issues/1243 and https://github.com/OPM/opm-common/issues/1243.

ASTNode will be supplied with a variable determining what type of keyword (function) is used. This is the FuncType func_type variable.

### CODE REVIEW

**Comment by stefoss23** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Could also  check with the strings which indicate time - `YEAR` and the month names, and use that to set the function type to time.

**Comment by joakim-hove** [comment]
Minor comments - otherwise ready to merge.

**Comment by stefoss23** [comment]
jenkins build this please

**Pull request merged**
