### PR TITLE
Changes to provide Summary output of more Block properties

### PR DESCRIPTION
**Pull request by jalvestad**
changes to allow Summary output of additional block variables

 Allow output of:

    BOSAT
    BWKR
    BOKR
    BKRO
    BGKR
    BKRG
    BKRW
    BWPC
    BGPC
    BVWAT
    BWVIS
    BVGAS
    BGVIS
    BVOIL
    BOVIS
      
For this to work, appropriate changes to opm-simulators in `ecloutputblackoilmodule.hh` needs to be included. This is made in a separate pull request since it belongs to a different repo.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by jalvestad** [comment]
The pull request is finished and ready to be merged unless there are comments from the maintainers.

**Comment by bska** [comment]
jenkins build this please

**Comment by jalvestad** [comment]
I have now rebased the pull request again and I hope it is ready for updating the reference data before merging - which I hope can be done soon so I do not need more rebasing.

**Comment by bska** [comment]
> I have now rebased the pull request again and I hope it is ready for updating the reference data [...] so I do not need more rebasing.

Thank you so much for your efforts and sorry about the delay. I'll do my best to get a data-update through today (Monday 13th May).

**Comment by bska** [comment]
Thank you for rebasing OPM/opm-simulators#1793 too!  I'm happy with the current state and I'll update the reference data.

**Comment by bska** [comment]
jenkins build this opm-simulators=1793 update_data please

**Comment by bska** [comment]
jenkins build this opm-simulators=1793 update_data please

**Comment by bska** [comment]
jenkins build this opm-simulators=1793 update_data please

**Comment by bska** [comment]
jenkins build this opm-simulators=1793 opm-tests=116 please

**Comment by bska** [comment]
jenkins build this opm-simulators=1793 opm-tests=116 please

**Comment by bska** [comment]
CI test with updated test data complete.  I'm merging this now along with OPM/opm-simulators#1793 and OPM/opm-tests#116 to bring in support for the new block quantities in the summary file.

**Pull request merged**
