### PR TITLE
Add support for MECH boundary conditions

### PR DESCRIPTION
**Pull request by akva2**
Sits on top of https://github.com/OPM/opm-common/pull/3633

Extracted from https://github.com/OPM/opm-common/pull/3471 and extended with a test.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
Build will fail, I forgot to run test in release (missing initializers).

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks.  This looks good to me and I'll merge into master.

**Pull request merged**
