### PR TITLE
VFP related needs to be processed even without THP target/limit

### PR DESCRIPTION
**Pull request by GitPaean**
and a zero-value THP limit for WCONPROD will not be treated as a THP limit.

The history matching part is slightly more tricky, was not handled by this PR yet.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
Efforts to fix the history matching mode is on-going, while the tests are not easy to fix due to some interface change.

**Comment by GitPaean** [comment]
There are some tests failed. It might take some substantial efforts to check all of them. Will come back later to this PR.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
The major purpose of this PR is that, even a well does not have a THP limit/target, if there is a valid VFP table assigned to it, its THP value needs to be calculated. The old behavoir for the injection wells is not correct. 

And for history matching wells, if VFP table number is zero/defaulted, it uses the VFP table number from last report step. 

When THP limit is zero, it means there will not be THP limit check.

Please review. If more tests need to be added, please let me know. 

The Schedule can be really complicated, it does not cover all the related possibilities, while it a step towards the correct direction based on understanding of the description. There might be more improvement coming based on future requirement.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Looks good - green in Jenkins; I must admit the gory details of this is so insanely complex it is *really* difficult to keep track.

**Pull request merged**
