### PR TITLE
Some janitoring

### PR DESCRIPTION
**Pull request by akva2**
Not entirely sure about all the contents here, in particular

1) removal of the unused method
2) removal of the unused UDQParams member

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
> Not entirely sure about all the contents here, in particular

The three last commits are uncontroversial - thank you. The unused function in the first commit is - as you point out unused - but it has been valuable when debugging - and will probably be so again if - heaven forbid - a bug should appear. So - would prefer to keep that around - at least a little longer.

**Comment by akva2** [comment]
no problem, hopefully #if 0 is an okay approach.

**Comment by akva2** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
> hopefully #if 0 is an okay approach.

Sure!

**Pull request merged**
