### PR TITLE
Wbp

### PR DESCRIPTION
**Pull request by joakim-hove**
Started on the process of evaluating the summary keywords `WBP, WBP4, WBP5` and `WBP9`. The essence of the these keywords is to calculate an average pressure in the wells. The calculation is based on weighting from the `WPAVE / WWPAVE` keywords and a stencil of n cells surrounding each connected cell.

The plan for this PR is to create a `PAvgCalculator`- this calculator can be filled up with the required values in the simulator, and then evaluated in the Summary code. 

Downstream: https://github.com/OPM/opm-simulators/pull/2940

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
The parallel tests all appear to be timing out at 1500 seconds now.  Could be something about the parallel communication here.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2940 please

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2940 please

**Comment by joakim-hove** [comment]
There is certainly a lot more work to in this part of town - but together with OPM/opm-simulators#2940 the api changes should be in place. Would therefor like to merge that pair later today.

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2940 please

**Pull request merged**
