### PR TITLE
Update RPTSCHED mnemonics instead of replace (support WELLS=N)

### PR DESCRIPTION
**Pull request by vkip**

### CODE REVIEW

**Comment by vkip** [comment]
jenkins build this opm-simulators=5626 please

**Comment by bska** [comment]
This looks fine from a quick glance, but I'll just ask a general question before I do a more thorough review: While there is an API change here, it does not appear that the downstream PR (OPM/opm-simulators#5626) depends on that API change.  Do we need to review/merge the two PRs at the same time or can we review this PR&ndash;in opm-common&ndash;first and then review its companion PR once this has been merged?

**Comment by vkip** [comment]
> This looks fine from a quick glance, but I'll just ask a general question before I do a more thorough review: While there is an API change here, it does not appear that the downstream PR ([OPM/opm-simulators#5626](https://github.com/OPM/opm-simulators/pull/5626)) depends on that API change. Do we need to review/merge the two PRs at the same time or can we review this PR–in opm-common–first and then review its companion PR once this has been merged?

I think only the const 'at' function is required in simulators from the one is common, so doing common first should be fine.

**Review by bska — APPROVED** [review]
>> Do we need to review/merge the two PRs at the same time or can we review this PR–in opm-common–first and then review its companion PR once this has been merged?
>
> I think only the const 'at' function is required in simulators from the one is common, so doing common first should be fine.

Thanks a lot for the confirmation.  I've reviewed this now and it looks good to me.  I'll merge into master.

As an aside, the more common pattern would probably be to introduce a new function,
```C++
bool RPTConfig::update(const DeckKeyword& kw);
```
which returns `true` if the internal state was "updated" in some way.  Then we'd call it from the keyword handler as
```C++
auto cfg = handlerContext.state().rpt_config(); // Intentional copy
if (cfg.update(handlerContext.keyword)) {
    handlerContext.state().rpt_config.update(std::move(cfg));
}
```
but the current approach is fine too.  If we want to add `RPTConfig::update()` in the future we can do so in follow-up work.

**Comment by vkip** [comment]
Thanks! Will keep in mind for next time.

**Pull request merged**
