### PR TITLE
Add dimension to uda in Python

### PR DESCRIPTION
**Pull request by joakim-hove**
This is to some extent a bag of mixed "stuff":

1. Expose `UDAValue, UnitSystem` and `Dimension` to Python
2. Fix bug when creating `UDAValue` in `DeckKeyword` from Python - the `UDAValues`created did not have the necessary dimension attached.
3. Remove some glue code to support Python2

@hakonhagland : I am quite certain that 2) fixes a bug which affects your work in #2833 - but I am afraid this is not enough for #2833.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by hakonhagland** [comment]
> I am quite certain that 2) fixes a bug which affects your work in #2833 - but I am afraid this is not enough for #2833.

@joakim-hove Yes, I tried to rebase #2833 onto this PR and I still get the same problem with the oil rate drops to zero at report step 3.

**Comment by joakim-hove** [comment]
> and I still get the same problem with the oil rate drops to zero at report step 3.

yes - as I said I expected that. I'll merge this now; and then I suggest we have a :movie_camera: meeting later today.

**Pull request merged**
