### PR TITLE
Message formatting edit

### PR DESCRIPTION
**Pull request by nairr**
- Adds linespace before Problem, Message, Bug and Error log output

### CODE REVIEW

**Comment by atgeirr** [comment]
I am pretty sure this would add a blank line to all types, not just those you mention. Furthermore I am skeptical about this change, for the following reasons:
 - If we should change this, a better place would be as a prefix formatting.
 - This will give too much space between normal messages, making the "structure" of timesteps etc. harder to see. This is subjective of course.
 - If particular messages get too little whitespace to stand out, we should consider making just those messages stand out more, either by type or individually (how to make them stand out is a separate question of course).

Do you have an example demonstrating what you seek to accomplish? A screenshot would do?

**Comment by nairr** [comment]
- The idea is to add a blank line before certain output so that it looks like:
commonpr2
instead of:

commonpr1

However I don't see why this inclusion of a blank line should be limited to problems.

- For me this PR doesn't add a blank line for all types. My output looks as follows:
commonpr

- Moreover, if it makes a difference, this change can also made in prefix formatting.

**Comment by atgeirr** [comment]
I was wrong about this affecting all messages. Since as used in Flow the formatter only applies itself to the Warning, Problem, Error and Bug messages, only those are affected. However, if a log was set up with this formatter, and set to apply to all messages (producing Info: before info messages etc.) the current PR would indeed lead to blanks everywhere.

To achieve the effect I think you want (more space around the more serious log messages) it is cleaner to add an initial "\n" character to the prefixes of lines 61 etc. of LogUtil.cpp (the prefixMessage() function), in particular not adding it to the prefixes of less serious messages.

**Comment by alfbr** [comment]
I like this change. While the colours make the serious messages stand out, colours are not available when it is sent to a LOG-file.

**Comment by nairr** [comment]
I have reverted to making the format changes in `prefixMessage()`. Should work fine now!

**Comment by atgeirr** [comment]
> I have reverted to making the format changes in prefixMessage(). Should work fine now!

Nice, will test and merge!

**Comment by atgeirr** [comment]
jenkins build this with downstreams please

**Comment by atgeirr** [comment]
jenkins build this with downstreams please

**Comment by atgeirr** [comment]
The Jenkins failure is because the tests have not been updated. Use "make test" to run them locally. Run the failing program directly (or via "ctest -VV -R pattern_matching_test") to see the details of what is failing. It should be a simple matter of adding some newlines to the expected log outputs.

**Comment by nairr** [comment]
My bad. I've now updated the tests.

**Comment by atgeirr** [comment]
jenkins build this with downstreams please

**Comment by atgeirr** [comment]
Thanks, merging!

**Pull request merged**
