### PR TITLE
Parse WOPRL

### PR DESCRIPTION
**Pull request by joakim-hove**
The summary keywords which start with 'W' and end with 'L' represent completions and should be handled differently from those which start with with 'W' and with !'L'. With this PR  summary keywords like:

```
WOPRL
  'W1'  1 /
  'W2'  4 /
/
```
are correctly parsed - however the resulting completion keyword is not handled in the summary output.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
This is quite trivial - I will merge as soon as Jenkins approves.

**Comment by joakim-hove** [comment]
```
[ 47%] Building CXX object CMakeFiles/co2injection_ncp_ecfv.dir/tests/co2injection_ncp_ecfv.cc.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
CMakeFiles/co2injection_ncp_ecfv.dir/build.make:62: recipe for target 'CMakeFiles/co2injection_ncp_ecfv.dir/tests/co2injection_ncp_ecfv.cc.o' failed
make[2]: *** [CMakeFiles/co2injection_ncp_ecfv.dir/tests/co2injection_ncp_ecfv.cc.o] Error 4
make[2]: *** Deleting file 'CMakeFiles/co2injection_ncp_ecfv.dir/tests/co2injection_ncp_ecfv.cc.o'
```

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins is not in a good mood lately. i'm trying to figure out what is killing all our jobs out of the blue...

**Comment by joakim-hove** [comment]
> jenkins is not in a good mood lately. i'm trying to figure out what is killing all our jobs out of the blue...

Good luck :-)  OOM?

**Comment by akva2** [comment]
no, it's not oom.

**Pull request merged**
