### PR TITLE
extend the range of default AQUTAB table (table 1)

### PR DESCRIPTION
**Pull request by GitPaean**
for better accuracy of the extrapolation. 

it is based on finding through the discussion in https://github.com/OPM/opm-simulators/issues/3985 .

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
The 11th item of the keyword `AQUTAB` is the table number for the influence function for Cater-Tracy aquifers.  The table number 1 also the table will be used if the item 11 was defaulted, is a table provided by the simulator based on a case with constant terminal rate case for an infinite aquifer as given by Van Everdingen and Hurst.  We used a table provided in the paper paper by Van Everdingen and Hurst. (Van Everdingen, A. & Hurst, W., December, 1949.The Application of the Laplace Transformation to Flow Problems in Reservoirs.  Petroleum Transactions, AIME.), while the range of table regarding dimensionless time is rather limited(0.01 to 1000), which causes significant extrapolation error (referring to the discussion in https://github.com/OPM/opm-simulators/issues/3985). 

 Based on the output from the reference simulator, in this PR, we extend the range of the table to `10000`. 

The following is the comparison of the results with the master branch and this PR against the reference output. 
comparison_default_aqutab

And the relative difference of the result from this PR compared with the reference output, 

relative_difference

@bska @atgeirr , let me know if you have some comments or suggestions.

**Comment by GitPaean** [comment]
relative_difference_part

We can see the relative difference is biggest within the original table range (0.01-1000), and also right after the original range.  Maybe we do not need to keep the original table at all, we can design a new table so that we can reduce the error. 

It is very likely the commercial simulator has a different source of default table other than the work mentioned in the comment above.

**Comment by bska** [comment]
> It is very likely the commercial simulator has a different source of default table other than the work mentioned in the comment above.

I don't think they're using an interpolation table at all.  The cited reference includes an empirically determined polynomial and two extensions; a linear approximation for very small (dimensionless) times and a nonlinear approximation for very large times.  That said, extending the range in the way proposed here is probably fine for most applications and is decidedly simpler than reworking they way we handle/represent the Carter-Tracey influence tables internally.

**Comment by atgeirr** [comment]
How did you calculate the extra values for the table?

**Comment by GitPaean** [comment]
> I don't think they're using an interpolation table at all. 

From the AQUDIMS, it looks like they use a 36 point/row table.

**Comment by OPMUSER** [comment]
The left hand table (LHT)  is the E100 table and that we originally had, and the right hand table is the new one from the PR.
2022-08-17 17_49_04-OPM_Flow_Reference_Manual_2022-10_Rev-A ods - LibreOffice Calc

And the real answer from the original paper

2022-08-17 17_52_33-SPE00000000 The Application of - SPE pdf - Adobe Acrobat

So up entry 47 in RHT looks like the original.

**Comment by OPMUSER** [comment]
Further note that:
image

**Comment by GitPaean** [comment]
> Further note that:

With the formula given by Eq. VI-15, the results deviate from the reference output. Maybe the commercial simulator uses a too small table?

**Comment by GitPaean** [comment]
Thanks all for the input. I believe this PR is probably okay as a working version to fix a currently found problem. Unless we want to design the table to be better, I believe the PR can be merged to improve the simulation results for the targeting case.

**Review by bska — APPROVED** [review]
I agree that this is a better alternative than what exists in the current master sources.  I'll merge into master.

**Pull request merged**
