### PR TITLE
Corrected dimensions of SALTPVD

### PR DESCRIPTION
**Pull request by plgbrts**
Note this is an OPM keyword  not present in the commercial simulator.
This PR is part of a few PRs to be  submitted for salt precipitation feature.

### CODE REVIEW

**Comment by bska** [comment]
> This PR is part of a few PRs to be submitted for salt precipitation feature.

Can this PR be reviewed/merged in isolation or do we have to merge everything together in a concerted effort?

**Comment by plgbrts** [comment]
This could be reviewed/merged in isolation

**Comment by bska** [comment]
>> > This PR is part of a few PRs to be submitted for salt precipitation feature.
>> 
>> Can this PR be reviewed/merged in isolation or do we have to merge everything together in a concerted effort?
>
> This could be reviewed/merged in isolation

Thanks, much appreciated.  This looks fine, but I'll run a build check just to be sure we don't accidentally break anything.

**Comment by bska** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Looks good to me.  I'll merge into master.

**Comment by totto82** [comment]
@OPMUSER I think the manual also needs an update if the values is expected to be dimensionless for SALTPVD. 
@plgbrts Does that mean that we should think of it as a saturation or volume concentration instead of a mass concentration?

**Comment by plgbrts** [comment]
Indeed it should be thought of as saturation. (For output we introduce also the SALTP dynamic grid variable representing the precipitated salt saturation.) @OPMUSER indeed the manual needs to be updated. We will inform you about the details.

**Comment by OPMUSER** [comment]
@plgbrts Are the only changes for SALTPVD in the manual the units in the keyword table from lb/stb etc. to dimensionless and some text: 

_A columnar vector of real positive values greater than or equal to zero and less than or equal to one that defines the initial corresponding volume fraction of precipitated salt for the given depth._
 
_Note only the standard Brine Model is supported and therefore there should be only one columnar vector of SALTSAT._

**Comment by plgbrts** [comment]
> @plgbrts Are the only changes for SALTPVD in the manual the units in the keyword table from lb/stb etc. to dimensionless and some text:

@OPMUSER Indeed the text as you propose and I would suggest to 
1) change the header into
_SALTPVD - Initial Precipitated Salt Volume Fraction versus Depth Tables_
2) rephrase  the description:
_The SALTPVD keyword defines the initial precipitated salt volume fraction versus depth tables for each
equilibration region for when OPM Flow’s Salt Precipitation Model has been activated in the input deck via
the PRECSALT keyword in the RUNSPEC section._ 
3) remove this line:
_This keyword is ignored by OPM Flow and....._
4) rephrase  the description of` DEPTH`: 
_A columnar vector of real monotonically increasing down the column
values that defines the depth for the corresponding salt volume fraction SALTSAT._
5) and the second note be rephrased into 
_This is the initial precipitated salt volume fraction contained within the pore space, see `SALTVD` in the
SOLUTION section that defines the initial salt concentration within the water phase._

I noticed that in the manual `PERMFACT` keyword is to be defined in the `SCHEDULE` section but that should be in the _PROPS_ section.

**Pull request merged**
