### PR TITLE
changed: always build with downstreams on jenkins

### PR DESCRIPTION
**Pull request by akva2**
Due to popular demand..

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
ignore failure status, i cancelled the build. good to go if this is what you want...

**Comment by atgeirr** [comment]
I think this is great, at least I have never started a jenkins build with the intention of *not* building downstream modules.

Any comments before we merge this @alfbr, @totto82, @andlaus ?

**Comment by andlaus** [comment]
> Any comments before we merge this @alfbr, @totto82, @andlaus ?

Just this: 👍

**Comment by akva2** [comment]
not doing it like this.

**Comment by akva2** [comment]
the change has been applied in the jenkins part of the build scripts so not visible but all pr builders now build with downstreams.

**Pull request closed without merging**
