### PR TITLE
Fix bgsat

### PR DESCRIPTION
**Pull request by totto82**

### CODE REVIEW

**Comment by akva2** [comment]
no tests picking this one up?

**Comment by totto82** [comment]
SPE1 will pick it up. So we will need to update the ref. data for this one.

**Comment by akva2** [comment]
good

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this update_data please

**Comment by joakim-hove** [comment]
jenkins build this opm-tests=102 please

**Pull request merged**
