### PR TITLE
Ensure units are applied with the MINVALUE and MAXVALUE keywords

### LINKED ISSUE #623: BUG MINVALUE
Unit conversion is not applied correctly when using the `MINVALUE` keyword
```
MINVALUE
'PERMX' 200  /
/
```
gives `PERMX` values of `200m^2` instead of `200 mD`.

Could this be a problem with `ADD` and `PERMX` as well?

### PR DESCRIPTION
**Pull request by joakim-hove**
Should fix #623

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
Does the implementation of `EQUALS` already do the right thing here?

**Comment by joakim-hove** [comment]
>Does the implementation of EQUALS already do the right thing here?

Yes

**Comment by totto82** [comment]
Thanks. Works for the test case.

**Pull request merged**
