### PR TITLE
remove support for the legacy ALUGrid library from dune-grid

### PR DESCRIPTION
**Pull request by andlaus**
Considering the fact that this library has been on life support within
dune-grid since the alugrid development moved to the dune-alugrid
module -- which is available since at least dune 2.3 --, I doubt that
this was very useful and possibly it is even broken.

### CODE REVIEW

**Comment by atgeirr** [comment]
I'll leave it to @dr-robertk to verify and merge this.

**Comment by andlaus** [comment]
Actually I just remembered a case were this could case troubles: if dune-grid was compiled with legacy alugrid support, OPM binaries possibly cannot be linked to such libdunegrids anymore because of missing symbols. Though in practice, I think this is unlikely to affect anyone, so I still argue that removing legacy alugrid support is beneficial.

**Comment by dr-robertk** [comment]
That is ok. ALUGrid has been turned into dune-alugrid which is a DUNE module in the regular sense. So I'll merge, if there is no objections.

**Comment by atgeirr** [comment]
No objection from me, forgot to merge or discovered problem?

**Pull request merged**
