### PR TITLE
Terminal pressure for nodes unequal to top node

### PR DESCRIPTION
**Pull request by plgbrts**
With this PR, the terminal node (root) may be defined for a node different than the top node of the network.
In case _no_ or _multiple_  nodes are found with a terminal pressure a throw will be generated. Two unit tests are added in this PR.

### CODE REVIEW

**Comment by plgbrts** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
I have up to now thought that it is allowed to have multiple nodes with defined pressure, as long as those nodes are at the root of disjoint trees. This PR changes both: it disallows multiple nodes, but at the same time removes the constraint that the node with defined pressure is a root of a tree. I am not sure if this is how the network behaviour should be, or not. Have you come across cases where the new behaviour was clearly required?

Note: despite currently accepting multiple roots with designated pressure in the input part, the simulator code would need a minor extension to work in that case.

Note 2: we should squash the commits to avoid doing-then-undoing changed. Can wait until we agree on merging or not.

**Comment by GitPaean** [comment]
> I have up to now thought that it is allowed to have multiple nodes with defined pressure, as long as those nodes are at the root of disjoint trees. 

I believe so also.  There might be some branches not depending on the main network and rather independent as a sub-network?

**Comment by GitPaean** [comment]
The alternative PR https://github.com/OPM/opm-common/pull/3702 was just merged. I think we can close this PR now. Please re-open the PR if you think this PR is still needed.

**Pull request closed without merging**
