### PR TITLE
Reveal to eclipse corner-point grid

### PR DESCRIPTION
**Pull request by flammmes**
Convert any corner-point grid from IPM's REVEAL simulator to be processed by flow.

Furthermore, flow's python bindings are used to create the deck.

There are no existing wells in this example. I was primarily focused on the correct import of the grid.

I have included two images that showcase a successful example since I am not allowed to provide the raw data.

The first image is from REVEAL. I can't get a better one since my academic license just expired and I am waiting on renewal. The x and y axis seem to be inverted.

image

The second image is from flow's generated .EGRID file viewed in ResInsight . 

image

### CODE REVIEW

**Comment by atgeirr** [comment]
This is interesting, and seems to me a valuable contribution that should be merged. However I am not strong in Python, so preferably someone with more Python experience should do the review. @akva2 or @blattms perhaps?

**Comment by akva2** [comment]
i think this would be better hosted in opm-utilities. it requires opm-simulators as well so opm-common is not a good place for this script.

**Comment by flammmes** [comment]
Ok, i will close this pr and transfer it to opm-utilities.

**Review by bska — COMMENTED** [review]
> i think this would be better hosted in opm-utilities. it requires opm-simulators as well so opm-common is not a good place for this script.

I agree with @akva2 for the same reason.  On another note, the [dimensions](https://github.com/OPM/opm-common/blob/dabb6c4e908790a44b55fddea000db1db784fb32/python/examples/revealToEclipse.py#L141-L152) used in the example will likely not apply to most other models, so the tool isn't quite general enough in its current form.

[OPM-Utilities](https://github.com/OPM/opm-utilities) is a good location for this example.

**Pull request closed without merging**
