### PR TITLE
Support More Summary Vectors

### PR DESCRIPTION
**Pull request by bska**
In particular, add support for outputting the following vectors

  - `WOGR`  &ndash; Well level oil/gas ratio
  - `WWGRH` &ndash; Well level water/gas ratio (observed rates)
  - `FPRH`  &ndash; Field level average pressure (hydrocarbon volume)
  - `FHPV`  &ndash; Field level total hydrocarbon pore-volume

### CODE REVIEW

**Comment by bska** [comment]
I am creating this PR in draft mode for two reasons

1. It is currently missing a set of unit tests
2. It depends on the downstream PR OPM/opm-simulators#4876 to compute the values that go into `FHPV`.

I will keep the PR in draft state until such time as it is ready for review.

**Comment by tklov11** [comment]
Hi,

I have tested the vectors WOGR, WWGRH and FHPV in a full field simulation model, and they look good to me.

Regards
Trygve

**Comment by bska** [comment]
> I have tested the vectors `WOGR`, `WWGRH` and `FHPV` in a full field simulation model, and they look good to me.

Thank you for testing.  I will add a set of unit tests to the current PR and then we'll prioritise getting this into the master branch.

**Comment by bska** [comment]
The upstream PR has been merged into the master branch and I've added a set of unit tests.  I'm marking this as "ready for review" and I'm running a build check.

**Comment by bska** [comment]
jenkins build this please

**Review by akva2 — APPROVED** [review]
Looks good.

**Review by bska — COMMENTED** [review]
Build check is green.  Merging per prior approval.

**Pull request merged**
