### PR TITLE
Multiple welsegs

### PR DESCRIPTION
**Pull request by joakim-hove**
Allow for multiple WELSGES keywords for the same well. The interaction between WELSEGS / COMPDAT / COMPSEGS is not particularly clean - there are probably multiple ways this can fail - but the current implementation is at least not any more fragile than what is already in master.

The initial motivation for this is to be able to run restart cases where the well definition for *all wells* is repeated in the prediction file.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by alfbr** [comment]
I can confirm that this works as advertised.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by akva2** [comment]
any reason this branch pushed to the main git (as in origin/multiple-welsegs)?

**Comment by joakim-hove** [comment]
> any reason this branch was pushed to the main git (as in origin/multiple-welsegs)?

The push to upstream was a mistake. Branch should be pruned.

**Pull request merged**
