### PR TITLE
Ignore THPRES input for restart runs

### PR DESCRIPTION
**Pull request by joakim-hove**
OK - in #391 we added support for writing THPRES data to restart file; now we are ready to read it.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this ewoms=324 please

**Comment by joakim-hove** [comment]
jenkins build this ewoms=324 opm-simulators=1488 please

**Comment by joakim-hove** [comment]
jenkins build this ewoms=324 opm-simulators=1488 please

**Comment by joakim-hove** [comment]
jenkins build this ewoms=324 opm-simulators=1488 please

**Comment by joakim-hove** [comment]
jenkins build this ewoms=324 opm-simulators=1488 please

**Comment by joakim-hove** [comment]
Review?

**Comment by totto82** [comment]
Thanks for the feature. I have looked through the code in common, ewoms and simulator and all seems nice. Have you checked it with one of the field models that uses defaulted THPRESS? Please feel free to merge.

**Comment by joakim-hove** [comment]
> Have you checked it with one of the field models that uses defaulted THPRESS? 

No I have not. The code does not affect the calculation of THPRES values at all, it just loads them from the restart file - when doing a restart. That said I was a little uncomfortable with the existing calculation of default THPRES. Assuming we have three equil regions and this THPRES input:

```txt
THPRES
  1   2  100 /
  1   3 /
/
``` 
then we will have a thresholdpressure between regions 1 & 2 of 100 Bar, the thresholdpressure between regions 1 and 3 will be given by the initial pressure difference along that boundary, and there will be no thpresholdpressure between regions 2 & 3. Looking at the [code here](https://github.com/OPM/ewoms/blob/master/ebos/eclthresholdpressure.hh#L167) I get the impression that OPM currently calculates an initial THPRES between *all* regions; i.e.also between 2 & 3 in the case above. I might be wrong though?

**Pull request merged**
