### PR TITLE
Output of UDQ properties to Eclipse compatible restart file

### PR DESCRIPTION
**Pull request by jalvestad**
This code facilitates output of UDQ-data to Eclipse compatible restart file. 
The code is not fully completed (only minor parts remain) 
The code does currently not write UDQ data to the restart file.
The code has been developed in close collaboration with Joakim Hove and builds on his  implementation of UDQ functionality.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by akva2** [comment]
please address https://ci.opm-project.org/job/opm-common-PR-builder/307/gcc/new/

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
All tests green :heavy_check_mark: :smile:

**Comment by akva2** [comment]
this merged an upstream merge :(

**Comment by atgeirr** [comment]
> this merged an upstream merge :(

I do not understand you comment?

**Comment by akva2** [comment]
the PR merged upstream/master instead of rebasing on it.

this means that in git history, all the changes that was merged in looks as if they came from this PR branch. it's mostly harmless but all hell breaks loose when you want to cut the three. i fought this a lot in opm-core etc when we split those tree's up, so it should be avoided.

**Comment by GitPaean** [comment]
Are you suggesting we should rebase before we get the PR in?  I would like it. 

It might not be very easy for some PR that went through long development period sometimes, while I think it is a good thing to do.

**Comment by akva2** [comment]
not what i'm saying. i'm saying that if you want/have to bring in changes from upstream into your feature branch this has to be done through a rebase, not through a merge.

**Comment by atgeirr** [comment]
> not what i'm saying. i'm saying that if you want/have to bring in changes from upstream into your feature branch this has to be done through a rebase, not through a merge.

Thanks for the explanation! You cannot assume I understand this easily...

**Pull request merged**
