### PR TITLE
Gconinje rst

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by jalvestad** [comment]
Hi,
I have tested this PR with the test data set 2_GCONINJE_NETV.DATA in opm-tests/model5. Eclipse restart from flow now works OK, so I think the PR is OK.

**Comment by joakim-hove** [comment]
jenkins build this update_data please

**Comment by joakim-hove** [comment]
jenkins build this opm-tests=704 please

**Comment by joakim-hove** [comment]
jenkins build this opm-tests=704 please

**Pull request merged**
