### PR TITLE
Allow using external static libraries with BUILD_SHARED_LIBS=ON

### PR DESCRIPTION
**Pull request by blattms**
Previously, this failed if one dependency was a static library compiled
without -fPIC. This is is the case for library libsuitesparseconfig on
Debian which has no dynamic alternative. The error messages read e.g.

```
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libsuitesparseconfig.a(SuiteSparse_config.o): relocation R_X86_64_PC32 against undefined symbol `malloc@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
```

With this patch we change the target_link_libraries call when using
BUILD_SHARED_LIBS=ON. We only pass the dynamic libraries as PUBLIC such
that they will get linked to the library. The static ones are passed as
INTERFACE libraries. This means that they will be automatically linked
to executables which link to the main library. Currently this transitive
linking will only work in the same module as we do not correctly export
libraries. But our build system explicitly links the others ones anyway.

### CODE REVIEW

**Comment by akva2** [comment]
this is a bug in debian, but you probably know that (fixed in testing/unstable, as well as derivatives).

that being said, this is the correct approach. ideally it should carry over in the config file as well, but as long as it works with dc it will do for now. you use dc right?

**Comment by blattms** [comment]
I must be getting old. Lots of new acronyms I have never heard
of. What is dc?

**Comment by akva2** [comment]
dune control

**Comment by blattms** [comment]
dunecontrol? Yes I use that, but that should be unrelated.

**Comment by akva2** [comment]
well it's not. dune-control uses cmake config mode, the opm buildsystem uses find rules.

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Comment by blattms** [comment]
> well it's not. dune-control uses cmake config mode, the opm buildsystem uses find rules.

That seems to be a myth as it just calls configure or cmake. Maybe
with different options, though.

With dune 2.3.1 the configure script of the opm module gets called:
```
--- calling configure for opm-parser ---
./configure  "--with-opm-common=/home/mblatt/build-test/opm-common/" ACLOCAL_AMFLAGS="-I ."
--- deleting previous CMake files ---
--- calling CMake ---
cmake "." "-DCMAKE_INSTALL_PREFIX=/usr/local" -DSIBLING_SEARCH=OFF  "-DOPM_COMMON_ROOT=/home/mblatt/build-test/opm-common"
```

2.4 or later calls cmake directly:
```
--- calling configure for opm-parser ---
/home/mblatt/src/dune/opm/opm-common/lib/opmcommonam2cmake.lib for converting options does not exist
/home/mblatt/src/dune/opm/opm-parser/lib/opmparseram2cmake.lib for converting options does not exist
 cmake -DCMAKE_MODULE_PATH=""  "-Dopm-common_DIR=/home/mblatt/src/dune/opm/opm-common/build-cmake"  "/home/mblatt/src/dune/opm/opm-parser"
```

My original question would habe been: "How does that influence how
find_package works?"

But then I tried to understand the code in OpmPackage.cmake and
miserably failed. That is a lot of magic. Maybe we should get rid of
some of it once we drop support for DUNE <2.4.

**Comment by akva2** [comment]
no, that's no myth at all. dune-control sets foo_DIR. this makes cmake see the foo-config.cmake that sits in the build directory. that overrides the entire find rule - the config file takes precedence. it's how modern cmake is meant to do things, so it's not a bad thing in itself. but as the "other" paths in the build system use the legacy find rule stuff, i need to look out for differences since we are basically maintaining both legacy and modern mode.

**Comment by akva2** [comment]
for reference, i addressed this issue on ubuntu back when i had to deal with it, 3-4 years ago, https://launchpad.net/~opm/+archive/ubuntu/ppa/+packages hence the rebuilt suitesparse for trusty. that's a backport from the debian science fixed packages.

**Comment by blattms** [comment]
Our very own build system begs to differ:

dunecontrol --only=opm-grid configure|grep "Finding package"|grep -e dune

-- Finding package dune-common using module mode
-- Finding package dune-grid using module mode
-- Finding package dune-geometry using module mode
-- Finding package dune-istl using module mode

dunecontrol --only=opm-grid configure|grep "Finding package"|grep -e opm

-- Finding package opm-parser using module mode

Do underestimate black magic ;)

**Comment by akva2** [comment]
well.

_DIR is set for things that are part of the build orchestrated by dune-control. it's the build directory for the particular module. 

```
dunecontrol all
....
cmake -DCMAKE_MODULE_PATH=""  "-Dopm-common_DIR=/home/akva/kode/opm/dc/opm-common/build-cmake"  "/home/akva/kode/opm/dc/opm-parser"

->

silenty located opm-common since /home/akva/kode/opm/dc/opm-common/build-cmake/opm-common-config.cmake is seen by cmake.
```

the opm buildsystem mocks around a lot with MODULE and CONFIG mode forcing in OpmFind.cmake so we end up with the use of find rules for dune rather than the prepared config files. why? no idea. but it's explicitly coded to behave like this, it's not what cmake would do on itself.

**Comment by blattms** [comment]
I did not take any offence.

And in this line of though: I did not want to bash the OPM buildsystem either. It must have been a rather tough job to implement this with all the bells and whistles in the times when DUNE was still only supporting autotools. The magic is there for a reason. Kudos to @rolk for his good job.

Thanks for merging.

**Pull request merged**
