### PR TITLE
Fix subsecond timesteps

### PR DESCRIPTION
**Pull request by atgeirr**
OPM Flow could not handle deck files with sub-second report steps due to multiple separate issues.
 - Use of `std::chrono::duration_cast<std::chrono::seconds>`. This casts any duration to std::chrono::seconds, which is a duration class with 1 second tick, storing the count of ticks in an integer. So it has 1s resolution. The cast is only needed when going from a duration storing the tick count in a float or double to one with integer count anyway, so it can be avoided some of the time, when we stay with double representation for durations. The Opm::time_point uses integer representation, but with a 1ms tick. So when converting to that we must do the duration_cast, but I think 1ms resolution is fine.
 - Clamping to time_t resolution, which is 1s. This was done because of serialization for Opm::time_point using time_t. This is no longer done, so the clamping has been removed here.
 
The downstream companion PR is needed for extending the serialization fix to the MPI packer.

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins build this opm-simulators=5795 failure_report please

**Comment by atgeirr** [comment]
Failures due to sub-second initial steps (0.0001 day mostly), causing mismatch in time step now that we do not round them down to whole seconds. Will initiate a data update.

**Comment by atgeirr** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
jenkins build this opm-tests=1263 opm-simulators=5795 please

**Review by akva2 — APPROVED** [review]

**Comment by atgeirr** [comment]
Merging as per approval.

**Pull request merged**
