### PR TITLE
Add More Segment Level Summary Vectors

### PR DESCRIPTION
**Pull request by bska**
In particular, add support for

* `SxFT`  - Cumulative flow of phase `x`
* `SxFV`  - Free flow velocity of phase `x`
* `SxHF`  - Free flow holdup fraction of phase `x`
* `SxVIS` - Phase viscosity of phase `x`

The last three of these were added to the RFT file in commit 802a401a8 (PR #3184), but are also useful in the summary output file.  In the interest of avoiding duplicate logic, refactor the existing segment-related quantity calculation/extraction in terms of callbacks.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
I'm satisfied that this does what I want it to do, so I'm marking it as "ready for review" and running a build check.

**Comment by bska** [comment]
jenkins build this please

**Review by akva2 — APPROVED** [review]
Looks good to me

**Comment by blattms** [comment]
Approved by @akva2. Merging.

**Pull request merged**
