### PR TITLE
 [cmake] Properly support scotch as a metis replacement

### PR DESCRIPTION
**Pull request by lisajulia**
Based on https://github.com/OPM/opm-common/pull/4115/

### CODE REVIEW

**Comment by lisajulia** [comment]
jenkins build this please

**Comment by bska** [comment]
> Based on #4115

Does that mean that this PR replaces #4115, or do the two PRs serve (slightly) different purposes?

**Comment by lisajulia** [comment]
> > Based on #4115
> 
> Does that mean that this PR replaces #4115, or do the two PRs serve (slightly) different purposes?

It replaces #4115

**Comment by lisajulia** [comment]
@bska or @akva2 or @blattms I'd say this can be merged :)

**Comment by blattms** [comment]
Shoot and my apologies. I merged the other one. Would you please rebase this one.

**Comment by lisajulia** [comment]
Yes :)

**Comment by blattms** [comment]
Thanks.
In CMake's if statements TRUE and positive numbers seem equivalent, also FALSE and 0.
Hence I am wondering what this fixes. Something in config.h?

**Comment by blattms** [comment]
Seems like some TRUE ends up in config.h and we get a compile about undefined literal.
Will merge once jenkins is green.

**Pull request merged**
