### PR TITLE
Actionx restart

### PR DESCRIPTION
**Pull request by joakim-hove**
This changes the internalization of the ACTIONX conditions to support restart.

I guess/hope this is a step in the right direction, but I am slightly uncomfortable - in particular I am uncertain on how paranthesis in the expression should be handled.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by jalvestad** [comment]
Hi Joakim,
I have used this pull request and the data structure provided seems to cover the needs I have as far as I can see just now, Thanks a lot! Jostein

**Comment by joakim-hove** [comment]
> I have used this pull request and the data structure provided seems to cover the needs I have a [...]

Good - thank you.

**Pull request merged**
