### PR TITLE
Support restart with VREP in GCONINJE

### PR DESCRIPTION
**Pull request by vkip**

### CODE REVIEW

**Comment by vkip** [comment]
jenkins build this please

**Comment by vkip** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
This looks good to me.  Thanks a lot for expanding our feature support in this area!  I'll merge into master.

**Comment by bska** [comment]
Sorry&ndash;I have to revert this pending a more thorough investigation of the test failures.

**Pull request merged**
