### PR TITLE
Stop pretending that we support CMake 2.8

### PR DESCRIPTION
**Pull request by blattms**
We actually already require at least CMake 2.8.12 due to the embedded pybind11 (some tests of it are even at 3.0). Anyway as Ubuntu LTS has 3.10.2 I doubt that anything less is tested by us.

@akva2 What version do  we need to support for Redhat? If that is lower then we need to drop the minimum of course,

### CODE REVIEW

**Comment by akva2** [comment]
centos7/rhel7 has 3.17 right now so there's no problem there.

**Comment by alfbr** [comment]
No problem bumping minimum cmake version on our end either.

**Comment by blattms** [comment]
jenkins build this opm-material=449 opm-models=644 opm-grid=518 opm-simulators=3237 opm-upscaling=330 please

**Comment by bska** [comment]
If we're bumping this anyway, is there a reason not to go to all the way to 3.10.2 (Ubuntu 18.04 LTS)?

**Comment by bska** [comment]
jenkins build this opm-material=449 opm-models=644 opm-grid=518 opm-simulators=3137 opm-upscaling=330 please

**Comment by blattms** [comment]
@bska I am a bit torn. Personally, I think requiring a patch-level should not be needed (as they should be compatible), Then again this CMake.... (which might indicate otherwise). If you insist, I will do that.

I will fix the fallout in the evening.

**Comment by bska** [comment]
> Personally, I think requiring a patch-level should not be needed

Agreed.  I don't care about the `.2`, but I'd appreciate having `3.10` or at least something more modern than `3.0`.  If we ever decide to go with imported targets and the `target_*` family of functions enabled by `find_package()`, `3.10` is very different from `3.0`.

**Comment by blattms** [comment]
the patch  is already requiring 3.10. Sorry, if that was not clear.

**Comment by bska** [comment]
> the patch is already requiring 3.10

Huh, you're absolutely right.  I guess I need an eye exam because I read the patch as `3.0` instead.

**Comment by blattms** [comment]
Maybe an effect of too much staring at monitors per day...

**Comment by bska** [comment]
> Maybe an effect of too much staring at monitors per day...

Definitely possible.  I do think the accompanying change in OPM/opm-grid#518 needs a little bit of attention though.

**Comment by blattms** [comment]
Could not reproduce the build failures with rebased versions. force-pushed the rebased ones and trying again.

**Comment by blattms** [comment]
Got jenkins, thanks. Wrong PR number for simulators.

**Comment by blattms** [comment]
jenkins build this opm-material=449 opm-models=644 opm-grid=518 opm-simulators=3137 opm-upscaling=330 please

**Comment by blattms** [comment]
Haunted by python. Of course I deactivated that on my system to save time. Kind of backfired...

**Comment by blattms** [comment]
jenkins build this opm-material=449 opm-models=644 opm-grid=518 opm-simulators=3137 opm-upscaling=330 please

**Comment by bska** [comment]
jenkins build this opm-material=449 opm-models=644 opm-grid=518 opm-simulators=3137 opm-upscaling=330 please

**Comment by bska** [comment]
jenkins build this opm-material=449 opm-models=644 opm-grid=518 opm-simulators=3137 opm-upscaling=330 please

**Comment by blattms** [comment]
Hopefully issues in opm-grid and opm-simulators are resolved now.

**Comment by blattms** [comment]
jenkins build this opm-material=449 opm-models=644 opm-grid=518 opm-simulators=3137 opm-upscaling=330 please

**Comment by blattms** [comment]
Off I go for another rebase...

**Comment by blattms** [comment]
jenkins build this opm-material=449 opm-models=644 opm-grid=518 opm-simulators=3137 opm-upscaling=330 please

**Comment by blattms** [comment]
Grrr.....

**Comment by blattms** [comment]
Let's try again. somehow an old commit got picked up for opm-models.

**Comment by blattms** [comment]
jenkins build this opm-material=449 opm-models=644 opm-grid=518 opm-simulators=3137 opm-upscaling=330 please

**Comment by blattms** [comment]
I am loosing my patience, and will do this one by one now.

**Comment by blattms** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this opm-material=449 opm-models=644 opm-grid=518 opm-simulators=3137 opm-upscaling=330 please

**Pull request merged**
