### PR TITLE
Add W keywords up to WSEGTABL

### PR DESCRIPTION
**Pull request by joakim-hove**
Some keywords

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
Do we need to update [`MissingFeatures.cpp`](https://github.com/OPM/opm-simulators/blob/cc2304c8b136689509a790fb94cb716ff84e1bc9/opm/simulators/flow/MissingFeatures.cpp#L82) accordingly?

**Comment by joakim-hove** [comment]
>åDo we need to update MissingFeatures.cpp accordingly?

Yes - have not got around to it yet.

**Comment by bska** [comment]
> > Do we need to update `MissingFeatures.cpp` accordingly?
> 
> Yes - have not got around to it yet.

Do you want to make those changes before we merge this [i.e., PR #1053]?

**Comment by joakim-hove** [comment]
> Do you want to make those changes before we merge this [i.e., PR #1053]?

The list of keywords is endless - I merge regularly when Jenkins is happy.

**Pull request merged**
