### PR TITLE
split out timing macros to separate header

### PR DESCRIPTION
**Pull request by akva2**
My OCD twitched. Separation of concerns, no reason to pull in strings, exceptions, logging.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-simulators=4498 please

**Comment by bska** [comment]
I'm slightly surprised there's no follow-up PR in OPM-Models given that OPM/opm-models#789 introduced such macro calls there too.

**Comment by akva2** [comment]
so was I. but header hygiene isn't very good in opm-models. it's not required to compile, but i can of course add some includes there.

**Comment by akva2** [comment]
jenkins build this opm-simulators=4498 opm-models=790 please

**Pull request merged**
