### PR TITLE
Fixup of alternating records special case

### PR DESCRIPTION
**Pull request by joakim-hove**
Ahh these keywords - they just neeeever end ... ;-(

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by totto82** [comment]
Thanks! I will rebase #1254 on top of this when merged. Hopefully, #1254 can be merged soon after.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
```
ure virtual method called
terminate called without an active exception
[opm-deb:11240] *** Process received signal ***
[opm-deb:11240] Signal: Aborted (6)
[opm-deb:11240] Signal code:  (-6)
[opm-deb:11240] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x110e0)[0x7fa6eb3140e0]
[opm-deb:11240] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcf)[0x7fa6e556bfff]
[opm-deb:11240] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7fa6e556d42a]
[opm-deb:11240] [ 3] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x15d)[0x7fa6e5dad0ad]
[opm-deb:11240] [ 4] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8f066)[0x7fa6e5dab066]
[opm-deb:11240] [ 5] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8f0b1)[0x7fa6e5dab0b1]
[opm-deb:11240] [ 6] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8fb8f)[0x7fa6e5dabb8f]
[opm-deb:11240] [ 7] /var/lib/jenkins/post-builder/workspace/opm-common-PR-builder/mpi/build-opm-simulators/bin/flow(_ZNK3Opm6Logger16addTaggedMessageElRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_+0x103)[0x561d55152de3]
[opm-deb:11240] [ 8] /var/lib/jenkins/post-builder/workspace/opm-common-PR-builder/mpi/build-opm-simulators/bin/flow(_ZNK3Opm6Logger10addMessageElRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x2b)[0x561d5515300b]
[opm-deb:11240] [ 9] /var/lib/jenkins/post-builder/workspace/opm-common-PR-builder/mpi/build-opm-simulators/bin/flow(_ZN3Opm9RestartIO4saveERNS_5EclIO12OutputStream7RestartEidNS_12RestartValueERKNS_12EclipseStateERKNS_11EclipseGridERKNS_8ScheduleERKNS_12SummaryStateEb+0x1bc5)[0x561d5503fd15]
[opm-deb:11240] [10] /var/lib/jenkins/post-builder/workspace/opm-common-PR-builder/mpi/build-opm-simulators/bin/flow(_ZN3Opm9EclipseIO13writeTimeStepERKNS_12SummaryStateEibdNS_12RestartValueEb+0x9d9)[0x561d55031f59]
[opm-deb:11240] [11] /var/lib/jenkins/post-builder/workspace/opm-common-PR-builder/mpi/build-opm-simulators/bin/flow(_ZN3Opm9EclWriterINS_10Properties4TTag22EclFlowOilWaterProblemEE15EclWriteTasklet3runEv+0x53)[0x561d543f8083]
[opm-deb:11240] [12] /var/lib/jenkins/post-builder/workspace/opm-common-PR-builder/mpi/build-opm-simulators/bin/flow(_ZN3Opm13TaskletRunner18startWorkerThread_EPS0_i+0xa7)[0x561d53f63887]
[opm-deb:11240] [13] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb9e6f)[0x7fa6e5dd5e6f]
[opm-deb:11240] [14] /lib/x86_64-linux-gnu/libpthread.so.0(+0x74a4)[0x7fa6eb30a4a4]
[opm-deb:11240] [15] /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7fa6e5621d0f]
[opm-deb:11240] *** End of error message ***
/var/lib/jenkins/post-builder/workspace/opm-common-PR-builder/deps/opm-simulators/tests/run-regressionTest.sh: line 19: 11240 Aborted                 ${BINPATH}/${EXE_NAME} ${TEST_ARGS} --output-dir=${RESULT_PATH}
```

Can not see how this relates to my PR? I'll try to kick it one more time

**Comment by joakim-hove** [comment]
jenkins build this please

**Pull request merged**
