### PR TITLE
Use argument reportStep + 1 when evaulating WELPI in  ACTIONX

### PR DESCRIPTION
**Pull request by joakim-hove**
See the comment in the code.

### CODE REVIEW

**Comment by bska** [comment]
> See the comment in the code.

Yeah, this is the way OPM/opm-simulators#2866 handles `WELPI`.  In light of ACTIONX, we may need to be able to run `WELPI` at the beginning of every timestep ("ministep") instead.  The extreme case would be in the prediction part of the simulation run, with one-year report steps and ACTIONX triggering a WELPI event on day two of the current report step.  That would lead to **very** different predictions compared to only handling the event one year later.

I'd prefer to get OPM/opm-simulators#2866 in in its current state, however, and then refining it to detect events at timestep levels  in a follow-up PR.  For now, this looks good to me.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks.  This looks good to me.  I'll merge into master.

**Pull request merged**
