### PR TITLE
Initialize group production guide_rate to Target::NONE

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by alfbr** [comment]
@joakim-hove maybe we can abuse this PR to do an update data once https://github.com/OPM/opm-tests/pull/319 is merged? If so, we need the update_data drill on this one.

**Comment by joakim-hove** [comment]
> @joakim-hove maybe we can abuse this PR to do an update data once OPM/opm-tests#319 is merged? If so, we need the update_data drill on this one.

Sure - it is all yours.

**Comment by alfbr** [comment]
jenkins build this update_data opm-tests=319 please

**Comment by bska** [comment]
> jenkins build this update_data opm-tests=319 please

Hm, that came back green and it really shouldn't have.  It looks like it didn't actually pick up the changes in OPM/opm-tests#319.  I'm inclined to just merge the latter and then rerun the data update from here.

**Comment by alfbr** [comment]
>I'm inclined to just merge the latter and then rerun the data update from here.

Please do, it is all yours.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
I'm merging this now.  There's no response from those who directly work in this area of the simulator, but it looks correct to me.

**Pull request merged**
