### PR TITLE
Add Means of Detecting Valid Cell Geometries

### PR DESCRIPTION
**Pull request by bska**
We define a valid cell geometry as one in which all components of all eight corner vertices of a cell have finite coordinate values (absolute value less than `1.0E+20`) and at least one pair of pillar vertices are separated by a positive distance.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by blattms** [comment]
Why the artificial bound for infinity? Is there a specific problem that this solves?

Should we use >\epsilon rather than >0 for positive distance?

**Comment by bska** [comment]
> Why the artificial bound for infinity?

The special value `1.0E+20` (positive or negative, irrespective of unit system convention) is the commercial simulator's notion of infinity in its restart/summary files.  If we interpret this value as a distance in metres it covers on the order of 10,000 light years or roughly 10% of the diameter of the Milky way galaxy.  In the case of large magnitude negative values (i.e., `-1.0E+20`) the value is additionally treated as a sentinel to signal "unset" or "undefined" item/quantity.  The `.INIT` file sometimes uses `2.0E+20` for similar purposes.

> Is there a specific problem that this solves?

Yes.  As I [mentioned](https://github.com/OPM/opm-simulators/pull/3845#issuecomment-1075317897) in the companion PR in opm-simulators I got a simulator crash on a model that used `GDFILE` to import an `EGRID` file in which all `COORD` and all `ZCORN` values were set to `-1.0E+20`.  To be clear, this was absolutely a model input error and there's no way for us to simulate that geometry but it's better to detect the situation than to try it.

> Should we use >\epsilon rather than >0 for positive distance?

Yes, probably.  Something on the order of millimetres to centimetres is probably better here.

**Comment by blattms** [comment]
> Yes, probably. Something on the order of millimetres to centimetres is probably better here.

So you will change it? Then I'll wait.

**Comment by bska** [comment]
>>> Should we use >\epsilon rather than >0 for positive distance?
>> 
>> Yes, probably. Something on the order of millimetres to centimetres is probably better here.
>
> So you will change it? Then I'll wait.

I've pushed an update to this effect now.

**Comment by bska** [comment]
jenkins build this please

**Pull request merged**
