### PR TITLE
Add prefix the schedule messages to highlight ACTIONX rerun

### PR DESCRIPTION
**Pull request by joakim-hove**
When an ACTIONX keyword has evaluated to true the Schedule section is replayed. This can become quite confusing in the .PRT file - with the current PR the reruns are formatted to stand out better.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
> with the current PR the reruns are formatted to stand out better.

May we see an example of before/after, please?

**Comment by joakim-hove** [comment]
Before:
```Time step 24, stepsize 1 days, at day 26.7901/31, date = 27-Jul-2020
The action: INJECTION evaluated to true at 2020/07/28  report:3 wells: P1
Processing dynamic information from
/home/hove/work/OPM/opm-tests/udq_actionx/ACTIONX_M1.DATA line 297
Initializing report step 5/15 at 2020-07-01 31.0 DAYS line 297
Complete report step 4 (27.0 DAYS) at 2020-08-01 (4.0 DAYS)

Initializing report step 5/15 at 2020-08-01 (4.0 DAYS) - line 426
Complete report step 5 (9.0 DAYS) at 2020-08-10 (31.0 DAYS)

Initializing report step 6/15 at 2020-08-10 (31.0 DAYS) - line 426
Complete report step 6 (10.0 DAYS) at 2020-08-20 (40.0 DAYS)

Initializing report step 7/15 at 2020-08-20 (40.0 DAYS) - line 426
Processing keyword WCONPROD at line 432
Complete report step 7 (12.0 DAYS) at 2020-09-01 (50.0 DAYS)

Initializing report step 8/15 at 2020-09-01 (50.0 DAYS) - line 436
Complete report step 8 (9.0 DAYS) at 2020-09-10 (62.0 DAYS)
Report limit reached, see PRT-file for remaining Schedule initialization.

Initializing report step 9/15 at 2020-09-10 (62.0 DAYS) - line 436
Complete report step 9 (10.0 DAYS) at 2020-09-20 (71.0 DAYS)

Initializing report step 10/15 at 2020-09-20 (71.0 DAYS) - line 436
Complete report step 10 (11.0 DAYS) at 2020-10-01 (81.0 DAYS)

Initializing report step 11/15 at 2020-10-01 (81.0 DAYS) - line 436
Complete report step 11 (9.0 DAYS) at 2020-10-10 (92.0 DAYS)

Initializing report step 12/15 at 2020-10-10 (92.0 DAYS) - line 436
Complete report step 12 (10.0 DAYS) at 2020-10-20 (101.0 DAYS)

Initializing report step 13/15 at 2020-10-20 (101.0 DAYS) - line 436
Complete report step 13 (12.0 DAYS) at 2020-11-01 (111.0 DAYS)

Initializing report step 14/15 at 2020-11-01 (111.0 DAYS) - line 436
Complete report step 14 (30.0 DAYS) at 2020-12-01 (123.0 DAYS)

Initializing report step 15/15 at 2020-12-01 (123.0 DAYS) - line 436
Complete report step 15 (31.0 DAYS) at 2021-01-01 (153.0 DAYS)

Initializing report step 16/15 at 2021-01-01 (153.0 DAYS) - line 436
```


After:
```
Time step 24, stepsize 1 days, at day 26.7901/31, date = 27-Jul-2020
The action: INJECTION evaluated to true at 2020/07/28  report:3 wells: P1
/----------------------------------------------------------------------
| Action INJECTION evaluated to true. Will add action keywords and
| rerun Schedule section
| 
| Processing keyword WELOPEN from /home/hove/work/OPM/opm-tests/udq_actionx/ACTIONX_M1.DATA line 379
| Processing keyword UDQ from /home/hove/work/OPM/opm-tests/udq_actionx/ACTIONX_M1.DATA line 383
| 
| Processing dynamic information from
| /home/hove/work/OPM/opm-tests/udq_actionx/ACTIONX_M1.DATA line 297
| Initializing report step 5/15 at 2020-07-01 31.0 DAYS line 297
| Complete report step 4 (27.0 DAYS) at 2020-08-01 (4.0 DAYS)
| 
| Initializing report step 5/15 at 2020-08-01 (4.0 DAYS) - line 426
| Complete report step 5 (9.0 DAYS) at 2020-08-10 (31.0 DAYS)
| 
| Initializing report step 6/15 at 2020-08-10 (31.0 DAYS) - line 426
| Complete report step 6 (10.0 DAYS) at 2020-08-20 (40.0 DAYS)
| 
| Initializing report step 7/15 at 2020-08-20 (40.0 DAYS) - line 426
| Processing keyword WCONPROD at line 432
| Complete report step 7 (12.0 DAYS) at 2020-09-01 (50.0 DAYS)
| 
| Initializing report step 8/15 at 2020-09-01 (50.0 DAYS) - line 436
| Complete report step 8 (9.0 DAYS) at 2020-09-10 (62.0 DAYS)
| Report limit reached, see PRT-file for remaining Schedule initialization.
| 
| Initializing report step 9/15 at 2020-09-10 (62.0 DAYS) - line 436
| Complete report step 9 (10.0 DAYS) at 2020-09-20 (71.0 DAYS)
| 
| Initializing report step 10/15 at 2020-09-20 (71.0 DAYS) - line 436
| Complete report step 10 (11.0 DAYS) at 2020-10-01 (81.0 DAYS)
| 
| Initializing report step 11/15 at 2020-10-01 (81.0 DAYS) - line 436
| Complete report step 11 (9.0 DAYS) at 2020-10-10 (92.0 DAYS)
| 
| Initializing report step 12/15 at 2020-10-10 (92.0 DAYS) - line 436
| Complete report step 12 (10.0 DAYS) at 2020-10-20 (101.0 DAYS)
| 
| Initializing report step 13/15 at 2020-10-20 (101.0 DAYS) - line 436
| Complete report step 13 (12.0 DAYS) at 2020-11-01 (111.0 DAYS)
| 
| Initializing report step 14/15 at 2020-11-01 (111.0 DAYS) - line 436
| Complete report step 14 (30.0 DAYS) at 2020-12-01 (123.0 DAYS)
| 
| Initializing report step 15/15 at 2020-12-01 (123.0 DAYS) - line 436
| Complete report step 15 (31.0 DAYS) at 2021-01-01 (153.0 DAYS)
| 
| Initializing report step 16/15 at 2021-01-01 (153.0 DAYS) - line 436
\----------------------------------------------------------------------
```

**Comment by bska** [comment]
Thanks for the example.  I agree that this will make the `.PRT` file easier to read for humans.

**Pull request merged**
