### PR TITLE
Tskille pybind eclio

### PR DESCRIPTION
**Pull request by joakim-hove**
This is a minor reworking of #1179. With this PR there is a Python api like:
```Python
from opm.io.ecl import EclFile
f = EclFile("CASE.INIT")
print("Available keywords:")
for header in f.arrays():
     print(header)


if "PRESSURE" in f:
    print("Have PRESSURE")
else:
   print("NO pressure")

print("Have {} keywords".format(len(f)))

kw0 = f[0]
```
`kw0` will then be `numpy` based array of the correct type. Name-based lookup like `f["PRESSURE"]` is deferred until we have found a good api; string based lookup should in my opinion return a list/iterable - but that is not what the current C++ class does. And they should probably agree ... 

Observe that this PR is on top of #1184 - which might very well receive a beating before it is merged.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
@tskille - I have updated this PR according to our discussion - I hope you are happy with it. Observe that this PR is situated on top of #1180 and #1190.

**Comment by tskille** [comment]
@joakim-hove - this is excellent. I'm looking forward to see this merge.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by akva2** [comment]
I am sorry for missing this in the other PR. You have to move the block adding the python library to opm-common_LIBRARIES into the config_hook macro. Where it sit now, it is processed too late, and you will only get it in the config file if you run cmake twice.

**Comment by joakim-hove** [comment]
> wrong analysis. this fixes it

Thank you!

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by akva2** [comment]
grml, the rule expects the full path to the python executable. fixed now.

**Comment by akva2** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
> grml, the rule expects the full path to the python executable. fixed now.

Cool - but fixed where...? Have you pushed a fix somewhere?

**Comment by akva2** [comment]
it is set in machine specific toolchain files, which i have updated.

**Comment by joakim-hove** [comment]
At last - thank you for help and patience!

**Pull request merged**
