### PR TITLE
test_co2brinepvt: Some janitoring

### PR DESCRIPTION
**Pull request by akva2**
- avoid dead stores
- convert to boost::test

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Review by blattms — COMMENTED** [review]
Shouldn't we put spaces/line breaks between the printed values.

**Comment by akva2** [comment]
Same as the other PR, these values are never actually printed.

**Review by bska — APPROVED** [review]
With the stated intention of gradually making this into a more proper unit test I'll merge this into master now.

**Pull request merged**
