### PR TITLE
Add missing HEATCR and HEATCRT to props

### PR DESCRIPTION
**Pull request by totto82**
The simulator supports HEATCR and HEATCRT but they where missing from the field prosps.

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by OPMUSER** [comment]
@atgeirr This does not fix the exception in issue https://github.com/OPM/opm-common/issues/3411, we still get:

`Program threw an exception: EclProblem::updateCompositionChangeLimits_()) failed:Invalid thermal conductivity approach: 0   `

The issue is that we do not check if all the require data for the Thermal model have been entered in the deck, if a particular data item is missing then the simulator throws an exception.

**Comment by atgeirr** [comment]
> This does not fix the exception in issue #3411

I think it was not claimed that it would. In any case, do not close the issue until fixed. Will you work on the fix, or should someone else implement it? I think you or @totto82 probably know best which keywords need to go together, I imagine it is complicated but perhaps I am wrong?

**Comment by OPMUSER** [comment]
> I think it was not claimed that it would. In any case, do not close the issue until fixed. Will you work on the fix, or should someone else implement it? I think you or @totto82 probably know best which keywords need to go together, I imagine it is complicated but perhaps I am wrong?

I think  @totto82 is better place to writing the checking code. Rather than checking that the Thermal model has been correctly defined, I think we should just implement checks as errors crop up. So for https://github.com/OPM/opm-common/issues/3411 we need to check that thermal rock fluid parameters have been fully defined, that is to define the thermal rock fluid conductivity:

1. Either use the `THCONR` keyword to define the combined rock and fluid conductivity, and optionally the `THCONSF` keyword, or
2. By specifying the rock and fluid conductivities individually using the `THCROCK`, `THCOIL`, `THCGAS`, and `THCWATER` keywords.

I'll add a note to the manual in the GRID section explaining the above.

**Pull request merged**
