### PR TITLE
added: helper class for implementing visitor overload sets

### PR DESCRIPTION
**Pull request by akva2**
This adds a helper class for implementing the visitor-overloadset-idiom plus a small test.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Review by blattms — COMMENTED** [review]
Looks good. Please add copyright holders to file, though

**Comment by akva2** [comment]
rebased.

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks a lot for the updates.  This looks good to me and I'll merge into master.

**Comment by blattms** [comment]
But these multiplexer PRs will not get merged, right? I don't have an opinion here, just always wonder when I come across those PRs.

**Comment by akva2** [comment]
Correct, unfortunately they slow things down.

**Pull request merged**
