### PR TITLE
Add Restart Support for NETBALAN Keyword

### PR DESCRIPTION
**Pull request by bska**
This PR loads NETBALAN parameters from the restart file and forms `Network::Balance` objects from these parameters.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
Unless anyone objects I intend to merge this no later than noon CEST tomorrow (Friday 9th September).

**Comment by bska** [comment]
jenkins build this please

**Review by blattms — APPROVED** [review]
Looks good to me. thanks

**Pull request merged**
