### PR TITLE
adding dgetri_ to blas_lapack.h

### PR DESCRIPTION
**Pull request by GitPaean**
to do the inversion of a matrix based on its LU decomposition from
dgetrf_.

### CODE REVIEW

**Comment by GitPaean** [comment]
It will be needed by an incoming PR from opm-simulators.

**Comment by bska** [comment]
The contents of this is fine&mdash;it declares `DGETRI` using the same pattern and name-mangling scheme that the other symbols use&mdash;but do we really need the explicit matrix inverse rather than its action on a vector?

Also, what is the expected size of the matrices being inverted here.  LAPACK does come with considerable overhead for small (N<20) matrices.

**Comment by joakim-hove** [comment]
Iff we are to include blas calls in this - and I am not the on to judge that; we should have also have small test - showing how this code should be used +++

**Comment by GitPaean** [comment]
> Also, what is the expected size of the matrices being inverted here. LAPACK does come with considerable overhead for small (N<20) matrices.

The current size is 5 X 5 at the biggest. Each (Standard) well has one matrix needs to be inverted based on the current implementation for each assembling of well equations. 

> but do we really need the explicit matrix inverse rather than its action on a vector?
Probably not, while https://github.com/OPM/opm-simulators/pull/1483 represents a relatively easier way to address the problem happening with PR https://github.com/OPM/opm-simulators/pull/1478 based on the current implementation. 

The failure with PR https://github.com/OPM/opm-simulators/pull/1478 is from the buggy routine invert() from dune. 

https://github.com/OPM/opm-simulators/pull/1484 and https://github.com/OPM/opm-simulators/pull/1480 are the two alternative ways trying to address the problem, while they will be very likely more expensive than ttps://github.com/OPM/opm-simulators/pull/1483 since they do LU decomposition each time calling `solve` (it will be several times for each assembling of the well equations), and they did not fix the problem 
```
Dune::FMatrixHelp::multMatrix(duneD_[0][0],  (*colB), tmp);
```
from the function add well contributions.

Among the few PRs, https://github.com/OPM/opm-simulators/pull/1483 is probably the more efficient one without introducing new difficulties. Anyway, if other approaches is suggested, I would like to follow.

**Comment by andlaus** [comment]
I see the problem which you need to solve and I agree that it needs to be solved one way or another, but I think that introducing a hard dependency of non-legacy flow is a very bad idea: e.g. the name mangling is different for different compilers and architectures, so this functionality will introduce significant headaches for people with slightly uncommon setups. (e.g. I cannot compile flow_legacy on my ARM system because of that name mangling issue.)

**Comment by joakim-hove** [comment]
> e.g. the name mangling is different for different compilers and architectures

For the record: this name mangling - i.e. adding a trailing `_` -  is between Fortran and C symbols, and not in anyway related to C++.

**Comment by andlaus** [comment]
> For the record: this name mangling - i.e. adding a trailing _ - is between Fortran and C symbols, and not in anyway related to C++.

yes, technically you're correct and I should have said "I cannot link flow_legacy on my ARM system", but the present PR is a precursor to bake exactly this problem into non-legacy flow: it adds a prototype in order call a function from C/C++ code, while the actual function is implemented in a library that is written in Fortran!?

to resolve the matrix inversion problem, wouldn't it be better to just ship a modified copy of `Dune::DenseMatrix::invert()` compared to introducing a hard dependency on a huge and potentially troublesome legacy library. (whether LAPACK should be tagged "legacy" or not is obviously a subject for debate.) I'm pretty sure @alfbr has some strong feelings about that matter...

**Comment by joakim-hove** [comment]
Again: I will not weigh in very strongly on this or another approach. But iff we want a LAPACK solver in opm-common it should be fully working, including tests *and* link time dependencies. The lapack library is currently not a dependency at all - so the `blas_lapack.h` is in my opinion just a dangling header, from the symbols used at the top of the file it seems it historically was meant to be used with runtime linking from matlab, that is probably not relevant any longer.

**Comment by andlaus** [comment]
if LAPACK is going to be used by the core of the well model, it *is* a hard dependency. I thought that this was a precursor to this. if not, please forget most of what I've said above. In any case, non-legacy flow should built on my ARM system (or your random supercomputer) even if LAPACK is available there...

**Comment by GitPaean** [comment]
> to resolve the matrix inversion problem, wouldn't it be better to just ship a modified copy of Dune::DenseMatrix::invert()

Any suggestion how to do this? 


Maybe `DenseMatrix::solve()` used in https://github.com/OPM/opm-simulators/pull/1484 maybe should be a better direction if we decide to modify DUNE code.

**Comment by andlaus** [comment]
> Any suggestion how to do this?

looking at this from the backseat, copying the code with a new name (e.g. `invertWellMatrix(M)`) and fixing whatever causes the inversion to fail would do the trick. Without having looked into why the standard routine fails, I would bet my money on some issue with the singularity detection logic, i.e., a call to `Dune::FMatrixPrecision<Scalar>::set_singularity_limit(1e-100)` might be sufficient. (note that this function was removed in Dune master, but the singularity detection logic seems to also have been significantly improved there.)

**Comment by GitPaean** [comment]
> Dune::FMatrixPrecision<Scalar>::set_singular_limit(1e-100)

You are right for this case, the matrix failed (https://github.com/OPM/opm-simulators/pull/1478) has determinant  -4.5651e-05, but the pvimax for the fifth row is 7.64765e-12, and singthres is 8.74552e-12 . 

While I am not sure it is always a good idea to copy DUNE code and modify it with OPM.

**Comment by andlaus** [comment]
> While I am not sure it is always a good idea to copy DUNE code and modify it with OPM.

Indeed, forking code should be avoided if possible. That said, if sufficient, we should simply go for reducing the singular limit here.

**Comment by GitPaean** [comment]
> Indeed, forking code should be avoided if possible. That said, if sufficient, we should simply go for reducing the singular limit here.

Thanks for the suggestion anyway. 

If we decided to use lapack to avoid inversion of the matrix, it will be the function `dgetrs_` needed, which is already there. `dgetri_ ` is not needed anyway. Closing this PR now and thanks for everyone's comments.

**Comment by alfbr** [comment]
> I'm pretty sure @alfbr has some strong feelings about that matter.

It depends (pun intended). Dependencies that typically do not come pre-installed on Red Hat/Debian/Ubuntu, or do not have stable APIs (SuperLU, I am looking at you), have proven costly in the past. I do not recall Lapack on that list, but there may be issues that did not bite me.

> Indeed, forking code should be avoided if possible.

I am afraid we are in a position where we need to fork parts of Dune (we need to support version 2.4 and up, and that is simply not possible without some patches). Forking parts is quite OK, but we should thrive to contribute upstream whatever naturally belongs in Dune. Actually, forking parts of Dune is the only way we can bring timely fixes for the Dune dependency as things are now. As such, Dune is a very costly dependency, but one which gives large value in return.

**Pull request closed without merging**
