### PR TITLE
Suggestion: repo reorg

### PR DESCRIPTION
**Pull request by joakim-hove**
Two filesystem changes:

1. The subdirectory `parser/eclipse/` has been renamed `input/eclipse/`. The actual `Parser` implementation is a *very* small part of said directory.
2. The directory `EclipseState/Schedule/` is moved to be alongside the `EclipseState/` directory.

Downstream:
https://github.com/OPM/opm-material/pull/487
https://github.com/OPM/opm-grid/pull/562
https://github.com/OPM/opm-models/pull/679
https://github.com/OPM/opm-simulators/pull/3742
https://github.com/OPM/opm-upscaling/pull/351

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this opm-material=487 opm-grid=562 opm-simulators=3742 please

**Comment by joakim-hove** [comment]
jenkins build this opm-material=487 opm-grid=562 opm-simulators=3742 please

**Comment by joakim-hove** [comment]
jenkins build this opm-material=487 opm-grid=562 opm-simulators=3742 please

**Comment by joakim-hove** [comment]
jenkins build this opm-material=487 opm-grid=562 opm-simulators=3742 opm-models=679 please

**Comment by joakim-hove** [comment]
jenkins build this opm-material=487 opm-grid=562 opm-simulators=3742 opm-models=679 please

**Comment by joakim-hove** [comment]
jenkins build this opm-material=487 opm-grid=562 opm-simulators=3742 opm-models=679 please

**Comment by joakim-hove** [comment]
jenkins build this opm-material=487 opm-grid=562 opm-simulators=3742 opm-models=679 please

**Comment by joakim-hove** [comment]
jenkins build this opm-material=487 opm-grid=562 opm-simulators=3742 opm-models=679 please

**Comment by joakim-hove** [comment]
jenkins build this opm-material=487 opm-grid=562 opm-simulators=3742 opm-models=679 please

**Comment by joakim-hove** [comment]
jenkins build this opm-material=487 opm-grid=562 opm-simulators=3742 opm-models=679 opm-upscaling=351 please

**Comment by joakim-hove** [comment]
If there are no objections I will merge this and the accompanying PR's later this afternoon.

**Comment by blattms** [comment]
I object, because it seems like this will mess up the history of these files:
```
mblatt@smaug:~/src/dune/opm/opm-common$ git log  opm/input/eclipse/Python/Python.hpp
commit ecefa1fb02b5b22369f58cf597587399e7b381ca
Author: Joakim Hove <joakim.hove@gmail.com>
Date:   Tue Dec 14 08:06:42 2021 +0100

    Filesystem rename parser/eclipse/ input/eclipse
mblatt@smaug:~/src/dune/opm/opm-common$ 
```

That makes it rather hard to find reasons for changes in the logs.

Personally, I would like to have a common file structure throughout the modules. It is always surprising that at least two modules do not follow the opm-module/opm/module scheme.

**Comment by bska** [comment]
> ```sh
> git log  opm/input/eclipse/Python/Python.hpp
> ```

Are you aware of the `--follow` option to `git log` which makes the history follow file renames? Note: The existence of `--follow` is not an argument for or against renaming files in this particular instance.

**Comment by joakim-hove** [comment]
> I object

OK - I'll let it be.

**Comment by joakim-hove** [comment]
> because it seems like this will mess up the history of these files:

I see the point about `git log` - but that would essentially be an argument against all file renames which is quite harsh. For the suggested renames the original filestructure was devised in a "different time" and no longer feels correct:

1. The repository was originally named `opm-parser` and the content was in `opm/parser/` - the repo has since then been renamed and the `Parser` itself is a *very small* part of the current filesystem hierarchy at current `opm/parser/` - that is why I suggest the rename to `opm/input/` which is a more apt name for all of the code in that directory.
2. At a very early stage the `Schedule` object was a member of the `EclipseState` object - since then the dependencies have changed and the `EclipseState` is a constructor argument to the `Schedule` class - i.e. it does not make sense any longer to have `Schedule` implementation in subdirectory of the `EclipseState` implementation.  

> I would like to have a common file structure throughout the modules

I could update this PR to have everything in subdirectories of `opm/common/`

**Comment by blattms** [comment]
> > because it seems like this will mess up the history of these files:
> 
> I see the point about `git log` - but that would essentially be an argument against all file renames which is quite harsh. 

It was not meant to harsh, but we should try to do our best to prevent this as makes it hard to find why something is the way it is,. We did move files between repositories with the complete history before and moving directories seems a bit like that. @akva2 certainly is an expert in this area.

> 
>     1. The repository was originally named `opm-parser` and the content was in `opm/parser/` - the repo has since then been renamed and the `Parser` itself is a _very small_ part of the current filesystem hierarchy at current `opm/parser/` - that is why I suggest the rename to `opm/input/` which is a more apt name for all of the code in that directory.
> 
> > I would like to have a common file structure throughout the modules
> 
> I could update this PR to have everything in subdirectories of `opm/common/`

Currently that is just my personal opinion. Might need a general discussion e.g. on the mailing list as it will effect users that might use particular modules in external projects.

**Comment by joakim-hove** [comment]
jenkins build this opm-material=487 opm-grid=562 opm-simulators=3742 opm-models=679 opm-upscaling=351 please

**Comment by atgeirr** [comment]
> Currently that is just my personal opinion. Might need a general discussion e.g. on the mailing list as it will effect users that might use particular modules in external projects.

I agree, this affects everyone. Other than that, I find the arguments of @joakim-hove here good, and support renaming along the lines he suggested. I would also not protest using opm/common as a superdir as @blattms prefers. But maybe we should also consider this: I would like to join all OPM repositories into one! Whatever structure we move to, it would be good if nothing had to change (include paths) if we decide to join the repos. I think that with such a goal, having a few more top-level directories can be appropriate, including i.e. opm/input/ as proposed here.

**Comment by bska** [comment]
> I would like to join all OPM repositories into one!

I used to be violently opposed to that idea, but have come around in recent years. I no longer believe that it is possible to use individual modules separately since everything sort of depends on everything else. Bringing everything together would certainly simplify a lot of things for the OPM developers, not least of which is bringing in new developers and possibly discontinuing our custom build system in favour of a more modern CMake setup. The fact that we have a number of modules that must all be separately downloaded and built in the right order raises a number of unnecessary hurdles in that case. The veteran developers have learned to navigate the current structure and are sufficiently familiar with it that it does not present daily challenges but that is just not the case for new talent. Simplifying the module and directory structure

As an aside, I have no opinion on whether to separate sources (`*.cpp`) from headers (`*.hpp`) as is currently done in opm-common, but I expect we'll have to have multiple iterations before we arrive at a final directory structure.

**Comment by atgeirr** [comment]
> I assume you are only referring to the ones concerning upscaling and flow

I did, thanks for making it more precise. Also, opm-tests should clearly kept out of it, I agree. Other than that, I think every part is fair game. It would still be possible to do "make cpchop" and not build anything related to Flow for example, as we can do today, so I think compile times may not be a big problem. A possible problem is allowing use of opm-common without requiring Dune or MPI, and keeping that enforced somehow. But having all the code in one (rather than even two) repo would still yield so great simplification that I am in favour of that, assuming we can find solutions to the problems we have raised.

**Comment by blattms** [comment]
We have to be aware that parts of OPM are used outside of opm-simulators and that there are kind of established processes that impose quite some work on us and others if there are massive changes.

1. As opm-models is a fork of dumux, there might be conflcts between the two if that is merged with any module that is used together with Dumux elsewhere. That is the case for opm-grid, at least. Hence there needs to be extensive testing that this is not the case.
2. We should prevent renaming models if there is no good reason. We are currently at the last step of inclusion into Debian (waiting in ftpmaster's new queue for Q&A). Any package renamed will need to go through the whole process again, which wastes a lot of time on both sides and has unsure outcome.

That being said I am not opposed to lesser modules. If done a few years back, it would have saved me a lot of work-force that might have been better invested somewhere.
My proposal would be opm-tests, opm-common (including opm-material), opm-grid, opm-simulators (including opm-models, opm-upscaling).

**Comment by atgeirr** [comment]
> 2\. We should prevent renaming models if there is no good reason. We are currently at the last step of inclusion into Debian (waiting in ftpmaster's new queue for Q&A). Any package renamed will need to go through the whole process again, which wastes a lot of time on both sides and has unsure outcome.

I had not thought about this, and agree it is important. Can we keep the *modules* as is (i.e. packages can be produced that have the same relationships as today), but have them all in a single repo?

**Comment by blattms** [comment]
> > 2. We should prevent renaming models if there is no good reason. We are currently at the last step of inclusion into Debian (waiting in ftpmaster's new queue for Q&A). Any package renamed will need to go through the whole process again, which wastes a lot of time on both sides and has unsure outcome.
> 
> I had not thought about this, and agree it is important. Can we keep the _modules_ as is (i.e. packages can be produced that have the same relationships as today), but have them all in a single repo?

Well, let me explain how this works (at least in Debian/Ubuntu). You have a source package (e.g. opm-common) and corresponding to the source package you have one or more binary packages (e.g. libopm-common, libopm-common-dev, libopm-common-bin). There is  a recipe-file that tells how to build the binary packages from the source file.All the review processing and acceptance is per source package.

Yes you can have one source package and build many binary packages from it as you want. One repository and the same binary packages as now is an option (but I guess it would be wise to reduce the number of these, too).

My comment was more about this:
Debian is a voluntary effort and the guys were very helpful in doing reviews etc. I was really glad that I found a sponsor that did the review and upload to ftpmaster in nearly no time after the last release. IMHO time should be treated as a precious resource (even more so if it is not ours and voluntary). Hence my argument to really think hard whether to rename a repository / source package (which corresponds to a repository). It can be done, but I suspect that this might not be to well received. If I would be Q&A in ftpmaster and would notice something like this shortly after that project got accepted, my motivation to process that new source package would certainly decrease if there are 350 others waiting for Q&A processing.

But of course I am still no expert in this and might be wrong. If there is a strong tendency, I could just ask whether there is a way to prevent this hassle. Who knows, there might be a way...

Having the upscaling applications in a repository called opm-simulators does not seem like a very big problem to me. You do simulate there, too. Reducing the number of modules certainly is a good thing.

**Comment by blattms** [comment]
> > ```shell
> > git log  opm/input/eclipse/Python/Python.hpp
> > ```
> 
> Are you aware of the `--follow` option to `git log` which makes the history follow file renames? Note: The existence of `--follow` is not an argument for or against renaming files in this particular instance.

I should have been, but apparently I was not. Indeed that works and also git blame works correctly. I underestimated git. Sorry about that. 

Then the only question is whether there are users outside of OPM for opm-common. Those will certainly feel the pain with a transition period with deprecated headers (to the move then add new header at the old place including the new ones with a deprecation warning about what has to be done). And then imaging they are trying to support different versions of OPM (like we do with DUNE)....

And indeed, at least OPM/ResInsight does use (a modified) version of opm-common. But they already know us and copy it to their repository to not get bitten that easily :wink: 
Maybe @magnesj can share whether they would appreciate using opm-common more directly than now.

**Comment by magnesj** [comment]
Interesting discussion. Let me explain shortly how we use opm-common code in ResInsight. First of all, we support Windows, and we have some Windows specific patches to the opm-common code.

**Usage of opm-common in ResInsight**
1. Parsing of `VFPPROD` and `VFPINJ` keywords. These are some of the most complex keywords I am aware of, and we wanted to avoid duplication of parsing and interpretation of these.
2. Improved performance for import of summary data using the `ESMRY` file format. This format is now fully supported in ResInsight. Also optional conversion of summary data to `ESMRY` and storage of user-defined summary data to `ESMRY` is included.
5. Create surface geometry of a K-layer using `EGrid` for performance, only coords for one layer is read from file. We use this to extract surface geo from all realizations in an ensemble.

**Plan going forward**
- use` io/eclipse/ERft` to import common RFT data and RFT well segment data
- test performance and start using `io/eclipse/EGrid`  for import of more/all grid data

I think the IO part of opm-common should easily be available for use in other projects. The performance and use of modern C++ in this module is highly appreciated. I am aware of that opm-common is available as a Python package, and I think it would be useful to create a separate repo/lib of the Eclipse IO.  This library should have Python bindings (including Windows support), and I think this library can replace ecl in several projects. If this code is separated into a repo, it would also make it easier for other developers to contribute.

Regarding the renaming/moving of files discussed here: This is a required operation as the codebase evolves. We have done several larger reorganizations in ResInsight, and it is painful. But when it is done the quality of life for all developers improves. I see that you have more module interdependencies, but I think that reorganization should rather be done sooner than later, it won't get easier further down the road.

**Comment by alfbr** [comment]
> I think the IO part of opm-common should easily be available for use in other projects.

You already mentioned using parts of the parser, so do you see the parsing code as part of this IO? Or are you simply suggesting a libecl replacement in a separate repository?

**Comment by magnesj** [comment]
> > I think the IO part of opm-common should easily be available for use in other projects.
> 
> You already mentioned using parts of the parser, so do you see the parsing code as part of this IO? Or are you simply suggesting a libecl replacement in a separate repository?

I would like a libecl replacement in a separate repo.

**Comment by joakim-hove** [comment]
jenkins build this opm-material=487 opm-grid=562 opm-simulators=3742 opm-models=679 opm-upscaling=351 please

**Comment by joakim-hove** [comment]
jenkins build this opm-material=487 opm-grid=562 opm-simulators=3742 opm-models=679 opm-upscaling=351 please

**Comment by atgeirr** [comment]
> I would like a libecl replacement in a separate repo.

That would be the opposite of what I want... I see that it is not easy to satisfy everyone here! If the io parts you want were their own object code library, and you could easily configure the build to only build that one, would it be ok for you if it was all in a single repo? I am thinking of something like an option to build or not for each module (as long as dependencies are respected, you cannot build opm-simulators without opm-grid etc.).

**Comment by joakim-hove** [comment]
jenkins build this opm-material=487 opm-grid=562 opm-simulators=3742 opm-models=679 opm-upscaling=351 please

**Comment by alfbr** [comment]
> > I would like a libecl replacement in a separate repo.
> 
> That would be the opposite of what I want... I see that it is not easy to satisfy everyone here! If the io parts you want were their own object code library, and you could easily configure the build to only build that one, would it be ok for you if it was all in a single repo? I am thinking of something like an option to build or not for each module (as long as dependencies are respected, you cannot build opm-simulators without opm-grid etc.).

Actually, I am not sure it would matter much at all, the io-code would still be copied over to the resinsight repository, rather than dynamically linking to a opm-common module. I am not even sure a separate io-repo would change that, or make the resinsight development significantly easier. Maybe @magnesj can clarify?

**Comment by joakim-hove** [comment]
This has evolved into a slightly larger topic of discussion than I had originally envisioned - here are my 2$:

__Organisation of repositiories:__

Here I have made the same journey as several of the other contributors in the thread. Originally I was strongly opposed to a mono repo, now I think it is a good idea[1]. The reason I have was originally opposed to a mono repo was that I thought it would become unmanageable. And maybe mostly a social challenge - what is it now to be a maintainer? Anyway - the hassle and maintenance burden of maintaining multiple repositories is quite significant - in particular for newcomers, so I have concluded I think a mono repo would be an improvement. Certainly e.g. the linux kernel manage a large repository with many different maintainers.

A possible way forward:

1. opm-material is merged into opm-common.
2. (This can wait: In opm-grid as much as possible is upstreamed to dune - and the rest is merged into opm-common)
3. opm-models is split: parts required for building flow are moved/copied into opm-simulators, and the remaining parts remain in opm-models. Observe that in this process I suggest accepting code duplication between opm-simulators and opm-models. That way the flow codebase and the other models/simulators in opm-models can de developed independetly.


After these steps we will have:
```
opm-common -> opm-grid - { opm-simulators, opm-models, opm-upscaling }
```
i.e. no chain is longer than three repositories. A next step could be:

1. opm-common +  opm-grid + opm-simulators is merged to a new opm-flow.
2. Now opm-models and opm-upscaling will depend on opm-flow.

The advantage of this is that the main codepath (building flow) is simplified / optimized, and the slightly less traveled roads like alternative simulators from opm-models and opm-upscaling take some burden (i.e. they must download the full flow repo, and also build the full flow / manually configure the opm-flow build).

I think we should keep pressure on this and not let it fissle out.




[1]: Markus has raised a point about the coming debian packaging; that is probably a good argument but I can not really judge it - so no more comments on that topic.

**Comment by joakim-hove** [comment]
jenkins build this opm-material=487 opm-grid=562 opm-simulators=3742 opm-models=679 opm-upscaling=351 please

**Comment by magnesj** [comment]
> > I would like a libecl replacement in a separate repo.
> 
> That would be the opposite of what I want... I see that it is not easy to satisfy everyone here! If the io parts you want were their own object code library, and you could easily configure the build to only build that one, would it be ok for you if it was all in a single repo? I am thinking of something like an option to build or not for each module (as long as dependencies are respected, you cannot build opm-simulators without opm-grid etc.).

It would be sufficient for our use in ResInsight if we could have flags to control the files to be included in the compilation. There are flags like `ENABLE_ECL_INPUT` and `ENABLE_ECL_OUTPUT`, but they did not work as expected last time I used them (back in 2020). A mono-repo with flags to control what files to compile will make it easier for ResInsight use.

**Comment by blattms** [comment]
>     2. (This can wait: In opm-grid as much as possible is upstreamed to dune - and the rest is merged into opm-common)

Maybe I am misunderstanding you. IMHO there is (nearly) nothing that can be upstreamed. Also if we merge we should do all of the merge at one time.

**Comment by joakim-hove** [comment]
>Maybe I am misunderstanding you. IMHO there is (nearly) nothing that can be upstreamed. 

I am probably the one misunderstanding here - this is your domain of expertise.

> Also if we merge we should do all of the merge at one time.

I understand - however if this becomes the inhibitor for getting anywhere that would be unfortunate.

**Comment by joakim-hove** [comment]
The discussion about repo reorganisation aside: How about merging this more limited PR; it is somewhat challenging to maintain a mergeable state on it.

**Comment by alfbr** [comment]
> > > I would like a libecl replacement in a separate repo.
> > 
> > 
> > That would be the opposite of what I want... I see that it is not easy to satisfy everyone here! If the io parts you want were their own object code library, and you could easily configure the build to only build that one, would it be ok for you if it was all in a single repo? I am thinking of something like an option to build or not for each module (as long as dependencies are respected, you cannot build opm-simulators without opm-grid etc.).
> 
> It would be sufficient for our use in ResInsight if we could have flags to control the files to be included in the compilation. There are flags like `ENABLE_ECL_INPUT` and `ENABLE_ECL_OUTPUT`, but they did not work as expected last time I used them (back in 2020). A mono-repo with flags to control what files to compile will make it easier for ResInsight use.

Thanks for the clarification! I interpret this to imply that you see the following need: 1) It gives an easy way to identify the necessary part of the code to compile for binary IO, and perhaps even more importantly 2) Ensure that the binary IO-code continues to build without dependencies introduced from other parts of the code base. I believe a cmake switch ensuring that the binary IO-code can built (and used) stand-alone addresses both points.

**Comment by joakim-hove** [comment]
I just repost this:

> opm-models is split: parts required for building flow are moved/copied into opm-simulators, and the remaining parts remain in opm-models. Observe that in this process I suggest accepting code duplication between opm-simulators and opm-models. That way the flow codebase and the other models/simulators in opm-models can de developed independetly.

because I think it is a freakin good idea.

**Comment by joakim-hove** [comment]
jenkins build this opm-material=487 opm-grid=562 opm-simulators=3742 opm-models=679 opm-upscaling=351 please

**Comment by atgeirr** [comment]
> The discussion about repo reorganisation aside: How about merging this more limited PR; it is somewhat challenging to maintain a mergeable state on it.

I am in favor of merging. The concerns about being able to follow a file's history have been addressed I believe?

**Comment by blattms** [comment]
As nobody seemed concerned about moving headers without a deprecation phase,
I retract my objection (t was more about having a discussion, anyway).

We should add a changelog entry about this in another PR though.

Unfortunately, jenkins is not happy...

**Comment by joakim-hove** [comment]
jenkins build this opm-material=487 opm-grid=562 opm-simulators=3742 opm-models=679 opm-upscaling=351 please

**Comment by joakim-hove** [comment]
Grateful if someone can take a look at [this](https://ci.opm-project.org/job/opm-common-PR-builder/4670/) build output. It works perfectly on my machine - and really do not understand how the error messages relate to the changes proposed here?

**Comment by blattms** [comment]
Missing rebase (of opm-simulators) or jenkins hickup? That line was changed in OPM/opm-simulators/commit/9c4478c35b00d

**Comment by joakim-hove** [comment]
> Missing rebase (of opm-simulators) or jenkins hickup? That line was changed in 9c4478c35b00d)

Thanks - it was rebased; but maybe jenkins/github is using an old ref. Have closed and trying again ....

**Comment by joakim-hove** [comment]
jenkins build this opm-material=487 opm-grid=562 opm-simulators=3742 opm-models=679 opm-upscaling=351 please

**Pull request merged**
