### PR TITLE
Co2GasPvt: encapsulate EclipseState w/ friends

### PR DESCRIPTION
**Pull request by akva2**
And move some logging to OpmLog instead of cerr.

Waiting for https://github.com/OPM/opm-common/pull/3246

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
sure, no problem. we can hold on the merges, but i will prepare the PRs nonetheless (and handle the rebasing afterwards).

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Looks good to me.  Please merge when the build check is green.

**Pull request merged**
