### PR TITLE
fixed: perform installation at end of main module

### PR DESCRIPTION
**Pull request by akva2**
not only if we build downstreams. ref https://github.com/OPM/opm-upscaling/pull/232 @bska

### CODE REVIEW

**Comment by bska** [comment]
Looks good to me.

**Comment by atgeirr** [comment]
jenkins build this with downstreams please

**Comment by akva2** [comment]
all good with downstreams, let's test without.

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
everything is happy. as i maintain i merge.

**Pull request merged**
