### PR TITLE
[cmake] Use uppercase for components in FindSuitesparse

### PR DESCRIPTION
**Pull request by blattms**
This is in line with DUNE since 2015 and fixes problems when trying to use opm-grid as a DUNE module.

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
Wow jenkins is blazingly  fast. [Works standalone](https://ci.opm-project.org/job/opm-common-PR-builder/7741/)

**Comment by blattms** [comment]
jenkins build this opm-simulators=5745 please

**Review by akva2 — APPROVED** [review]
Looks fine

**Pull request merged**
