### PR TITLE
W keywords up to an including WFRICTNL

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this update_data please

**Comment by joakim-hove** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
need a failing test... it will happen automagically next time we have to do an update.

**Comment by joakim-hove** [comment]
Hmmm looks like a data update was created although there was no failing test; should I just close  OPM/opm-tests#160 and forget about it; or can it be merged?

**Comment by akva2** [comment]
i had a brainfart (smells bad here); i have disabled the exit code check at some point precisely for these situations so it's all good. the only thing that worries me is the unsmry update for the uqd_wconprod.

**Comment by joakim-hove** [comment]
> the only thing that worries me is the unsmry update for the uqd_wconprod.

I agree - for all it is worth that file has been updated in all of the last three tests, for no obvious immediately obvious reason - so it might have a undefined issue of it's own?

**Comment by akva2** [comment]
yes, likely. converting to formatted shows it's pretty systematic, exactly one value changes per step.

**Comment by joakim-hove** [comment]
OK - I'll merge the opm-common PR; I'll let @akva2 determine the fate of OPM/opm-tests#160

**Comment by akva2** [comment]
it's an improvement - merge it.

**Pull request merged**
