### PR TITLE
Rename Completion -> Connection

### PR DESCRIPTION
**Pull request by joakim-hove**
See: https://github.com/OPM/opm-common/issues/420

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=326 ewoms=325 opm-simulators=1494

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=326 ewoms=325 opm-simulators=1494 please

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=326 ewoms=325 opm-simulators=1494 please

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=326 ewoms=325 opm-simulators=1494 please

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=326 ewoms=325 opm-simulators=1494 please

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=326 ewoms=325 opm-simulators=1494 please

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=326 ewoms=325 opm-simulators=1494 please

**Comment by joakim-hove** [comment]
@atgeirr: This is *pure* renaming; any objections to merging this chain when Jenkins gives the green?

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=326 ewoms=325 opm-simulators=1494 please

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=326 ewoms=325 opm-simulators=1494 please

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=326 ewoms=325 opm-simulators=1494 please

**Comment by atgeirr** [comment]
> @atgeirr: This is pure renaming; any objections to merging this chain when Jenkins gives the green?

No, I am good with the renaming. Please run at least Norne as a sanity check to verify identical behaviour though...

**Comment by joakim-hove** [comment]
> Please run at least Norne as a sanity check to verify identical behaviour though...

Ehhh  - we have a reasonably extensive test suite; if we are not willing to merge based on that it has limited value.

**Comment by atgeirr** [comment]
> Ehhh - we have a reasonably extensive test suite; if we are not willing to merge a rename refactoring based on that it has limited value.

I guess you are right, I am probably a bit over-cautious. I withdraw my comment.

**Pull request merged**
