### PR TITLE
internalize STONE|STONE1|STONE2

### PR DESCRIPTION
**Pull request by akva2**
To avoid deck usage downstream

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-simulators=2433 please

**Comment by bska** [comment]
A little after the fact, but I'll say it anyway: I don't think "stone type" is a particularly good name for this.  STONE1 and STONE2 (and default) are different models for how to combine two-phase relative permeabilities in the oil/gas and oil/water systems into a three-phase relative permeability for oil (oil/gas/water system).

**Comment by akva2** [comment]
i'm more than willing to refactor and rename however you see it fit, i just needed the data internalized :)

**Comment by bska** [comment]
> i'm more than willing to refactor and rename however you see it fit

I haven't thought this through fully, but how about an `enum` of the form
```C++
enum class ThreePhaseOilKrModel {
    Default,
    Stone1,
    Stone2,
};
```
as a data member in the [saturation function control](https://github.com/OPM/opm-common/blob/d1e4b28ad2d8580313aa83b04663d62d47ce3e98/opm/parser/eclipse/EclipseState/Runspec.hpp#L186) structure?

**Pull request merged**
