### PR TITLE
Construct tuple<> Objects Explicitly

### PR DESCRIPTION
**Pull request by bska**
Needed in GCC 4.9 due to incomplete standard library implementation of class template `tuple<>`&mdash;especially its conditionally implicit constructors.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
Any objections to merging this build-related PR which is only needed for GCC 4.9?

**Comment by joakim-hove** [comment]
Go ahead

**Comment by bska** [comment]
>> Any objections to merging this build-related PR which is only needed for GCC 4.9?
>
> Go ahead

Thanks! Merging now.

**Pull request merged**
