### PR TITLE
Well.hpp: forward WellMICPProperties

### PR DESCRIPTION
**Pull request by akva2**
Reduces hotness for WellMIPCProperties.hpp by 97% (276 files, 9 files instead of 285)

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks.  I'll merge into master.

**Comment by blattms** [comment]
Not sure why, but somehow this does not play well with my PR #3355

**Comment by akva2** [comment]
Likely because of the missing downstream merge?

**Pull request merged**
