### PR TITLE
Permfact table fix

### PR DESCRIPTION
**Pull request by plgbrts**
PERMFACT table was using equilibration regions instead of PVT regions.

### CODE REVIEW

**Comment by plgbrts** [comment]
jenkins build this please

**Comment by bska** [comment]
> jenkins build this please

Looks like that failed for unrelated reasons (inopportune race with updating the reference solutions.)  I'll rerun the build check to be sure.

**Comment by bska** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
This looks good to me.  If the proper semantics of `PERMFACT` is one table per PVT region then I'm prepared to merge this.

**Comment by plgbrts** [comment]
Indeed, that is how it is intended one table per PVT region

**Comment by bska** [comment]
>> This looks good to me. If the proper semantics of `PERMFACT` is one table per PVT region then I'm prepared to merge this.
>
> Indeed, that is how it is intended one table per PVT region

Very good.  In that case I'll merge this into master.

**Pull request merged**
