### PR TITLE
Add warning for MULTREGT in EDIT section

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by alfbr** [comment]
Please also make explicit in the message that MULTREGT is applied (contrary to being ignored). The commercial simulator is very confusing in this respect, we should be better :-)

**Comment by joakim-hove** [comment]
> The commercial simulator is very confusing in this respect, we should be better :-)

I have updated the message; kind of awkward message to write without bashing the alternative documentation. Happy to update the message text if you have a better alternative.

**Comment by alfbr** [comment]
Perfect, much appreciated! The most important aspect at my end is that the message is clear and self-explanatory so that users know exactly what it means.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Pull request merged**
