### PR TITLE
Add new tests and corresponing fixes in the hysteresis model

### PR DESCRIPTION
**Pull request by totto82**
- New tests for restart is added for gasoil, oilwater nonwetting hysteresis
- 3-Phase tests are added for Baker (default), Stone 1 and Stone 2
- hysteresis parameter set and get methods directly work on min/max saturations to avoid conversion in output layer
UPDATE
- fix for wetting phase hysteresis

### CODE REVIEW

**Comment by totto82** [comment]
I get a lot of 

```
not same keywords in Restart, sequence 0

  DOUBHEAD |   DOUBHEAD
    ENDSOL |     ENDSOL
  INTEHEAD |   INTEHEAD
  LOGIHEAD |   LOGIHEAD
      PBUB |       PBUB
      PDEW |       PDEW
      PPCW |       PPCW
  PRESSURE |   PRESSURE
        RS |         RS
        RV |         RV
    SEQNUM |     SEQNUM
      SGAS |       SGAS
     SGMAX |      SGMAX
     SOMAX |      SOMAX
  STARTSOL |   STARTSOL
      SWAT |       SWAT
  THRESHPR |   THRESHPR
```

that confuse me. Since they look the same. I should I interpretate this?

**Comment by bska** [comment]
>> How should I interpret this?
>
> I haven't seen that particular failure mode before and it suggests a deficiency in the analysis program.

Quick follow-up here: It **could** be that the order of the output arrays is different in the two cases.  The analysis program uses `vector<string>::operator==(const vector<string>&)` to determine if the set of keywords/vectors are the same.  That comparison is influenced by ordering.  On the other hand, the list is reported in sorted order and won't show differences in the ordering.

**Comment by totto82** [comment]
>Quick follow-up here: It could be that the order of the output arrays is different in the two cases

Thanks. Adding a sort before the check fixed the issue. 

We still have differences, but they are mostly in the initial output before updateHysteresis() is called. The max values are then negative and differ between the reference and this PR with swmin.  

```
1 keyword exhibit failures
	SGMAX: Restart, sequence 0
		Fails for 2794 entries
		Largest absolute error: 1.9000006e-01
		Largest relative error: 1.5966391e-01
```


image

For the Norne restart case it misses SOMIN which know is required for PC hysteresis. 
`
Simulation aborted as program threw an unexpected exception: Could not initialize the problem: Requisite restart vector 'SOMIN' is not available in restart file`

For the WAG case. The reference case misses SOMIN and SWHY1, which is know outputted for PC hysteresis. 

i.e. the test failures are expected and we need to update the reference solutions.

**Comment by bska** [comment]
Thanks for looking into the failures&ndash;greatly appreciated.  Is this PR expected to work on its own or does it also require that the downstream PR is merged at the same time?

**Comment by totto82** [comment]
>Is this PR expected to work on its own or does it also require that the downstream PR is merged at the same time?

They need to be merged together.

**Review by bska — APPROVED** [review]
Very good.  I'm happy about this simplification.  I'll review the downstream PR now.

**Comment by bska** [comment]
jenkins build this opm-simulators=5402 ignore_extra please

**Comment by totto82** [comment]
jenkins build this opm-simulators=5402 ignore_extra please

**Comment by totto82** [comment]
jenkins build this opm-simulators=5402 update_data please

**Comment by bska** [comment]
> ignore_extra

There were a number of [test failures](https://ci.opm-project.org/job/opm-common-PR-builder/7203/testReport/) even in this case.  Did you check all of them to verify that the failures were benign?  In one instance, I noticed `SGMAX` going from `-1` to `1.0913` in one cell, for instance.  Is that expected?

**Comment by totto82** [comment]
The test failure in restart step 0 is expected. See my comment above. But I didn't notice values above 1. I will double check that. Do you remember the case name? In the failure report I only see the error. How did you noticed SGMAX going from -1 to 1.0913 in one cell? Manual checking? I did some manual checking on some of the failures like the one reported above, but not all, since they all seemed to be related.

**Comment by bska** [comment]
> The test failure in restart step 0 is expected. See my comment above.

Ah, okay.  I forgot about that.

> But I didn't notice values above 1. I will double check that.

Sorry&ndash;that was a misprint.  I **meant** to say the value of `SGMAX` changed `-1` :arrow_right: `-1.0913` (negative), not `1.0913` (positive).

> Do you remember the case name?

[9_EDITNNC_MODEL2](https://ci.opm-project.org/job/opm-common-PR-builder/7203/testReport/(root)/mpi/compareECLFiles_flow_9_EDITNNC_MODEL2/)

> How did you noticed `SGMAX` going from -1 to 1.0913 in one cell? Manual checking?

Yes, manual checking.  I (almost) always pay attention to changes to the restart files when `ignore_extra` does not "cure" the differences.

**Comment by totto82** [comment]
I will update the initial min/max so they output the correct values not just some random initialized values. It does not look nice, even though it shouldn't affect the results. We will still need an update of the data for the same reason.

**Comment by totto82** [comment]
jenkins build this opm-simulators=5402 ignore_extra please

**Comment by totto82** [comment]
jenkins build this opm-simulators=5402 please

**Comment by totto82** [comment]
jenkins build this opm-simulators=5402 ignore_extra please

**Comment by totto82** [comment]
@bska is this still approved. The code now updated the saturation limits  after initialization. There is still differences on somax etc. in report step 0, as the old code reported unupdated values.

**Review by bska — APPROVED** [review]
> is this still approved? The code now updated the saturation limits after initialization.

Yes, this looks good to me now.  I'll update the reference solutions.

**Comment by bska** [comment]
jenkins build this opm-simulators=5402 update_data please

**Comment by bska** [comment]
jenkins build this opm-simulators=5402 opm-tests=1188 please

**Comment by bska** [comment]
The new reference solutions have been installed on the CI system.  I'll merge this and its downstream counterpart into their respective master branches now.

**Pull request merged**
