### PR TITLE
changed: rename serializeObject to serializationTestObject

### PR DESCRIPTION
**Pull request by akva2**
makes it more clear what these members are used for.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-simulators=4144 please

**Review by bska — APPROVED** [review]
Excellent.  I'll merge this and its downstream companion once the build check is green.

**Comment by bska** [comment]
jenkins build this serial opm-simulators=4144 please

**Review by bska — APPROVED** [review]
Sorry for being paranoid and delaying this by running a second build check.  I just wanted to be sure that we did not accidentally break the sequential build.  I'll merge this and its companion PR into master now.

**Pull request merged**
