### PR TITLE
Fixup: THPRESPR -> THRESPR

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this update_data ewoms=380 please

**Comment by joakim-hove** [comment]
jenkins build this update_data ewoms=380 please

**Comment by joakim-hove** [comment]
commented 38 minutes ago
jenkins build this update_data ewoms=380 opm-tests=54 please

**Comment by joakim-hove** [comment]
commented 38 minutes ago
jenkins build this ewoms=380 opm-tests=54 please

**Comment by alfbr** [comment]
Any chance we can have this merged?

**Comment by joakim-hove** [comment]
I hope so - will look into it in 5 minutes

**Comment by joakim-hove** [comment]
jenkins build this ewoms=380 opm-tests=54 please

**Comment by joakim-hove** [comment]
I will merge this as soon as it is green.

**Pull request merged**
