### PR TITLE
Add Restart I/O Support for Well's THP

### PR DESCRIPTION
**Pull request by bska**
This commit adds support for saving and restoring a well's THP quantitiy.  We put the THP into the summary facility's list of "required restart quantities" and pick up the value converted to output units from the `SummaryState`.

On restart we restore the THP value to internal (SI) units and transport the value to the simulator in `data::Well::thp`.  While here, also add the THP value to the `RstWell` object although currently not strictly needed in that context.

### CODE REVIEW

**Comment by bska** [comment]
Note: This will add more items to the restart file and therefore require an update to the reference data.  For now I'll just launch the regular build check.  We'll update the reference data as the last step before merging, and only once the PR is approved.

**Comment by bska** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
> [...] and only once the PR is approved.

The PR is approved - I will start the data update process.

**Comment by joakim-hove** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=324 please

**Comment by bska** [comment]
Merging this per prior approval.

**Pull request merged**
