### PR TITLE
Update Various JSON Definitions

### PR DESCRIPTION
**Pull request by OPMUSER**
AQUCON, AQUCT, AQUFETP, EQUIL, MESSAGES, PLYMAX, REGDIMS, and RESTART

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
1. Adding E300 specific items like the two new items added to `EQUIL` is perfectly OK; but we should have no ambition of complete E300 coverage.
2. The test failure in this PR is related to the new items in `EQUIL` - I have just removed the test here: #2558

**Comment by joakim-hove** [comment]
jenkins build this please

**Pull request merged**
