### PR TITLE
Add class Action::State to keep track of ACTIONX count

### PR DESCRIPTION
**Pull request by joakim-hove**
The purpose of this PR is to add an object `Action::State`which keeps track of how many times an action has been run (i.e. succeeded), and the last time it was run. This was previously handled with a pair of mutable members in `ActionX` class - remember this kids: `mutable` as a way to implement functionality (beyond caching) **always** comes back to bite you.

The `Action::State`object is owned by the simulator. Main content of PR is adding `Action::State&`argument all over the place.

Downstream: https://github.com/OPM/opm-simulators/pull/2674

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2674 please

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2674 please

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2674 please

**Comment by joakim-hove** [comment]
This has been tested on field case in Equinor - merging.

**Comment by akva2** [comment]
Merging to restore ci as downstream was merged.

**Comment by akva2** [comment]
Downstream is still broken.

**Comment by joakim-hove** [comment]
Damn - I'll have a look

**Comment by bska** [comment]
>> Downstream is still broken.
>
> Damn - I'll have a look

For what it's worth I'm running a build check of current master using OPM/opm-simulators#2667.  It's looking good so far.

**Comment by akva2** [comment]
Must have been a fluke cause that build succeeded. Guess i was too quick on the trigger.

**Comment by bska** [comment]
> Must have been a fluke cause that build succeeded. Guess i was too quick on the trigger.

Actually, you're right.  The build is broken&mdash;at least the sequential build.  MPI appears to be okay.  I had to apply the patch below to the non-MPI branch of [`loadParallelRestart()`](https://github.com/OPM/opm-simulators/blob/d89a2e5eb7f31a0966f6dc9ec3998c74f24ee594/opm/simulators/utils/ParallelRestart.cpp#L821) in order to make my sequential build go through

--- 

```diff
diff --git a/opm/simulators/utils/ParallelRestart.cpp b/opm/simulators/utils/ParallelRestart.cpp
index 8ac89e8d..fb4745a6 100644
--- a/opm/simulators/utils/ParallelRestart.cpp
+++ b/opm/simulators/utils/ParallelRestart.cpp
@@ -851,7 +851,7 @@ RestartValue loadParallelRestart(const EclipseIO* eclIO, Action::State& actionSt
     return restartValues;
 #else
     (void) comm;
-    return eclIO->loadRestart(summaryState, solutionKeys, extraKeys);
+    return eclIO->loadRestart(actionState, summaryState, solutionKeys, extraKeys);
 #endif
 }
```

**Comment by joakim-hove** [comment]
> The build is broken—at least the sequential build

Looks right

**Pull request merged**
