### PR TITLE
move the infrastructure for valgrind client requests into the Opm namespace

### PR DESCRIPTION
**Pull request by andlaus**
this emerged as during OPM/opm-material#200.

### CODE REVIEW

**Comment by andlaus** [comment]
be aware that OPM/ewoms#151 needs to be merged synchronously with this PR.

**Comment by andlaus** [comment]
jenkins build this with downstreams ewoms=151 please

**Comment by dr-robertk** [comment]
Was this necessary?

**Comment by andlaus** [comment]
technically? no; as long as you do not to mix Dumux and OPM code. wanted? I don't know.

**Comment by dr-robertk** [comment]
I didn't follow the other discussion. So then there is a good reason.

**Comment by andlaus** [comment]
yeah: Dumux has the same file with the same functions which is obviously not appreciated by C++ compilers...

**Comment by dr-robertk** [comment]
You could also make the header guard have the same name O:-)

**Comment by andlaus** [comment]
*rofl*

**Pull request merged**
