### PR TITLE
Don't Copy Well Objects During Summary Vector Evaluation

### PR DESCRIPTION
**Pull request by bska**
This PR makes the `find_wells()` helper function return a vector of (`const`) `Well` pointers instead of fully fledged `Well` objects. This, in turn, eliminates quite a bit of the overhead of evaluating well-based summary vectors (i.e., well, group, field, and connection level vectors).

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
> jenkins build this please

Don't bother, it's (likely) going to fail. I'm working on an update.

**Comment by bska** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 1.003    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 1.035    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 1.018    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1.056    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 1.003    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 1.014    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1120

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by alfbr** [comment]
I am very surprised to see the gains achieved here on the parallel runs, great work!

**Comment by bska** [comment]
> I am very surprised to see the gains achieved here on the parallel runs

Just goes to show that copying (and destroying) objects is expensive once you do it a lot.  Too bad we can't use this until we understand why the regression test is [failing](https://ci.opm-project.org/job/opm-common-PR-builder/3465/testReport/junit/(root)/mpi/compareECLFiles_flow_MOD4_UDQ_ACTIONX/).

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
I'm no longer able to reproduce regression failures on my local machine for this PR.  I'll run a CI system build check to assess the state.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
> I'm no longer able to reproduce regression failures on my local machine for this PR. I'll run a CI system build check to assess the state.

The Jenkins build check comes back green too.  I now consider this to be ready for final review and merging when approved.

**Comment by bska** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 0.992    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 0.813    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 0.991    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1.077    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.993    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 1.021    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1184

**Comment by joakim-hove** [comment]
Great stamina getting this through. I have been ready to merge this for a long time; and was planning to do so now - but was a little surprised / disappointed by the recent benchmark results? Will kick that again.

**Comment by joakim-hove** [comment]
benchmark please

**Pull request merged**
