### PR TITLE
Load WGRUPCON Information From Restart File

### PR DESCRIPTION
**Pull request by bska**
While here, remove two tests which only passed by accident and pull a number of helper functions out of the `Opm` namespace.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
Upstream PR is merged so I'm marking this as "ready for review" and running a build check.

**Comment by bska** [comment]
jenkins build this please

**Comment by akva2** [comment]
shouldn't rst_test.cpp be nuked? unless i'm blind there is no usage of it now.

**Comment by bska** [comment]
> shouldn't [`tests/rst_test.cpp`](https://github.com/OPM/opm-common/blob/1850e45ed592da257250070babe7faa1a079d252/tests/rst_test.cpp) be nuked? unless i'm blind there is no usage of it now.

I'm on the fence.  It's kinda-sorta useful as a developer basic/debugging check of the restart objects, but you're right that we don't use it for unit or regression testing anymore.  I'd be happy to remove it from the list of binaries that we always build.  Do we have an easy way of marking something as "opt in"?  If so I think that would be a decent compromise.

**Comment by akva2** [comment]
well, easy can be discussed, but you can pull it out of CMakeLists_files.txt and add it using opm_add_test with DEFAULT_ENABLE_IF OFF

**Comment by bska** [comment]
>> > shouldn't [`tests/rst_test.cpp`](https://github.com/OPM/opm-common/blob/1850e45ed592da257250070babe7faa1a079d252/tests/rst_test.cpp) be nuked? unless i'm blind there is no usage of it now.
>>
>> I'm on the fence. It's kinda-sorta useful as a developer basic/debugging check of the restart objects, but you're right that we don't use it for unit or regression testing anymore.
>
> you can pull it out of CMakeLists_files.txt and add it using `opm_add_test` with DEFAULT_ENABLE_IF OFF (and ONLY_COMPILE).

I tried to do that just now and noticed that the utility remains in use in `ExtraTests.cmake`, notably in [``rst_deck_test``](https://github.com/OPM/opm-common/blob/351a5d7292a6bc0de8de670c24acd6c633280e66/ExtraTests.cmake#L73) and [`rst_deck_test2`](https://github.com/OPM/opm-common/blob/351a5d7292a6bc0de8de670c24acd6c633280e66/ExtraTests.cmake#L79).  While these tests are arguably somewhat misleading and **probably** should be removed, I don't think that should be the subject of this PR.

I therefore think this PR should be merged once the rest of the implementation is approved.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
Unless anyone objects I'm going to merge this no later than noon CEST tomorrow (Wednesday 28 September).

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
> Unless anyone objects I'm going to merge this no later than noon CEST tomorrow (Wednesday 28 September).

No objection and build check is green.  I'm self-merging this now.

**Pull request merged**
