### PR TITLE
More serialization effort

### PR DESCRIPTION
**Pull request by akva2**
This contains various fixes for the schedule serialization.

However, I cannot make this work properly without the use of mutable accessors. I do not understand why it makes a difference, but it does; if i serialize into a temporary and pass the well and group maps through the constructor, everything goes tits up in the SPE9_CP_GROUP test and I cannot figure out why (the rest of the tests pass fine). If I however deserialize directly into the member, everything appears to be working fine.

I have separated out the mutable accessor addition and marked the commit as temporary. I hope that some more eyes can help me crack this problem.

Likewise, there are separate commits marked as temporary in the downstream.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-simulators=2277 please

**Comment by akva2** [comment]
jenkins build this opm-simulators=2277 please

**Comment by bska** [comment]
I'm a bit torn on adding the CTF kind to
```C++
bool Connection::operator==(const Connection& rhs) const
```
I intentionally did not include that parameter when I added it for output purposes.  Arguably, two connection objects are equal if they intersect the same cell, in the same direction, in the same well segment and have the same transmissibility factors.  Whether that factor was calculated from geometry and property data or entered directly in the description of the reservoir connection.

I get that it's convenient for unit testing the seralization code, but I also think we're exposing a bit too much about the internal implementation here.

**Comment by akva2** [comment]
Sure, I can remove it from operator==, most important is the serialization.

**Comment by akva2** [comment]
jenkins build this opm-simulators=2277 please

**Comment by akva2** [comment]
do not merge though, the temp commit thing is not meant to hit mainline!

**Comment by bska** [comment]
> do not merge though, the temp commit thing is not meant to hit mainline!

Understood.  I came `->this<-` close to hitting the merge button, but then I remembered that there were still some unresolved issues.

**Comment by akva2** [comment]
jenkins run norne_parallel opm-simulators=2277 please

**Comment by akva2** [comment]
jenkins run norne_parallel opm-simulators=2277 please

**Comment by akva2** [comment]
woop woop. this and downstream is ready for final review.

**Comment by bska** [comment]
Merging now since the build test succeeded.  Thanks a lot.

**Pull request merged**
