### PR TITLE
Add Python copy/install hack

### PR DESCRIPTION
**Pull request by joakim-hove**
This PR adds a small python script `install.py`which will install and bytecompile a python source tree in `${CMAKE_INSTALL_PREFIX}` would have preferred to avoid this and just use `setup.py install` but that had two problems I did not find a good solution to:

1. The `setup.py install` based solution requires that the current running python process can load from `${CMAKE_INSTALL_PREFIX}`- that is funny policy - and was solved with `PYTHONPATH` hack in the `setup.py` file.
2. The setup.py based solution insist on installing *eggs* - at least in a debugging phase the opaque eggs are cumbersome to work with.

Possibly/hopefully we can can change back to a pure `setup.py` based solution in the future.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
@tskille : Can you give this a try?

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
@akva2 : Do you have any objections/opinions on this, packaging ... ?

**Comment by akva2** [comment]
no objections. haven't done the packaging yet so i just have to do it the new way when i do.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Pull request merged**
