### PR TITLE
Added cmake files for opm-output.

### PR DESCRIPTION
**Pull request by joakim-hove**
Added initial prereqs and find rules for opm-output.

### CODE REVIEW

**Comment by akva2** [comment]
looks fine. is the boost list real or copy-pasted ?

**Comment by joakim-hove** [comment]
> is the boost list real or copy-pasted ?

Well - it is my best guess of probably needed features; I was uncertain about `system` - but thought that might be needed transitively by some of the other modules.

**Comment by joakim-hove** [comment]
I am actually waiting a bit for this - merge?

**Comment by joakim-hove** [comment]
Cool - thanks.

**Pull request merged**
