### PR TITLE
Use SummaryState::has_group_var() / SummaryState::get_group_var()

### PR DESCRIPTION
**Pull request by joakim-hove**
This was lost from #1844

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
OK - done!

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
> I'll merge once the build check is successful.

Build check successful. Merging as promised.

**Pull request merged**
