### PR TITLE
Avoid converting group surface injection rate to SI twice

### PR DESCRIPTION
**Pull request by vkip**

### CODE REVIEW

**Comment by vkip** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Good catch!  I think we have the same problem in [`eval_well_uda_rate()`](https://github.com/OPM/opm-common/blob/2ed5ee34c2a9d6f29b7d92e38972e636207d5aa7/opm/input/eclipse/Schedule/eval_uda.cpp#L52-L53) too.

I might personally prefer to use the ternary operator here in order to have a single call to `rateToSI()`, but that's a matter of taste so I'll leave it to you to decide.  In any case, with the ternary operator we'd have something along the lines of
```C++
const auto raw_rate = value.is<double>()
    ? value.get<double>()
    : eval_group_uda(value, name, st, udq_undefined);

return injection::rateToSI(raw_rate, phase, unitSystem);
```

**Comment by vkip** [comment]
> Good catch! I think we have the same problem in [`eval_well_uda_rate()`](https://github.com/OPM/opm-common/blob/2ed5ee34c2a9d6f29b7d92e38972e636207d5aa7/opm/input/eclipse/Schedule/eval_uda.cpp#L52-L53) too.
> 
> I might personally prefer to use the ternary operator here in order to have a single call to `rateToSI()`, but that's a matter of taste so I'll leave it to you to decide. In any case, with the ternary operator we'd have something along the lines of
> 
> ```c++
> const auto raw_rate = value.is<double>()
>     ? value.get<double>()
>     : eval_group_uda(value, name, st, udq_undefined);
> 
> return injection::rateToSI(raw_rate, phase, unitSystem);
> ```

I agree, looks better with the ternary op. Updating, and good point about the wells, fixing that as well.

**Comment by vkip** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks a lot for the updates.  This looks good to me now and I'll merge into master.

**Comment by bska** [comment]
I also back-ported this to the release branch ahead of the 2024.10 release as this fixes a real problem and there's no need to release the software with the original problem in place.

**Pull request merged**
