### PR TITLE
Rebased brine module

### PR DESCRIPTION
**Pull request by totto82**
This is a rebased version of #1254

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
@joakim-hove Could you take a look at this? It is just a rebased version of #1254

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
OK - I am ready to merge this; however as part of the ongoing serialization effort a bit more is required[1]:

1. The `Well::operator==` must be updated to include comparison of the brine properties.
2. The brine properties need a `operator==` and also value based (i.e. just one double) constructor.
3. In opm-simulators: [ParallelRestart](https://github.com/OPM/opm-simulators/blob/master/opm/simulators/utils/ParallelRestart.cpp) must be updated.



[1]: I am not intimately familiar with this myself - you will have to ask @akva for guidance if it is not clear how to proceed.

**Comment by akva2** [comment]
i'll send you some pr's soon.

**Comment by akva2** [comment]
PRs have been sent.

**Comment by totto82** [comment]
Thanks to @akva2 !

**Comment by akva2** [comment]
you should read my instructions though, i seldom state random stuff ;) you merged a branch in conflict into this branch. now you have to rebase and fix up the mess.

**Comment by totto82** [comment]
I rebased my branch and then merged your stuff on top and fixed the merge conflicts. Its build fine locally and the merge is green.

**Comment by akva2** [comment]
then github is confused cause it shows two copies of "your" commits.

**Comment by totto82** [comment]
Better now?

**Comment by akva2** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Not quite yet .... :-(

**Comment by akva2** [comment]
this part is fine but i inherited your forgetting to specify downstreams..

**Comment by totto82** [comment]
I started a jenkins from the brine branch in opm-simulators. Locally test_ParallelRestart still fails.  
```
/home/thsa/workspace/opm/opm-simulators/tests/test_ParallelRestart.cpp:1405:5:   required from here
/home/thsa/workspace/opm/opm-material/opm/material/fluidsystems/blackoilpvt/WaterPvtThermal.hpp:359:40: error: no match for ‘operator==’ (operand types are ‘const IsothermalPvt {aka const Opm::WaterPvtMultiplexer<double, false, false>}’ and ‘const IsothermalPvt {aka const Opm::WaterPvtMultiplexer<double, false, false>}’)
                (*this->isoThermalPvt() == *data.isoThermalPvt())) &&
                                        ^
```

**Comment by akva2** [comment]
your opm-material is out of date.

**Comment by totto82** [comment]
Now it isn't, but I guess I have to add the == operator and default constructor to ConstantCompressibilityBrinePvt.hpp.

**Comment by akva2** [comment]
yes, i missed the opm-material pr. note that the pvt stuff is rather messy so be sure to monkey everything i did to the other pvt classes. i can do it if you prefer.

**Comment by totto82** [comment]
Done. Now it works!

**Comment by joakim-hove** [comment]
@totto82 : Will you update the PR description with pointers to the relevant PR's in opm-material and opm-simulators.

**Comment by totto82** [comment]
OPM/opm-material#381 OPM/opm-models#585 OPM/opm-tests#227 OPM/opm-simulators#2270

I just started jenkins from opm-simulators.

**Comment by joakim-hove** [comment]
jenkins build this opm-material=381 opm-models=585 opm-tests=227 opm-simulators=2270 please

**Pull request merged**
