### PR TITLE
fixed: apply VAPPARS from SOLUTION section

### PR DESCRIPTION
**Pull request by akva2**
I think this is the fix you had in mind @bska. Seems to work. I'm not sure what to do about testing, while there is a regression test this feels a little bit like material for a unit test to me.

### CODE REVIEW

**Comment by bska** [comment]
> I think this is the fix you had in mind @bska.

Yes it is.  That's exactly the approach I imagined.

> I'm not sure what to do about testing, while there is a regression test this feels a little bit like material for a unit test to me.

Agreed.  There should be a unit test to cover this alternative.  Using SUMMARY section support for `SUMTHIN` and `RPTONLY`/`RPTONLYO` as an example&mdash;see PR #2761&mdash;I suggest adding a test to [`tests/parser/ScheduleTests.cpp`](https://github.com/OPM/opm-common/blob/24ce7e05a74ad3b2feb9b07fa7b998f611967279/tests/parser/ScheduleTests.cpp), possibly next to the [existing `VAPPARS`](https://github.com/OPM/opm-common/blob/24ce7e05a74ad3b2feb9b07fa7b998f611967279/tests/parser/ScheduleTests.cpp#L1673) test.

**Comment by akva2** [comment]
okay, one more question; since it can be in the SCHEDULE section is this supposed to be dynamic data ? the reason I ask is that the [pvt classes](https://github.com/OPM/opm-common/blob/master/src/opm/material/fluidsystems/blackoilpvt/WetGasPvt.cpp#L157) initializes up front.

**Comment by bska** [comment]
> since [`VAPPARS`] can be in the SCHEDULE section is this supposed to be dynamic data ?

In principle yes, but as you note:

> the [pvt classes](https://github.com/OPM/opm-common/blob/master/src/opm/material/fluidsystems/blackoilpvt/WetGasPvt.cpp#L157) initializes up front.

and that's a big limitation in our implementation.  I think we'll have split `VAPPARS` parameter settings out from the PVT classes, but I suggest we do that in one or more separate PRs.

**Comment by akva2** [comment]
okay. but i revised the existing test to better reflect this.

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks a lot for the updates.  I'll merge this into master and make a work item to uncouple `VAPPARS` from the PVT classes.  I also notice that the implementation appears to be treating `VAPPARS` per PVT region, but the keyword applies to the whole field.

**Pull request merged**
