### PR TITLE
Add micro class to contain information from ACTDIMS keyword

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Ehh - I must admit I was ready to merge in the current state - the class really has quite limited functionality; but I will add a test if you think that is important.

**Comment by bska** [comment]
> the class really has quite limited functionality

Sure, but there is a default constructor which corresponds to `ACTDIMS` missing.  Ensuring that the default constructor behaves correctly (produces expected values), especially during maintenance, would be a reasonable unit test in my opinion.

> but I will add a test if you think that is important.

For this particular instance, maybe not.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Pull request merged**
