### PR TITLE
Add static code analysis support

### PR DESCRIPTION
**Pull request by akva2**
This adds static code analysis support to the buildsystem. Currently clang-check and cppcheck is supported.

These are added as conditional tests - tests which only run if you specify a given ctest configuration.

- ctest -C analyze will run both analyzers
- ctest -C clang-check will only run clang-check
- ctest -C cppcheck will only run cppcheck

The main consumer of this will be a jenkins job running at some interval (possibly nightly, I need to see how long it takes on the server to run for the whole suite).

Note: clang-check requires that you configure with -DCMAKE_EXPORT_COMPILE_COMMANDS=1

In particular cppcheck gives a lot of false positives and general annoying things, so there are scripts sitting between ctest and the analyzer invocation so that we can classify returns codes a little better and thus reflect this in the test status.

Currently opm-parser and ewoms are not covered - first because of the dedicated buildsystem, second because it manually adds executables / do not work through the opm_compile macros.

### CODE REVIEW

**Comment by akva2** [comment]
requires https://github.com/OPM/opm-output/pull/190 to work for opm-output.

**Comment by akva2** [comment]
how should i interpret the silence ? i'd like to get this off my todo-list either through rejection or through merge so i can carry on with the jenkins bits.

**Comment by atgeirr** [comment]
I think it sounds great! Merge when green.

**Comment by atgeirr** [comment]
jenkins build this with downstreams please

**Comment by akva2** [comment]
green, permission granted.

**Pull request merged**
