### PR TITLE
Make pvt tables nested arrays instead of vectors

### PR DESCRIPTION
**Pull request by multitalentloes**
If change in https://github.com/OPM/opm-utilities/pull/86 passes through we need another ctor that accepts nested arrays instead of just nested vectors. For now both generated tables use the same dimensions so this is hardcoded right now for simplicity.

### CODE REVIEW

**Comment by multitalentloes** [comment]
Currently unclear to me why this produced such a large diff in the table. The libraries used in opm-utilities are specified in requirements and the generated file contains the command used to run it which is identical...

**Comment by bska** [comment]
> Currently unclear to me why this produced such a large diff in the table.

Slightly different machines/CPUs generating slightly different text for the individual values?  Might consider running the old&ndash;i.e., current master&ndash;version of the script with the `vector<vector<>>` structure and comparing the output to that of the version in OPM/opm-utilities#86.

**Comment by multitalentloes** [comment]
Running the master version of the script produces 3/4 tables seemingly fine (one or two different values among a few houndred thousands). The second H2 table, which contains enthalpy values still comes out differently. practically every value is slightly different, with values typically being different from the 10 decimal point... floating point numberes are very fragile, so maybe having different CPUs/different versions of pythons are sufficient explanations? If so, what should I do, add "fake" regenerated tables with only the non-numeric changes to keep the diff small and OPM behaviour identical?

**Comment by atgeirr** [comment]
I think it is possible that these differences are due to OS, hardware or similar causes. Maybe we would see the same table if running on the same system as was done originally. Since the values are different only after 10 digits or so I would expect only insignificant differences in simulation results.

So I am not completely opposed to updating the table, however I think your suggestion to avoid this, and only modify the non-numerical parts, is a better idea.

Unless arguments to the contrary are brought, I suggest that is what we do.

**Comment by bska** [comment]
> Unless arguments to the contrary are brought, I suggest that [we only alter the data structure and not the numerical values]

Agreed.  I think that's the best course of action.

**Comment by multitalentloes** [comment]
The large diff is now avoided, will rebase before we merge to ensure it is not stored twice over in the commit history

**Comment by multitalentloes** [comment]
Is this change mergable with the hardcoding of the dimensions or should I further change the generator script to produce a headerfile containing the dimensions should that other code can include the dimensions without including the bulk data?

**Comment by atgeirr** [comment]
jenkins build this please

**Review by atgeirr — APPROVED** [review]

**Comment by bska** [comment]
> will rebase before we merge to ensure it is not stored twice over in the commit history

I guess this step didn't quite do what you wanted because commit 9b3715d543e7156f339f7ffc1630e84e1f92f2c8 is still in the history with its +40,000 -40,000 line change.

**Comment by atgeirr** [comment]
> I guess this step didn't quite do what you wanted because commit [9b3715d](https://github.com/OPM/opm-common/commit/9b3715d543e7156f339f7ffc1630e84e1f92f2c8) is still in the history with its +40,000 -40,000 line change.

This is my fault, I am very sorry. Is there anything we can do now?

**Comment by bska** [comment]
> Is there anything we can do now?

Not really, no.  Once it's merged into the master branch the history is effectively frozen.  Strictly speaking, there are some technical things we can do, but those all have the potential to break all users so it's best not to do them.

**Pull request merged**
