### PR TITLE
Implement add and multiply semantics for repeated AQUANCON keywords

### PR DESCRIPTION
**Pull request by joakim-hove**
New aquifer  mathematics!

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
@tskille : can you test if this solves your  case.

**Comment by tskille** [comment]
Excellent, I'll start testing now. Not sure exactly how to test this, but I will try make some test models and take it from there.

**Comment by tskille** [comment]
I managed to create a small test model which was well suited to run sensitivities with different input. Results are in excellent agreement and I recommend that this PR can be merged.

**Comment by joakim-hove** [comment]
> I managed to create a small test model which was well suited to run sensitivities with different input. 

Thank you for testing

**Pull request merged**
