### PR TITLE
convertECL, new option for unified restart file

### PR DESCRIPTION
**Pull request by tskille**
Added two new options for program convertECL. Both of these are valid for unified restart files.

 * `-r <restartNumber>`: select one specific report step and convert only this 
 * `-l `will list avaliable report step in selected unified restart file

Unified restart files are often huge and converting the entire file can be time consuming. After file is converted these huge formatted files are not easy to work with. 

This options will be useful especially for working with QC of restart functionality

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
What does the convertECL program do? Convert between ASCII and binary format (as convert.x from libecl)?

**Comment by tskille** [comment]
Yes, this is doing the same as convert.x from libecl. Notice that convertECL is based on eclipse io classes in OPM and is not dependent on libecl.

**Pull request merged**
