### PR TITLE
changed: make Tuning hold values in maps

### PR DESCRIPTION
**Pull request by akva2**
simpler code

### CODE REVIEW

**Comment by bska** [comment]
Not a fan of this particular version.  It replaces type-safe lookup (i.e., function names) with string-based ones.

**Comment by akva2** [comment]
jenkins build this opm-simulators=2227 please

**Comment by akva2** [comment]
try serializing this class. you'll realize just how this code sucks. but fine, whatever, i knew that comment would appear.

**Comment by bska** [comment]
> try serializing this class.

There's nothing that prevents you from using a map-like container to implement `Tuning`.  I'd just prefer client code to not have to use strings to look up the parameters.

**Comment by bska** [comment]
> > Try serializing this class.
> 
> There's nothing that prevents you from using a map-like container to implement `Tuning`

And for extra credit, make the `Tuning` class independent of time (i.e., remove the `timestep` parameters) by turning `Schedule::m_tuning` into a `DynamicState<shared_ptr<Tuning>>` instead.

**Comment by akva2** [comment]
i already have about 2000 lines of code changes so far i need to land for my current work. i don't have time to clean up the mess others created here. i did the map cause it adds sanity and made my work easier. you refused me to make it easier so now i will just continue the current code style.

**Comment by blattms** [comment]
I feel @akva2's pain. But couldn't this be accomplished with a vector and an enum?
```
enum StateIndex {TSINIT = 0, ....}; 
tuple<DynamicState<double>, ....> states;
```
or
```

enum IntStateIndex { TRWGHT= 0, ....}; 
enum DoubleStateIndex {TSINIT=0, .... }
std::vector<DynamicState<int>> intstates;
std::vector<DynamicState<int>> doublestates;
```
Then one could leave the other function signatures alone, get easier serialization, and omit the map lookup.

**Comment by joakim-hove** [comment]
> you'll realize just how this code sucks [...] to clean up the mess others created here.

I have certainly had thoughts like this myself; I might even have posted them. But oh my it looks bad - lesson learned.

Anyway - for the current PR my suggestion would be:
1. A plain struct 
```
struct Tuning {
     double TSINIT;
     double TSMAXZ;
     ...
}
```
with no time dependence.

2. Time dependence is moved to `Schedule` like suggested by @bska. I realize that this is not exactly the task you were set up to solve - but I actually think/hope tour task will be simpler that way, in addition to actually improving the code.

For string based lookup it is possible to use the compile time constants for the item names - the amount of boilerplate here is so large that these constants have not been much used - but anyway for this PR user space could do:

```
#include <opm/parser/ParserKeywords/T.hpp>
...
value = tuning.get<double>(Tuning::TSMAXZ::itemName);
```

**Comment by joakim-hove** [comment]
Just a note: If this reopened with string based lookup and external time-dependence I will merge it. This is not sufficiently important code to set the bar at "the best @akva2 can do".

**Pull request closed without merging**
