### PR TITLE
add unit gas oil ratio rate for output of drsdt

### PR DESCRIPTION
**Pull request by totto82**

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this opm-simulators=3977 please

**Comment by bska** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Could you add tests for the LAB and PVT-M unit conventions too, please?

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks for the updates.  I'll merge into master.

**Pull request merged**
