### PR TITLE
added: ability to use jenkins build scripts for release test building

### PR DESCRIPTION
**Pull request by akva2**
we need to be able to specify absolute refs to use for the repos
rather than a pull request number.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this with downstreams opm-simulators=3875 please

**Review by blattms — COMMENTED** [review]
Looks good (although it is not 100% clear who to call it for the release). Works for the old use case.

There is one thing that we need to think about: How do we treat opm-tests if there have been merged update_data calls for stuff not in the release. Would there be a release branch there that we use?

**Comment by akva2** [comment]
please check your email

**Comment by blattms** [comment]
thanks. that explains it.

**Pull request merged**
