### PR TITLE
Add DRSDTR and DRVDTR

### PR DESCRIPTION
**Pull request by totto82**

### CODE REVIEW

**Comment by joakim-hove** [comment]
This does of course look perfectly innocent; and ready to be merged but I have some questions to the PR in ewoms which uses this.

1. We really try to limit the use the `Deckxxxx` datastructures outside of opm-common, if at all possible these keywords should be internalized in a suitable `EclipseState` structure (probably the `Schedule` class?).

2. Since this keyword is used in the `Schedule` section I would assume that it can have timedependence? In that case it should be in `DynamicState<double>` instance in the `Schedule`class.

**Comment by totto82** [comment]
> 1. We really try to limit the use the Deckxxxx datastructures outside of opm-common, if at all possible these keywords should be internalized in a suitable EclipseState structure (probably the Schedule class?). 
> 2. Since this keyword is used in the Schedule section I would assume that it can have timedependence? In that case it should be in DynamicState<double> instance in the Scheduleclass.

I guess both these also applies to the current implementation of the DR[SV]DT keyword. 

I can try to add a layer in EclipseState with a DynamicState vector.

**Comment by joakim-hove** [comment]
>I can try to add a layer in EclipseState with a DynamicState vector.

Very good - then it should be in the `Schedule` class. 

Yes - you are right that this applies to the existing DRSDT as well.

**Comment by andlaus** [comment]
> if at all possible these keywords should be internalized in a suitable EclipseState structure (probably the Schedule class?).

In principle, we don't mind using internalized versions of the data; in practice, creating all these boiler plate classes comes with a lot of additional work while the benefits are very limited for most keywords. (besides, at least me constantly struggles to find out how these objects are exposed by EclipseState, but it is clear from the outset how to retrieve keywords from the deck.)

**Comment by totto82** [comment]
Now DRSDT etc. is properly implemented using the DynamicState vector. Most of the changes is due to change in the Schedule interface. I needed the pvt table size from the runspec.

**Comment by andlaus** [comment]
jenkins build this ewoms=401 please

**Comment by joakim-hove** [comment]
Thank you for the changes; I must admit I am quite surprised how large they became. I'm ready to merge this when Jenkins is.

**Comment by joakim-hove** [comment]
jenkins build this ewoms=401 please

**Comment by totto82** [comment]
Ops. I forgot to push the needed changes in opm-simulators. I have asked Jenkins to test this PR from the opm-simulator PR.

**Comment by joakim-hove** [comment]
@totto82 - I am ready to merge this; but it needs a little rebase love.

**Comment by totto82** [comment]
Now it should be ready to go. I have launched a test from opm-simulators.

**Pull request merged**
