### PR TITLE
add serialization template to SummaryNode

### PR DESCRIPTION
**Pull request by akva2**
Time to start replacing external serialization with internal serialization. This moves the SummaryConfig class completely to the new approach.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-simulators=2460 please

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2460 please

**Comment by akva2** [comment]
jenkins build this opm-simulators=2460 please

**Comment by blattms** [comment]
Cool. Merge when the upstream jenkins test is green.

**Comment by blattms** [comment]
My comment was supposed to made downstream, of course

**Pull request merged**
