### PR TITLE
added: support building with superlu for dune 2.6 (complete version)

### PR DESCRIPTION
**Pull request by blattms**
This is @akva2's #313 with a few previously missing defines.

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins build this with downstreams please

**Comment by blattms** [comment]
Squashed my commit into @akva2's

**Comment by blattms** [comment]
Works with the companion PRs in the other modules and #319

**Comment by akva2** [comment]
jenkins build this with downstreams dune2.6 please

**Pull request merged**
