### PR TITLE
adding unit PPM

### PR DESCRIPTION
**Pull request by GitPaean**
Parts per million (ppm). We are not distinguishing PPM volume or PPM mass, or other forms. Will update when it comes to be necessary.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
not sure whether all the codes are needed here.

**Review by bska — APPROVED** [review]
Thanks a lot&ndash;this is most excellent and I'll merge into master.

**Comment by bska** [comment]
> not sure whether all the codes are needed here.

Very strictly speaking you needn't have added the [`ppm`](https://github.com/OPM/opm-common/blob/f95cbea9211bec2479b01ccb87cf92dc41d6bf29/opm/input/eclipse/Units/UnitSystem.hpp#L86) entry to `UnitSystem::measure` "just" to introduce the new `Dimension`.  However, by making the extra effort to also add it there, you've greatly simplified future work in the result output layer and for that I am very grateful.

**Pull request merged**
