### PR TITLE
Make the Python `opm` package a namespace package

### PR DESCRIPTION
**Pull request by hakonhagland**
Depends on #3037 which should be merged first.
See also https://github.com/OPM/opm-simulators/pull/3933

Convert the Python `opm` package from a regular package to a [namespace package](https://peps.python.org/pep-0420/) such that `opm-simulators` can contribute to the package from a different filesystem path. In this way, the two packages `opm.simulators` and `opm.io` (for example) can have a different parent filesystem path.

### CODE REVIEW

**Comment by hakonhagland** [comment]
jenkins build this please

**Comment by hakonhagland** [comment]
Hmm.. the jenkins build fails due to some tests in opm-simulators. I did not know that the Jenkins build for opm-common was running downstream tests but I see from the [console log](https://ci.opm-project.org/job/opm-common-PR-builder/4855/console)
``` 
Building downstream opm-simulators=master configuration=mpi
```
How do I run a jenkins build with opm-simulators=3933 ? Can I just use the same syntax as with upstream in opm-simulators:

**Comment by hakonhagland** [comment]
jenkins build this opm-simulators=3933 please

**Comment by blattms** [comment]
Looks like a nice cleanup

**Comment by blattms** [comment]
The only thing that seems up for debate is:
Should python < 3.3 really be an error? Or a just warning and we deactivate pyhon bindings in this case?

**Comment by hakonhagland** [comment]
> Should python < 3.3 really be an error? Or a just warning and we deactivate pyhon bindings in this case?

@blattms Yes, currently it will only give an error if the user has enabled python bindings, see line 172:
```
if (OPM_ENABLE_PYTHON)
```

Since `if(Python3_VERSION_MINOR LESS 3)` is inside that `if` on line 172, it will only be an error if `OPM_ENABLE_PYTHON` is true.

**Comment by hakonhagland** [comment]
jenkins build this opm-simulators=3933 please

**Pull request merged**
