### PR TITLE
Use Std::Move()

### PR DESCRIPTION
**Pull request by bska**
Missed in commit f92d0be54d.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Review by akva2 — APPROVED** [review]
I should have caught that one..

**Comment by bska** [comment]
> Although I am again somewhat astonished that it compiles,

I was surprised myself.  I don't have an explanation for this right now.

**Comment by bska** [comment]
PR approved and build check is green.  I'll merge into master.

**Pull request merged**
