### PR TITLE
Restart items

### PR DESCRIPTION
**Pull request by joakim-hove**
Add items to resart file - magic numbers provided by @tskille 

This will add two new items to the `SWEL` vector and one new item to the `SCON` vevctyor, for each well and connection - i.e. data update is required.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
Looks good, just one question: Do we not need to assign a value in `swel[EfficiencyFactor2]`?

**Comment by joakim-hove** [comment]
> Do we not need to assign a value in swel[EfficiencyFactor2]?

As I have understood it this value is repeated in two items; I have chosen to only assign to one the of the items - because only one is read in our case - and just maybe they  values might be different under circumstance 'X'. I guess you could argue that both should be assigned - I'll update if you suggest that.

**Comment by joakim-hove** [comment]
enkins build this opm-data=261 please

**Comment by bska** [comment]
jenkins build this opm-tests=261 please

**Comment by bska** [comment]
> I guess you could argue that both should be assigned - I'll update if you suggest that.

I think it's fine as is.  I suggest you add a comment about intentionally not assigning `EfficiencyFactor2` though.

**Pull request merged**
