### PR TITLE
Export some ESMRY methods to python

### PR DESCRIPTION
**Pull request by akva2**
Give ability for python scripts to easily
- get list of dates for summary results
- obtain the units for a summary vector.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
added some basic tests. marking this ready for review

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
This looks good to me and it clearly enables a useful use case.  I'll merge into master.

**Pull request merged**
