### PR TITLE
fixed: increase iteration count

### PR DESCRIPTION
**Pull request by akva2**
Found by CppCheck

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
Some context since it's hard to read from the diff. There is a while loop for this count to ensure we don't inf loop. It is nuitered as-is because the iteration count is not currently increased. But there is a break when converged so we usually get out that way.

**Comment by bska** [comment]
> There is a while loop for this count to ensure we don't inf loop. It is neutered as-is because the iteration count is not currently increased. But there is a break when converged so we usually get out that way.

This looks like an improvement to me, but I want those more familiar with the PT flash calculation to have a closer look as well.  Perhaps @GitPaean would care to comment?

**Comment by GitPaean** [comment]
I will have a look.

**Review by GitPaean — APPROVED** [review]
Good catch! Thanks.

**Pull request merged**
