### PR TITLE
Enable fine grained control of Python ON | OFF

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
This breaks configurations that don't enable Python.  In that configuration we end up dereferencing null pointers in [`tests/parser/EmbeddedPython.cpp`](https://github.com/OPM/opm-common/blob/eca0589fe1b2082bdbc1d9f2268241c7c699857f/tests/parser/EmbeddedPython.cpp#L42)

I can sort of restore my configuration if I apply the patch  below, but I don't know if that's the appropriate solution.

---

```diff
diff --git a/src/opm/parser/eclipse/Python/Python.cpp b/src/opm/parser/eclipse/Python/Python.cpp
index eed6fecfa..10a935789 100644
--- a/src/opm/parser/eclipse/Python/Python.cpp
+++ b/src/opm/parser/eclipse/Python/Python.cpp
@@ -47,6 +47,11 @@ Python::Python() : Python(Enable::COND)
 }
 
 bool Python::exec(const std::string& python_code) const {
+    if (this->interp == nullptr)
+        throw std::logic_error {
+            "Interpreter not initialized"
+        };
+
     this->interp->exec(python_code);
     return true;
 }
@@ -60,11 +65,21 @@ bool Python::enabled() {
 }
 
 bool Python::exec(const std::string& python_code, const Parser& parser, Deck& deck) const {
+    if (this->interp == nullptr)
+        throw std::logic_error {
+            "Interpreter not initialized"
+        };
+
     this->interp->exec(python_code, parser, deck);
     return true;
 }
 
 bool Python::exec(const Action::PyAction& py_action, EclipseState& ecl_state, Schedule& schedule, std::size_t report_step, SummaryState& st) const {
+    if (this->interp == nullptr)
+        throw std::logic_error {
+            "Interpreter not initialized"
+        };
+
     this->interp->exec(py_action, ecl_state, schedule, report_step, st);
     return true;
 }
```

**Comment by joakim-hove** [comment]
Damn - I'll fix

**Comment by joakim-hove** [comment]
I have to look a bit more into this - band aid "fix" here: #1643. It worked on my machine - but that was probably undefined behavior.

**Comment by bska** [comment]
>  It worked on my machine - but that was probably undefined behavior.

I guess so.  This is one of those cases for which a checked iterator build is **really** helpful.  Transcript below.  I wish Address Sanitizer would have caught this too because the runtime overhead of ASAN is a lot less than the checked iterator build, but at least on my system (Ubuntu 18.04 LTS, GCC 7.5.0) I didn't get any signals.

---

```
$ ../bin/EmbeddedPython --run_test=INSTANTIATE
Running 1 test case...
/usr/include/c++/7/bits/shared_ptr_base.h:968: std::__shared_ptr_access<_Tp, _Lp, <anonymous>, <anonymous> >::element_type* std::__shared_ptr_access<_Tp, _Lp, <anonymous>, <anonymous> >::operator->() const [with _Tp = Opm::PythonInterp; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2; bool <anonymous> = false; bool <anonymous> = false; std::__shared_ptr_access<_Tp, _Lp, <anonymous>, <anonymous> >::element_type = Opm::PythonInterp]: Assertion '_M_get() != nullptr' failed.
unknown location(0): fatal error: in "INSTANTIATE": signal: SIGABRT (application abort requested)
/home/bska/work/opm/src/opm.kdev/opm-common/tests/parser/EmbeddedPython.cpp(42): last checkpoint

*** 1 failure is detected in the test module "EMBEDDED_PYTHON"
```

**Pull request merged**
