### PR TITLE
Fixes from the debian packages

### PR DESCRIPTION
**Pull request by blattms**
Quite some issues became apparent during the Debian packaging work. These are the patches that should be uncontroversial and should not interfere with other packaging efforts.

pkg-config files were quite broken with include paths like '-I/parmetis' or imported library names in the linker lines.

Two more comments:

SOVERSION:
The version of our shared library was the year before this. Now it is year.month (i.e. the version). I think this is more sound as the ABI needs to stable if the SOVERSION does not change and I would be quite surprised if take care that this only happens if the year changes.

Manpages / Executables:
We install all executables created in bin. Some of them, did not offer any reasonable help messages and might only be intended for  internal usage (At least I could not easily figure out what they are supposed to do). I have skipped man pages for them and even excluded them from the Debian packages. These are test_esmry_lod and opmi. If somebody feels that these need to be installed and need manpages, then please add a PR that adds man pages for them.

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Non build related stuff looks fine.

> I have skipped man pages for them and even excluded them from the Debian packages. These are test_esmry_lod and opmi.

Makes sense

**Comment by akva2** [comment]
i think those executables should not be marked for installation, certainly not test_esmry_lod, and i'm not sure opmi is very useful outside development either.

it looks fine to me. i don't quite get what the problem with stdc++fs was, but i'm sure it makes sense.

**Comment by blattms** [comment]
@akva2 Unfortunately, that did not fix anything, but it did not break anything either. Maybe you know what the colon in `-l:stdc++fs` does?

**Comment by akva2** [comment]
hmm.

usually that is used to indicate that the linker should not prepend lib to resolve the .so name, ie, -l:foo to link to foo.a|so and not libfoo.a|so

**Pull request merged**
