### PR TITLE
not forbidding opening wells with zero rate and disallowing crossflow

### PR DESCRIPTION
**Pull request by GitPaean**
other keywords might change the control to make it openable.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
Not saying the PR is complete. But let us test it out the incomplete part.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 1.024    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 1.062    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 0.995    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.996    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 0.998    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1836

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
At least some of the jenkins failures should not be relevant to this PR at all, at least the first two regression test ([mpi.compareECLFiles_flow+2D_FETKOVICHAQUIFER](https://ci.opm-project.org/job/opm-common-PR-builder/5649/testReport/junit/(root)/mpi/compareECLFiles_flow_2D_FETKOVICHAQUIFER/)
[mpi.compareECLFiles_flow+SPE5CASE1](https://ci.opm-project.org/job/opm-common-PR-builder/5649/testReport/junit/(root)/mpi/compareECLFiles_flow_SPE5CASE1/)). Not sure what is going one,

**Comment by GitPaean** [comment]
> At least some of the jenkins failures should not be relevant to this PR at all, at least the first two regression test ([mpi.compareECLFiles_flow+2D_FETKOVICHAQUIFER](https://ci.opm-project.org/job/opm-common-PR-builder/5649/testReport/junit/(root)/mpi/compareECLFiles_flow_2D_FETKOVICHAQUIFER/)
[mpi.compareECLFiles_flow+SPE5CASE1](https://ci.opm-project.org/job/opm-common-PR-builder/5649/testReport/junit/(root)/mpi/compareECLFiles_flow_SPE5CASE1/)). Not sure what is going on.

For these cases, I think the results are not changed by this PR, but some output files might have different status for the OPEN or CLOSE of the well. 
```
Keyword: ICON, origin Restart, sequence 203

Value index                 = 155
(first value, second value) = (1, 0)

Non floating point values not identical 
```

**Comment by GitPaean** [comment]
benchmark please

**Comment by GitPaean** [comment]
The following cases, the simulation results are not changed, but some output file `ICON` might have difference between 1 and 0.
```
[mpi.compareECLFiles_flow+2D_FETKOVICHAQUIFER](https://ci.opm-project.org/job/opm-common-PR-builder/5651/testReport/junit/(root)/mpi/compareECLFiles_flow_2D_FETKOVICHAQUIFER/)
[mpi.compareECLFiles_flow+SPE5CASE1](https://ci.opm-project.org/job/opm-common-PR-builder/5651/testReport/junit/(root)/mpi/compareECLFiles_flow_SPE5CASE1/)
[mpi.compareECLFiles_flow+SPE5CASE1_DYN](https://ci.opm-project.org/job/opm-common-PR-builder/5651/testReport/junit/(root)/mpi/compareECLFiles_flow_SPE5CASE1_DYN/)
[mpi.compareECLFiles_flow+9_3E_GAS_MIN_EXPORT_STW](https://ci.opm-project.org/job/opm-common-PR-builder/5651/testReport/junit/(root)/mpi/compareECLFiles_flow_9_3E_GAS_MIN_EXPORT_STW/)
[mpi.compareECLFiles_flow+9_3D_GINJ_GAS_MAX_EXPORT_STW](https://ci.opm-project.org/job/opm-common-PR-builder/5651/testReport/junit/(root)/mpi/compareECLFiles_flow_9_3D_GINJ_GAS_MAX_EXPORT_STW/)
[mpi.compareECLFiles_flow+9_3D_GINJ_GAS_MAX_EXPORT_MSW](https://ci.opm-project.org/job/opm-common-PR-builder/5651/testReport/junit/(root)/mpi/compareECLFiles_flow_9_3D_GINJ_GAS_MAX_EXPORT_MSW/)
[mpi.compareECLFiles_flow+9_3E_GAS_MIN_EXPORT_MSW](https://ci.opm-project.org/job/opm-common-PR-builder/5651/testReport/junit/(root)/mpi/compareECLFiles_flow_9_3E_GAS_MIN_EXPORT_MSW/)
```

**Comment by GitPaean** [comment]
The cases with ACTIONX with jenkins failures, the results are changed, 
```
[mpi.compareECLFiles_flow+ACTIONX_GCONPROD](https://ci.opm-project.org/job/opm-common-PR-builder/5651/testReport/junit/(root)/mpi/compareECLFiles_flow_ACTIONX_GCONPROD/)
[mpi.compareECLFiles_flow+ACTIONX_GCONINJE](https://ci.opm-project.org/job/opm-common-PR-builder/5651/testReport/junit/(root)/mpi/compareECLFiles_flow_ACTIONX_GCONINJE/)
[mpi.compareECLFiles_flow+ACTIONX_WCONINJE](https://ci.opm-project.org/job/opm-common-PR-builder/5651/testReport/junit/(root)/mpi/compareECLFiles_flow_ACTIONX_WCONINJE/)
[mpi.compareECLFiles_flow+ACTIONX_WEFAC](https://ci.opm-project.org/job/opm-common-PR-builder/5651/testReport/junit/(root)/mpi/compareECLFiles_flow_ACTIONX_WEFAC/)

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
Now the only failure is the [mpi.ScheduleTests](https://ci.opm-project.org/job/opm-common-PR-builder/5655/testReport/junit/(root)/mpi/ScheduleTests/)

Basically, it means this PR does not change the running results much at all, since we partially handle the zero rate and crossflow related in the BlackoilWellModel when we try to create the wells for the simulation.

**Comment by GitPaean** [comment]
Especially, the UDQ might change the values in the control, I think there is no very good point to disallowing the opening of the well at the parsing stage, since it can be changed in the later stage.

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                              | Relative |
| ------- | ------------------------------------------ | -------- |
| opm-git | OPM Benchmark: drogon - Threads: 1         | 0.99     |
| opm-git | OPM Benchmark: drogon - Threads: 8         | 0.861    |
| opm-git | OPM Benchmark: smeaheia - Threads: 1       | 1        |
| opm-git | OPM Benchmark: smeaheia - Threads: 8       | 0.956    |
| opm-git | OPM Benchmark: spe10_model_1 - Threads: 1  | 1.003    |
| opm-git | OPM Benchmark: spe10_model_1 - Threads: 8  | 0.998    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 | 1.016    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 | 1.025    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 | 1.003    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 | 0.982    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=2030

**Comment by GitPaean** [comment]
Testing and investigation is completed. I open a new PR based this PR for ease of communication.

**Pull request closed without merging**
