### PR TITLE
Fix check for access to first_RFT()

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
@bska

**Review by bska — APPROVED** [review]
Looks good.  I still wish `Schedule::first_RFT()` were constant time though.

**Comment by joakim-hove** [comment]
>Looks good. I still wish Schedule::first_RFT() were constant time though.

That I understand; we might fix that some way, but that will require some statefull caching - would like to Waitz with things like that. But I have pushed ut om the stack.

**Comment by bska** [comment]
> would like to Waitz with things like that

Grete or Tom?

> will require some stateful caching

Sure, but I don't think it'd be particularly hard if we accept that the first call to `Schedule::first_RFT()` is linear in the number of report steps.  We could go back to returning an unconditional `std::size_t` and add an `optional<std::size_t>` at the `Schedule` level that gets set at the first call to `Schedule::first_RFT()` using logic of the form
```C++
std::size_t first_RFT()
{
    if (this->first_rft_output.has_value()) {
        return this->first_rft_output.value();
    }

    this->first_rft_output = number_of_report_steps;
    for (step = 0; step < number_of_report_steps; ++step) {
        if (rft_active(step)) {
            this->first_rft_output = step;
            break;
        }
    }

    return this->first_rft_ouput.value();
}
```

As an added benefit this would be easier to use from the client side than then current scheme of returning an `optional<>` with `nullopt` signifying "RFT output not needed".  If you still want to return an optional then you'd need an `optional<optional<size_t>>` to distinguish "value not set" from "doesn't want RFT output".

**Comment by joakim-hove** [comment]
> [...] but I don't think it'd be particularly hard if we accept that the first call to Schedule::first_RFT() is linear in the number of report steps.

I agree - and an implementation will be along the lines outlined here. However - with the new `Schedule` implementation we can rerun the schedule construction runtime, and then we suddenly must invalidate the cached value; as we all there are only two difficult topics in programming: cache, counting and naming.

So - what I have in mind is creating a small "cache class" which cache the report step linear search for selected properties - like e.g. `first_RFT` - but just not quite ready yet ...

**Comment by joakim-hove** [comment]
Thanks for merging!

**Pull request merged**
