### PR TITLE
Adding injectivity keywords

### PR DESCRIPTION
**Pull request by GitPaean**
The major purpose of this PR is to introduce the support for the following three non-ECL keywords.

PLYMWINJ, SKPRWAT, and SKPRPOLY, 

and two associated SCHDULE keywords, WPMITAB and WSKPTAB. 

The keywords are related to polymer injectivity study. They share very similar 2D Cartesian table structure, as a result, a very simple `PolyInjTable`  class is introduced, which turns out to be sufficient.

The definition and example of the three table keywords are as follows,
```
PLYMWINJ    (PROPS)
this keyword describes the molecular weight after injected during polymer injection process through a form of 2D table. This keyword can be input for multiple time to describe multiple tables. 

PLYMWINJ
    1   /    -- table number
    0.0     200.0   800.0   / -- throughput values (m^3/m^2)
    0.0     1.0   2.0  3.0  / -- velocity values  (m/day)
 -- the rest will be the polymer molecular weight   (MDa)
 -- each row corresponds to one sample points in the throughput direction
    20.    19.   18.   16. /
    20.    16.   14.   12. /
    20.    12.     8.     4. /

```

```
SKPRWAT (PROPS)
this keyword describes the skin pressure during water injection considering the throughput and water velocity. This keyword can be input for multiple times to describe multiple tables. 

SKPRWAT
    1   /    -- table number
    0.0     200.0   800.0   / -- throughput values (m^3/m^2)
    0.0     1.0   2.0  3.0  / -- velocity values  (m/day)
 -- the rest will be the skin pressure (Barsa)
 -- each row corresponds to one sample points in the throughput direction
    20.    19.   18.   16. /
    20.    16.   14.   12. /
    20.    12.     8.     4. /

```

```
SKPRPOLY (PROPS)
This keyword describes the skin pressure during polymer injection considering the throughput and water velocity. This keyword can be input for multiple time to describe multiple table. 

SKPRPOLY
    1    2.0 /    -- table number     reference polymer concentration  (kg/m^3)
    0.0     200.0   800.0   / -- throughput values (m^3/m^2)
    0.0     1.0   2.0  3.0  / -- velocity values  (m/day)
 -- the rest will be the skin pressure (Barsa)
 -- each row corresponds to one sample points in the throughput direction
    20.    19.   18.   16. /
    20.    16.   14.   12. /
    20.    12.     8.     4. /
```

And two related SCHEDULE keywords, 
```
WPMITAB    (SCHEDULE)
this keyword specifies the table will be used to calculate molecular weight  during polymer injection. 

  WPMITAB
  -- well name   table id
      INJE1               1  /
      INJE2               2  /
  /
WSKPTAB
this keyword specifies the table will be used to calculate the skin pressure during water injection and polymer injection.

    WSKPTAB
    -- well name    id-SKPRWAT     id-SKPRPOLY
        INJE1                   1                   2 / 
        INJE2                   1                   3 / 
     /

```

### CODE REVIEW

**Comment by GitPaean** [comment]
This PR is not ready for review yet, it is created for self-motivation to finish it since it has been there for long.  I will finish cleaning up and adding all the tests soon and remove the `WIP` tag later.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
All the implementation of the newly introduced tables is moved to one single file  `PolyInjTables.cpp`.  Initially I was thinking to move them to `Tables.cpp`, while in the end, I think a separate `PolyInjTables.cpp` will be better for the clarity. It is really only for the polymer injectivity study, and they are non-ECL keywords, better they stay in their own file.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
I  removed the tab [WIP]. This PR is ready for review.

**Comment by GitPaean** [comment]
> has it been rebased on current master?

It is rebased just now.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
Some prompt review will be much appreciated, @joakim-hove . Thanks.

**Comment by joakim-hove** [comment]
This looks good - thank you for the testing @GitPaean !

**Pull request merged**
