### PR TITLE
Add function Schedule::changed_wells() to use in WELSPECS reporting

### PR DESCRIPTION
**Pull request by joakim-hove**
Check if well structure (connections++) has changed. Will not flag a change for changes in production/injection

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
comments?

**Comment by bska** [comment]
> comments?

Just one.  Do you really need to return complete `Well` objects?  Could you not get mostly the same properties from returning a list of well names instead?

**Comment by joakim-hove** [comment]
> Do you really need to return complete Well objects?

I will eventually need the full `Well`objects; but you are right that I could start with a list of names.

**Comment by bska** [comment]
>> Do you really need to return complete Well objects?
> 
> I will eventually need the full Wellobjects; but you are right that I could start with a list of names.

Right.  If you already have a `Schedule` object and a time step then a list of well names is sufficient to access those associate well objects too.

**Comment by joakim-hove** [comment]
OK - changed to return a list of wellnames.

**Comment by joakim-hove** [comment]
jenkins build this please

**Pull request merged**
