### PR TITLE
adding function getCompletionsByConnectionIndices to Well2

### PR DESCRIPTION
**Pull request by GitPaean**
The function name is pretty bad. 

Basically, `getCompletions` returns `std::map<int, std::vector<Connection>> `, which is not easy to use in the simulator code, since we have to search to find the `connection number/index` for this `Connection`. 

A function return `std::map<int, std::vector<int>>` is added for the ease to handle COMPLUMP related in the simulator code. 

Please suggest what is the best way to do this.

### CODE REVIEW

**Comment by GitPaean** [comment]
Not sure about the usage of the function `getCompletions`. One way can be to replace `getCompletions` with the added `getCompletionsByConnectionIndices`, which can be even cheaper. We have all the `connections`, it is easy to find the connection with the index.

**Comment by joakim-hove** [comment]
> The function name is pretty bad

That was an understatement.

Naming aside my initial reaction is to be a bit sceptical - to me it feels like you are exposing too much internal details this way. I will look more into it.

**Comment by GitPaean** [comment]
> Please indicate the callsite in opm-simulators which is currently cumbersome


See the discussion, https://github.com/OPM/opm-simulators/pull/1882#discussion_r292866567

**Comment by GitPaean** [comment]
With private communication, we decided to do this from the simulator side to avoid strengthening further the requirement that the order of connections needs to be equal on parser and simulator side, although the current implementation assumes it already in the simulator side since the WellsManager is created.

**Pull request closed without merging**
