### PR TITLE
fixed: really handle the _prepare target for tests

### PR DESCRIPTION
**Pull request by akva2**
So many source tree's, i pushed a partly done change. sorry for that

@atgeirr you should try it before merge this time.

### CODE REVIEW

**Comment by atgeirr** [comment]
I had no problems on my end, but then I have not built ewoms tests, so I guess that fell through the cracks. What level of testing should I do on this one?

**Comment by atgeirr** [comment]
jenkins build this with downstreams please

**Comment by akva2** [comment]
make sure that you can build on your machine using the superbuild now.

**Comment by atgeirr** [comment]
I can confirm that the superbuild now went off without a hitch. Merging here!

**Pull request merged**
