### PR TITLE
not throwing for numerical aquifers do not have connections

### PR DESCRIPTION
**Pull request by GitPaean**

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
The throwing was an intended behavoir by design. Now with reference behavoir from commercial behavoir, we are removing the throwing and change it to a warning message. (although the commercial simulator does not give warning message.)

**Comment by bska** [comment]
Does this handle the case of a numerical aquifer being defined using `AQUNUM`, but then **not** supplying connections for that aquifer in `AQUCON`?  If so, don't we run the risk of generating systems of linear equations for which one or more sets of degrees of freedom are not linked to any other degrees of freedom&mdash;i.e.,essentially cells that don't communicate with anything?

**Comment by GitPaean** [comment]
>  If so, don't we run the risk of generating systems of linear equations for which one or more sets of degrees of freedom are not linked to any other degrees of freedom—i.e.,essentially cells that don't communicate with anything?

Yeah. that is correct.  The running is fine and the matrix should not be singular either.

**Comment by GitPaean** [comment]
@bska , I understand your concerns. It will not be a very helpful situation that the aquifer cells are defined while they are not connected to the rest of the reservoir. But it should not cause big problem either (might affect the averaged amount calculation or parallelisation in the numerical level). 

Can you help to give a review and merge it if you are happy with the pull request?

**Comment by bska** [comment]
The implementation is fine if we "only" care about numerical aquifers defined in `AQUNUM` which don't have corresponding records in `AQUCON`, and assuming our solvers can handle that case.  The next level up **might** be to also consider the case of a numerical aquifer whose `AQUCON` connections all go to inactive/deactivated cells.  I don't think we handle that case today, and it's probably not a priority but it might be something to think about in future updates here.

**Comment by GitPaean** [comment]
>  The next level up might be to also consider the case of a numerical aquifer whose AQUCON connections all go to inactive/deactivated cells. 

Let me double check. It is possible that the master branch can handle it already without this PR.

**Comment by GitPaean** [comment]
> The next level up might be to also consider the case of a numerical aquifer whose AQUCON connections all go to inactive/deactivated cells.

After checking the following functions, I believe the above situation is handled in the master branch. 
```c++
    void NumericalAquifers::initConnections(const Deck& deck, const EclipseGrid& grid);
    void SingleNumericalAquifer::postProcessConnections(const EclipseGrid& grid, const std::vector<int>& actnum);
```

**Review by bska — APPROVED** [review]
> > The next level up might be to also consider the case of a numerical aquifer whose AQUCON connections all go to inactive/deactivated cells.
> 
> After checking the following functions, I believe the above situation is handled in the master branch.

Ah, yes.  You're right.  In that case I'll merge this into the master branch.

**Pull request merged**
