### PR TITLE
Move Well status enum to Well2 class

### PR DESCRIPTION
**Pull request by joakim-hove**
Move enums from `ScheduleEnums` to the natural class; use `class enum` for all enums.

Reorganisation / cleanup of all the enums in the `Schedule` implementation. The PR is large - but it is 100% mechanical.

Downstream: https://github.com/OPM/opm-simulators/pull/1986

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=1986 please

**Comment by bska** [comment]
jenkins build this opm-simulators=1986 please

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=1986 please

**Comment by atgeirr** [comment]
Seems reasonable, and downstream is green. Remove WIP heading?

**Comment by joakim-hove** [comment]
> Seems reasonable, and downstream is green. Remove WIP heading?

Thanks but no thanks - this is truly *Work in progress* - there are many enums left in `ScheduleEnums.hpp` ... :cry:

**Comment by atgeirr** [comment]
> Thanks but no thanks - this is truly _Work in progress_ - there are many enums left in `ScheduleEnums.hpp` ... 😢

Ok, still some way to go then, just thought you were done after seeing the downstream PR green.

**Comment by joakim-hove** [comment]
@totto82 : This is now soon ready to be merged; I fear it might come in conflict with your control refactoring. Opinions?

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=1986 please

**Comment by totto82** [comment]
Yes, this will definitely conflict with my work. Is the changes in opm-simulators just renaming?

**Comment by joakim-hove** [comment]
The changes in simulators is pure renaming.

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=1986 please

**Comment by joakim-hove** [comment]
This seems to refuse to pick up new versions of the opm-simulators pr; I'll try again.

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=1986 please

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=1986 please

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=1986 please

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=1986 please

**Pull request merged**
