### PR TITLE
Add UnitSystem member to Well2 class

### PR DESCRIPTION
**Pull request by joakim-hove**
Due to the UDA mechanism and phase dependent rate dimensions in the WCONINJE keyword the SI conversion is performed veeery late; need the `UnitSystem` object available in the Well.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
OK - this is quite trivial - and it is green at this very instant; I will merge tomorrow.

**Comment by bska** [comment]
> OK - this is quite trivial - and it is green at this very instant; I will merge tomorrow.

No real issue, but just one question: Is the new data member supposed to be used as an argument in [`UDAValue::set_dim()`](https://github.com/OPM/opm-common/blob/ba2a12e876ee2fad3842d3bbf08dd691f0106926/opm/parser/eclipse/Deck/UDAValue.hpp#L44) or is there some other intended use?

**Comment by joakim-hove** [comment]
> Is the new data member supposed to be used as an argument in `UDAValue::set_dim()` [...]

No - the `UDAValue::set_dim()` atrocity is called while building up the `Deck` datastructure, the problem the current PR addresses is the `RATE` item in the `WCONINJE` keyword; the dimension of that item depends on the injected phase, so the conversion to SI units must be performed at a later stage; previously that "later stage" was during `Schedule` construction, with the evaluation of `UDA` values that has become even later - during the simulation, and that is where we need access to a `UnitSystem` object.

**Comment by bska** [comment]
> the problem the current PR addresses is the `RATE` item in the `WCONINJE` keyword; the dimension of that item depends on the injected phase, so the conversion to SI units must be performed at a later stage

Does that mean that the ultimate motivation for this PR is to ensure correct responses from `Well2::getInjectionProperties()`, `Well2::injection_rate()` and/or `Well2::injectionControls()`?  If so, did you consider passing a `UnitSystem` argument to those functions instead?  I only ask because having a `UnitSystem` in each well seems like a bit of a hack when they're all supposed to be equal.

**Comment by joakim-hove** [comment]
> Does that mean that the ultimate motivation for this PR is to ensure correct responses from Well2::getInjectionProperties(), Well2::injection_rate() and/or Well2::injectionControls()

yes - in particular `Well2::injectionControls()`

> did you consider passing a UnitSystem argument to those functions instead?

I did not really consider that; but I agree it would work. The `Well2::injectionControls()` method is called from the well setup code in the simulator, so then the `UnitSystem` must be handled from there. That would certainly work - but iff I were in charge in that part of town I would prefer to keep the simulator blissfully unaware of anything but SI.

**Comment by bska** [comment]
> [Passing a `UnitSystem` argument] would certainly work - but iff I were in charge [of well setup] I would prefer to keep the simulator blissfully unaware of anything but SI.

Agreed, I too would prefer to keep unit handling out of the simulator core.  This **may** be a case for [reference_wrapper](https://en.cppreference.com/w/cpp/utility/functional/reference_wrapper) to underscore the fact that there is a single source of unit definitions, but we can make that change in the next iteration of this code.

For now I'm satisfied that the justification for the change is sound. I'll merge into master.

**Comment by joakim-hove** [comment]
>This may be a case for reference_wrapper to underscore the fact that there is a single source of unit definitions

In principle I agree - but I have never got the `reference_wrapper` to work properly and have stopped trying to use it.

**Comment by atgeirr** [comment]
Two assumptions from me, one of which is apparently wrong:
 - Only SI values are communicated between the simulator and other facilities, including the SummaryState being SI.
 - The functions defining UDQs are valid using SI.
If both are right, I do not see how we would need unit support?

I fear perhaps the second assumption is wrong, and definitions will include all kinds of crazy unit conversion constants, but I hope not... (If I define a UDQ equal to some function of gas surface rate and use it to set an oil rate that would certainly be ugly in FIELD units...)

**Comment by joakim-hove** [comment]
As usual the answers are not all-that-clear-cut:

> Only SI values are communicated between the simulator and other facilities, including the SummaryState being SI.

Currently the numerical values passed between the simulator and the input layer are "all SI" - with the exception: The values stored in the `SummaryState` class are in deck units, however the numerical values in the `SummaryState`are **never** accessed from the simulator, as seen from the simulator the `SummaryState` is a sealed container.

> The functions defining UDQs are valid using SI.

I do not fully understand what you mean here, but the way units go in the case of `UDQ` is as follows:

```
SCHEDULE
UDQ
    DEFINE MY_ORAT  FOPR * 0.25 /
    -- We assign a UNIT string to the 'MY_ORAT'; opm/flow will *only* use this string as output
    -- in the summary files, and will *not* take part in SI conversions.
    UNIT MY_ORAT 'SM3/DAY' /
/

WCONPROD
    .... 'MY_ORAT'  ... /
/
```
When initializing the `ProductionControls` structure we use this code:
```
    double eval_uda(const UDAValue& value, const SummaryState& st) {
        if (value.is<double>())
            return value.get<double>();

        double output_value = st.get(value.get<std::string>());
        return value.get_dim().convertRawToSi(output_value);
    }
```
from #774. The `UDAValue` has the necessary `Dimension` object embedded. The reason we needed the `UnitSystem` in the `Well2` object was not mainly due to the `UDA` mechanism, but rather that the `RATE` items in the `WCONINJE` keyword have a phase dependent dimension - i.e. different conversion should be applied to a water injector than for a gas injector. Currently that conversion is handled as this:
```
double rateToSI(double rawRate, WellInjector::TypeEnum wellType, const Opm::UnitSystem &unitSystem) {
        switch (wellType) {
        case WellInjector::MULTI:
            // multi-phase controlled injectors are a really funny
            // construct in Eclipse: the quantity controlled for is
            // not physically meaningful, i.e. Eclipse adds up
            // MCFT/day and STB/day.
            throw std::logic_error("There is no generic way to handle multi-phase injectors at this level!");

        case WellInjector::OIL:
        case WellInjector::WATER:
            return unitSystem.to_si( UnitSystem::measure::liquid_surface_rate, rawRate );

        case WellInjector::GAS:
            return unitSystem.to_si( UnitSystem::measure::gas_surface_rate, rawRate );

        default:
            throw std::logic_error("Unknown injector type");
}
```
but to be able to evaluate that during the simulation - with only a `Well2` instance as context, we need access to a `UnitSystem` instance.

Of course this - like everything else can be improved.

**Comment by joakim-hove** [comment]
> If I define a UDQ equal to some function of gas surface rate and use it to set an oil rate that would certainly be ugly in FIELD units...

The conversions applied to the UDQ values are done according to the dimension defined on the relevant item in the json config; as with all other unit conversion. It does *not* in any way infer dimensions from the string used to define the UDQ.

**Comment by atgeirr** [comment]
Thanks for your explanation, I was a bit confused about the purpose of this PR, but now I see it. I do not understand fully the implications of the UNIT part of a UDQ definition though.

> The conversions applied to the UDQ values are done according to the dimension defined on the relevant item in the json config; as with all other unit conversion. It does _not_ in any way infer dimensions from the string used to define the UDQ.

I assume this means that if a UDQ is used to set (for example) a gas rate, then it is converted to SI exactly as if it was a value from the deck. I.e. a UDQ used for keyword X, item Y, is assumed to have the unit given for keyword X, item Y in the json spec. If the same UDQ is used for item Z instead, which has a different unit (say surface oil rate vs surface gas rate in field units), we would we have inconsistent use of the UDQ, is that allowed to happen?

In the end, what is the UNIT specification used for?

**Comment by joakim-hove** [comment]
>I assume this means that if a UDQ is used to set (for example) a gas rate, then it is converted to SI exactly as if it was a value from the deck. I.e. a UDQ used for keyword X, item Y, is assumed to have the unit given for keyword X, item Y in the json spec.

yes

> If the same UDQ is used for item Z instead, which has a different unit (say surface oil rate vs surface gas rate in field units), we would we have inconsistent use of the UDQ, is that allowed to happen?

Yes - that is allowed to happen; you could even call it a feature.

> In the end, what is the UNIT specification used for?

**Only** to output the string to the summary output.

**Pull request merged**
