### PR TITLE
Add open well events for WCONHIST and WCONINJH

### PR DESCRIPTION
**Pull request by vkip**
Pair with https://github.com/OPM/opm-simulators/pull/5124.

### CODE REVIEW

**Comment by GitPaean** [comment]
The code for sure is doing its job in a correct way. It looks fine to me. 

The only thing I am concerned with is whether we can unify the ways adding the event `ScheduleEvents::REQUEST_OPEN_WELL` in the multiple occurrences. 

I would like to hear whether @bska has any comments regarding the new function `WellStatus HandlerContext::getWellStatus(const std::string& well) const`. 

Please mark the PR as ready for review and if it is easy for you to do, it is good to rebase and squash the commits to be one. But it is not so important from my side. @vkip

**Comment by vkip** [comment]
> Please mark the PR as ready for review and if it is easy for you to do, it is good to rebase and squash the commits to be one. But it is not so important from my side. @vkip

No problem, had a go at it now. Thanks!

**Comment by GitPaean** [comment]
jenkins build this opm-simulators=5124 please

**Comment by bska** [comment]
> I would like to hear whether @bska has any comments regarding the new function
> ```C++
> WellStatus HandlerContext::getWellStatus(const std::string& well) const
> ```

The function itself is fine&ndash;no notes.  It's not **completely** clear to me that we need it here, because in the context of handling `WCONHIST` and `WCONINJH` the call to [`HandlerContex::updateStatus()`](https://github.com/OPM/opm-common/blob/c0cb540aadbdbcc96772eafbbdea2d2fa6781d8b/src/opm/input/eclipse/Schedule/Well/WellKeywordHandlers.cpp#L96-L97) will "almost always" write the [keyword's status](https://github.com/OPM/opm-common/blob/c0cb540aadbdbcc96772eafbbdea2d2fa6781d8b/src/opm/input/eclipse/Schedule/Well/WellKeywordHandlers.cpp#L93) to each matching well given that [`Well::updateStatus()`](https://github.com/OPM/opm-common/blob/d63ec44775ccab11ca6d61d3adf51e7662e38fd3/src/opm/input/eclipse/Schedule/Well/Well.cpp#L811-L814) is unconditional.  The one [exception](https://github.com/OPM/opm-common/blob/d63ec44775ccab11ca6d61d3adf51e7662e38fd3/src/opm/input/eclipse/Schedule/Schedule.cpp#L711) is a closed well without any connections to the grid.  That well will remain closed.

**Comment by GitPaean** [comment]
> > I would like to hear whether @bska has any comments regarding the new function
> > ```c++
> > WellStatus HandlerContext::getWellStatus(const std::string& well) const
> > ```
> 
> The function itself is fine–no notes. It's not **completely** clear to me that we need it here, because in the context of handling `WCONHIST` and `WCONINJH` the call to [`HandlerContex::updateStatus()`](https://github.com/OPM/opm-common/blob/c0cb540aadbdbcc96772eafbbdea2d2fa6781d8b/src/opm/input/eclipse/Schedule/Well/WellKeywordHandlers.cpp#L96-L97) will "almost always" write the [keyword's status](https://github.com/OPM/opm-common/blob/c0cb540aadbdbcc96772eafbbdea2d2fa6781d8b/src/opm/input/eclipse/Schedule/Well/WellKeywordHandlers.cpp#L93) to each matching well given that [`Well::updateStatus()`](https://github.com/OPM/opm-common/blob/d63ec44775ccab11ca6d61d3adf51e7662e38fd3/src/opm/input/eclipse/Schedule/Well/Well.cpp#L811-L814) is unconditional. The one [exception](https://github.com/OPM/opm-common/blob/d63ec44775ccab11ca6d61d3adf51e7662e38fd3/src/opm/input/eclipse/Schedule/Schedule.cpp#L711) is a closed well without any connections to the grid. That well will remain closed.

Thanks for your comments.  That was also my concern.  We probably can do without it, but after some thinking, I think this might make the logic easier.  Basically if the `WCON*` keyword manage to make a well to be `OPEN`, we add the event.  We might make the other `WCON*` keyword the same manner.

**Review by GitPaean — APPROVED** [review]
Thanks, It looks good to me. I am getting the PR and its downstream PR in now.

**Pull request merged**
