### PR TITLE
Python: avoid searching from Development.Embed unless required

### PR DESCRIPTION
**Pull request by akva2**
The change to unconditionally search for Development broke the pypi builders. The reason is that the manylinux2014 docker images used to build does not contain the embedding headers.

Since this is more correct in general, I opted to fix it like this instead of hackery in the pypi builder.

Also remove outdated check for setuptools. No longer required, only used for the pypi builder and that checks this thoroughly on its own.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — COMMENTED** [review]
Completely tangential, but if we reverse the condition then we can write it as
```CMake
if (NOT OPM_ENABLE_EMBEDDED_PYTHON)
  find_package(Python3 REQUIRED COMPONENTS Interpreter Development.Module)
else()
  find_package(Python3 REQUIRED COMPONENTS Interpreter Development.Embed Development.Module)
  # ...
endif()
```
which has the (potential) benefit of bringing the two `find_package()` calls closer together.  That **might** make the difference stand out more.

**Comment by akva2** [comment]
fair enough.

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
good to go?

**Comment by bska** [comment]
> good to go?

Even if this is outside my domain of expertise, the change looks simple enough that I'm comfortable approving.  I'll merge into master.

**Pull request merged**
