### PR TITLE
Summary state update

### PR DESCRIPTION
**Pull request by joakim-hove**
This PR replaces `SummaryState::add()`with `SummaryState::update()`- the new `update()` function is aware of totals - i.e.  for
```
SummaryState::update("FOPT", 1000);
```
the field oil production will be shifted with a value of 1000. This a step in the direction of extracting the `SummaryState`instance totally out from the `Summary`object, and make sure the latter is stateless.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
Quick skimming looks good. I'll review this more thoroughly later today. Sadly our CI system isn't really accessible at the moment so we can't schedule new jobs.

**Comment by bska** [comment]
> Sadly our CI system isn't really accessible at the moment so we can't schedule new jobs.

The CI system is back online so I'll launch a new job.  I'll submit my review later today.

**Comment by bska** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
> What is the intended/expected use case for these functions? 

The `Summary` object currently has a scalar `double seconds` which keeps track of the number of seconds elapsed, the plan is to instead use the member in the `SummaryState` - then the `Summary` object can be stateless - and all change of state will be confined to the `SummaryState`object. This requires that the simulator manages the `SummaryState`object - which is the topic of this PR: https://github.com/OPM/opm-simulators/pull/1837

But you are correct - right now the `update_elapsed()` and `get_elapsed()`functions are not used.

**Comment by bska** [comment]
> the plan is [for the `Summary` class] instead use the [`elapsed`] member in the `SummaryState` [rather than its own]

I see&mdash;cool.  I'll merge this into master now.

**Comment by bska** [comment]
> I'll merge this into master now.

Hm, the post-commit build [failed](https://ci.opm-project.org/job/opm-common/455/) with an internal compiler error. I don't think it's related to this PR since the pre-commit CI build check got through but it's something we should look for in the nightly builds.

**Pull request merged**
