### PR TITLE
Schedule add rst argument

### PR DESCRIPTION
**Pull request by joakim-hove**
This PR adds an optional `const RstState *` to the `Schedule`constructor - to facilitate loading/initializing the `Schedule` object from restart information. The PR only has an api change - actually "doing something" is still on my machine.

Part of #1396

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
Just some basic questions:
 - Is it possible to create a Schedule from only restart info? I assume it's not? (If it is, there should be a constructor taking essentially only that.)
 - What kind of information *can* you get from restart info?
 - Could there be a conflict between info from restart and info from the deck? How do we handle that?

**Comment by joakim-hove** [comment]
>Is it possible to create a Schedule from only restart info? 

Right now the answer is no. I agree that creating a constructor taking only a `RstState` argument would be interesting - but mind you: That would result in `Schedule`object which only represented a snapshot of the situation *right at* the restart time - to actually get something interesting from this `Schedule` object you would have to add time steps and well controls by other means. This might very well be an interesting direction - but a large change.

> What kind of information (relevant for Schedule) can you get from restart info?

Wells and groups and stuff - the whole crux of the matter for this work is the situation where the historical schedule section has vanished from the earth - and we need to initialize well and group structures from the restart file.

> Could there be a conflict between info from restart and info from the deck? How do we handle that?

Ohh yes. If people update the input in the historical schedule section and then restart the updates will be ignored; for a restart the `Deck` keywords prior to the restart point will not be considered at all[*]. This is the way it is in our sibling simulator as well.


[*]: As usual there are some exceptions ...

**Comment by atgeirr** [comment]
Thanks for informative answers. The code looks fine, will merge.

I looks like we should try to reduce the number of constructors with not-too-different sets of parameters though. It is not clear what it the use-case for each one.

**Comment by joakim-hove** [comment]
> will merge.

Thanks!

**Pull request merged**
