### PR TITLE
fixing bug for python bindings ERst

### PR DESCRIPTION
**Pull request by tskille**
> bug related to occurence parameter in function get_erst_vector(..)
 > additional python unittest related to this function

### CODE REVIEW

**Comment by joakim-hove** [comment]
Yes it is possible with multiple argument to `__getitem__ / []`- but is it smart? I think the multiple arguments in this situation should be used for strongly related arguments, e.g. `i,j,k`. I think this should rather be a `get()` method with multiple optional arguments.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by tskille** [comment]
This PR if fixing a bug (1 single line in python/cxx/eclipse_io.cpp). In addition, I have added one extra python unit test for regression testing of this functionality.

Notice that multiple arguments are used  for __getitem__ and __contains__. If this should be replaced by  get(..) and  has(..) methods, I would prefer to do this in a separate PR.  

Hopefully this PR can be merge soon.

**Comment by joakim-hove** [comment]
> Hopefully this PR can be merge soon.

yes it can - I was a bit uncertain whether you intended to address the `__getitem__()` stuff. I'll merge.

**Pull request merged**
