### PR TITLE
Update of compareECL

### PR DESCRIPTION
**Pull request by tskille**
Added new classes EclFile, EGrid, ERft, ERst and ESmry for reading binary and formatted output files on Eclipse format. New class EclOutput for writing data (vectors) to files (formatted and binary).

### CODE REVIEW

**Comment by bska** [comment]
Wow!  That's a **massive** amount of work.  Thanks a lot for the contribution, both of you.  I look forward to getting this into master.

**Comment by joakim-hove** [comment]
This was an impressive piece of work - as Bård it is also quite massive and it will take some time to review, my initial impressions are:

1. Nice C++ - you are more or less guaranteed the a positive review when you use find `std::iota()`.
2. You seem to derive your classes from `EclFile` - I think it would be better to *use* an `EclFile` instance - i.e. the `EclGrid` constructor could look like:
```C++
EclGrid::EclGrid(const std::string& filename) {
     EclFile f(filename);
     this->coord = f.get<float>("COORD");
     this->zcorn = f.get<float>("ZCORN");
     if (f.hasKey("ACTNUM")) { .
     }
}
```
i.e. - no reason to hold an `EclFile`instance open for the lifetime of the grid.

3.  As a reviewer I would be very grateful if you could split the work in more managable sized pull requests; it *is* an overwhelming task try to review a pull request of several thousand lines in one go. This particular pull request contains changes to the existing `EclFile` class - and then many new classes based on that. In my opinion an ideal organisation of this would be one PR with changes to existing code, and then a series of separate PR's for each new class.

**Comment by joakim-hove** [comment]
Many of the commits have message like "cleanup ERFt" and "cleanup ESmry"; but this is *new* code for this particular PR - for the review process it would help if you did some git work so that new code came in one "all green" diff.

**Comment by joakim-hove** [comment]
It seems this PR directly affects the test binaries; I would *really* if that could split in a separate PR which can be merged after the eclipse utilities have been merged.

**Comment by akva2** [comment]
merged through separate pr's. thanks for the fish!

**Pull request closed without merging**
