### PR TITLE
Summary years

### PR DESCRIPTION
**Pull request by joakim-hove**
Unconditionally add  'YEARS` to the summary files. Will require a data update.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=298 please

**Comment by bska** [comment]
> jenkins build this opm-tests=298 please

We're still getting a single [test failure](https://ci.opm-project.org/job/opm-common-PR-builder/1954/testReport/(root)/mpi/compareECLFiles_flow_NNC_AND_EDITNNC/).  Does `update_data` not account for RSM files or does the RSM file not (currently) account for the `YEARS` data?

```
Checking 8  vectors  ...  done.
Program threw an exception: [/var/lib/jenkins/workspace/opm-common-PR-builder/test_util/EclRegressionTest.cpp:986] The RSM file did not compare equal to the summary file
Comparing '/var/lib/jenkins/workspace/opm-common-PR-builder/deps/opm-tests/editnnc/opm-simulation-reference/flow/NNC_AND_EDITNNC' to '/var/lib/jenkins/workspace/opm-common-PR-builder/mpi/build-opm-simulators/tests/results/flow+nnc/NNC_AND_EDITNNC'.
```

**Comment by joakim-hove** [comment]
> We're still getting a single test failure. Does update_data not account for RSM files or does the RSM file not (currently) account for the YEARS data?

update_data does not account for RSM files; if a RSM file is generated (pure filesystem check) it is compared with the summary case. Will investigate why this PR fails.

**Comment by joakim-hove** [comment]
The precision in the RSM files was not sufficient for the YEARS vector - had to loosen.

**Comment by joakim-hove** [comment]
jenkins build this opm-tests=298 please

**Comment by joakim-hove** [comment]
jenkins build this opm-tests=298 please

**Comment by joakim-hove** [comment]
@atgeirr : Can this be merged when it is green - or should I wait for:  OPM/opm-simulators#2553?

**Comment by atgeirr** [comment]
> Can this be merged when it is green - or should I wait for: [OPM/opm-simulators#2553](https://github.com/OPM/opm-simulators/pull/2553)?

Since that PR is red and therefore not yet mergable, I'd say this should go in if green.

**Pull request merged**
