### PR TITLE
Add Unit Tests for EQUALREG on MULTY

### PR DESCRIPTION
**Pull request by bska**
Mostly to ensure that our current `EQUALREG` implementation continues to work in the future.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by blattms** [comment]
Would you please add a check for global MULTZ that just checks the active entries, too.
Also, please  check the default value of item 4, which is M, by omitting it's specification in one of the tests.

**Comment by bska** [comment]
> Would you please add a check for global MULTZ that just checks the active entries, too.

I've pushed an update that adds a couple of such checks.

> Also, please check the default value of item 4, which is M, by omitting it's specification in one of the tests.

Unfortunately, our implementation does not behave that way.  If the region set (item 4) is omitted, then we implement the behaviour outlined in a [comment](https://github.com/OPM/opm-common/blob/4b60b7b97228d1217d254775b030baf464d306e7/opm/input/eclipse/EclipseState/Grid/FieldProps.cpp#L230) in `FieldProps.cpp`.  Other than a change to `//`-style comments, this text is unaltered since it was first added in commit a7187abc17 (PR #1056).  To me this behaviour seems very nonintuitive, but I'm not going to change it right now.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Review by akva2 — APPROVED** [review]
Moar tests

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
PR approved and build check is green.  I'll merge into master.

**Comment by blattms** [comment]
> Unfortunately, our implementation does not behave that way. If the region set (item 4) is omitted, then we implement the behaviour outlined in a [comment](https://github.com/OPM/opm-common/blob/4b60b7b97228d1217d254775b030baf464d306e7/opm/input/eclipse/EclipseState/Grid/FieldProps.cpp#L230) in `FieldProps.cpp`. Other than a change to `//`-style comments, this text is unaltered since it was first added in commit [a7187ab](https://github.com/OPM/opm-common/commit/a7187abc177367f14e1a2f2f4f18fe02124a063a) (PR #1056). To me this behaviour seems very nonintuitive, but I'm not going to change it right now.

Thanks a lot for digging that up. We shoulc check whether this is documented in the manual and add if it is not. Pinging @gdfldm

**Comment by gdfldm** [comment]
How about this [opm-reference-manual#401](https://github.com/OPM/opm-reference-manual/pull/401).

**Pull request merged**
