### PR TITLE
Use regression test data from opm-tests, not opm-data

### PR DESCRIPTION
**Pull request by akva2**
opm-data today serves multiple purposes, more than originally intended.
this splits out the regression test part to a separate repository. in particular this will allow to make modified versions of datasets more suitable for testing (less timesteps etc).

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-tests=2 opm-simulators=1436 please

**Comment by akva2** [comment]
jenkins build this opm-tests=2 opm-simulators=1436 please

**Comment by akva2** [comment]
jenkins build this opm-tests=2 opm-simulators=1436 please

**Comment by akva2** [comment]
jenkins build this opm-tests=2 opm-simulators=1436 please

**Comment by akva2** [comment]
jenkins build this opm-tests=2 opm-simulators=1436 please

**Comment by akva2** [comment]
jenkins build this opm-tests=2 opm-simulators=1436 please

**Comment by atgeirr** [comment]
Superficially, it looks ok to me, I guess the only way to be sure is through jenkins. The first real test will be when executing the update_data part for the first time.

**Comment by akva2** [comment]
it was green, trivial rebase due to #351.

**Comment by akva2** [comment]
update data will take some action from the admins, namely giving jenkins4opm the necessary rights in opm-tests.

**Comment by akva2** [comment]
jenkins build this opm-tests=2 opm-simulators=1436 please

**Comment by alfbr** [comment]
@atgeirr , will you handle this one?

**Comment by atgeirr** [comment]
> @atgeirr , will you handle this one?

If all is ready, sure!

**Comment by atgeirr** [comment]
jenkins build this opm-tests=2 opm-simulators=1436 please

**Comment by atgeirr** [comment]
jenkins build this opm-tests=2 opm-simulators=1436 please

**Comment by akva2** [comment]
jenkins build this opm-tests=2 opm-simulators=1436 please

**Comment by akva2** [comment]
jenkins build this opm-tests=2 opm-simulators=1436 please

**Comment by akva2** [comment]
i'm going to merge this. it will take some adjustments to get update_data to work again.

**Pull request merged**
