### PR TITLE
Sunbeam import

### PR DESCRIPTION
**Pull request by joakim-hove**
The `sunbeam` python package was created in equinor to create a Python package for working with Eclipse input files. At the time the ambition was to create a good *Pythonic* package - the fact it was based on the opm-common C++ was an "implementation detail", and the ambition was to have a loose coupling with a well defined interface between the opm-common C++ code and the Python layer in sunbeam. This has not worked out so well in practice, mainly because opm-common does not provide any notion of version stability[1], and furthermore the resources alloted to the project have been limited. In opm there is an ambition of creating python wrappers, to enable that I see it as essential to have a tighter integration between the C++ code and the Python code, and for that reason I have created this PR which will import the sunbeam repository wholesale into the opm-common repository. This "fork" is done in agreement with the equinor team.

When this PR is merged it just comes in as a new subdirectory `python/` - the code is *not* integrated in the build process in any way, that will be subject of upcoming PR's. The Python wrapper approach used in sunbeam is based on the `pybind11` package, the use of `pybind11` has been "comfortable" - and I see it a natural to continue to use that, but other aspects of the Python binding is certainly up for discussion, although I do consider the current sunbeam implementation a good start.

I will let this linger here for some time, and then merge it in a couple of days.

[1]: For use and development in the flow pipeline it is of course convenient that we do not limit ourselves when it comes to API changes, but for external projects like sunbeam it becomes difficult. This is another discussion though.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
This looks rather...large? What is the intention here?

**Comment by joakim-hove** [comment]
> This looks rather...large? What is the intention here?

I'll write more later - but basically this PR is just an unmodified import of: https://github.com/equinor/sunbeam into a `python/` subfolder.

**Comment by alfbr** [comment]
> This looks rather...large? What is the intention here?

There has been a long lasting wish for Python wrappers for OPM from several parties. Sunbeam was a good start, but only caters to the parser part. Hence, I hope it can serve as a starting point for more comprehensive Python support in OPM. Right now we have a clear need, and that is the PYACTION functionality that was presented at the OPM summit. Just my birds perspective, I am sure @joakim-hove has a much better overview.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
OK - I'll merge this now, actually merging it in the build system will be the topic of future pull requests.

**Pull request merged**
