### PR TITLE
Avoid python dep

### PR DESCRIPTION
**Pull request by joakim-hove**
When building the Python wrappers was turned ON one python related file was incorrectly compiled into the main library, leading to a dependency from libopmcommon to libpython. This should fix that.

### CODE REVIEW

**Comment by joakim-hove** [comment]
@hakonhagland : I suggest this as an alternative to your: https://github.com/OPM/opm-common/pull/2838 - cool if you try it out.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by hakonhagland** [comment]
> I suggest this as an alternative to your: #2838 - cool if you try it out.

@joakim-hove Yes this works fine!

**Comment by joakim-hove** [comment]
> Yes this works fine!

Thank you for testing - then I will merge this and close #2838

**Pull request merged**
