### PR TITLE
Add solid salt density as input

### PR DESCRIPTION
**Pull request by goncalvesmachadoc**

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by goncalvesmachadoc** [comment]
jenkins build this please

**Comment by bska** [comment]
@goncalvesmachadoc : Is there more work incoming here or is this PR ready for review/merging?

**Comment by goncalvesmachadoc** [comment]
Yes, this is ready for review/merging. It goes together with https://github.com/OPM/opm-models/pull/745 , https://github.com/OPM/opm-tests/pull/832 and https://github.com/OPM/opm-tests/pull/743

**Comment by goncalvesmachadoc** [comment]
jenkins build this opm-models=745 please

**Comment by goncalvesmachadoc** [comment]
Everything passes, except the cases we expected to fail due to now missing the input for salt density.

**Comment by bska** [comment]
> Everything passes, except the cases we expected to fail due to now missing the input for salt density.

Am I to understand that this means that unless we merge both OPM/opm-tests#745 and OPM/opm-tests#832, this PR (and the companion PR OPM/opm-models#745) won't run?  If so, does merging those the PRs in OPM-Tests create other problems?  If so, do we have to accept a (small) time window in which there are a couple of regression tests that will fail?

**Comment by goncalvesmachadoc** [comment]
I don't expect the PR's in OPM-tests to create any problems. flow runs the same when adding the salt density value as input in the cases (it seems just to ignore it).

**Comment by bska** [comment]
> I don't expect the PR's in OPM-tests to create any problems. flow runs the same when adding the salt density value as input in the cases (it seems just to ignore it).

Ah right, because `SALTSOL` is [`size_type: "ALL"`](https://github.com/OPM/opm-common/blob/c7dc6de3b3b5b6d67cc8c12159e0a0e1eb067f62/src/opm/input/eclipse/share/keywords/900_OPM/S/SALTSOL#L14) and we're adding it as a "simple table".  Yeah, in that case the extra data items don't matter and merging the OPM-Tests PRs should be benign.  I've started a build check just to be sure, but if that comes back clean I'll merge them.

**Comment by bska** [comment]
jenkins build this opm-models=745 please

**Comment by bska** [comment]
Hi @goncalvesmachadoc: The build check fails on [`SPE1CASE1_PRECSALT`](https://ci.opm-project.org/job/opm-common-PR-builder/5202/testReport/junit/(root)/mpi/compareECLFiles_flow_SPE1CASE1_PRECSALT/) with this change after we've applied the changes in OPM/opm-tests#743.  Is that failure expected?

**Comment by goncalvesmachadoc** [comment]
I think the failure is due to this model being in field, and we had a hard-coded value in SI before. The other cases in metric passed.  It's a small difference in the pressure in the regression test. I hope this fix it: https://github.com/OPM/opm-tests/pull/858/files

**Comment by bska** [comment]
jenkins build this opm-models=745 opm-tests=858 please

**Comment by bska** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks a lot for your patience, @goncalvesmachadoc!  The build check is green and this brings a very welcome feature.  I'll merge this into the master branch now.

**Pull request merged**
