### PR TITLE
Rename group production control mode variable

### PR DESCRIPTION
**Pull request by joakim-hove**
Small preparations to facilitate restart; bith the active group control and the group control requested in the deck should be in the restart file.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
Will this not the presence of active_mode change the semantics of the Group class in a significant way? Before: Group represents the information in the Schedule only. Now: Group also contains dynamic information that must be found by simulation (or restart), i.e. information must start flowing back into the Group objects?

**Comment by joakim-hove** [comment]
> Will this not the presence of active_mode change the semantics of the Group class in a significant way?

I understand your point; no the intention was not such a large scale change. This change is only motivated to support restart; the restart file contains both the deck requested control mode and the currently active control mode. This is to ensure that when the simulation starts after a restart and the simulator ask for the control mode we should return the control mode which was active at the time of simulation.

Does this sound feasible to you? Maybe better naming - or heaven forbid - comments, could clarify the intent?

**Comment by atgeirr** [comment]
> Does this sound feasible to you? Maybe better naming - or heaven forbid - comments, could clarify the intent?

I think the current control belongs in a state variable, not the Group object. How is this done now for well controls? I think that would be an equivalent situation.

**Comment by joakim-hove** [comment]
> I think the current control belongs in a state variable, not the Group object.

Well - when we are restarting there is no state variable; when restarting the initial current control is loaded from the restart file - and that is passed to the state variable when it asks.

> How is this done now for well controls? I think that would be an equivalent situation.

Also for well controls this is done in the same way - but that is currently only in my branch.

**Comment by atgeirr** [comment]
After discussions I agree this is an ok solution. An ideal solution would read the "current control" state in the opm-simulators code where the rest of the state is read from restart, but we do not need to go there immediately.

Merging!

**Pull request merged**
