### PR TITLE
Make use of system includes for cross-module optional.

### PR DESCRIPTION
**Pull request by atgeirr**
This makes the new behaviour of #202 optional, restoring old behaviour as default.

### CODE REVIEW

**Comment by blattms** [comment]
Works for me.
Closes #209

**Comment by blattms** [comment]
@atgeir I still wonder why you do not see the problems. I my case there a lot of includes missing. Do youn install all modules?

**Comment by atgeirr** [comment]
> Works for me.

Good, I'll merge this when green then, unless objections are raised. @GitPaean and @bska, could you also check if this fixes the problems you observed (in @GitPaean's case it was not clear that is was related to #202 though).

**Comment by atgeirr** [comment]
> I my case there a lot of includes missing. Do youn install all modules?

No, the only thing I install is ert.

**Comment by bska** [comment]
jenkins build this with downstreams please

**Comment by atgeirr** [comment]
No problems with this raised, merging.

**Comment by atgeirr** [comment]
@bska sorry, did not see that you started Jenkins (apparently it can take a few minutes for the page to update itself)

If there are further changes needed I guess I'll make a new PR.

**Comment by bska** [comment]
I'm not entirely happy about this situation.  While this patch (and the new option in its default state of `OFF`) does restore my ability to build [opm-flowdiagnostics](https://github.com/OPM/opm-flowdiagnostics) without any local changes, it nevertheless feels a bit like a hack or papering over the issue.  I'd like to get to the bottom of this and understand what's actually going on.

**Pull request merged**
