### PR TITLE
Replace all tabs with two whitespaces.

### PR DESCRIPTION
**Pull request by dr-robertk**
This PR removes all tabs from all .cmake files in opm-common to have a consistent situation. 
If this is of interest I suggest to merge this after the release.

### CODE REVIEW

**Comment by atgeirr** [comment]
Yay! Why wait until after the release?

Also: for C++ code we are usually using 4 spaces. Any particular reason for 2 spaces (I assume this is an easily changeable detail and that you wrote a small script to do this)?

**Comment by dr-robertk** [comment]
It's a one line command:
find . -name "*.cmake" -exec vim -c "set tabstop=2 shiftwidth=2 expandtab|retab|wq" {} \;

Can emacs do the same ;-)?

Please adjust the width yourself if you think it should be 4. I chose 2 because, as you can see from the diff, that is the tabbing used in some of the areas. So choosing 2 everything looks nice and clean.

**Comment by dr-robertk** [comment]
PS: I would wait until after the release because no a lot of files are changed, and maybe, something went wrong. That is hard to see in the PR from my point of view. But i might be ok. It's just a risk, a very small one though.

**Comment by atgeirr** [comment]
> Can emacs do the same ;-)?

Probably, with a fair bit of lisp (that I don't know)...

> Please adjust the width yourself if you think it should be 4. I chose 2 because, as you can see from the diff, that is the tabbing used in some of the areas. So choosing 2 everything looks nice and clean.

A fair argument, although I tend to not be able to follow code nesting very well with only 2 spaces. Since I don't really know CMake very well and therefore do not review build-system things much I'll leave this decision (#spaces for indenting in CMake) to other people such as @akva2, @joakim-hove and @andlaus.

> I would wait until after the release because now a lot of files are changed, and maybe, something went wrong

I would not merge it unless I did a successful clean build at least. Jenkins would also find problems I think?

**Comment by andlaus** [comment]
> Can emacs do the same ;-)?

yes, it seems to be slightly more complicated (and general), though: http://stackoverflow.com/questions/6395898/emacs-how-do-i-replace-regexp-with-a-lisp-function-in-a-defun

using `sed` for stuff like this is quite a bit simpler than either vi or emacs, though:

```bash
find -name "*.cmake" -print0 | xargs -0 sed -i "s/\t/  /g"
```

**Comment by atgeirr** [comment]
jenkins build this with downstream please

**Comment by akva2** [comment]
i guess i really have to make that re more tolerant to you guys and your lack of attention to details ;)

**Comment by atgeirr** [comment]
> lack of attention to details

It's "downstreams" right? I could not find it in the doc here:

http://wiki.opm-project.org/index.php?title=Jenkins_triggers

Would you mind checking that page and adding any missing parts?

**Comment by atgeirr** [comment]
jenkins build this with downstreams please

**Comment by akva2** [comment]
yes, it's downstreams ref https://github.com/OPM/opm-parser/pull/942 that triggered my comment - twice in a day and all that :)

**Comment by pgdr** [comment]
> Can emacs do the same ;-)?

Of course, but emacs users recognize scenarios where `sed` is more suited, e.g., scenarios where you essentially want to do search and replace on a bunch of files.

**Comment by atgeirr** [comment]
I agree now, we should not do this for the release. Will merge shortly afterwards though.

**Comment by pgdr** [comment]
@dr-robertk perhaps it time to rerun your command and update the PR?

**Comment by joakim-hove** [comment]
This has gone quite stale; closing.

**Pull request closed without merging**
