### PR TITLE
ert->ecl

### PR DESCRIPTION
**Pull request by jokva**
The libecl module is identified as `ecl`, not `ERT`.

### CODE REVIEW

**Comment by andlaus** [comment]
while I don't mind this in principle, I don't like the idea of calling this "ecl" because sombody may think this is a whole simulator. libecl is better and libeclio would be best (IMO)

**Comment by atgeirr** [comment]
I agree that libecl would be a more precise name, which perhaps we should have used all along (as it never was the whole of ert we needed anyway).

**Comment by pgdr** [comment]
@andlaus ask anyone what they think `ecl` is and count the number of people who believe it's a simulator.  Adding `io` certainly doesn't do anything good.  Yes, it reads files, but you wouldn't call flow/ebos `flowio` just because it's able to read a file from disk.

@atgeirr no, `libxxx` is not really adding anything.  We should perhaps also suggest that `numpy` rename their modules to `libnumpy` while we're at it, and `tensorflow` should be `libtensorflowio`.

`ecl` is a pretty good name.

**Comment by atgeirr** [comment]
> @atgeirr no, libxxx is not really adding anything. We should perhaps also suggest that numpy rename their modules to libnumpy while we're at it, and tensorflow should be libtensorflowio.

I disagree, the library is named libecl, not ecl: https://github.com/Statoil/libecl

**Comment by jokva** [comment]
If that's the case, why does opm-simulators output `flow` and not `opm-simulatorsio`?

**Comment by pgdr** [comment]
> I disagree, the library is named libecl, not ecl: https://github.com/Statoil/libecl

@atgeirr Are you trying to logically deduce the name of `ecl` despite the lead developers telling you it's actually called `ecl`?

**Comment by atgeirr** [comment]
> @atgeirr Are you trying to logically deduce the name of ecl despite the lead developers telling you it's actually called ecl?

Well, it seems logical to me that the name of a package is the same as the name on github. If that is not so, perhaps you should rename it to "ecl" there? I just want things to be consistent.

**Comment by pgdr** [comment]
@atgeirr My apologies for not replying earlier, I understand that you got confused.  We should consider renaming the repository to `ecl`, perhaps you can create an issue there?

**Comment by atgeirr** [comment]
> perhaps you can create an issue there?

Done!

**Pull request closed without merging**
