### PR TITLE
Use pyaction

### PR DESCRIPTION
**Pull request by joakim-hove**
Expose basic functionality for calling python code in the Schedule section.

Right now it is not hooked up in the main simulator - only in a test. The technical bit and pieces of this now works; the most important open question - in my head at least - is how we should configure/determine *when* the `PYACTION` code should run. The `ACTIONX` has a well defined configuration for this which we can choose to copy, but personally I do not think that is optimal.

**ACTIONX:**

First of all it should be noted that the `ACTIONX` keyword is actually mainly a *condition*, the actual *action* is  a list of normal `SCHEDULE` section keywords - i.e.

```
-- Define the condition:
ACTIONX
    <NAME>   <TRIGGER_COUNT=1>   <TRIGGER_WAIT>  /
    'WWCT'  'OP1' > 0.80 /
/

WELOPEN
     'OP1'  'SHUT' /
/
ENDACTIO
```

When this action/condition has been defined it is tested at the end of every consecutive timestep; when the condition evaluates to true the keywords before the `ENDACTIO` keyword are executed - i.e. the well `OP1` is closed in this case. By default the condition will not be checked again when it has evaluated to true, but the trigger_count item in the ACTIONX definition can be used to configure that the condition should be tested repeatedly.

**PYACTION**
For the `PYACTION` we can determine this behavior just like we want. Some questions to consider:

1. Should we retain the structure with condition - and then the action as a list of normal keywords? I would strongly say no - and argue that condition and resulting action should be integrated in one go. The `ACTIONX` functionality above is implemented in this PR as:

```
PYACTION
if context.sim.well_var("OP1", "WWCT") > 0.80:
      context.schedule.shut_well( "OP1", context.report_step )
```

2. Should we have the same "check at the end of every timestep" semantics, or should we explicitly ask for the action to be tested when we want it to be tested - or both?

3. Should we have the same behavior with respect to multiple invocations?

Right now there is only keyword `PYACTION` which defines the actual code - with no metadata. My preferred way forward forward is to define one keyword e.g. `PYCODE` which can load Python code - optionally from a file, and then another keyword which configures how that code should be invoked. These remaining questions are not particularly difficult from a technical point of view, but I guess they are important to get right for the end-user experience. Opinions very welcome.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by OPMUSER** [comment]
Okay I'll bite.

Use ENDPY to terminate a PY code block and use the INCLUDE keyword to load a file containing Python statements. So one can also just load an include that contains the PYACTION and ENDPY keywords. I don't see the need for PYCODE as PYACTION should do this.

**Comment by OPMUSER** [comment]
Okay I'll bite.

Use ENDPY to terminate a PY code block and use the INCLUDE keyword to load a file containing Python statements. So one can also just load an include file that contains the PYACTION and ENDPY keyword and the Python code in between the two. I don't see the need for PYCODE as PYACTION should do this.

1. I don't have a problem with this, as it will give potentially much more functionality; however, if you go this route then there has to be documentation on how to access variables, because only the developers and  "The Shadow"  know how to access the various variables. If you go the keyword route then we already have the documentation. I don't like the ACTIONX syntax at all as it very cumbersome for implementing multiple conditions, which should be a lot easier using Python.
2. Both. Can we have a statement like` if DATE > 2020-01-01 and  GRAT < 10E3`, do something? 
3. Yes, common occurrence is to  shut-in wells/completions and open wells/completions using wells declared as a well list (`WLIST`).
4. Could the number of times to execute the test be set via a keyword within the PYACTION/ENDPY set? For example PYTSTEP set 0 (stop), 1, 2,.......ect. and ALL. This should be the first keyword after a the PYACTION keyword.
5. Is it possible to include multiple PYACTION/ENDPY sets within, say, one include file? I have a preference to have everything in the one place to avoid errors and to include them at the beginning of the SCHEDULE section to trap errors at the beginning of the run. This would mean having a name variable on the PYACTION keyword or a separate PYNAME keyword for each PYACTION/ENDPY set.
6. Will it possible to set up SUMMARY variables. So for example, I want to calculate the LPG and the Net Sales Gas from the wellhead gas, and store the results (with units) as a SUMMARY variable? So we and duplicate the UDQ/UDQPARAM functionality as well?

So taking your example and the comments above, we have:

```
PYACTION WCUT
  PYTSEP ALL
  if context.sim.well_var("OP*", "WWCT") > 0.80:
        context.schedule.shut_well( "OP*", context.report_step )
ENDPY
PYACTION GOR
  PYTSEP ALL
  if context.sim.well_var("OP*", "WGOR") > 5E3:
        context.schedule.shut_well( "OP*", context.report_step )
ENDPY
```

or

```
PYACTION WELL
  PYTSEP ALL
  if context.sim.well_var("OP*", "WWCT") > 0.80:
        context.schedule.shut_well( "OP*", context.report_step )
  if context.sim.well_var("OP*", "WGOR") > 5E3:
        context.schedule.shut_well( "OP*", context.report_step )
ENDPY
```

Now you are sorry you asked for comments ;-)

**Comment by joakim-hove** [comment]
> if you go this route then there has to be documentation on how to access variables,

Obviously - even I concede to that.

**Comment by joakim-hove** [comment]
> Can we have a statement like if DATE > 2020-01-01 and GRAT < 10E3, do something?

Conditions like this should in my opinion be part of the Python code; i.e. 
```
PYACTION
...
if context.sim_time > datetime.date(2020, 01, 01) and context.sim["GRAT:G2"] > 1000:
      ...
```
this will work - when I have added `sim_time` to the `context`.

**Comment by joakim-hove** [comment]
> Will it possible to set up SUMMARY variables. So for example, I want to calculate the LPG and the Net Sales Gas from the wellhead gas, and store the results (with units) as a SUMMARY variable

To some extent. You can calculate the SUMMARY variable and assign to it from Python; you can not define an entirely new summary variable - i.e. the variable must already have been defined in the `SUMMARY` section of the input deck.

**Comment by joakim-hove** [comment]
> Is it possible to include multiple PYACTION/ENDPY sets within, say, one include file?

The normal `INCLUDE` functionality works normally - i.e. you can include a a file which contains `PYACTION`keywords. But in addition it might be benefical to put 100% pure Python code in a separate file and point to that in the PYACTION keyword. The first record of PYACTION could contain the name of the action, and optionally  the name of a file implementing the keyword:

**PYACTION with external code**
```
PYACTION
    WCUT  'filename/with/python/code/well.py' /
ENDPY
```

**PYACTION with inlined code**
```
PYACTION
    WCUT  /
if context.sim.well_var("OP1", "WWCT")> 0.80:
      context.schedule.shut_well("OP1")
ENDPY
```

For the number of runs+++ the action itself could store the number of times it has run, and the last time it was run (this does not work yet - but should be quite simple to implement).
```
...
if context.run_count < 10:
     # Do your stuff
```

**Comment by joakim-hove** [comment]
> I have a preference to have everything in the one place to avoid errors and to include them at the beginning of the SCHEDULE section to trap errors at the beginning of the run.

That I fully agree; thou it should be said that most errors will not be exposed before actual use, irrespective of where the `PYACTION`keyword is located.

> > Should we have the same "check at the end of every timestep" semantics, or should we explicitly ask for the action to be tested when we want it to be tested - or both?

> Both. [...]

I guess this is the question where I am most at a loss. One thing I have thought of is that in addition to `PYACTION` which actually defines the keyword we could have another keyword which says "Run this keyword now", or "Start running this keyword now":

```
PYACTION
    WCUT 'path/to/action.py' /
ENDPY


DATES 
/    

DATES
/

DATES
/

-- Run the PYACTION 'WCUT" once here.
PYRUN
     WCUT /

DATES

-- Start the PYACTION running at the end of every timestep - from here.
PYRUN
    WCUT START /

DATES

-- Stop the PYACTION 
PYRUN
    WCUT STOP /
```

**Comment by joakim-hove** [comment]
> Now you are sorry you asked for comments ;-)

On the contrary - thank you for the response!

**Comment by OPMUSER** [comment]
> Conditions like this should in my opinion be part of the Python code; i.e.
> 
> PYACTION
> ...
> if context.sim_time > datetime.date(2020, 01, 01) and context.sim["GRAT:G2"] > 1000:
>       ...
> 
> this will work - when I have added sim_time to the context.

Fully agree.

**Comment by OPMUSER** [comment]
> PYACTION
>     WCUT 'path/to/action.py' /
> ENDPY
> 

Don't like this mixing OPM Flow and Python syntax in the deck. In the deck have
 ```
INCLUDE
 'path/to/action.py' 
/
```
And in the include file have
```
PYACTION
    def WCUT ()
..........
ENDPY
```
or in the deck invoke the script directly via: 
```
PYACTION
    def WCUT ()
..........
ENDPY
```
So if you are in the deck only use the keywords and if you are in a PYACTION/ENDPY set only allow Python comments. Don't mix and match, it will very hard to debug.

Ideally we would like to check the Python script syntax using the interpreter when we invoke NOSIM.

**Comment by OPMUSER** [comment]
> For the number of runs+++ the action itself could store the number of times it has run, and the last time it was run (this does not work yet - but should be quite simple to implement).
> if context.run_count < 10:
>      # Do your stuff
> 
That's a lot better than what I suggested, so great.

**Comment by OPMUSER** [comment]
> To some extent. You can calculate the SUMMARY variable and assign to it from Python; you can not define an entirely new summary variable - i.e. the variable must already have been defined in the SUMMARY section of the input deck.

Can you check in NOSIM mode, that the SUMMARY variable request is available, and if not STOP with an error message

**Comment by OPMUSER** [comment]
> I guess this is the question where I am most at a loss. One thing I have thought of is that in addition to PYACTION which actually defines the keyword we could have another keyword which says "Run this keyword now", or "Start running this keyword now":

No need for this as we can use:

`if context.sim_time > datetime.date(2020, 01, 01)`

instead. Try to keep things simple.

**Comment by joakim-hove** [comment]
> Don't like this mixing OPM Flow and Python syntax in the deck. In the deck have

I think we roughly agree on the goal here, but maybe not 100% on how that goal should be accomplished/interpreted. What I I would like was the possibility to point to a python file from the deck - as:

```
PYACTION
    WCUT  'path/to/action.py' /
```

where the file `action.py` is 100% pure an clean Python - to the extent that it can be tested and in principle even run - outside of flow. That means that it should *not* even have `PYACTION` or `ENDPY` markers. But this a bit into the future - so we can fight it for a while before we need to conclude.

**Comment by joakim-hove** [comment]
> Ideally we would like to check the Python script syntax using the interpreter when we invoke NOSIM.

yes I agree - we are not there yet, but that a pure syntax check should be within striking distance. However there will still be significant room for errors/bug which are not syntax errors, but will still fail the script - those will be harder to check up front I think.

**Comment by OPMUSER** [comment]
> I guess this is the question where I am most at a loss. One thing I have thought of is that in addition to PYACTION which actually defines the keyword we could have another keyword which says "Run this keyword now", or "Start running this keyword now":

No need for this as we can use:

`if context.sim_time > datetime.date(2020, 01, 01)`

instead. Try to keep things simple.

**Comment by OPMUSER** [comment]
> I think we roughly agree on the goal here, but maybe not 100% on how that goal should be accomplished/interpreted. What I I would like was the possibility to point to a python file from the deck - as:
> 
> PYACTION
>     WCUT  'path/to/action.py' /
> 
> where the file action.py is 100% pure an clean Python - to the extent that it can be tested and in principle even run - outside of flow. That means that it should not even have PYACTION or ENDPY markers. But this a bit into the future - so we can fight it for a while before we need to conclude.

Still don't like this at all, if you want to just have pure Python script as input why not:
```
PYACTION
     def WCUT()  
INCLUDE
    'path/to/action.py' 
/
PYEND
```
So the only valid keyword in a PYACTION/PYEND block is the INCLUDE keyword.

I also don't like the block name syntax as it will cause confusion with just a name, that is why I'm suggesting we use `def NAME()` because it looks more like Python, and clearly defines the intent of this part of the script.

**Comment by joakim-hove** [comment]
> Still don't like this at all, [...]

This was not entirely simple ..... In addition to the aesthetics we are discussing now there are also some technical constraints:

1. The text must be parsed and internalized by the existing deck file parser - which is written to handle a quite specific input format.
2. Python itself has  quite specif requirements for textual structure - we must extract the Python code from the deck *exactly* - with spaces and all.

 > I also don't like the block name syntax as it will cause confusion with just a name, that is why I'm suggesting we use def NAME() because it looks more like Python, and clearly defines the intent of this part of the script.

Well here I think you misunderstand - if we start with my suggested form:
```
PYACTION
     wcut /
if context.sim.well_var("OP", "WWCT") > 0.80
     context.schedule.shut_well("OP")
PYEND
```
then the record `wcut /` is *not* Python - that is string parsed in flow context and the resulting name `wcut` is used by the flow C++ - code, not Python - so to me `def WCUT()` is really confusing - because this string is not part of the Python code. 

It is good with discussions and opinions on the topic, but we do not have to conclude right away - good if someone else want's to chime in. In addition to the technical constraints listed above there is one functional requirement which is currently not satisfied:

- It must be possible to *name* the Python action in some way, the name is required for the C++ management layer and will be used there. The name will not be used from Python. 

In the current master branch the PYACTION keyword does not allow a name, it goes directly from the `PYACTION` keyword header to Python code:

```
-- Current master:
PYACTION
if context.sim.well_var("OP", "WWCT") > 0.80
     context.schedule.shut_well("OP")
PYEND   
```
and the ability to add a name is the motivation for #1399. 

Observe that this discussion is attached to a PR which only points in the direction of syntax changes, merging this PR will have no consequences whatsoever when it comes to the syntax of the `PYACTION` keyword. PR #1399 has some *preparations* to allow for a record with name before the actual code starts, but also that can be merged without any consequences for the `PYACTION` input syntax.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Pull request merged**
