### PR TITLE
Fix typo - and test the automatic deployment to opm-python-documentat…

### PR DESCRIPTION
**Pull request by lisajulia**
…ion with this

### CODE REVIEW

**Comment by lisajulia** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
I see this:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   151  100   109  100    42   1131    435 --:--:-- --:--:-- --:--:--  1572
{
  "message": "Bad credentials",
  "documentation_url": "https://docs.github.com/rest",
  "status": "401"
}
```
in the "Send dispatch..." section of the first check, yet it is classified as "Successful in 4s", does that make sense? Is it a false negative?

**Comment by lisajulia** [comment]
> I see this:
> 
> ```
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100   151  100   109  100    42   1131    435 --:--:-- --:--:-- --:--:--  1572
> {
>   "message": "Bad credentials",
>   "documentation_url": "https://docs.github.com/rest",
>   "status": "401"
> }
> ```
> 
> in the "Send dispatch..." section of the first check, yet it is classified as "Successful in 4s", does that make sense? Is it a false negative?

Yes, and bad credentials seems like there is something wrong with the token we just added..

**Comment by lisajulia** [comment]
@atgeirr: I think we had this before: If the github action is triggered from a fork, there are authentication problems, in this PR it ran through: https://github.com/OPM/opm-common/pull/4151.
I have deactivated the trigger for PRs now in this commit, so now only if sth on master changes, opm-python-documentation will get notified
That should be all now!

**Comment by lisajulia** [comment]
jenkins build this please

**Review by atgeirr — APPROVED** [review]

**Pull request merged**
