### PR TITLE
fixed: initialize data in ConditionalStorage

### PR DESCRIPTION
**Pull request by akva2**
@GitPaean had some grief due to missing initialization of temperature in the BlackoilFluidState.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
Thanks for the help. It is good it gets fixed. It is rather confusing to have non-deterministic behavior across different computers and builds.

**Review by GitPaean — APPROVED** [review]
Thanks for fixing this. I am getting it in now.

**Comment by bska** [comment]
This will fail if `T` does not have a default constructor or cannot be direct initialised.  I don't think we have a lot of such types, certainly not ones that we use in `ConditionalStorage`, but it's something to be aware of if the situation would occur in the future.

**Pull request merged**
