### PR TITLE
Update actnum in FieldProps and EclipseGrid right after scanning GRID+EDIT

### PR DESCRIPTION
**Pull request by vkip**
Reason: Certain workflows de-activate cells by setting PORO=0 while at the same time setting the region numbers (e.g., SATNUM) to invalid values (not supported by current master).

### CODE REVIEW

**Comment by vkip** [comment]
jenkins build this please

**Comment by bska** [comment]
> Certain workflows de-activate cells by setting PORO=0 while at the same time setting the region numbers

Might these workflows also reactivate the zero-porosity cells by making them part of a numerical aquifer?  Because if they do, then this PR is wrong.

**Comment by bska** [comment]
> good point - we should cater for that also.

Agreed.  This PR might actually be correct in its current form, but the interactions between the parts that manipulate the set of active cells are...intricate.  We also need to make sure that the fixes in PRs #3049/#3063 continue to work.

**Comment by vkip** [comment]
> .. the interactions between the parts that manipulate the set of active cells are...intricate. 

Very true - steep learning curve for me at least.. Will test aquifer re-activation of PORO=0 cells first.

**Comment by vkip** [comment]
jenkins build this please

**Comment by vkip** [comment]
Seems to work, but not a very elegant solution I'm afraid, so certainly open for good suggestions!

**Review by bska — APPROVED** [review]
At some point we'll probably have to rework the entire strategy for how we determine `ACTNUM`.  One possibility might be some kind of deferred, transactional structure which accumulates/aggregates changes to the array all the way through the `EDIT` section and then "commits" those changes at the end of the `EDIT` section.  At that point we'll have a self-consistent view of `ACTNUM` and can compress the other grid properties with confidence.

That's in the future though.  For now I'm satisfied that this does what it claims to do and I'll merge into master.

**Pull request merged**
