### PR TITLE
Some changes to facilitate building using a super project

### PR DESCRIPTION
**Pull request by akva2**
These are some small changes/fixes which facilitates building opm using a super project, ref https://gist.github.com/akva2/8af198a963741592309265a72f0d2bc8

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this with downstreams opm-parser=1195 opm-output=234 opm-material=279 ewoms=275 opm-simulators=1390 opm-upscaling=245 serial dune2.4 please

**Comment by akva2** [comment]
jenkins build this with downstreams opm-parser=1195 opm-output=234 opm-material=279 ewoms=275 opm-simulators=1390 opm-upscaling=245 serial dune2.4 please

**Comment by akva2** [comment]
jenkins build this with downstreams opm-parser=1195 opm-output=234 opm-material=279 ewoms=275 opm-simulators=1390 opm-upscaling=245 serial dune2.4 please

**Comment by atgeirr** [comment]
Thanks for this, merging!

**Pull request merged**
