### PR TITLE
modify terminal output color for problem messages

### PR DESCRIPTION
**Pull request by nairr**
Changed terminal output color for problem messages to magenta from red

### CODE REVIEW

**Comment by atgeirr** [comment]
This looks like a simple and nice change. Since it primarily affects user experience I'd appreciate if @alfbr would consider it for a moment. This is what it looks like to me (and I think it is nice):

skjermbilde 2017-04-04 kl 11 11 07

**Comment by alfbr** [comment]
Yes, this is a welcome change. Red should be reserved for serious errors, not a simply chopping of a timestep. I also suggest that the preceeding Error message is removed, possibly including the number of iterations that failed in the Problem message.

**Comment by atgeirr** [comment]
> I also suggest that the preceeding Error message is removed, possibly including the number of iterations that failed in the Problem message.

I expected that one... I agree, it should be a minor change.

**Comment by atgeirr** [comment]
jenkins build this with downstreams please

**Comment by atgeirr** [comment]
Jenkins is green (Travis failure is a timeout as usual, nothing dangerous), merging.

Thanks for the patch!

**Pull request merged**
