### PR TITLE
add support for temperature and analytical aquifers

### PR DESCRIPTION
**Pull request by totto82**

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this opm-simulators=4035 please

**Comment by totto82** [comment]
jenkins build this opm-simulators=4035 please

**Review by bska — COMMENTED** [review]
For what it's worth, we'll need more work before this feature is supported in restarted simulations but this is a good initial step seeing as the Carter-Tracy model already is aware of temperature (PR #2694).  It's not immediately clear to me if we do/could support someone defaulting the initial aquifer temperature in a thermal simulation in order to defer the derivation to the equilibration facility, but in that case we may also need to add temperature handling to the `finishInitialisation()` routine.

Other than a couple of minor nits concerning diagnostic messages for failing unit tests I think this is ready to go in.

**Comment by totto82** [comment]
jenkins build this opm-simulators=4035 please

**Comment by totto82** [comment]
jenkins build this opm-simulators=4035 please

**Pull request merged**
