### PR TITLE
Well controls

### PR DESCRIPTION
**Pull request by joakim-hove**
Create small data transfer objects `ProductionControls` and `InjectionControls`. The purpose of these small classes is that they can be instantiated - with evaluated UDA values - on demand. The UDA evaluation is not yet implemented. As part of this PR the header files `WellProductionProperties` and `WellInjectionProperties` are made private - i.e. not installed any longer.

https://github.com/OPM/opm-simulators/pull/1831
Merged: ~~https://github.com/OPM/opm-grid/pull/365~~

OK - this should be ready for review - along with the opm-simulators PR.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=365 opm-simulators=1831 please

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=365 opm-simulators=1831 please

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=365 opm-simulators=1831 please

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=365 opm-simulators=1831 please

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=365 opm-simulators=1831 please

**Comment by bska** [comment]
I haven't looked at this in any kind of detail, but commit 32ebfd0 needs to be handled differently.  Saying `#include "src/..."` is not appropriate, at least not for the output code.  We need to know the well target values in order to fill in certain entries in `SWEL`, but we can get those in the same way that the simulator retrieves the targets.

**Comment by joakim-hove** [comment]
> Saying #include "src/..." is not appropriate

I agree it is not pretty; and it is on the list for improvements - but apart from the dubious aesthetics there is nothing wrong with it as such - or?

> but we can get those in the same way that the simulator retrieves the targets.

I guess

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=1831 please

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=1831 please

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=1831 please

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=1831 please

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=1831 please

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=1831 please

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=1831 please

**Comment by joakim-hove** [comment]
OK - this is yet another necessary step in the UDQ sequel. I would like to merge this in the not so distant future. Unless someone objects I will do so on Wednesday 29.th of May.

**Pull request merged**
