### PR TITLE
TESTING: Test co2/brine density/viscosity model

### PR DESCRIPTION
**Pull request by totto82**

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
The activity model is merged. Rebasing the PR.

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
jenkins build this please

**Comment by akva2** [comment]
hmm, have you been naughty? jenkins seems to ignore your requests for some reason.

**Comment by akva2** [comment]
jenkins build this please

**Pull request closed without merging**
