### PR TITLE
Use std::chrono instead of std::vector<int> to store start date

### PR DESCRIPTION
**Pull request by joakim-hove**
Timezones are currently eating at my soul ....

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
> Timezones are currently eating at my soul ....

Obligatory Computerphile [link](https://www.youtube.com/watch?v=-5wpm-gesOY)

**Comment by bska** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
> Obligatory Computerphile link

I think I'll fold long before we reach the westbank ...

**Comment by bska** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
@bska : This has the suggested `asLocalTimeT()` as first commit and is ready to go for my part.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Pull request merged**
