### PR TITLE
updating crossflow and auto-shutin with new WELSPECS

### PR DESCRIPTION
**Pull request by GitPaean**
The PR is targeting the following scenario. 

```
WELSPECS with crossflow on
WCONHIST give a ZERO rate

DATES

WELSPECS with crossflow off.

DATES
WELSPECS with crossflow on
```

Basically, part of the properties from the WELSPECS can be updated without providing a new WCON* keyword.  Then for the scenario with zero rate constraints from the WCON* keyword, the well status might be OPEN or SHUT depending on the new WELSPECS input. 

The current master could not handle the above behavior. 

I also include the aut shut-in in the PR, but that is not the motivation of the PR, just seeing it should be done in the same manner.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
It needs more checking. I make it draft.

**Comment by GitPaean** [comment]
Okay. The tricky scenario here is that a well 

WELSPECS  with crossflow on
WCONHIST give a ZERO rate

DATES
WELSPECS with crossflow off. 


With this types of schedule, the well might have difficulty if we want to solve the well with zero target and crossflow off. 

Our current way of parsing will not detect that a well is zero rate target and not allowing crossflow.

**Comment by GitPaean** [comment]
It has some similarity with the PR 
https://github.com/OPM/opm-common/pull/3463 .


The current sequential parsing of the SCHEDULE keyword will resulting in making well status update based on incomplete information.

**Comment by GitPaean** [comment]
jenkins build this opm-simulators=5139 please

**Comment by GitPaean** [comment]
It fails only the parsing test and did not fail any regression test. 

The scenarios we are targeting here is most likely something new. 

Basically, we have WELSPECS for a well, and WCONHIST with zero rate target, and WELSPECS in a later report step changes the crossflow flag without new WCON* setup. 

Then for some report steps, the well should be able to run with zero rate target (when crossflow flag is YES) and it needs to be SHUT for some other report steps (when crossflow flag is NO).

**Comment by GitPaean** [comment]
jenkins build this opm-simulators=5139 please

**Comment by GitPaean** [comment]
jenkins build this opm-simulators=5139 please

**Comment by GitPaean** [comment]
I am marking the PR ready for review so that we can begin the reviewing process and also discussion. 

Changing this part of the code, the main complications will be related to well testing and re-open the shut wells.  But let us see how the testing shows. 

We also discussed the possibility to do the update the well status in the parser side, but that way is not necessarily simpler or avoiding the same complication.

**Comment by GitPaean** [comment]
jenkins build this opm-simulators=5139 please

**Review by bska — APPROVED** [review]
Thanks a lot for the updates.  I'll merge into master.  At some point we may have to fully decide on how we split responsibilities between the input/parser layer and the simulator layer, but for now I'm happy with this approach.

**Pull request merged**
