### PR TITLE
Added Findopm-data module.

### PR DESCRIPTION
**Pull request by joakim-hove**
If a variety of this PR is merged - I will continue to merge this: https://github.com/OPM/opm-parser/pull/588

### CODE REVIEW

**Comment by akva2** [comment]
at some point this could likely be improved on the opm-data side but for now, this works.

**Comment by andlaus** [comment]
I'm wondering: what is the intention of this? simplifying the integration tests?

**Comment by akva2** [comment]
yes. to be able to disable them if the data isn't available. the actual tests will be in modules like opm-autodiff.

**Comment by andlaus** [comment]
cool!

**Pull request merged**
