### PR TITLE
add serialization template to SummaryConfig

### PR DESCRIPTION
**Pull request by akva2**
As discussed at dev-meeting, this is the start of moving the serialization support into the classes.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-simulators=2450 please

**Comment by blattms** [comment]
jenkins build this opm-simulators=2450 please

**Comment by joakim-hove** [comment]
This needs a much more detailed description; specifically I wonder:

1. Where can I find a general description of the new approach to serialization? 
2. What will be the required changes to the classes which should be serialized?
3. How will this be done practically - will there be a flag day?

I agree that this is in accordance with the consensus at the developer meeting and I certainly welcome a new approach to serialization, but to me this was quite fast. I was expecting serialization 1.0 to be operational for some time before it was replaced with serialization 2.0.

**Comment by akva2** [comment]
1) See the code. What you see is all it will take. Each type needs to have a template like the one added this class. We can kill off a lot of the accessors added for the previous iteration and if we change the tests in opm-simulators to construct things from decks, we can also kill off some, if not all, of the constructors added. The equality operators will have to stay for testing purposes.

2) Basically, nothing apart from adding these templates, and potentially the removals as discussed above.

3) No flag day. The two approaches will coexist like they do now, gradually being moved to the new approach on a type for type basis.

**Comment by joakim-hove** [comment]
> What you see is all it will take.

OK - that looks quite doable.  

> We can kill off a lot of the accessors added for the previous iteration and if we change the tests in opm-simulators to construct things from decks, we can also kill off some, if not all, of the constructors added.

That sounds good - I would very much like to get rid of the default constructors which create invalid instances.

> No flag day. The two approaches will coexist like they do now, gradually being moved to the new approach on a type for type basis.

OK very good; does that imply that this PR could be extended with also removing the accessors added for serialization 1.0 - or will we need synchronized changes opm-common / opm-simulators?

**Comment by akva2** [comment]
We cannot kill the default constructors, that's a prerequisite. as we need to instance empty instances before we can deserialize. But we can kill the constructors taking the pieces of data as primitives, if we do construction in tests from deck (strings).

It has to be done in sync with opm-simulators. This one has a little more though as I change a "root"-type to use the new serializer here.

Yes I will add the accessor removals. I just wanted to show the general concept, so I opened a little early.

**Comment by joakim-hove** [comment]
> We cannot kill the default constructors, that's a prerequisite. as we need to instance empty instances before we can deserialize.

Could this be done with pointers instead?

> It has to be done in sync with opm-simulators.

OK

> Yes I will add the accessor removals. I just wanted to show the general concept, so I opened a little early.

Cool.

Thank you for the information updates.

**Comment by akva2** [comment]
No, pointers will not help. We do not have a Deck to construct from, it's really as simple as that.

**Comment by akva2** [comment]
jenkins build this opm-simulators=2450 please

**Comment by joakim-hove** [comment]
> No, pointers will not help. We do not have a Deck to construct from, it's really as simple as that.

You are the expert here, but just to be a wise ass:
```
void unpack(std::unique_ptr<Rock2dTable>& data, std::vector<char>& buffer, int& position,
            Dune::MPIHelper::MPICommunicator comm)
{
    std::vector<std::vector<double>> pvmultValues;
    std::vector<double> pressureValues;
    unpack(pvmultValues, buffer, position, comm);
    unpack(pressureValues, buffer, position, comm);
    
    data.reset(new  Rock2dTable(pvmultValues, pressureValues));
}
```
??

**Comment by joakim-hove** [comment]
Sorry - wrong button

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2450 please

**Comment by akva2** [comment]
so you want to change absolutely every variable in the entirety of EclipseState, Schedule and SummaryConfig to pointers?

**Comment by joakim-hove** [comment]
> so you want to change absolutely every variable in the entirety of EclipseState, Schedule and SummaryConfig to pointers?

No heaven forbid - absolutely not; I just thought pointers could be used internally in the serialization orchestration to avoid the use of default constructed temporary objects. But I get the distinct feeling I am out on a limb - I'll back off now.

**Comment by akva2** [comment]
I don't think you have quite grasped how this work. The one template added to SummaryConfig does serialization and deserialization. The packSize/pack/unpack functions in ParallelRestart.cpp are gone for the SummaryConfig type now. But even so we still have to create SummaryConfig, EclipseState and Schedule objects on the receiver end before we can deserialize into them. And these need to be default constructed.

**Comment by joakim-hove** [comment]
> I don't think you have quite grasped how this work. 

No that is right - I had an epiphany now though;

> But even so we still have to create SummaryConfig, EclipseState and Schedule objects on the receiver end before we can deserialize into them

I get it - how about a constructor which takes a serialized buffer as argument:
```
EclipseState(Serializer& serializer) 
{

}
```
that would probably require a concrete serializer class though? OK *now* I will shut up.

**Comment by akva2** [comment]
It could work. Problem with that is that then you have to implement deserialization and serialization separately. The beauty of the current approach is that there is exactly one function that does both of them, leading to less chance of screwups. To me, that is worth the cost of the short lived default-constructed objects.

**Pull request merged**
