### PR TITLE
Use std::optional and value objects instead of std::shared_ptr

### PR DESCRIPTION
**Pull request by joakim-hove**
to manage endpoint values. Similar to: https://github.com/OPM/opm-common/pull/2411

Downstream: 
https://github.com/OPM/opm-material/pull/450
https://github.com/OPM/opm-simulators/pull/3144

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this opm-material=450 please

**Comment by joakim-hove** [comment]
jenkins build this opm-material=450 opm-simulators=3144 please

**Comment by atgeirr** [comment]
In general I like std::optional, and using it is better than std::shared_ptr for expressing the can-be-null condition. But why are these objects optional? Is it to cover the case that we ask for something in a table that does not exist? If so, maybe throwing inside is better than an optional return.

**Comment by bska** [comment]
> But why are these objects optional?

They're not.  I chose `shared_ptr<>` here for shared ownership.

**Comment by atgeirr** [comment]
I see now that I misunderstood, I thought you replaced shared_ptr with optional in the interface, but that was only internal to a class, using it for delayed initialization. Looks good to me!

**Comment by joakim-hove** [comment]
> I chose shared_ptr<> here for shared ownership.

I might misunderstand here - but as I see it the `std::shared_ptr<>` was only used to control delayed initialization? Objections to merging this?

**Comment by atgeirr** [comment]
> Objections to merging this?

None, merging!

**Pull request merged**
