### PR TITLE
Add three argument (year, month, day) constructor TimeStampUTC

### PR DESCRIPTION
**Pull request by joakim-hove**
A small convenience for those of us who are `{ }` challenged.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
I'd really prefer that we not add this.  It's not about what's convenient but about which expressions we want to have compile.  Constructors that take multiple elements of the same built-in types are inherently more unsafe than those that have strong types.  In particular the call sites become less expressive if we have this constructor.

**Comment by joakim-hove** [comment]
> I'd really prefer that we not add this.

I'd of course prefer to merge it; but I will not exactly invite to a duel Galois style over it.

>In particular the call sites become less expressive if we have this constructor.

Well - here I beg to differ. With this PR I have replaced multiple call sites like:
```
TimeStampUTC( {2001,12,30} );
```
with
```
TimeStamp( 2001, 12, 30 );
```
I agree that in current master you can not mix up three integer arguments, but the fuck up potential has just moved to the construction of the internal `YMD` struct. But maybe there is a convenient way I do not see? Anyway - for the situation where I have year, month and day from some other means; how would you recommend creating `TimeStampUTC`:
```
int year = 2020;
int month = 12;
int day = 25;

auto christmas_day = TimestampUTC( .... );
```

**Comment by atgeirr** [comment]
> Constructors that take multiple elements of the same built-in types are inherently more unsafe than those that have strong types. In particular the call sites become less expressive if we have this constructor.

Usually true, but as the example given shows, not necessarily for this class' typical usage. Unless we want to have separate types for years, months and days (and convert ints to them etc.) I think internal checking (is this a valid date) will have to be enough.

**Comment by bska** [comment]
When I built this I wanted to have
```C++
TimeStampUTC({2020, 4, 7})
```
be a compile error.  The call site was supposed to require saying
```C++
TimeStampUTC(YMD{ 2020, 4, 7 })
```
which would provide the requisite hints to the reader.  I didn't manage to impose that restriction however, so we're in the current situation.  Of course in C++20 this becomes moot with the extended calendar support in the standard library.

In the meantime, I guess this doesn't reduce the guarantees too much so I'll merge this into master.  I may revisit this later if time allows.

**Pull request merged**
