### PR TITLE
Mark CO2 In-Place Summary Vectors as OPM Extensions

### PR DESCRIPTION
**Pull request by bska**
Mostly to reduce the risk of confusion.  These vectors were introduced in commit 00bdaa0d4 (PR #3875).

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Review by akva2 — APPROVED** [review]
Seems fine to me.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
Merging per approval.

**Pull request merged**
