### PR TITLE
python: rewrite of tests using ParseContext.

### PR DESCRIPTION
**Pull request by stefoss23**
This PR circumvents the use of some parser functions from parser_module.py in tests.

### CODE REVIEW

**Comment by stefoss23** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
I'll abuse this to get a data update after the slightly premature merging of #967

**Comment by joakim-hove** [comment]
jenkins build this update_data please

**Comment by joakim-hove** [comment]
jenkins build this opm-tests=166 please

**Pull request merged**
