### PR TITLE
Add method WellSegments::topSegment()

### PR DESCRIPTION
**Pull request by joakim-hove**
Exactly what constitutes the top segment is not entirely clear to me - here I have just made the current implementation more explicit.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
> Exactly what constitutes the top segment is not entirely clear to me

The top segment is the segment with segment number equal to one.  Hopefully we always store that at index `0`.

**Comment by joakim-hove** [comment]
> The top segment is the segment with segment number equal to one. Hopefully we always store that at index 0.

OK good - thank you. What has confused and worried me a bit is that (it seems to me ...) that the segment number is sometimes treated as a random numerical - and at other times as an index. Clearly the usage described means that at least for the first element in the storage segment number is an index, but on the other hand we have a [special mapping](https://github.com/OPM/opm-common/blob/master/opm/parser/eclipse/EclipseState/Schedule/MSW/WellSegments.hpp#L116) mapping from segment number to storage index - which implies that it is not a simple index. Probably the truth is "both"?

**Comment by bska** [comment]
> What has confused and worried me a bit is that (it seems to me ...) that the segment number is sometimes treated as a random numerical ID - and at other times as an index.

It's a little bit of both.  Segment numbers must be in the range `1 .. NSEGMX` with the latter value specified as item 2 of [WSEGDIMS](https://github.com/OPM/opm-common/blob/4a2ccf31705f2bb99c0f9f1ead1ce7aeb85637df/src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WSEGDIMS#L3).  The top segment is always segment number one, but there may well be holes in the sequence&mdash;especially if branches and/or segments come online partway through the simulation period.  Still, the segment number is pretty much an index when outputting (or interpreting) the `RSEG` array so it's definitely possible to have `RSEG` arrays that contain a sequence of values, then a sequence of "non-values", followed by another sequence of values.

That said, the value of `WSEGDIMS(2)` greatly impacts the size of the restart files so it's usually desirable to not allocate more segments than we need in any particular run.

**Comment by joakim-hove** [comment]
> It's a little bit of both.

Thank you - I had a feeling it was like this.

**Comment by GitPaean** [comment]
I think we should have used `std::map` or `std::unordered_map` for WellSegments.

**Comment by joakim-hove** [comment]
> I think we should have used std::map or std::unordered_map for WellSegments.

That is probably right - not to late!

**Pull request merged**
