### PR TITLE
Selectively Bypass FIELD Exclusion From Group Level Keywords

### PR DESCRIPTION
**Pull request by bska**
When handling UDQs and, especially, `ACTIONX` condition blocks, it is permissible to treat `FIELD` as a regular group.  In particular, an `ACTIONX` condition block might use conditions such as
```
GGOR 'FIELD' > 123.4 AND /
GOPR 'FIELD' < 654.3 /
```
and we need to be prepared to handle those.  We therefore bypass the check for `group == "FIELD"` in `keywordG()` in this particular context.

We nevertheless preserve the `FIELD` group exclusion when processing ordinary group level keywords which don't name specific groups in the SUMMARY section such as
```
GOPR
/
```
Future work may elect to include `FIELD` in this context too.

### CODE REVIEW

**Comment by bska** [comment]
For what it's worth, [`ACTIONX_GCONPROD`](https://github.com/OPM/opm-tests/blob/540cd1e9622d98487d6665d789b9dcddb12ac05a/actionx/ACTIONX_GCONPROD.DATA#L504-L507) uses exactly these kinds of constructions.

**Comment by bska** [comment]
jenkins build this please

**Review by akva2 — APPROVED** [review]
Looks like it implements the intended behavior.

**Comment by bska** [comment]
PR approved and build check is green.  I'll merge into master.

**Pull request merged**
