### PR TITLE
Store Peaceman Denominator and Connection Length in Restart File

### PR DESCRIPTION
**Pull request by bska**
This PR writes the value of the denominator expression in Peaceman's formula to `SCON[6]` and the connection's interval length to `SCON[31]` in the restart file.  Using this information at restart time is the subject of follow-up work.

### CODE REVIEW

**Comment by bska** [comment]
I am creating this PR in draft mode for two reasons:

1. It depends on, and contains, upstream PR #3766.
2. It changes the content of the restart file of every regression test so it must be reviewed carefully before we update the reference solutions.

**Comment by bska** [comment]
The upstream PR has been merged into the master branch.  Marking this as "ready for review".

**Comment by bska** [comment]
jenkins build this please

**Comment by totto82** [comment]
jenkins build this please

**Review by totto82 — APPROVED** [review]
Thanks. Please merge when green.

**Comment by bska** [comment]
> jenkins build this please

Appreciate it, but I need to bring some parts of #3772 back to this PR before it'll pass certain restart checks.  I'll revert this PR back to "draft" state until that work is done.

**Comment by totto82** [comment]
>Appreciate it, but I need to bring some parts of https://github.com/OPM/opm-common/pull/3772 back to this PR before it'll pass certain restart checks. I'll revert this PR back to "draft" state until that work is done.

I will re-review it when it is back in shape.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
> > Appreciate it, but I need to bring some parts of #3772 back to this PR before it'll pass certain restart checks. I'll revert this PR back to "draft" state until that work is done.
> 
> I will re-review it when it is back in shape.

Thanks a lot for your patience.  I've backported the essential bits of #3772 and we no longer fail the restart regression tests.  I've reviewed the [build failures](https://ci.opm-project.org/job/opm-common-PR-builder/6657/testReport/) from this PR and they're all expected.  This PR outputs new non-zero items to the `SCON` array, meaning every existing regression test for which there is at least one active well/reservoir connection will fail.  We will have to update the reference solutions in response to those new items.

I'm moving this back to "ready for review" state.

**Comment by bska** [comment]
Unless anyone objects I intend to merge this no later than 12 Noon CET tomorrow (Wednesday the 7th of February).

**Comment by bska** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=1130 please

**Pull request merged**
