### PR TITLE
Don't Output RFT Files Unless Specifically Requested

### PR DESCRIPTION
**Pull request by bska**
This commit ensures that we do not create RFT output files unless the simulation model specifically requests such output (e.g., through keywords WRFT or WRFTPLT).  Notably, the `OutputStream::RFT`
constructor will also create the file so we must take care not to form an object of this type unless actually needed.

~As an implementation detail, we scan the SCHEDULE section for the first active RFT event&mdash;represented by its report step&mdash;and then cache this step to simplify later lookups.~

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Hmmm - I have not looked into this in detail; but I must admit I am a little surprised - my memory is that an insane effort has already gone into understanding the twists of the `WRFT`, and `WPLT` keywords. That might certainly have bugs - but to me it seems we now have two independent machineries for this question? The existing (possibly faulty?) implementation is in `Schedule::RFTConfig`.

>As an implementation detail, we scan the SCHEDULE section for the first active RFT event—represented by its report step—and then cache this step to simplify later lookups.

That is already internalized in the `RFTConfig` object.

**Comment by bska** [comment]
> The existing (possibly faulty?) implementation is in `Schedule::RFTConfig`.
> 
> > As an implementation detail, we scan the SCHEDULE section for the first active RFT event—represented by its report step—and then cache this step to simplify later lookups.

I'm **guessing** you're referring to [`RFTConfig::firstRFTOutput()`](https://github.com/OPM/opm-common/blob/3c29d4c41091e950f7228a01588847671c5d57b1/opm/parser/eclipse/EclipseState/Schedule/RFTConfig.hpp#L76).  If so, then that's currently not sufficient for this purpose.  For instance, when running the [TEST_WSEGSICD](https://github.com/OPM/opm-tests/blob/707072781c589909d92d138c55ce108eec4a7bdf/wsegsicd/TEST_WSEGSICD.DATA) model, this member function returns `firstRFTOutput() = 1` despite the simulation model not using either of `WRFT` or `WRFPLT`.

If there's a simple way to ensure that `firstRFTOutput()` returns exactly the point at which the first RFT output occurs I'll happily switch to using it.

**Comment by joakim-hove** [comment]
> For instance, when running the TEST_WSEGSICD model, this member function returns firstRFTOutput() = 1 despite the simulation model not using either of WRFT or WRFPLT.

Well OK; then there is a bug in the `RFTConfig` class  - or it is difficult to use "right" - and that should be fixed.

**Comment by bska** [comment]
jenkins build this opm-tests=226 please

**Comment by bska** [comment]
jenkins build this opm-tests=226 please

**Comment by bska** [comment]
jenkins build this opm-tests=226 please

**Comment by bska** [comment]
I have rebased this onto current master to take advantage of the abilities added to the `RFTConfig` class in #1412.  I now consider this to ready for final review.

Please observe that this PR must not be merged with the associate update to remove empty RFT files in PR OPM/opm-tests#226.

**Comment by bska** [comment]
jenkins build this opm-tests=226 please

**Comment by bska** [comment]
> This should be merged - did not really understand the message:
> 
> > Please observe that this PR must not be merged with [...]

Shoot.  That should say "must not be merged **without** ..."

> so I will let you merge it yourself.

Okay, thanks.

**Comment by bska** [comment]
Merging now per prior approval.

**Comment by bska** [comment]
> this broke post-builder

I'm inclined to say "no it didn't".  Unless the post-builder is doing something **really** strange, I ran all tests repeatedly in multiple configurations both sequentially and in parallel on my local machine and never saw that symptom.

**Comment by akva2** [comment]
i agree it looks like a fluke, but the status is yellow nontheless.

**Comment by bska** [comment]
>>> this broke post-builder
>> 
>> I'm inclined to say "no it didn't".
>
> the status is yellow nonetheless.

Right.  Is there a way to trigger a post-build without merging a new PR?  If not, we won't get a new answer until the next merge (which **might** be #1415).

**Comment by akva2** [comment]
i have manually started a build.

**Comment by akva2** [comment]
indeed, the build passed fine this time. however, running with valgrind locally i find this;

```==16172== 
==16172== Conditional jump or move depends on uninitialised value(s)
==16172==    at 0x6A985C7: __wmemchr_avx2 (memchr-avx2.S:250)
==16172==    by 0x5E5AE38: std::codecvt<wchar_t, char, __mbstate_t>::do_out(__mbstate_t&, wchar_t const*, wchar_t const*, wchar_t const*&, char*, char*, char*&) const (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25)
==16172==    by 0x589D1B1: boost::filesystem::path_traits::convert(wchar_t const*, wchar_t const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::codecvt<wchar_t, char, __mbstate_t> const&) (in /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.65.1)
==16172==    by 0x589D63A: boost::filesystem::detail::unique_path(boost::filesystem::path const&, boost::system::error_code*) (in /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.65.1)
==16172==    by 0x7F4BCA: boost::filesystem::unique_path(boost::filesystem::path const&) (operations.hpp:723)
==16172==    by 0x7E9C96: (anonymous namespace)::WorkArea::WorkArea(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (WorkArea.cpp:33)
==16172==    by 0x7EADB6: UDQ_SORTA_EXAMPLE::test_method() (test_msim_ACTIONX.cpp:160)
==16172==    by 0x7EAA05: UDQ_SORTA_EXAMPLE_invoker() (test_msim_ACTIONX.cpp:154)
==16172==    by 0x801F06: boost::detail::function::void_function_invoker0<void (*)(), void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:118)
==16172==    by 0x4E872CD: boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==16172==    by 0x4E8677C: boost::execution_monitor::catch_signals(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==16172==    by 0x4E86860: boost::execution_monitor::execute(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==16172== 
==16172== Conditional jump or move depends on uninitialised value(s)
==16172==    at 0x6A98E77: __wcsnlen_avx2 (strlen-avx2.S:261)
==16172==    by 0x69C7458: wcsnrtombs (wcsnrtombs.c:58)
==16172==    by 0x5E5AE6D: std::codecvt<wchar_t, char, __mbstate_t>::do_out(__mbstate_t&, wchar_t const*, wchar_t const*, wchar_t const*&, char*, char*, char*&) const (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25)
==16172==    by 0x589D1B1: boost::filesystem::path_traits::convert(wchar_t const*, wchar_t const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::codecvt<wchar_t, char, __mbstate_t> const&) (in /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.65.1)
==16172==    by 0x589D63A: boost::filesystem::detail::unique_path(boost::filesystem::path const&, boost::system::error_code*) (in /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.65.1)
==16172==    by 0x7F4BCA: boost::filesystem::unique_path(boost::filesystem::path const&) (operations.hpp:723)
==16172==    by 0x7E9C96: (anonymous namespace)::WorkArea::WorkArea(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (WorkArea.cpp:33)
==16172==    by 0x7EADB6: UDQ_SORTA_EXAMPLE::test_method() (test_msim_ACTIONX.cpp:160)
==16172==    by 0x7EAA05: UDQ_SORTA_EXAMPLE_invoker() (test_msim_ACTIONX.cpp:154)
==16172==    by 0x801F06: boost::detail::function::void_function_invoker0<void (*)(), void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:118)
==16172==    by 0x4E872CD: boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==16172==    by 0x4E8677C: boost::execution_monitor::catch_signals(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.65.1)
==16172== 
^C==16172== 
==16172== Process terminating with default action of signal 2 (SIGINT)
==16172==    at 0x66FB34C: read (read.c:27)
==16172==    by 0x5E5EED6: std::__basic_file<char>::xsgetn(char*, long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25)
==16172==    by 0x5E99ADF: std::basic_filebuf<char, std::char_traits<char> >::underflow() (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25)
==16172==    by 0x5ECE7B5: std::basic_streambuf<char, std::char_traits<char> >::xsgetn(char*, long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25)
==16172==    by 0x5E9A2E2: std::basic_filebuf<char, std::char_traits<char> >::xsgetn(char*, long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25)
==16172==    by 0x5EA74BC: std::istream::read(char*, long) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25)
==16172==    by 0xA1E2D2: (anonymous namespace)::isEOF(std::basic_fstream<char, std::char_traits<char> >*) (EclFile.cpp:59)
==16172==    by 0xA20D4B: Opm::EclIO::EclFile::EclFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) (EclFile.cpp:480)
==16172==    by 0xE92B07: Opm::EclIO::ERst::ERst(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (ERst.cpp:60)
==16172==    by 0xE98492: (anonymous namespace)::Open::Restart::read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (OutputStream.cpp:142)
==16172==    by 0xE98ED3: Opm::EclIO::OutputStream::Restart::openUnified(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, int) (OutputStream.cpp:388)
==16172==    by 0xE98ADF: Opm::EclIO::OutputStream::Restart::Restart(Opm::EclIO::OutputStream::ResultSet const&, int, Opm::EclIO::OutputStream::Formatted const&, Opm::EclIO::OutputStream::Unified const&) (OutputStream.cpp:304)
```

**Comment by bska** [comment]
> running with valgrind locally i find this;

Did you run this with `--track-origins=yes`?  I too am getting "conditional jump depends on uninitialised", but here the culprit appears to be the
```C++
WellProductionProperties::WellProductionProperties(const std::string& name)
```
[constructor](https://github.com/OPM/opm-common/blob/a8d05385e6e44806cb9a7f57deea3b7f58df540a/src/opm/parser/eclipse/EclipseState/Schedule/Well/WellProductionProperties.cpp#L44-L47) which doesn't fully initialise all members of the structure.  For instance, the [`bhp_hist_limit`](https://github.com/OPM/opm-common/blob/a8d05385e6e44806cb9a7f57deea3b7f58df540a/opm/parser/eclipse/EclipseState/Schedule/Well/Well.hpp#L311) looks to be uninitialised in this case.

**Comment by akva2** [comment]
i did not and right now i am deep in other things. i see that bug too (and i have fixed it elsewhere) but it is not the one causing issues here i think.

**Comment by bska** [comment]
>  [uninitialised `bhp_hist_limit`] is not the one causing issues here i think.

Just one more datapoint: I locally changed the `WellProductionProperties` structure to fully initialise all data members in the name-constructor, and then all of the unit tests in `test_msim_ACTIONX` produce variations of
```
*** No errors detected
==6547== 
==6547== HEAP SUMMARY:
==6547==     in use at exit: 72,704 bytes in 1 blocks
==6547==   total heap usage: 2,895,991 allocs, 2,895,990 frees, 275,535,758 bytes allocated
==6547== 
==6547== LEAK SUMMARY:
==6547==    definitely lost: 0 bytes in 0 blocks
==6547==    indirectly lost: 0 bytes in 0 blocks
==6547==      possibly lost: 0 bytes in 0 blocks
==6547==    still reachable: 72,704 bytes in 1 blocks
==6547==         suppressed: 0 bytes in 0 blocks
==6547== Rerun with --leak-check=full to see details of leaked memory
==6547== 
==6547== For counts of detected and suppressed errors, rerun with: -v
==6547== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```
when run with `--track-origins=yes`.  Admittedly this probably an older version of Valgrind than yours though, so it's definitely possible that I'm missing some failures.

**Comment by akva2** [comment]
May be also very well be newer boost - the trace points to a boost issue.

**Comment by bska** [comment]
> May be also very well be newer boost - the trace points to a boost issue.

Okay, just for completeness I'm running 1.66.0 on my workstation.

**Pull request merged**
