### PR TITLE
Box global list

### PR DESCRIPTION
**Pull request by joakim-hove**
Small preparation to allow for global 3D properties.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
I don't really understand the use-case here.  Is it to account for multipliers in pinched-out layers or similar applications?  That said, box objects are hopefully short-lived so the added memory use should be moderate in the common case.

I'm going to merge this into master now.

**Comment by joakim-hove** [comment]
> I don't really understand the use-case here. Is it to account for multipliers in pinched-out layers or similar applications?

Yes - that is the use case - exactly!

**Pull request merged**
