### PR TITLE
Add optional global flag to FieldPropsManager::porv()

### PR DESCRIPTION
**Pull request by joakim-hove**
YAPR - 3D refactoring

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by blattms** [comment]
And global=true means that the size of the properties array is the one of the cartesian grid? I assume this will be temporary. Otherwise a comment would be nice.

**Comment by joakim-hove** [comment]
> And global=true means that the size of the properties array is the one of the cartesian grid? 

The method in question returns a `std::vector<double>` value object; that will by default have `nactive` cells, but if the new flag is passed as `true` the returned vector will have `nx*ny*nz` elements. The container as such will never store global arrays.

The rationale for this is that for the `PORV` vector a global representation is needed, either it must be assembled at callsite or the container can supply it.

**Pull request merged**
