### PR TITLE
Avoid use of generated header S.hpp in header file

### PR DESCRIPTION
**Pull request by joakim-hove**
Fix for: https://github.com/OPM/opm-common/issues/2812

### CODE REVIEW

**Comment by akva2** [comment]
isn't moving the constructor to the cpp a better solution?

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
> Fix for: #2812

Cool.  However, the current code has been in place since [August of this year](https://github.com/OPM/opm-common/pull/2575) so why did we not see build issues earlier?

**Comment by akva2** [comment]
the issue is one of dependencies between build jobs. it's likely nobody did a clean build using the super-build.

**Comment by goncalvesmachadoc** [comment]
> > Fix for: #2812
> 
> Cool. However, the current code has been in place since [August of this year](https://github.com/OPM/opm-common/pull/2575) so why did we not see build issues earlier?

I just changed my system from Ubuntu 18 to 20...

**Pull request merged**
