### PR TITLE
Gen source dep fixup

### PR DESCRIPTION
**Pull request by joakim-hove**
Fix for: https://github.com/OPM/opm-common/issues/2340 and https://github.com/OPM/opm-common/issues/2343

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
This does indeed fix my problem.  I'll merge this into master&mdash;thanks a lot!

**Pull request merged**
