### PR TITLE
Fixing warnings

### PR DESCRIPTION
**Pull request by GitPaean**
Most of them are shadowing warnings.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
I will let this wait until I have the UDA work complete; getting that from 99% to final merge has been a f....ing nightmare in git gymnastics - and it is still ongoing.

**Comment by GitPaean** [comment]
It is not a problem. Initially I just wanted to fix the several warning show up downstream, while more are revealed when re-compiling opm-common.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
With https://github.com/OPM/opm-common/pull/858  , maybe it is good to get this in sooner then we can remove more warnings and I do not have to keep maintain it. 

But it also depends how much conflicts it causes with the on-going work.

**Pull request merged**
