### PR TITLE
Use Previous Output Time to Decide Next Output Time

### PR DESCRIPTION
**Pull request by bska**
This commit switches the criterion for `BASIC=4` and `BASIC=5` to using the difference between the previous and the next output time instead of "just" the next output time.  The original criteria
```
year % freq == 0
month % freq == 0
```
don't do what we want.  `BASIC=4` and `BASIC=5` should output every `freq` year (=4) or `freq` month (=5) of simulated time.

### CODE REVIEW

**Comment by bska** [comment]
Note: This PR must be merged along with downstream PR OPM/opm-simulators#3416.

**Comment by bska** [comment]
jenkins build this opm-simulators=3416 please

**Comment by bska** [comment]
jenkins build this opm-simulators=3416 please

**Comment by bska** [comment]
jenkins build this opm-simulators=3416 please

**Comment by bska** [comment]
jenkins build this opm-simulators=3416 please

**Comment by joakim-hove** [comment]
I am positively surprised you managed to fix this so quickly; when writing the original implementation I had a sinking feeling hoping that *no one will ever need to revisit this quagmire*.

When it comes to the updated tests *I assume* that the main change is new code based on the case which failed with master, but in addition there are lots of other formatting changes. For the review process it would be helpful if the formatting changes were relegated to separate commits.

**Review by joakim-hove — APPROVED** [review]

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
Merging this to finally solve #2547.  Thanks to @alfbr for testing.

**Pull request merged**
