### PR TITLE
Changing default value for number of pressure points used in equilibration

### PR DESCRIPTION
**Pull request by vkip**
Changing value to be consistent with current implementation.

### CODE REVIEW

**Comment by bska** [comment]
We've merged #3581 into the master branch.  Would you mind rebasing this PR on top of the current master sources, please?

**Comment by vkip** [comment]
> We've merged #3581 into the master branch. Would you mind rebasing this PR on top of the current master sources, please?

Thanks, and of course, no problem. Should be OK now.

**Comment by bska** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Very good.  I'll merge into master.

**Pull request merged**
