### PR TITLE
Restartview

### PR DESCRIPTION
**Pull request by joakim-hove**
Restartview - add code to handle `<std::string> / ECL::CHAR` type. Small change extracted from: #1835

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins buiild this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
> Looks good to me. I'll merge once the build check is successful.

Build check is successful.  I'm merging this as promised.

**Pull request merged**
