### PR TITLE
POD classes for restart info

### PR DESCRIPTION
**Pull request by joakim-hove**
Simple `state` class for well and group information loaded from restart file.

### CODE REVIEW

**Comment by joakim-hove** [comment]
The purpose of this is to able to [initialize a Schedule object from a restart file](https://github.com/OPM/opm-common/issues/1396) - the code will probably see modifications here and there before the complete task is solved, but I would like to merge this chunk now quite soon.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
> Is the final goal of this work to replace src/opm/output/eclipse/LoadRestart.cpp

Ehhh - this is embarasing; no my final goal is to be able to instantiate a Schedule object from a restart file - as described here: https://github.com/OPM/opm-common/issues/1396 - these POD classes have just been a temporary means on the way. 

I was not aware of the details of `LoadRestart.cpp`; maybe I could/should use that instead.

**Comment by bska** [comment]
> I was not aware of the details of `LoadRestart.cpp`; maybe I could/should use that instead.

I think you'd be able to use the `RestartFileView` and the `*Vectors` classes quite easily&mdash;although you'd need to add accessors for `SCON`, `SGRP`, and `SWEL`.  Putting the results into POD containers is a separate matter, but the `RstState::load()` function here would at least be easier to write.

**Comment by joakim-hove** [comment]
> I think you'd be able to use the RestartFileView and the *Vectors classes quite easily

Thank you - I will look into that; although the implementation has just reached the "Works for me" state so it does not feel that urgent.

**Pull request merged**
