### PR TITLE
Use double overload for eclGrid

### PR DESCRIPTION
**Pull request by joakim-hove**
Requires: https://github.com/Statoil/libecl/pull/418

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this libecl=418

**Comment by joakim-hove** [comment]
jenkins build this libecl=418 please

**Comment by joakim-hove** [comment]
jenkins build this libecl=418 please

**Comment by atgeirr** [comment]
Thanks, will use this for testing the pore volumes!

**Comment by atgeirr** [comment]
Testing errors here are not unexpected. We should probably update the INIT tests to use Eclipse-generated reference INIT files in any case. So we should not auto-generate new data for this PR yet, but only do that for the non-INIT test cases.

**Comment by atgeirr** [comment]
My preliminary testing of this PR was successful, I have so far observed a good match with expected values. Running Norne unfortunately displays a small performance loss, primarily due to a few more failed iterations, I think. Also there are test failures, but so far those seem to be of the usual "regression test shows the solutions have changed, but they are equivalent to the old" kind (not checked all yet).

In any case, my local Norne run is as follows (serial run), with new cell volumes:
```
Total time (seconds):         650.32
Solver time (seconds):        645.734
 Assembly time (seconds):     324.871 (Failed: 14.5782; 4.48736%)
 Linear solve time (seconds): 297.135 (Failed: 14.619; 4.92%)
 Update time (seconds):       12.6637 (Failed: 0.61765; 4.87734%)
 Output write time (seconds): 5.6425
Overall Well Iterations:      983 (Failed: 23; 2.33978%)
Overall Linearizations:       1975 (Failed: 88; 4.4557%)
Overall Newton Iterations:    1634 (Failed: 88; 5.38556%)
Overall Linear Iterations:    24907 (Failed: 1211; 4.86209%)



Error summary:
Warnings          281
Info              1105
Errors            0
Bugs              0
Debug             3824
Problems          8
```
Old cell volumes:
```
Total time (seconds):         633.761
Solver time (seconds):        629.193
 Assembly time (seconds):     318.953 (Failed: 10.9937; 3.44681%)
 Linear solve time (seconds): 287.576 (Failed: 10.7564; 3.74035%)
 Update time (seconds):       12.2511 (Failed: 0.467335; 3.81464%)
 Output write time (seconds): 5.57237
Overall Well Iterations:      978 (Failed: 21; 2.14724%)
Overall Linearizations:       1933 (Failed: 66; 3.41438%)
Overall Newton Iterations:    1594 (Failed: 66; 4.14053%)
Overall Linear Iterations:    24213 (Failed: 878; 3.62615%)



Error summary:
Warnings          281
Info              1094
Errors            0
Bugs              0
Debug             3770
Problems          6
```
I have not made any model 2 runs to compare.

**Comment by GitPaean** [comment]
Testing results with model 2. 

With current PR with Statoil/libecl#418

```
171222 ================    End of simulation     ===============
171223 
171224 Total time (seconds):         4498.69
171225 Solver time (seconds):        4472.46
171226  Assembly time (seconds):     1857.85 (Failed: 162.503; 8.74681%)
171227  Linear solve time (seconds): 2531.89 (Failed: 197.689; 7.80795%)
171228  Update time (seconds):       56.6684 (Failed: 5.1722; 9.12713%)
171229  Output write time (seconds): 29.1314
171230 Overall Well Iterations:      783 (Failed: 49; 6.25798%)
171231 Overall Linearizations:       2197 (Failed: 189; 8.60264%)
171232 Overall Newton Iterations:    1859 (Failed: 189; 10.1668%)
171233 Overall Linear Iterations:    48537 (Failed: 3651; 7.5221%)
171234 
171235 
171236 
171237 Error summary:
171238 Warnings          301
171239 Info              1030
171240 Errors            0
171241 Bugs              0
171242 Debug             4073
171243 Problems          18
```

With current master
```
171187 ================    End of simulation     ===============
171188      
171189 Total time (seconds):         4236.13
171190 Solver time (seconds):        4210.12
171191  Assembly time (seconds):     1809.26 (Failed: 140.804; 7.78243%)
171192  Linear solve time (seconds): 2319.76 (Failed: 136.496; 5.88405%)
171193  Update time (seconds):       55.6033 (Failed: 4.52714; 8.14185%)
171194  Output write time (seconds): 28.8672
171195 Overall Well Iterations:      769 (Failed: 41; 5.3316%)
171196 Overall Linearizations:       2187 (Failed: 166; 7.59031%)
171197 Overall Newton Iterations:    1850 (Failed: 166; 8.97297%)
171198 Overall Linear Iterations:    47581 (Failed: 2583; 5.42864%)
171199 
171200 
171201 
171202 Error summary:
171203 Warnings          301
171204 Info              1024
171205 Errors            0
171206 Bugs              0
171207 Debug             4054
171208 Problems          16
171209 
```

**Comment by atgeirr** [comment]
I hope that the 6% runtime increase is mostly noise, as judging from the overall iteration numbers it should be more like 1% increase. We will have a few more results like this tomorrow, and then we'll see.

In the end, we should really merge this PR, but we should have an idea of unfortunate (because I think it is really down to luck on this) consequences.

**Comment by atgeirr** [comment]
jenkins build this update_data please

**Comment by atgeirr** [comment]
jenkins build this libecl=418 update_data please

**Comment by atgeirr** [comment]
From @tskille we have more test data for this, that indicates there are no systematic increase (or decrease) in iteration counts. I quote his results:
```
Realization A, old:
================    End of simulation     ===============
 
Total time (seconds):         6957.9
Solver time (seconds):        6930.38
Assembly time (seconds):     2323.79 (Failed: 102.728; 4.42073%)
Linear solve time (seconds): 4444.17 (Failed: 114.873; 2.58481%)
Update time (seconds):       111.418 (Failed: 5.25189; 4.71368%)
Output write time (seconds): 32.9638
Overall Well Iterations:      1608 (Failed: 129; 8.02239%)
Overall Linearizations:       3487 (Failed: 154; 4.4164%)
Overall Newton Iterations:    2961 (Failed: 154; 5.20095%)
Overall Linear Iterations:    69208 (Failed: 1664; 2.40435%)
 
Realization A, new:
================    End of simulation     ===============
 
Total time (seconds):         6684.15
Solver time (seconds):        6658.82
Assembly time (seconds):     2166.94 (Failed: 93.7595; 4.32682%)
Linear solve time (seconds): 4346.72 (Failed: 134.813; 3.10149%)
Update time (seconds):       99.5691 (Failed: 4.57611; 4.59591%)
Output write time (seconds): 30.2145
Overall Well Iterations:      1603 (Failed: 125; 7.79788%)
Overall Linearizations:       3482 (Failed: 149; 4.27915%)
Overall Newton Iterations:    2956 (Failed: 149; 5.0406%)
Overall Linear Iterations:    69325 (Failed: 1498; 2.16084%)

++++++++++++++++++++++++++++++++++++++++++++++

Realization B, old:
===============    End of simulation     ===============
 
Total time (seconds):         12045.7
Solver time (seconds):        12008.9
Assembly time (seconds):     2517.62 (Failed: 89.8634; 3.56938%)
Linear solve time (seconds): 9233.89 (Failed: 305.51; 3.30858%)
Update time (seconds):       184.281 (Failed: 6.91994; 3.75511%)
Output write time (seconds): 44.0917
Overall Well Iterations:      1461 (Failed: 27; 1.84805%)
Overall Linearizations:       3362 (Failed: 119; 3.53956%)
Overall Newton Iterations:    2839 (Failed: 119; 4.19162%)
Overall Linear Iterations:    74586 (Failed: 2368; 3.17486%)

Realization B, new:
================    End of simulation     ===============
 
Total time (seconds):         9594.97
Solver time (seconds):        9564.6
Assembly time (seconds):     2199.27 (Failed: 53.4094; 2.42851%)
Linear solve time (seconds): 7168.72 (Failed: 150.615; 2.101%)
Update time (seconds):       141.477 (Failed: 3.71022; 2.62249%)
Output write time (seconds): 36.1955
Overall Well Iterations:      1449 (Failed: 17; 1.17322%)
Overall Linearizations:       3297 (Failed: 77; 2.33546%)
Overall Newton Iterations:    2779 (Failed: 77; 2.77078%)
Overall Linear Iterations:    73466 (Failed: 1393; 1.89612%)
 
++++++++++++++++++++++++++++++++++++++++++++++

Realization C, old:
================    End of simulation     ===============
 
Total time (seconds):         9738.45
Solver time (seconds):        9704.17
Assembly time (seconds):     2492.81 (Failed: 46.5197; 1.86616%)
Linear solve time (seconds): 6984.05 (Failed: 146.468; 2.09718%)
Update time (seconds):       165.116 (Failed: 3.29696; 1.99675%)
Output write time (seconds): 40.7053
Overall Well Iterations:      1515 (Failed: 17; 1.12211%)
Overall Linearizations:       3439 (Failed: 62; 1.80285%)
Overall Newton Iterations:    2922 (Failed: 62; 2.12183%)
Overall Linear Iterations:    64309 (Failed: 1444; 2.24541%)
 
Realization C, new:
================    End of simulation     ===============
 
Total time (seconds):         9330.92
Solver time (seconds):        9299.5
Assembly time (seconds):     2348.99 (Failed: 52.646; 2.24122%)
Linear solve time (seconds): 6741.8 (Failed: 130.407; 1.93431%)
Update time (seconds):       151.649 (Failed: 3.75934; 2.47898%)
Output write time (seconds): 37.3394
Overall Well Iterations:      1510 (Failed: 20; 1.3245%)
Overall Linearizations:       3451 (Failed: 77; 2.23124%)
Overall Newton Iterations:    2933 (Failed: 77; 2.6253%)
Overall Linear Iterations:    64125 (Failed: 1123; 1.75127%)
```

I believe the timings here should be disregarded: they are from a cluster with varying load. The update time may be a reasonable proxy for general cluster performance here.

**Comment by atgeirr** [comment]
The regression test failures are all close to 1e-5 (the relative limit), and are either pore volume changes or well curve changes of the same order of magnitude. I believe this is good to merge when green. Will run final jenkins including the data update.

**Comment by atgeirr** [comment]
jenkins build this libecl=418 opm-tests=23 please

**Comment by atgeirr** [comment]
jenkins build this opm-tests=23 please

**Comment by atgeirr** [comment]
In it goes, thanks!

**Pull request merged**
