### PR TITLE
Alq dimension

### PR DESCRIPTION
**Pull request by joakim-hove**
The dimension of the ALQ value in WCONPROD / WCIONHIST depends on the type of the AQL value in the corresponding vfp table. Nice and clean design!

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Review by totto82 — APPROVED** [review]
Thanks. The WCONHIST/PROD interface becomes a bit more complicated since it needs the ALQ type but I guess that is unavoidable. Merge at will.

**Pull request merged**
