### PR TITLE
Py code records

### PR DESCRIPTION
**Pull request by joakim-hove**
Small baby refactorings to enable multi record Python keywords:
```
PYACTION
    WWCT /

if context.well_var("OP1", "WWCT") > 0.80:
     context.schedule.shut_well("OP1")

PYEND
```

the important point is the normal first record "WWCT /". 

There will be more steps.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by OPMUSER** [comment]
```
PYACTION
    WWCT /

if context.well_var("OP1", "WWCT") > 0.80:
     context.schedule.shut_well("OP1")

PYEND

```
I'm busy, so just a short reply will add more tomorrow.

I don't like this syntax at all `WWCUT /` , you are mixing OPM Flow syntax with Python.  I would recommend that we should just use Python syntax within PYACTION/PYEND, what about `def WWCT()`

**Comment by joakim-hove** [comment]
> I would recommend that we should just use Python syntax within PYACTION/PYEND

My point is that it is benefical to give the python block a name - that is what is achieved with the first record - but it was myabe misleading that I had chosen a well know Flow symbol - i.e. `WWCT`- maybe this illustrates what I mean better:
```
PYACTION
    'wwct_ACTION' /

if context.well_var("OP1" , "WWCT") > 0.80:
      context.shut_well("OP1")

PYEND
```
In addition it be advantageous to be able to point to an external file with Python code instead of inlining it in the deck - this could maybe be done with a new keyword  `PYINCLUDE`:

```
PYINCLUDE
      'wwct_ACTION'  'path/to/wwct_action.py' /
```

??? Anyway - great with opinions and input.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by tskille** [comment]
I don't see any problems of mixing a first record with properties related to the PYACTION object, and then one subsequent record with python code. 

In fact it is quite common within the eclipse keyword format. 

COMPSEGS is one example

Record 1
The first record consists of a single item of data that identifies the well.

Each subsequent record

set the start and end of each connection’s perforations in terms of distance along ....

**Pull request merged**
