### PR TITLE
[cmake] Properly support scotch as a metis replacement.

### PR DESCRIPTION
**Pull request by blattms**
If the METIS header is from scotch, then we also need to search for PtScotch and link to it. For this we now detect scotch and adapt the METIS::METIS target to inlude PtScotch. We also force our build system to use the target instead of the library for linking to also get the necessary flags automatically.

If PtScotch is used as a metis replacement then we explicitely request METIS version 5 API by defining SCOTCH_METIS_VERSION appropriately.

Note that without this PR our config.h will contain `#define HAVE_METIS TRUE`

### CODE REVIEW

**Comment by blattms** [comment]
I am not even sure whether METIS is actually searched for in master, but this is important for OPM/opm-grid#725.

I will also test this on Debian oldstable.

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
I checked this on bullseye, too. Works.

**Review by akva2 — APPROVED** [review]

**Comment by lisajulia** [comment]
Thanks :)

**Pull request merged**
