### PR TITLE
[discussion] adding UMFpack to prerequisite of opm-simulators

### PR DESCRIPTION
**Pull request by GitPaean**
I am not sure if this is the correct place or correct way to do it. 

The reason for this is because a direct solver is required as part of the multisegment well solution procedure. 

Please suggest.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this with downstreams please

**Comment by atgeirr** [comment]
I did not notice this PR before merging the multisegment well PR, I see I may have made an error there if it leads to people without UMFPACK's builds failing. However, Jenkins succeeded so it cannot be too disruptive. We already state on our web site (in our build instructions) that UMFPACK is required, was that because of opm-upscaling perhaps? In any case, I cannot find it as REQUIRED in cmake currently, it is asked for by opm-core but not required. Perhaps this was a little broken in the current state?

**Comment by atgeirr** [comment]
jenkins build this with downstreams please

**Comment by akva2** [comment]
umfpack (or superlu, but there are other issues with superlu) is required in everything using AMG with dune < 2.5 so this is a completely noncontroversial change.

**Comment by atgeirr** [comment]
Merging!

**Comment by blattms** [comment]
BTW The "REQUIRED" has no effect as UMFPack is already search as non-required for opm-core and we do not check again. On one of my system cmake configured successfully without UMFPack installed and I got compile errors later.

**Pull request merged**
