### PR TITLE
Small fixes to RSM output

### PR DESCRIPTION
**Pull request by joakim-hove**
- MAI -> MAY
- Update text header with simulation time and flow version

Some minor tweaks in the RSM file. ~~Will in addition need to calculate the YEARS column - hope to get that into the release.~~

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
Do you want to rebase ths on top of current master?

**Comment by joakim-hove** [comment]
> Do you want to rebase ths on top of current master?

yes

**Comment by joakim-hove** [comment]
jenkins build this please

**Pull request merged**
