### PR TITLE
Use std stringview

### PR DESCRIPTION
**Pull request by joakim-hove**
With this PR we use std::string_view instead of the opm specific variety.

Unfortunately it turns out that significant functionality does not arrive before C++ 20, so it was a bit more work than expected 😕

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by magnesj** [comment]
> With this PR we use std::string_view instead of the opm specific variety.
> 
> Unfortunately it turns out that significant functionality does not arrive before C++ 20, so it was a bit more work than expected 😕

I have seen a library for early adoption of new features. Have not used it, but might be useful. 
https://abseil.io/

**Comment by joakim-hove** [comment]
jenkins build this please

**Pull request merged**
