### PR TITLE
Add PORV argument when creating PAvgCalculator

### PR DESCRIPTION
**Pull request by joakim-hove**
Start to support PORV based averaging in the WBP calculator.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Looks good to me.  Unless there is more work coming here, I suggest to merge it in its current state.

**Comment by joakim-hove** [comment]
Thanks for the review - this is complere. Merging!

**Pull request merged**
