### PR TITLE
SimulationDatacontainer

### PR DESCRIPTION
**Pull request by joakim-hove**
Added methods to register cell and face data in a SimulationDataContainer.

### CODE REVIEW

**Comment by atgeirr** [comment]
> I would prefer std::vector< std::vector< double > >

I agree with this, although I am usually a fan of std::map. Among the reasons: when debugging I frequently need to access these data, and doing so through an std::map is more involved.

Anyway thanks for providing a starting point for discussions! I have a bit to say:
 - I'd like to put into this data of at least four kinds (or types, or perhaps better, domains): cell, face, well and perforation(well completion). This can be done by up-front deciding that those four are acceptable, or we could have a more generic mechanism (see below).
 - Data associated with any domain may be scalar or have a (typically small, but not compile-time known) size or number of components, for example cell saturations or well fluxes, this 
 - Each data item has a name string, but they could still be stored in a vector (as in SimulatorState).
 - Although perhaps convenient, we should try to remove the `numPhases()` member, it seems to not fit well with the generic concept?
 - The default/legacy fields should be removed (but kept initially perhaps in the SimulatorState class).

An example of how I imagine the generic interface (using strings for domain names).
```
void registerDomain(const std::string& domain_name,
                    const int num_elements);
void registerData(const std::string& name,
                  const std::string& domain_name,
                  const int num_components,
                  const double initial_value);
```
This could be used as follows:
```
state.registerDomain("cell", num_cells);
state.registerData("pressure", "cell", 1, 100*barsa);
state.registerData("saturation", "cell", num_phases, 0.0);
```
A minor drawback would be that we would need to establish conventions about the domain names too, not just particular field names, but the great advantage would be that it would support arbitrary extension with no changes to the base class.

**Comment by joakim-hove** [comment]
> Why std::map? I would prefer std::vector< std::vector< double > >. The mapping from name to id can then be handled with a map.

Well - I guess it is a matter of taste and opinion; I think the `std::vector<std::vector<double> >` has unnecessary low level of abstraction. I am not as familiar with the use of this code as you are - but are there other disadvantages with `std:map<>` apart from personal taste (I saw @atgeirrs comment about debugging) - at least when we nevertheless want to keep track of the names anyway I see no reason to manually maintain a separate `std::vector<std::string>` and integer Ids.

**Comment by joakim-hove** [comment]
>  [...]  I have a bit to say:

In general I agree with your quite generic approach[1]; - apart from that my main point is that I would first like to merge something which is functionally equivalent to the current situation, and then subsequently extend it. Too much up front design and planning will in my opinion probably be wasteful.

[1]: Which in my opinion screams for `std::map<>`.

**Comment by bska** [comment]
The debugging argument does not hold anyway.  Just download and use the GDB pretty printers which will display contents of any standard container.  There is something to be said for a `std::unordered_map<>` though.

**Comment by joakim-hove** [comment]
> There is something to be said for a std::unordered_map<> though.

That I agree - my main point is to get an associative(?) array relation from string to data.

**Comment by bska** [comment]
>> There is something to be said for a `std::unordered_map<>` though. 
> 
> That I agree - my main point is to get an associative(?) array relation from string to data.

Absolutely, there's no question about that.  If lookup speed turns out to be a bottleneck we can always make the structure into something like
```C++
std::unordered_map<std::string, std::unique_ptr<Data>>
```
or
```C++
std::unordered_map<std::string, Index>
```
in which `Index` is a contiguous index into the structure that holds the actual data.

**Comment by joakim-hove** [comment]
I'll merge this later today?

**Comment by bska** [comment]
> I'll merge this later today?

I suppose so.  There are some minor details that I'd prefer be done differently (e.g., braces on `if`/`else` blocks, the explicit `return true` or `return false` from a function consisting only of evaluating a Boolean expression), but those aren't important enough to delay the merge.

**Pull request merged**
