### PR TITLE
Some debug-iterator Janitoring

### PR DESCRIPTION
**Pull request by akva2**
Fix some debug iterator failures:
- missing initialization
- broken erase-loop iterator usage.

### CODE REVIEW

**Review by atgeirr — APPROVED** [review]
Looks fine to me, but maybe we should change to use the remove-erase idiom instead? That is harder to mess up in the first place. I leave it up to you if you want to do this or not.

**Comment by akva2** [comment]
sure. done.

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks a lot for the updates.  This looks good to me and I'll merge into master.

**Pull request merged**
