### PR TITLE
not allowing unknown group names in extended network

### PR DESCRIPTION
**Pull request by GitPaean**
in keywords BRANPROP and NODEPROP.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
I am marking this PR as ready for review.  Jenkins testing is expected to pass.

**Review by bska — COMMENTED** [review]
This appears to throw an exception if we encounter node names which do not correspond to groups.  Is that really what we want?  While the leaf nodes in the extended network indeed must be groups, `BRANPROP` and `NODEPROP` are supposed to be able to define nodes which are not groups.

**Comment by GitPaean** [comment]
> While the leaf nodes in the extended network indeed must be groups, BRANPROP and NODEPROP are supposed to be able to define nodes which are not groups.

You are right about this.  I misunderstood the logic, closing this PR now.

**Pull request closed without merging**
