### PR TITLE
Introducing water-gas ratio RVW keyword

### PR DESCRIPTION
**Pull request by plgbrts**
Note, the unit of `OilDissolutionFactor ` unit is reused for the `RVW `quantity.

### CODE REVIEW

**Comment by bska** [comment]
Would you mind adding a unit test to demonstrate what the keyword and its data would look like in an input file?

**Comment by goncalvesmachadoc** [comment]
> Would you mind adding a unit test to demonstrate what the keyword and its data would look like in an input file?

Should the test be in test_EclipseIO.cpp?

**Comment by bska** [comment]
>>Would you mind adding a unit test to demonstrate what the keyword and its data would look like in an input file?
>
> Should the test be in `test_EclipseIO.cpp`?

Good question, @goncalvesmachadoc!  I thought we already had a set of unit tests to exercise the enumerated initialisation method (keywords `PRESSURE`, `SGAS`, `RS` and similar), but looking more closely at this now we clearly do not.  That's a pretty big hole in our test coverage so thank you for alerting me to this situation.

I'm going to run a build check of the current PR and merge it if that comes back green and then I'm going to create those unit tests for you.

**Comment by bska** [comment]
jenkins build this please

**Pull request merged**
