### PR TITLE
Rst wellopen

### PR DESCRIPTION
**Pull request by joakim-hove**
**Updates to well control mode reported in IWEL**

With this commit the IWEL[ActWCtrl] is assigned a value independently of the
wells OPEN / SHUT status.

With this PR the index enum value Status is used instead of the previously used
item11. Also numerical constants are introduced for eclipse status values for
Shut, Stop, Open and Auto.

This will commit will set the active control flag also for wells which are not open, this will induce a data update of IWEL. Regarding the commit: "Store Value::Shut == -1000 for shut wells in IWEL" - should maybe also apply to the item9?

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this update_data please

**Review by bska — APPROVED** [review]
Very good.  I'm glad we finally characterised that flag.  I'll run one final build check against the updated reference data and merge if it comes back green.

**Comment by bska** [comment]
jenkins build this opm-tests=401 please

**Comment by bska** [comment]
Reference data updated in tests repository. Merging this now to synchronise with those.

**Pull request merged**
