### PR TITLE
CO2STORE new reference state for enthalpy

### PR DESCRIPTION
**Pull request by svenn-t**
Generated new CO2 table (using Coolprop) and new polynomial coefficients in SimpleHuDuanH2O class with reference state equal to (T, P) = (288.71 K, 101325.0 Pa) = (15.56 C, 1 atm). With this change, enthalpy/internal energy calculations in CO2STORE THERMAL runs should all have the same reference state.

The PR will be a draft until further testing have been done.

Note that the PR will give errors in the unit tests in test_components (possibly other tests as well) due to the new reference state. I will update the unit tests when/if this becomes an actual PR.

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by svenn-t** [comment]
Unit tests have been updated. After testing with the new enthalpy data, I have changed PR to a real one.

**Comment by bska** [comment]
jenkins build this please

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
Thanks for the fix. This will make the rock and fluid enthalpy using the the default reference temperature and pressure given by STCOND. If STCOND is modified we will still have a problem. My suggestion is to add a check in Co2GasPvt.hpp and BrineH2Pvt.hpp that STCOND is 15C and 1atm. (i.e not changed) with a throw back to the user that the user has to use default STCOND values. Another approach is to store the reference pressure and temperature in the CO2 table and then check that this corresponds to the values given by STCOND. If this is combined with scripts to generate new tables we can support non default STCONDs. I suggest we do the simple check and throw first.

**Comment by svenn-t** [comment]
I have updated the code to give an error if values other than default values in STCOND are used.

**Comment by bska** [comment]
jenkins build this please

**Comment by svenn-t** [comment]
A test gave error when `Scalar = float`. Fixed with latest commit.

**Comment by bska** [comment]
jenkins build this please

**Comment by svenn-t** [comment]
I had a look at the CO2STORE test and compared BPR in block 10,1,1 (see figure). Curve details: CO2STORE-PR is the PR version, CO2STORE-OPMTESTS is the regression test result, CO2STORE-PR-STRICT and CO2STORE-MASTER-STRICT are the PR and master versions, respectively, run with `--tolerance-mb=1e-12`. It seems to me that the test fail due to different convergent solution between the PR version and regression test result. This is also the case for CO2STORE_DIFFUSIVE test.

For the CO2STORE_GW and CO2STORE_GASWATER tests the deviations are  small, as far as I can see, probably due to difference in convergence here as well.The _ENERGY tests are expected to be different due the changes in this PR.

CO2STORE_BPR_10-1-1

**Comment by totto82** [comment]
Thanks for the testing. I will update the reference and merge this. I am looking forward to a PR with the actual code that generates this new table.

**Comment by totto82** [comment]
jenkins build this update_data please

**Comment by totto82** [comment]
jenkins build this opm-tests=1063 please

**Pull request merged**
