### PR TITLE
RWGSALT table implementation based on PvtxTable

### PR DESCRIPTION
**Pull request by plgbrts**
This PR implements the RWGSALT table (described in the user manual) based on PvtxTable class.

### CODE REVIEW

**Comment by plgbrts** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by plgbrts** [comment]
jenkins build this please

**Comment by plgbrts** [comment]
jenkins build this opm-material=538 opm-models=744 opm-simulators=4189 please

**Comment by bska** [comment]
jenkins build this please

**Pull request merged**
