### PR TITLE
Make GroupTree::handleSeqIndex() private

### PR DESCRIPTION
**Pull request by joakim-hove**
Minor step for `Group2`

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
The [failure mode](https://ci.opm-project.org/job/opm-common-PR-builder/202/testReport/junit/(root)/mpi/compareECLFiles_flow_BASE_MODEL_1/) here is a little conspicuous.  IGRP index 214 corresponds to Item 1 (index 0) of IGRP for the third (index 2) group.  The number of items in `IGRP` for each group is [dynamic](https://github.com/OPM/opm-common/blob/729948b71284ea787a39e8e3d1442ae5697d5789/src/opm/output/eclipse/CreateInteHead.cpp#L111), but it is 107 for [0_BASE_MODEL2](https://github.com/OPM/opm-tests/blob/b52ea8014b3fe8852af309d8b36a0daac88e269d/model2/0_BASE_MODEL2.DATA#L52-L54).

In any case, the first `max(ngmax, nwgmax)` elements in `IGRP` are the sequence indices of the group's children (and/or padding).  I suggest you talk to @jalvestad about the details before you do anything else involving that quantity.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Pull request merged**
