### PR TITLE
Output SWATINIT Array to INIT File if Present

### PR DESCRIPTION
**Pull request by bska**
This commit makes the INIT file writing code aware of the `SWATINIT` array and will output this array to the INIT file if it exists in the input deck.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by blattms** [comment]
I asked this because I could not see any check whether SWATINIT is used in the deck. According to jenkins that might be missing.

**Comment by bska** [comment]
>> I could not see any check whether `SWATINIT` is used in the deck. According to jenkins that might be missing.
>
> I don't know what happened there. I'll look into it and update the PR.

Okay, I understand it now.  It's a fallout from the [implementation](https://github.com/OPM/opm-common/blob/4bb104c8590a80de4ca3dab3202193ec30619c4e/src/opm/output/eclipse/WriteInit.cpp#L513-L514) of the [`FILLEPS`](https://github.com/OPM/opm-tests/blob/ed04b687f2997579f9e0d2f66b08b4700925adfa/cskin/CSKIN-01.DATA#L173) keyword.

I could add a special case for `SWATINIT` there, but I think it's better to have a more complete solution&ndash;possibly a flag in the `CellProperty` structure to specify whether or not the property supports automatic property creation.

**Comment by tskille** [comment]
PR is teste on a field model in Equinor and results are excellent. looking forward to see this going into master

**Comment by bska** [comment]
> PR is tested on a field model in Equinor and results are excellent. looking forward to see this going into master

Thanks a lot for testing.  I just need to fix an unexpected fallout from `FILLEPS` interaction and then this should be ready for merging.  We'll need to update the reference solutions of a number of regression tests to account for `SWATINIT` now being output to the INIT file.

**Comment by bska** [comment]
> I think it's better to have a more complete solution–possibly a flag in the `CellProperty` structure to specify whether or not the property supports automatic property creation.

I have pushed an update to this PR which uses that approach.  I'll run a new build check to see if there's anything else I've missed.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this ignore_extra please

**Comment by bska** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
PR approved and the new reference solutions have been installed on the CI system.  I'll merge this now to enable the new output array.

**Pull request merged**
