### PR TITLE
Two small but critical fixes

### PR DESCRIPTION
**Pull request by atgeirr**
1. Fix compile error due to missing includes (might just bite clang users though)
2. Fix for control mode bug that cause Norne to fail (or rather worse: run but produce totally wrong results).

The control mode bug fix might not be completely sufficient, but at least it recovers the running of Norne.

@akva2 the second commit should be picked to the release branch (sorry for the extra work), unless @joakim-hove has a better alternative.

### CODE REVIEW

**Comment by joakim-hove** [comment]
> Fix for control mode bug that cause Norne to fail (or rather worse: run but produce totally wrong results).

How the h... did this bug slip through in the first place?

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
> How the h... did this bug slip through in the first place?

Because we do not do automatic regression testing on Norne. Also, the results on Norne has not changed significantly in years, so we tend to assume that if it runs, it's ok. That held until now...

On the other hand, we use it frequently to test almost any change, so it would have been discovered soon-ish. Small consolation...

**Comment by bska** [comment]
Is there anything that's blocking this PR? If not I suggest merging this into master as soon as possible.

**Comment by joakim-hove** [comment]
No - merge it

**Comment by bska** [comment]
> No - merge it

:+1: 

I'm merging now. Is this PR cause for an -RC3 or did #711 not make it into the release branch?

**Comment by joakim-hove** [comment]
I would say the second commit should be cherry-picked to rc3.

**Comment by joakim-hove** [comment]
It would be very good if someone who *really* understood the matter - e.g. @atgeirr or @GitPaean could create a test for this; I am happy to assist.

**Comment by GitPaean** [comment]
> could create a test for this; I am happy to assist.

I am modifying one existing test to handle it.

**Pull request merged**
