### PR TITLE
drop unused friend declarations

### PR DESCRIPTION
**Pull request by akva2**
Always sad to see friends go, but these friends are now imaginary.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-simulators=4083 please

**Comment by akva2** [comment]
jenkins build this opm-simulators=4083 please

**Review by bska — COMMENTED** [review]
Since you're removing the `friend` declarations, you can probably remove the forward declaration of [`Mpi::Packing`](https://github.com/OPM/opm-common/blob/f36c20a90b83ac978523ae5e5637c649c2ec25e0/opm/output/data/Wells.hpp#L39) too.

**Comment by akva2** [comment]
jenkins build this opm-simulators=4083 please

**Review by bska — APPROVED** [review]
This looks good to me and I'll merge into master.  Thanks a lot!

**Pull request merged**
