### PR TITLE
minimum dune version required is now 2.7

### PR DESCRIPTION
**Pull request by akva2**
In preparation for bumping to dune 2.7. Leaving in draft mode as we should merge this close to 23.04 release.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by blattms** [comment]
Might be better to merge this soon unless we fix compilation with 2.6. With this PRs users will notice broken compilation with 2.6  earlier and get a more decent error.

**Comment by akva2** [comment]
the problem with that is our ubuntu 20.04 users/devs; if i push out the backported dune 2.8 packages, it will break the existing opm-packages unless they manually freeze dune. i would rather not rebuild the 22.10 packages. and i would really like to see the dune packages go through a testing period before we push it out to the main ppa where it will impact end users, which happens naturally in the release cycle (where we use the testing-ppa until final release).

**Comment by atgeirr** [comment]
> the problem with that is our ubuntu 20.04 users/devs; if i push out the backported dune 2.8 packages, it will break the existing opm-packages unless they manually freeze dune.

I am a little confused as to the best order and timing for this. Can you order and estimate when:
 - This should be merged
 - The backported Dune packages are pushed to testing
 - The backported Dune packages are pushed to the ppa

Also, why cannot we just merge this and not yet push packages, is it to avoid problems for developers currently on Ubuntu 20.04?

**Comment by akva2** [comment]
precisely, it's to avoid headaches for devs.

my idea was to merge this close just before branching.
then push out dune packages to testing ppa and push out rc's built against these, see if the world burns, and if not, put them in the main ppa along with the final release.

**Comment by blattms** [comment]
I am lost.
OPM master does not compile on Ubuntu 20.04. So how can any developer currently use this system with OPM master?
Or did someone fix OPM/opm-simulators#4472?

**Comment by akva2** [comment]
it compiles if you disable hdf5 support.

**Comment by goncalvesmachadoc** [comment]
We in TNO are using Ubuntu 20.04. We have avoid rebasing since the issue. I just asked IT for Ubuntu 22.10 today, currently in the process of getting it to work.

**Comment by akva2** [comment]
jenkins build this please

**Pull request merged**
