### PR TITLE
Pack only unique VFP tables

### PR DESCRIPTION
**Pull request by joakim-hove**
Ma - look I can write templates ;-)

@bska - can you take this for a ride?

<sub>Bjarne, forgive him, for he do not know what he is doing.</sub>

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
> @bska - can you take this for a ride?

I ran the model which triggered excessive memory consumption distributing the VFP tables.  It got much further with this PR, but not all the way through.  Instead, we triggered an error about the VFP table being [inaccessible](https://github.com/OPM/opm-simulators/blob/1af403c45d3bb317b5203d9fe3c937cf79680636/opm/simulators/wells/WellInterface_impl.hpp#L1276-L1277) at
```
Report step 177/476 at day 2430/7573,
```
At that report step the well in question gets new controls through `WCONHIST` and the VFP table number for the well (item 7) is positive.  For what it's worth this positive VFP table number is the same as that reported in the error message.  It is strange though because the same well is also in the the previous `WCONHIST` with the same positive VFP table number and that step goes through.

I don't have any further information at this time.  It takes about 50 minutes in release mode with `mpirun -np 6` to get to the failing report step.

**Comment by joakim-hove** [comment]
> I ran the model which triggered excessive memory consumption distributing the VFP tables. It got much further with this PR, but not all the way through. Instead, we triggered an error about the VFP table being inaccessible at

OK - thank you; looks like the basic serialization and the memory problem works, but obviously there is still a bug somewhere. Less than obvious for me. Can you send me the full error message. I am in the process of getting a copy of the model.

**Comment by bska** [comment]
> Can you send me the full error message.

I'll send you a personal e-mail.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
I ran the version of this PR from before the latest rebase/update and this time it got all the way to the end.
```
Number of MPI processes:         6
Threads per MPI process:         2
Total time (seconds):         4966.01 
Solver time (seconds):        4960.23 
 Assembly time (seconds):     1259.09 (Failed: 389.0; 30.9%)
   Well assembly (seconds):    229.43 (Failed: 71.6; 31.2%)
 Linear solve time (seconds): 2845.69 (Failed: 643.5; 22.6%)
   Linear setup (seconds):     423.47 (Failed: 151.3; 35.7%)
 Update time (seconds):        419.48 (Failed: 145.8; 34.8%)
 Pre/post step (seconds):      396.45 (Failed: 9.9; 2.5%)
 Output write time (seconds):   35.09
Overall Linearizations:      16679    (Failed: 5313; 31.9%)
Overall Newton Iterations:   14847    (Failed: 5313; 35.8%)
Overall Linear Iterations:  176630    (Failed: 34617; 19.6%)
```
Unless you'd like me to rerun based on the very latest version of this patch (including commit c24ed3f) I'm tempted to say that you've solved the most pressing issue in distributing the VFP tables.

**Comment by joakim-hove** [comment]
> Unless you'd like me to rerun based on the very latest version of this patch (including commit c24ed3f) I'm tempted to say that you've solved the most pressing issue in distributing the VFP tables.

Thank you - I am running through the screaming latest and greatest now locally; If that is OK I consider this ready for merge.

**Comment by joakim-hove** [comment]
jenkins build this please

**Pull request merged**
