### PR TITLE
changed: use initializer list for enums

### PR DESCRIPTION
**Pull request by akva2**
quells a sca warning. no hard feelings if you prefer to keep it as-is.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
@akva2 is @joakim-hove on the jenkins list for this repo? I'll try to trigger as well.

**Comment by atgeirr** [comment]
jenkins build this please

**Pull request merged**
