### PR TITLE
Minimize dune dependencies

### PR DESCRIPTION
**Pull request by akva2**
In particular this should fix build again. Can you test @bska or are you already on vacation?

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by bska** [comment]
> In particular this should fix build again. Can you test @bska or are you already on vacation?

I'm travelling right now, but I'll test this once I'm at my destination.

**Comment by akva2** [comment]
jenkins build this please

**Comment by bska** [comment]
> > In particular this should fix build again. Can you test @bska or are you already on vacation?
> 
> I'm travelling right now, but I'll test this once I'm at my destination.

Good news; this does indeed fix my build.  Please rebase to fix the tiny merge conflict and then we'll get this into the master branch right away.

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks a lot. I'll merge into master.

**Pull request merged**
