### PR TITLE
linearInterpolation.hpp: reformat and use stl

### PR DESCRIPTION
**Pull request by akva2**
Remove tabs and reformat. And replace home-grown binary search with std::lower_bound.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
I like it.  For one additional refactoring, maybe we could have a helper function of the form
```C++
std::pair<double, int>
linearInterpolationSlope(const std::vector<double>& xv,
                         const std::vector<double>& yv,
                         const double x)
{
    const auto i = tableIndex(xv, x);
    return { (yv[i + 1] - yv[i]) / (xv[i + 1] - xv[i]), i };
}
```
and then implement the others in terms of that?

On another note, and not a new problem, this code is going to index out of bounds if `xv.size() < 2`.  Finally, it will fail if `xv[i] == xv[i + 1]` for some `i`, but that's acceptable I guess.

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks a lot for the updates.  This looks good to me now.  Please merge when the build check is green.

**Pull request merged**
