### PR TITLE
removing whitespaces from test_ERst.cpp

### PR DESCRIPTION
**Pull request by GitPaean**
This PR is created to test the master branch.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
The recent update of ECL broke the building of OPM master. 

``` c++
In file included from /usr/include/signal.h:80:0,
                 from /var/lib/jenkins/post-builder/workspace/opm-common-PR-builder/mpi/install/include/ert/util/util.h:28,
                 from /var/lib/jenkins/post-builder/workspace/opm-common-PR-builder/mpi/install/include/ert/util/type_macros.hpp:8,
                 from /var/lib/jenkins/post-builder/workspace/opm-common-PR-builder/mpi/install/include/ert/ecl/smspec_node.hpp:29,
                 from /var/lib/jenkins/post-builder/workspace/opm-common-PR-builder/src/opm/output/eclipse/Summary.cpp:29:
/var/lib/jenkins/post-builder/workspace/opm-common-PR-builder/src/opm/output/eclipse/Summary.cpp: In member function 'void Opm::out::Summary::eval(Opm::SummaryState&, int, double, const Opm::EclipseState&, const Opm::Schedule&, const Wells&, const std::map<std::__cxx11::basic_string<char>, double>&, const std::map<std::__cxx11::basic_string<char>, std::vector<double> >&, const std::map<std::pair<std::__cxx11::basic_string<char>, int>, double>&) const':
/var/lib/jenkins/post-builder/workspace/opm-common-PR-builder/src/opm/output/eclipse/Summary.cpp:1543:20: error: expected initializer before '.' token
             double si_value = value_pair.second;
                    ^
/var/lib/jenkins/post-builder/workspace/opm-common-PR-builder/src/opm/output/eclipse/Summary.cpp:1544:64: error: '_sifields' was not declared in this scope
             double output_value = es.getUnits().from_si(unit , si_value );
                                                                ^
/var/lib/jenkins/post-builder/workspace/opm-common-PR-builder/src/opm/output/eclipse/Summary.cpp:1558:24: error: expected initializer before '.' token
                 double si_value = value_pair.second[reg];
                        ^
/var/lib/jenkins/post-builder/workspace/opm-common-PR-builder/src/opm/output/eclipse/Summary.cpp:1559:68: error: '_sifields' was not declared in this scope
                 double output_value = es.getUnits().from_si(unit , si_value );
                                                                    ^
/var/lib/jenkins/post-builder/workspace/opm-common-PR-builder/src/opm/output/eclipse/Summary.cpp:1571:20: error: expected initializer before '.' token
             double si_value = value_pair.second;
                    ^
/var/lib/jenkins/post-builder/workspace/opm-common-PR-builder/src/opm/output/eclipse/Summary.cpp:1572:64: error: '_sifields' was not declared in this scope
             double output_value = es.getUnits().from_si(unit , si_value );
```

**Comment by GitPaean** [comment]
It is the last merge from ECL, https://github.com/equinor/libecl/pull/634

**Comment by bska** [comment]
> It is the last merge from ECL, [equinor/libecl#634](https://github.com/equinor/libecl/pull/634)

They may need to do something like Equinor/libecl#397.  Redeclaring Posix function `signal()` isn't as harmless as they appear to think.

**Comment by bska** [comment]
For what it's worth I was able to restore my local build of opm-common through the patch below on top of current LibECL master.  I suspect that macros in `<signal.h>` were interfering with the names used in `Summary.cpp`.

---

```diff
diff --git a/lib/include/ert/util/util.h b/lib/include/ert/util/util.h
index 073fe8581..7f0c18055 100644
--- a/lib/include/ert/util/util.h
+++ b/lib/include/ert/util/util.h
@@ -25,7 +25,7 @@
 #include <stdarg.h>
 #include <sys/types.h>
 #include <time.h>
-#include <signal.h>
+/* #include <signal.h> */
 
 
 #include <ert/util/ert_api_config.hpp>
@@ -390,10 +390,10 @@ typedef bool (walk_dir_callback_ftype)   (const char * , /* The current director
 
 /* Redefining sighandler_t in case it isn't defined (Windows).
 This is harmless on other platforms. */
-typedef void (*sighandler_t)(int);
+/* typedef void (*sighandler_t)(int); */
 /* When installing our abort handler, remeber if there was a previous one,
 * so we can call that afterwards */
-extern sighandler_t previous_abort_handler;
+extern void (*previous_abort_handler)(int);
 
 #ifdef _MSC_VER
 #define util_abort(fmt , ...) util_abort__(__FILE__ , __func__ , __LINE__ , fmt , __VA_ARGS__)
diff --git a/lib/util/util.c b/lib/util/util.c
index c23445a83..000eb03ad 100644
--- a/lib/util/util.c
+++ b/lib/util/util.c
@@ -4405,7 +4405,7 @@ char * util_realloc_sprintf(char * s , const char * fmt , ...) {
   The various signals can be found in: /usr/include/bits/signum.h
 */
 
-sighandler_t previous_abort_handler = SIG_IGN;
+void (*previous_abort_handler)(int) = SIG_IGN;
 
 void util_abort_signal(int the_signal) {
     if (previous_abort_handler == SIG_IGN) {
@@ -4426,7 +4426,7 @@ void util_install_signals(void) {
                                              Killing with SIGKILL (-9) will not give a backtrace.*/
 
 
-  sighandler_t previous_abort = signal(SIGABRT , util_abort_signal);    /* Signal abort. */
+  void (*previous_abort)(int) = signal(SIGABRT , util_abort_signal);    /* Signal abort. */
   if (previous_abort != util_abort_signal) {
       /* Let previously installed abort handler (i.e. python faulthandler) be called in the end */
       previous_abort_handler = previous_abort;
@@ -4443,7 +4443,7 @@ void util_install_signals(void) {
 
 static void update_signal( int signal_nr) {
 
-  sighandler_t current_handler = signal(signal_nr , SIG_DFL);
+  void (*current_handler)(int) = signal(signal_nr , SIG_DFL);
   if (current_handler == SIG_DFL)
     signal( signal_nr , util_abort_signal );
   else
```

**Comment by atgeirr** [comment]
After discussion with @akva2 I have proposed a workaround in #885, which if it works should not be too much of a hack: using commit 7abee4f1a19dbba0c845e3dc23f7950021e12059 instead of the master branch by default, but still letting the user override that on github.

**Comment by joakim-hove** [comment]
jenkins build this libecl=637 please

**Comment by joakim-hove** [comment]
jenkins build this libecl=637 please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this libecl=637 please

**Comment by GitPaean** [comment]
https://github.com/equinor/libecl/pull/637 was merged.

**Comment by GitPaean** [comment]
jenkins build this libecl please

**Comment by bska** [comment]
Does this serve a purpose anymore?  The upstream LibECL issue was already solved.

**Comment by joakim-hove** [comment]
> Does this serve a purpose anymore?

Probably not

**Comment by GitPaean** [comment]
reopening this to test master branch.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
reopening this to test master branch.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by GitPaean** [comment]
Maybe here is a better place to update_data for the master branch?

**Pull request closed without merging**
