### PR TITLE
Restart File: Output Well's Preferred Phase

### PR DESCRIPTION
**Pull request by bska**
Note: We're missing the 'LIQUID' option (integer value 4) since
```C++
Well::getPreferredPhase()
```
does not return that value.

### CODE REVIEW

**Comment by bska** [comment]
Note: This will update all reference data since it will output one additional non-zero value to the `IWEL` vector for each well.

Also, please don't merge this until we've really clarified that the `IWEL` index is really correct.

**Comment by joakim-hove** [comment]
I am happy to see this come so fast!

> Also, please don't merge this until we've really clarified that the IWEL index is really correct.

Sure!

**Comment by joakim-hove** [comment]
Is this considered ready for merge now? After the obligatory `update_data` dance.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
> Is this considered ready for merge now?

No, I don't think so.  It sort of passes my local checks apart from needing new reference data but I'd like confirmation that we're still able to restart ECLIPSE from the updated files.  Also, right now we don't read the preferred phase value back out of the restart file.  Fixing the latter is easy however.

**Comment by joakim-hove** [comment]
> Also, right now we don't read the preferred phase value back out of the restart file

That is what I am desperately chasing ....

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
This has been kept alive for some time! Is "Ready for merge" in the pipeline?

**Comment by bska** [comment]
> Is "Ready for merge" in the pipeline?

Still awaits upstream testing.

**Comment by jalvestad** [comment]
I have tested this pull request on several data sets with both injection and production wells and it works OK on all these tests! The injection wells have experienced varying preferred phase during the simulation and this PR works OK for these cases.

**Comment by bska** [comment]
> I have tested this pull request on several data sets with both injection and production wells and it works OK on all these tests!

Thank you for testing!  I then believe this is ready for final review but I will however hold back on marking it as such until PRs OPM/opm-simulators#2909 and OPM/opm-tests#432 have been merged.  This PR, by construction, will change the contents of the restart files and therefore require an update to our reference solutions.

**Comment by bska** [comment]
I'm marking this as "ready for review" now and I'm running a build check.  I expect test failures in all regression tests since this PR will change each well's `IWEL` array.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
I have reviewed the [test failures](https://ci.opm-project.org/job/opm-common-PR-builder/2820/testReport/) and they're all of the expected form ("preferred phase differs").  Once this is approved we will have to generate new reference solutions before merging the PR.

**Comment by joakim-hove** [comment]
I have Bernt ready to merger this for literally months

**Comment by bska** [comment]
> I have Bernt

And I have Ernie :wink:

**Comment by bska** [comment]
> I have [been] ready to merger this for literally months

So I take it that's maintainer approval?  If so, I'll update the reference data.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
> > I have [been] ready to merger this for literally months
> 
> So I take it that's maintainer approval? If so, I'll update the reference data.

No response from maintainer.  Reading between the lines I think this PR is nevertheless approved, so I am going to go ahead and update the reference data before merging this.

**Comment by bska** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=435 please

**Comment by joakim-hove** [comment]
> Reading between the lines I think this PR is nevertheless approved

That is correct!

**Comment by bska** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-simulators=2917 update_data please

**Comment by bska** [comment]
jenkins build this opm-simulators=2917 opm-tests=437 please

**Comment by bska** [comment]
jenkins build this opm-simulators=2917 update_data please

**Comment by joakim-hove** [comment]
I have lost track og this, but I really thought IT was om the way in?

**Comment by bska** [comment]
> have lost track og this, but I really thought IT was om the way in?

It was&mdash;I promise.  However we got blocked on not being able to update all the reference data.  Part of that is solved in OPM/opm-simulators#2917 and the other part was solved in #2121.  I was just preparing to launch the final data update now.

**Comment by bska** [comment]
jenkins build this opm-simulators=2917 update_data please

**Comment by bska** [comment]
> I was just preparing to launch the final data update now.

I've reviewed the [regression test failures](https://ci.opm-project.org/job/opm-common-PR-builder/2869/testReport/) and  I'm satisfied that the tests fail only because item 15 of `IWEL` changes.  I am going to run the build check against the updated reference data in OPM/opm-tests#440 and merge if that comes back green.

**Comment by bska** [comment]
jenkins build this opm-simulators=2917 opm-tests=440 please

**Comment by bska** [comment]
jenkins build this opm-simulators=2917 opm-tests=440 please

**Comment by bska** [comment]
Build check is green and updated reference solutions have been installed in the opm-tests repository.  Merging this now per prior approval.

**Pull request merged**
