### PR TITLE
Avoid setting UDAs to 0 default in GCONINJE

### PR DESCRIPTION
**Pull request by vkip**
Needed for https://github.com/OPM/opm-common/pull/4346

### CODE REVIEW

**Comment by vkip** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Yep, this makes a lot of sense.  There aren't supposed to be any default injection limits at the group level.

**Comment by bska** [comment]
> There aren't supposed to be any default injection limits at the group level.

Tracing the history here, it appears that the zero default value was introduced when the `GCONINJE` file was first added in commit 2ec09d4cf&ndash;originally commit OPM/opm-parser@18bf0f2 from PR OPM/opm-parser#44.

**Comment by vkip** [comment]
Makes sense - pre-UDA remnants then, I guess.

**Pull request merged**
