### PR TITLE
Use restart object in regression testing

### PR DESCRIPTION
**Pull request by joakim-hove**
The purpose of this PR is to enable more context rich comparisons in the regression testing; instead of
```
Keyword: IWEL, origin Restart, sequence 51
 
Value index                 = 3026
(first value, second value) = (1, 0)
 
Non floating point values not identical 
```
you can now get something like:
```
Different active_control for well: OPL1  reference: -1  simulation: 4
```
This is only a first step - just what I need right now - if it is deemed valuable it can be improved & extended. The current code is *in addition* to the existing code and will not (yet) influence the pass/fail status of a test.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Comments to this?

**Review by bska — COMMENTED** [review]
Looks good for the most part, except the designations "reference" and "simulation".  For better or worse, inside `EclRegressionTest` you don't (currently) know which of the cases is the reference and which is the new simulation case.  For instance, the [pore volume comparison test]() for Norne flips those two around.

Unless we change the semantics of the utility I think we can only refer to these as "case 1" and "case 2" (or some other, equally non-descriptive, terms).

**Comment by joakim-hove** [comment]
>Unless we change the semantics of the utility I think we can only refer to these as "case 1" and "case 2" (or some other, equally non-descriptive, terms).

I really think we should change the whole implentation to use e.g. reference and simulation, I can do that. If there are objections to such a change I will change case1 and case2

**Comment by joakim-hove** [comment]
I changed back to `case1` and `case2` - changing to e.g. `reference` and `simulation` could be part of a larger refactor.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks for the updates.  This looks good to me now and I'll merge once the build check succeeds.

I agree that we probably want to refer to "reference" and "simulation" (comparison candidate? something else) instead of "case1" and "case2", but that doing so will require a bit of a coordinated effort across the modules.

**Comment by bska** [comment]
> This looks good to me now and I'll merge once the build check succeeds.

Build check is green.  I'll merge into master.

**Pull request merged**
