### PR TITLE
Pass sibling dirs HINTS to find_package calls for opm-parser.

### PR DESCRIPTION
**Pull request by blattms**
These take precendence over the package registry where we have no control
on which entry will be used. The registry is only the last resort.

On some Linux version the most recently created package registry key will
be used. Please not that an entry is only created for a build try that is
not already in the registry. If there is already key, then not even the
modification date of the key will be updated. This default behaviour might
lead to strange mixes of build configurations.

Alternative to #256

### CODE REVIEW

**Comment by blattms** [comment]
BTW everything after line 73 could be stripped as it is buggy and the stuff above should always work for recent versions of opm-parser and

**Comment by joakim-hove** [comment]
jenkins build this with downstreams please

**Comment by joakim-hove** [comment]
@blattms: Is this PR enough to solve your problems, or do you also need to disable `EXPORT` from opm-parser with something like: https://github.com/OPM/opm-parser/issues/1085#issuecomment-307754442

**Comment by joakim-hove** [comment]
> BTW everything after line 73 could be stripped 

Yes - I guess it *should* be stripped.

**Comment by akva2** [comment]
looks fine. please drop the dead code.

**Comment by akva2** [comment]
oh, and please use the opportunity to get rid of the return() and mind the mark_as_advanced

**Comment by blattms** [comment]
Requested changes applied. mark_as_advanced is still there. IMHO it has no effect as opm-parser_LIBRARIES is not in CMakeCache.txt anyway.

@joakim-hove Yes it solves my problem and there is no need for additional changes.

**Comment by joakim-hove** [comment]
>  Yes it solves my problem and there is no need for additional changes.

Cool - thank you. @akva2 will merge this when ready.

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
... just to test the last cleanup commit.

**Comment by akva2** [comment]
probably a good idea to push it first ;)

**Comment by akva2** [comment]
and if there are no cached variables, please do not mark them as such. i wasn't sure..

**Comment by blattms** [comment]
Agreed.

**Comment by blattms** [comment]
jenkins build this please

**Comment by akva2** [comment]
thanks!

**Pull request merged**
