### PR TITLE
WIP: Store THPRES to restart file

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by totto82** [comment]
Great. When this is in place we can do some clean up in the restart functionality in flow. This needs to be extended with an option for writing defaulted thpress values as computed from the initial conditions.

**Comment by joakim-hove** [comment]
> This needs to be extended with an option for writing defaulted thpress values as computed from the initial conditions.

Dang - that was not on my radar :-( Can you point me to the code where this initial value is calculated?

**Comment by totto82** [comment]
It is calculated and stored in ewoms/ebos/eclthresholdpressure.hh.

**Comment by joakim-hove** [comment]
This must die - continued here: #391

**Pull request closed without merging**
