### PR TITLE
updating liquid rate for WCONHIST

### PR DESCRIPTION
**Pull request by GitPaean**
Otherwise, we get zero value for liquid rate. 

I will check whether I can find related test here. If yes, I will update the test.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by bska** [comment]
> If yes, I will update the test.

And otherwise you should **add** a set of tests.

**Comment by GitPaean** [comment]
> And otherwise you should add a set of tests.

you are right, I am trying to do that. I do have a little complaining about that it takes much more times to figure out the tests than fixing the problem itself, sometimes.  

Anyway, it is correct thing to do to have a test to guard the development. Otherwise, it might be broken later without noticing it.

**Comment by bska** [comment]
> I do have a little complaining about that it takes much more times to figure out the tests than fixing the problem itself, sometimes.

Well, you can always ask for guidance.  On the other hand
```sh
find tests -name '*.cpp' | xargs grep -l WellProductionProperties
```
is a decent start at a list of files.

**Comment by GitPaean** [comment]
> is a decent start at a list of files.

Things are more tricky. I will come back to the `WellTests.cpp` to understand things better. 

I am having a difficult time in understanding the following test
```
 892 BOOST_AUTO_TEST_CASE(WCH_Rates_Defaulted_BHP_Defaulted)
 893 {
 894     const Opm::WellProductionProperties& p =
 895         WCONHIST::properties(WCONHIST::all_defaulted());
 896 
 897     BOOST_CHECK( !p.hasProductionControl(Opm::WellProducer::ORAT));
 898     BOOST_CHECK( !p.hasProductionControl(Opm::WellProducer::WRAT));
 899     BOOST_CHECK( !p.hasProductionControl(Opm::WellProducer::GRAT));
 900     BOOST_CHECK(p.hasProductionControl(Opm::WellProducer::LRAT));
 901     BOOST_CHECK( !p.hasProductionControl(Opm::WellProducer::RESV));
 902     BOOST_CHECK_EQUAL(p.controlMode , Opm::WellProducer::LRAT);
 903 
 904     BOOST_CHECK(p.hasProductionControl(Opm::WellProducer::BHP));
 905     BOOST_CHECK_EQUAL(p.VFPTableNumber, 12);
 906     BOOST_CHECK_EQUAL(p.ALQValue, 18.);
 907     BOOST_CHECK_EQUAL(p.BHPLimit, 100.);
 908 }
```

Anyway, I update some tests in ScheduleCreateFromDeck.cpp. I this PR is protected by the tests there.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by bska** [comment]
> I am having a difficult time in understanding the following test

That really comes down to what `hasProductionControl()` is supposed to return.  A well whose control mode is specified by `WCONHIST` always, unconditionally, supports being controlled by all of `{O,W,G,L}RAT` and `RESV`.  On the other hand, its active/target control mode is not supposed to change during the simulation (until its target/control is explicitly reset using a subsequent `WCON*` request) so the non-active control modes aren't supposed to be interpreted as limits.

You altered that behaviour in commit 35ecd2e37a910cfbd4ab8d6a178f1ab7d73eb240 (PR OPM/opm-parser#1179), so you will have to retrace the steps that led to that change.

**Comment by bska** [comment]
> Basically it means for a WCONHIST well, it will always has a BHP limit

That's only partially correct.  If a history well is set to any of the rate controls (which is **always** possible, even if all observed rates are defaulted&mdash;that's what I meant earlier), then the BHP "limit" is atmospheric pressure.  In that case it is essentially an error for the well to switch to BHP target.  These wells only have non-trivial BHP limits if the observed BHP value (item 10 of `WCONHIST`) is not defaulted.

**Comment by GitPaean** [comment]
>  In that case it is essentially an error for the well to switch to BHP target. 

It is correct. But it will prevent the well gets negative BHP, which is possible in `numerical` simulation. Non-linear iteration basically can send us anywhere.  Anyway, we implement it as a 1 atm. bhp limit. 

> These wells only have non-trivial BHP limits if the observed BHP value (item 10 of WCONHIST) is not defaulted.

I think if the control mode is not BHP control, the observed BHP value will not serve as a limit, the BHP limit is possibly still 1 atm with non-defaulted observed BHP value, unless `WELTARG` or other keywords join to change the BHP limit.

**Comment by GitPaean** [comment]
Some information kindly related to the discussion here. 

One WCONHIST case we received yesterday, well is under RATE control, defaulted BHP limit (1 atm.). For some part of the simulation, some well actually operates at the defaulted BHP limit. 

OPM-flow fails for this case.  A fix is incoming when time permits.  Most likely, it will be the PR https://github.com/OPM/opm-simulators/pull/1362 and a possible PR in opm-common.

**Pull request merged**
