### PR TITLE
Remove some empty headers

### PR DESCRIPTION
**Pull request by akva2**

### CODE REVIEW

**Review by bska — COMMENTED** [review]
Maybe I'm missing something, but this PR does not appear to actually remove `InjectionControls.hpp`.  As far as I can tell the PR "only" removes the references to the file.  Did you accidentally forget `git rm path/to/InjectionControls.hpp`?

**Comment by akva2** [comment]
indeed, I forgot the rm for InjectionControls.hpp.

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks a lot for the updates.  I'll merge into master.

**Pull request merged**
