### PR TITLE
Some janitoring

### PR DESCRIPTION
**Pull request by akva2**
Last commit (std::transform usage) might not be wanted, it's a little of bend-over-backwards for cppcheck.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Regarding the last commit I think the proposed solution is a step backwards in readability - I would prefer to not merge that.

**Comment by akva2** [comment]
fair enough.

**Comment by akva2** [comment]
jenkins build this please

**Pull request merged**
