### PR TITLE
Fix Default Value Initializers for Field Properties KR*R

### PR DESCRIPTION
**Pull request by bska**
In current master the `KR*R` properties (i.e., `KRWR` and `KRGR`) get initialized as zero unless explicitly set in the input.  The reason is that the `findKr*r()` functions select the first relative permeability values in the phase columns and these are always zero.  This PR corrects that behaviour by returning the relative permeability values in the displacing saturations

 * `KRWR = Krw(Sw=1 - Sowcr - Sgl)`
 * `KRGR =  Krg(Sg=1 - Sogcr - Swl)`

As a preparation for this change we switch to collecting/calculating all saturation end-points in all tables for each call to `Opm::satfunc::init()`.  This is more work than needed for any single property, but I would like to expose the collection of end-points to the `FieldProps` class (as a member) in which case we would calculate the end-points at most once and then be able to reuse the values to initialize subsequent properties.

We also pull the "family 1" special casing of `SOGCR` (subtract `SWL`) into the table-scanning code.  This enables removing the hackish `FieldProps::subtract_swl()` function and to simplify the logic of  `FieldProps::init_get()`.

With these changes the `FILLEPS` operation now produces expected output in almost all cases.  We currently do not support `TOLCRIT` as part of these initializers.  That will be the subject of a follow-up PR.

Note: This change does not actually appear to influence any simulation results.  As far as I can tell, Flow's saturation function interpolants do not incorporate the `KR*R` vertical scaling options.

---

### Example Model (BASE_MODEL1) ###

[BASE_MODEL_1](https://github.com/OPM/opm-tests/blob/13371acd15717a6bb4ecf6f196564c7f97fd312b/model1/BASE_MODEL_1.DATA) from opm-tests uses [`FILLEPS`](https://github.com/OPM/opm-tests/blob/13371acd15717a6bb4ecf6f196564c7f97fd312b/model1/BASE_MODEL_1.DATA#L262) to request saturation function end-points be output the `.INIT` file even if not provided in the input data.  With the changes in this PR we're able to output non-trivial `KRGR` values and also recover scaled saturation function plots that coincide with the unscaled curves.

|    | KRGR Property | Saturation Functions |
|----- | ------------- | ----------------- |
|Current Master | BASE_MODEL_1_MASTER_3D_View_KRGR_00_01_Feb_2000 | base kr master |
| This PR | BASE_MODEL_1_DEV_3D_View_KRGR_00_01_Feb_2000| base kr dev |

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
The KR details are beyond me, but I like the use of a struct with endpoint values.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
Note: This is going to change a couple of regression tests due to `FILLEPS` requesting `KR*R` property output.  Those properties are going to be different as a result of this PR.  Please don't issue any `update_data` requests until the data update that is already in flight (OPM/opm-tests#308) is merged into master.

**Comment by joakim-hove** [comment]
> Please don't issue any update_data requests until the data update that is already in flight

OK - I'll let you guide it in.

**Comment by bska** [comment]
> > Please don't issue any update_data requests until the data update that is already in flight
> 
> OK - I'll let you guide it in.

The data update previously mentioned (OPM/opm-tests#308) has been merged into master.  I have also rebased this onto the current opm-common master branch.  I now consider this work to be complete and submit it for final review and an update to the reference cases that use `FILLEPS`.

**Comment by bska** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=310 please

**Comment by bska** [comment]
I'm merging this into master now per prior approval.  The reference data has been updated accordingly in OPM/opm-tests#310.

**Pull request merged**
