### PR TITLE
Added keywords beginning w/ A

### PR DESCRIPTION
**Pull request by stefoss23**

### CODE REVIEW

**Comment by stefoss23** [comment]
jenkins build please

**Comment by stefoss23** [comment]
jenkins build this please

**Comment by stefoss23** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
You are fast :-)

**Comment by OPMUSER** [comment]
Can we add the ACTIONG and ACTIONS keywords as recognized by the Parser but have no functionality? I have these as unrecognized in the manual.

**Comment by joakim-hove** [comment]
They were added in a previous A round.

**Comment by OPMUSER** [comment]
Okay, I'll change - do you ever sleep :-)

**Pull request merged**
