### PR TITLE
Make only one json for GCONPROD

### PR DESCRIPTION
**Pull request by goncalvesmachadoc**
Is there a reason to have two GCONPROD json files? Could we simplify as proposed in the this PR?

### CODE REVIEW

**Comment by goncalvesmachadoc** [comment]
jenkins build this please

**Comment by bska** [comment]
> Is there a reason to have two GCONPROD json files?

I don't think so, at least not anymore.  As far as I can tell, the 001 version was introduced in commit 86851e2fe, which does not have a lot of justification in its commit message.

**Comment by goncalvesmachadoc** [comment]
Ok, thanks. Will change this PR to ready for review then.

**Comment by bska** [comment]
> Ok, thanks. Will change this PR to ready for review then.

Very good.  As it happens, I was able to track down the original PR (OPM/opm-parser#955, from before OPM-Parser was [merged into OPM-Common](https://github.com/OPM/opm-common/pull/341)).  Even then there was [very little discussion](https://github.com/OPM/opm-parser/pull/955#issuecomment-257569626) about having a separate `GCONPROD` file in 001.

**Review by bska — APPROVED** [review]
This looks good to me and I'll merge into master.

**Pull request merged**
