### PR TITLE
Region cache fp

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by akva2** [comment]
this broke test_Restart (and likely other stuff) - try compiling in debug. valgrind says

```==18337== Invalid read of size 8
==18337==    at 0xD32CEE: std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Opm::FieldProps::FieldData<int> >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Opm::FieldProps::FieldData<int> > >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_bucket_index(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long) const (hashtable.h:631)
==18337==    by 0xD3153E: std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Opm::FieldProps::FieldData<int> >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Opm::FieldProps::FieldData<int> > >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::find(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (hashtable.h:1424)
==18337==    by 0xD30018: std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Opm::FieldProps::FieldData<int>, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Opm::FieldProps::FieldData<int> > > >::find(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (unordered_map.h:920)
==18337==    by 0xD29476: Opm::FieldProps::FieldData<int>& Opm::FieldProps::get<int>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (FieldProps.cpp:366)
==18337==    by 0xC766C9: Opm::FieldProps::FieldData<int> const* Opm::FieldProps::try_get<int>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (FieldProps.hpp:136)
==18337==    by 0xC75BBD: std::vector<int, std::allocator<int> > const* Opm::FieldPropsManager::try_get<int>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const (FieldPropsManager.cpp:52)
==18337==    by 0xC758D2: std::vector<int, std::allocator<int> > const& Opm::FieldPropsManager::get<int>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const (FieldPropsManager.cpp:39)
==18337==    by 0x95F9C1: Opm::out::Summary::SummaryImplementation::SummaryImplementation(Opm::EclipseState const&, Opm::SummaryConfig const&, Opm::EclipseGrid const&, Opm::Schedule const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (Summary.cpp:2063)
==18337==    by 0x9619E8: Opm::out::Summary::Summary(Opm::EclipseState const&, Opm::SummaryConfig const&, Opm::EclipseGrid const&, Opm::Schedule const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (Summary.cpp:2360)
==18337==    by 0x940D14: Opm::EclipseIO::Impl::Impl(Opm::EclipseState const&, Opm::EclipseGrid, Opm::Schedule const&, Opm::SummaryConfig const&) (EclipseIO.cpp:122)
==18337==    by 0x941AB9: Opm::EclipseIO::EclipseIO(Opm::EclipseState const&, Opm::EclipseGrid, Opm::Schedule const&, Opm::SummaryConfig const&) (EclipseIO.cpp:262)
==18337==    by 0x6D1F33: Opm::EclipseReadWriteWellStateData::test_method() (test_Restart.cpp:581)
==18337==  Address 0xd8 is not stack'd, malloc'd or (recently) free'd
==18337== 
==18337== Warning: client switching stacks?  SP change: 0x97e59f8 --> 0x1ffeffecd0
==18337==          to suppress, use: --max-stackframe=137262895832 or greater
unknown location(0): fatal error: in "EclipseReadWriteWellStateData": memory access violation at address: 0x000000d8: no mapping at fault address


```

**Comment by joakim-hove** [comment]
This was a rough day... 😕

**Comment by akva2** [comment]
forgot to mention, this is without the define so it is the fallback path - hence not seen on jenkins.

**Comment by joakim-hove** [comment]
Ahhh - thanks.

**Comment by blattms** [comment]
My guess: The EclipseGrid passed to SummaryImplementation exhibits subtle differences to the one in EclipseState since it is constructed from the actual (processed) grid in eclwriter.hh:
```
./ebos/eclwriter.hh-            eclIO_.reset(new Opm::EclipseIO(simulator_.vanguard().eclState(),
./ebos/eclwriter.hh:                                            Opm::UgGridHelpers::createEclipseGrid(globalGrid_, simulator_.vanguard().eclState().getInputGrid()),
./ebos/eclwriter.hh-                                            simulator_.vanguard().schedule(),
./ebos/eclwriter.hh-                                            simulator_.vanguard().summaryConfig()));
```

These are muddy waters..., but at least it is not a distributed grid at this point.

**Comment by akva2** [comment]
markus, this is in opm-common, long before we hit the ecl writer code :)

**Comment by joakim-hove** [comment]
OK - fix here: #1267 

Again jenkins will build with the define and not be that relevant; I was a little anxious something like this would pop up - and indeed it did - quite fast :-(

**Comment by akva2** [comment]
fast is good - long lingering problems are the real buggers.

**Comment by blattms** [comment]
I could not agree more.

**Pull request merged**
