### PR TITLE
Update INTEHEAD[51] value based on presence of GCONPROD / GCONINJE

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
The testcase `spe9group/SPE9_CP_GROUP` has both `GCONINJE` and `GCONPROD` - and should according to the logic in this PR have `INTEHEAD[51] = 2`. Will update data.

**Comment by bska** [comment]
> Will update data.

Please wait until OPM/opm-simulators#2909 and OPM/opm-tests#432 have been merged to avoid conflicts.

**Comment by joakim-hove** [comment]
> Please wait until 

OK - will do

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
> > Please wait until
> 
> OK - will do

Thanks holding back.  The other reference data update in flight (OPM/opm-simulators#2909, OPM/opm-tests#432) has been merged which unblocks this.  I'll launch a new data update build.

**Comment by bska** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=434 please

**Comment by bska** [comment]
jenkins build this opm-tests=434 please

**Comment by bska** [comment]
New reference solution is installed on the CI system. Merging this now to bring the system state back up to date.

**Pull request merged**
