### PR TITLE
Inline Schedule::getMaxNumCompletionsForWells() in test

### PR DESCRIPTION
**Pull request by joakim-hove**
The method `Schedule::getMaxNumCompletionsForWells()` was only used in the tests `test_serialize_ICON` and `test_serialize_SCON`; with this PR the method is removed from the `Schedule` class and instead inlined in the test source; to avoid duplication the two test sources are combined to one.

Edit: As indicated by @bska in a comment below there was room for more removal ...

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
Note that we don't actually need `serialize_*CON` anymore. The feature set is entirely contained in AggregateConnData nowadays. It might just be better to remove these functions alltogether.

**Comment by joakim-hove** [comment]
> Note that we don't actually need serialize_*CON anymore.  [...] It might just be better to remove these functions alltogether.

I.e. the full [WellDataSerializers.cpp](https://github.com/OPM/opm-common/blob/master/src/opm/output/eclipse/WellDataSerializers.cpp)?

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
I'll merge later today.

**Comment by bska** [comment]
> > Note that we don't actually need serialize_*CON anymore.  [...] It might just be better to remove these functions alltogether.
> 
> I.e. the full [WellDataSerializers.cpp](https://github.com/OPM/opm-common/blob/master/src/opm/output/eclipse/WellDataSerializers.cpp) can go?

That is correct.  For a minute I was worried that we might still need it for the `OPM_IWEL` and `OPM_XWEL` [extended vectors](https://github.com/OPM/opm-common/blob/34dfbee01be43247058a5f38187ca5463df5e72d/src/opm/output/eclipse/RestartIO.cpp#L376-L387), but I've now verified that those vectors are implemented as the [`serialize_OPM_IWEL()`](https://github.com/OPM/opm-common/blob/34dfbee01be43247058a5f38187ca5463df5e72d/src/opm/output/eclipse/RestartIO.cpp#L85-L87) and [`serialize_OPM_XWEL()`](https://github.com/OPM/opm-common/blob/34dfbee01be43247058a5f38187ca5463df5e72d/src/opm/output/eclipse/RestartIO.cpp#L100-L105) functions in `RestartIO.cpp`.

**Comment by bska** [comment]
You should also remove the [declarations](https://github.com/OPM/opm-common/blob/34dfbee01be43247058a5f38187ca5463df5e72d/opm/output/eclipse/WriteRestartHelpers.hpp#L67-L76) from `WriteRestartHelpers.hpp`.

**Pull request merged**
