### PR TITLE
fixed: set the boost dynamic test define if we build shared libs

### PR DESCRIPTION
**Pull request by akva2**
Downstreams: 
- https://github.com/OPM/opm-grid/pull/310
- https://github.com/OPM/opm-output/pull/254
- https://github.com/OPM/opm-simulators/pull/1406
- https://github.com/OPM/opm-upscaling/pull/250

Sidestream: 
- https://github.com/OPM/opm-parser/pull/1214

### CODE REVIEW

**Comment by akva2** [comment]
won't be tested, but let's make sure it doesn't break anything.

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this opm-parser=1214 opm-grid=310 opm-output=254 opm-simulators=1406 opm-upscaling=250 please

**Comment by bska** [comment]
I have one comment on this, based on a cursory reading of the change-set.  Do please let me know if there's something I've overlooked.

It is decidedly a good idea to have the build system manage the `BOOST_TEST_DYN_LINK` flag (and decide whether or not to add the flag to the `COMPILE_DEFINITIONS` of individual tests).  I do not understand the [conditional](https://github.com/akva2/opm-common/blob/d14c911c3bc72c41fb7a7d0c560a0e3009e36d79/cmake/Modules/OpmSatellites.cmake#L68-L73) in `OpmSatellites.cmake` however.

The `BOOST_TEST_DYN_LINK` flag must be set if we are linking the individual tests to a shared library version of the Boost unit test framework (with its built-in test runners).  I would have thought that that would be mostly unrelated to whether or not we're building OPM libraries as shared objects.

**Comment by akva2** [comment]
yes, i agree in principle, however opm-parser has this construct https://github.com/OPM/opm-parser/blob/master/CMakeLists.txt#L48 (which i kept from the previous build system). 

admittedly i was trying to minimize the work as i am already taking time out of my vacation to target the regression, so i figured i'd spare myself the investigation into why opm-parser has that for now. since the assumption that dyn boost test is used with shared libs is already in opm-parser, i figured it wouldn't kill us to  (temporarily!) apply it to the whole opm suite for now.

so this was sort of the minimal effort solution, but it grew as we got tons of redefined errors in other modules and i had to target that as well. is it okay to do what i have pushed now then as a temporary measure?

**Comment by bska** [comment]
> Is it okay to do what i have pushed now then as a temporary measure?

Yes, I think this looks good as a stepping stone.  We should verify through the usual mechanisms before we install it, but this is a tentative thumbs up from me.

**Comment by akva2** [comment]
jenkins build this opm-parser=1214 opm-grid=310 opm-output=254 opm-simulators=1406 opm-upscaling=250 please

**Comment by akva2** [comment]
jenkins build this opm-grid=310 opm-output=254 opm-simulators=1406 opm-upscaling=250 please

**Pull request merged**
