### PR TITLE
Add WEPT and WEPR to Summary

### PR DESCRIPTION
**Pull request by goncalvesmachadoc**

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
Note that in its current form, this PR will report the quantities as liquid surface volume rates (`WEPR`) and liquid surface volumes (`WEPT`) respectively.  If we want to report these values as energy rates and energies, then we also need to expand the unit system support in both `Summary.cpp` and `UnitSystem.cpp`.

**Comment by goncalvesmachadoc** [comment]
Thank you @bska  Yes, my plan is to have the implementation finished this week.

**Comment by bska** [comment]
> [M]y plan is to have the implementation finished this week.

Very good!  Please don't hesitate to ask if you have any questions regarding the summary output system.

**Comment by goncalvesmachadoc** [comment]
> > [M]y plan is to have the implementation finished this week.
> 
> Very good! Please don't hesitate to ask if you have any questions regarding the summary output system.

Thank you, @bska. I think now is ready. :)

**Comment by bska** [comment]
> > > [M]y plan is to have the implementation finished this week.
> > 
> > 
> > Very good! Please don't hesitate to ask if you have any questions regarding the summary output system.
> 
> Thank you, @bska. I think now is ready. :)

Thanks @goncalvesmachadoc.  This looks really great&mdash;you've done a good job getting to know an unfamiliar system.  There is one more, totally non-obvious, change you'll need to make in order for this to be perfect.  You'll need to record the `WEPT` and `WEIT` quantities as **cumulative** in the `SummaryState` too.  Otherwise, the values that'll be reported in the summary output for these quantities will just be the latest one rather than the sum of all previous values plus the latest contribution..

Technically you need to make the change outlined below which adds the strings `"EPT"` and `"EIT"` to the list of [known cumulative quantities](https://github.com/OPM/opm-common/blob/83cfe4b50ceeab665336b063eef0a639678a2d4f/src/opm/parser/eclipse/EclipseState/Schedule/SummaryState.cpp#L34-L37).  By omitting the leading prefix `W`, we get group and field level support for free when we implement those.

If you'd like me to do this I can merge the current PR and then make a small follow-up PR with the final change.  Otherwise, feel free to make the change and update this PR at which point we'll merge it into master.

---

```diff
diff --git a/src/opm/parser/eclipse/EclipseState/Schedule/SummaryState.cpp b/src/opm/parser/eclipse/EclipseState/Schedule/SummaryState.cpp
index 943b853ab..24b560252 100644
--- a/src/opm/parser/eclipse/EclipseState/Schedule/SummaryState.cpp
+++ b/src/opm/parser/eclipse/EclipseState/Schedule/SummaryState.cpp
@@ -34,7 +34,7 @@ namespace {
         static const std::vector<std::string> totals = {"OPT"  , "GPT"  , "WPT" , "GIT", "WIT", "OPTF" , "OPTS" , "OIT"  , "OVPT" , "OVIT" , "MWT" ,
                                                         "WVPT" , "WVIT" , "GMT"  , "GPTF" , "SGT"  , "GST" , "FGT" , "GCT" , "GIMT" ,
                                                         "WGPT" , "WGIT" , "EGT"  , "EXGT" , "GVPT" , "GVIT" , "LPT" , "VPT" , "VIT" , "NPT" , "NIT",
-                                                        "CPT", "CIT", "SPT", "SIT"};
+                                                        "CPT", "CIT", "SPT", "SIT", "EPT", "EIT"};
 
         auto sep_pos = key.find(':');
 
```

**Comment by bska** [comment]
jenkins build this please

**Comment by goncalvesmachadoc** [comment]
> Technically you need to make the change outlined below which adds the strings `"EPT"` and `"EIT"` to the list of [known cumulative quantities](https://github.com/OPM/opm-common/blob/83cfe4b50ceeab665336b063eef0a639678a2d4f/src/opm/parser/eclipse/EclipseState/Schedule/SummaryState.cpp#L34-L37). By omitting the leading prefix `W`, we get group and field level support for free when we implement those.

Thank @bska for the great explanation. Added them to SummaryState.cpp.

**Comment by bska** [comment]
> Added [`"EPT"` and `"EIT"`] to SummaryState.cpp.

Thank you for the updates, I'll run a build check now.  The previous run had a [failure](https://ci.opm-project.org/job/opm-common-PR-builder/2509/testReport/(root)/mpi/compareECLFiles_flow_SPE1CASE1_BRINE/) that I don't understand at all (reported per-cell salt content off by 100% in the restart file of [`SPE1CASE1_BRINE`](https://github.com/OPM/opm-tests/blob/07418b1ea33525034184cb644e9cb1d5012fa716/spe1_brine/SPE1CASE1_BRINE.DATA)) and I want to see if that was a one-off.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
> The previous run had a [failure](https://ci.opm-project.org/job/opm-common-PR-builder/2509/testReport/(root)/mpi/compareECLFiles_flow_SPE1CASE1_BRINE/) that I don't understand at all (reported per-cell salt content off by 100% in the restart file of [`SPE1CASE1_BRINE`](https://github.com/OPM/opm-tests/blob/07418b1ea33525034184cb644e9cb1d5012fa716/spe1_brine/SPE1CASE1_BRINE.DATA)) and I want to see if that was a one-off.

Unfortunately, we're still seeing that [failure mode](https://ci.opm-project.org/job/opm-common-PR-builder/2511/testReport/junit/(root)/mpi/compareECLFiles_flow_SPE1CASE1_BRINE/) in the latest run.  I absolutely do not understand this because there's no way that calculations performed purely in the output layer would affect the simulation results., at least not unless the `SALT` property in some way depends on the `SummaryState`.  Perhaps @totto82 could shed some light on that, as I'm not deeply familiar with the Brine model.  I will nevertheless try to run this PR locally and compare it to the current master results to see if I can get some more clues.

**Comment by bska** [comment]
> > The previous run had a [failure](https://ci.opm-project.org/job/opm-common-PR-builder/2509/testReport/(root)/mpi/compareECLFiles_flow_SPE1CASE1_BRINE/) that I don't understand at all (reported per-cell salt content off by 100% in the restart file of [`SPE1CASE1_BRINE`](https://github.com/OPM/opm-tests/blob/07418b1ea33525034184cb644e9cb1d5012fa716/spe1_brine/SPE1CASE1_BRINE.DATA)) and I want to see if that was a one-off.
> 
> Unfortunately, we're still seeing that [failure mode](https://ci.opm-project.org/job/opm-common-PR-builder/2511/testReport/junit/(root)/mpi/compareECLFiles_flow_SPE1CASE1_BRINE/) in the latest run. I absolutely do not understand this because there's no way that calculations performed purely in the output layer would affect the simulation result

I finally figured out what's happening.  In retrospect, I probably should have noticed before but that just goes to show that the system is somewhat inscrutable.  We **also** need to add a unit conversion **offset** in `UnitSystem.cpp` lest the `salinity` unit conversion read outside of the [`*_offset`](https://github.com/OPM/opm-common/blob/6ee4e5ce9a8ca272bb91281ee7e28bef6b305998/src/opm/parser/eclipse/Units/UnitSystem.cpp#L45) arrays.  In short, we need the change below.  With that in place I can run the tests locally and I believe that's all we need to get this merged.

---

```diff
diff --git a/src/opm/parser/eclipse/Units/UnitSystem.cpp b/src/opm/parser/eclipse/Units/UnitSystem.cpp
index 6975418c6..c9850ce13 100644
--- a/src/opm/parser/eclipse/Units/UnitSystem.cpp
+++ b/src/opm/parser/eclipse/Units/UnitSystem.cpp
@@ -79,6 +79,7 @@ namespace {
         0.0,
         0.0,
         0.0,
+        0.0,
     };
 
     static const double to_metric[] = {
@@ -246,6 +247,7 @@ namespace {
         0.0,
         0.0,
         0.0,
+        0.0,
     };
 
     static const double to_field[] = {
@@ -413,6 +415,7 @@ namespace {
         0.0,
         0.0,
         0.0,
+        0.0,
     };
 
     static const double to_lab[] = {
@@ -580,6 +583,7 @@ namespace {
         0.0,
         0.0,
         0.0,
+        0.0,
     };
 
     static const double to_pvt_m[] = {
```

**Comment by goncalvesmachadoc** [comment]
I did add the the unit conversion offsets in this PR (see below the first one):
image

Would that mean that I should add two elements in each offset?

**Comment by bska** [comment]
> I did add the the unit conversion offsets in this PR (see below the first one):

Yes, it is indeed there.  Weird...

Oh, now I think I know what's actually happening.  If this is true, then It is indeed subtle.  @totto82 added a [salinity](https://github.com/OPM/opm-common/blob/3036441c8ccab915af5b23d234b49aa9f6ada273/opm/parser/eclipse/Units/UnitSystem.hpp#L78) unit as part of fixing the salt concentration unit in PR #1874.  This PR is based on an older version of the master branch and then when Git notices that both PRs adds a new `0.0` element to the offset arrays it assumes that these elements are in fact the same and discards one of them as part of the merging process.

At this point I believe the best, but sadly not the easiest, course of action is to rebase this PR onto the current master sources and to let Git know that we do in fact want both of the new `0.0` elements.  I can do this for you if you'd like me to, or I can provide instructions if you'd like to do it yourself.

**Comment by goncalvesmachadoc** [comment]
> > I did add the the unit conversion offsets in this PR (see below the first one):
> 
> Yes, it is indeed there. Weird...
> 
> Oh, now I think I know what's actually happening. If this is true, then It is indeed subtle. @totto82 added a [salinity](https://github.com/OPM/opm-common/blob/3036441c8ccab915af5b23d234b49aa9f6ada273/opm/parser/eclipse/Units/UnitSystem.hpp#L78) unit as part of fixing the salt concentration unit in PR #1874. This PR is based on an older version of the master branch and then when Git notices that both PRs adds a new `0.0` element to the offset arrays it assumes that these elements are in fact the same and discards one of them as part of the merging process.
> 
> At this point I believe the best, but sadly not the easiest, course of action is to rebase this PR onto the current master sources and to let Git know that we do in fact want both of the new `0.0` elements. I can do this for you if you'd like me to, or I can provide instructions if you'd like to do it yourself.

Done :)

**Comment by bska** [comment]
> > At this point I believe the best, but sadly not the easiest, course of action is to rebase this PR onto the current master sources and to let Git know that we do in fact want both of the new `0.0` elements. I can do this for you if you'd like me to, or I can provide instructions if you'd like to do it yourself.
> 
> Done :)

Yes, success!

I've run the new version locally and everything works out of the box.  I'll launch a final build check&mdash;which I expect to succeed&mdash;and then merge this when that build check comes back green.

**Review by bska — APPROVED** [review]
This looks good to me.  I'll merge this once the build check is green.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
> I'll merge this once the build check is green.

It's green.  I'll merge this into master now.  Thanks a lot for your contribution and for your patience in getting the various issues resolved.

**Pull request merged**
