### PR TITLE
Sunbeam to opm

### PR DESCRIPTION
**Pull request by stefoss23**
This renames python package sunbeam to opm.
Also installation of python packages will be taken care of by setup.py.

### CODE REVIEW

**Comment by stefoss23** [comment]
jenkins build this please

**Comment by akva2** [comment]
while at it can you please fix the python installation path.

due to missing variables we end up with an install path of 'python./dist-packages/..'

as in, there's a missing FindPackage(Python)

**Comment by stefoss23** [comment]
It should be 'pythonx.x/dist-packages', but will be fixed in  different repo.

**Comment by stefoss23** [comment]
jenkins build this please

**Comment by stefoss23** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Is this ready from your end?

**Comment by stefoss23** [comment]
I just removed the 'WIP' prefix, so yes.

**Pull request merged**
