### PR TITLE
Check for MPI 2 functionality and activate it for DUNE.

### PR DESCRIPTION
**Pull request by blattms**
This allows mixing the MPIHelper and MPI_Init/MPI_Finalize. This commit
makes OPM a bit more DUNE compatible.

### CODE REVIEW

**Comment by atgeirr** [comment]
Assigned @akva2 to review this.

**Comment by blattms** [comment]
Just for clarification the define MPI_2 inidiates that MPI_Initialized and MPI_Finalized are available. It is used by DUNE to prevent calling these methods multiple times (which is a bug) in some situations.

**Comment by akva2** [comment]
minor, but please if() on USE_MPI.

**Comment by blattms** [comment]
I would rather if() on MPI_<LANG>_FOUND.

**Comment by akva2** [comment]
yup.

**Comment by akva2** [comment]
tested locally.

**Pull request merged**
