### PR TITLE
Make sf_multiplier mutable to be able to reset it 

### PR DESCRIPTION
**Pull request by vkip**
(reset from WellFilterCake in opm-simulators)

### CODE REVIEW

**Comment by atgeirr** [comment]
Would it be better to keep this as is but make a new member in the WellFilterCake class instead?

**Comment by vkip** [comment]
> Would it be better to keep this as is but make a new member in the WellFilterCake class instead?

In my opinion, no... At least I cannot see a simple solution for achieving the same (in https://github.com/OPM/opm-simulators/pull/5627), but maybe you can?

**Comment by GitPaean** [comment]
jenkins build this opm-simulators=5627 failure_report please

**Comment by GitPaean** [comment]
jenkins build this opm-simulators=5627 failure_report please

**Review by GitPaean — APPROVED** [review]
Thanks for the contribution.  Ideally we should be able to find a systematic way to handle this type of event type schedule keyword, which can be left out of the current PR as a separate refactoring efforts.

**Comment by GitPaean** [comment]
jenkins build this please

**Pull request merged**
