### PR TITLE
Support for capillary pressure hysteresis.

### PR DESCRIPTION
**Pull request by osae**
Some additional input from kw `EHYSTR` to support Killough's approach for hysteresis in relperm and cap-pressure.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by totto82** [comment]
jenkins build this opm-material=535 opm-simulators=4148 please

**Comment by totto82** [comment]
jenkins build this opm-material=535 opm-simulators=4148 please

**Comment by totto82** [comment]
jenkins build this opm-material=535 opm-simulators=4148 please

**Comment by totto82** [comment]
jenkins build this opm-material=535 opm-simulators=4148 please

**Comment by totto82** [comment]
Thanks for the contribution. Jenkins is happy and so am I. Will merge this ans its friends. What's remaining is to set it up for regression testing.

**Pull request merged**
