### PR TITLE
Use previous vfp table if default in historical runs

### PR DESCRIPTION
**Pull request by totto82**
For WCONHIST and WCONINJH default vfp table is the previous one

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Review by bska — COMMENTED** [review]
I'm not opposed to this and I think we need to do something, but this does at least in part revert @vkip's commit bfa61992de (PR #4058) so I think we should discuss what the actual behaviour should be here.

**Comment by vkip** [comment]
> I'm not opposed to this and I think we need to do something, but this does at least in part revert @vkip's commit [bfa6199](https://github.com/OPM/opm-common/commit/bfa61992de20e020cac90be145f776fa12b4c800) (PR #4058) so I think we should discuss what the actual behaviour should be here.

Although I see it could be convenient to keep the existing table number when defaulted, the manual is quite clear that the default is 0, so I suggest we stick to that.

**Comment by bska** [comment]
> For prediction (WCONPROD) I believe it should be reset to 0 when defaulted, while using the previous value for WCONHIST is fine.

Okay, cool&ndash;thank you very much for your insight.  In that case I'll update the reference solution for the failing regression test case and then I'll merge this.

**Comment by bska** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=1232 please

**Review by bska — APPROVED** [review]
Good catch.  The new reference solutions have been installed on the CI system so I'll merge this into the master branch now.

**Pull request merged**
