### PR TITLE
fix python bindings for parser

### PR DESCRIPTION
**Pull request by tskille**
adding section keywords RUNSPEC and EDIT to eclSectionType

### CODE REVIEW

**Comment by tskille** [comment]
This is a bug that was introduced with https://github.com/OPM/opm-common/pull/3863.

**Comment by blattms** [comment]
jenkins build this please

**Comment by tskille** [comment]
There is one more issue that needs to be fixed.

**Comment by asnyv** [comment]
Looks like it works as expected for me now 👍

**Comment by bska** [comment]
jenkins build this please

**Comment by blattms** [comment]
Looks good to me. Merging.

**Pull request merged**
