### PR TITLE
Add new well event for wells which have been touched by ACTIONX

### PR DESCRIPTION
**Pull request by joakim-hove**
Downstream: https://github.com/OPM/opm-simulators/pull/3288

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=3288 please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by akva2** [comment]
not enough with the ptsd, now u go and put a label on the poor things.

**Pull request merged**
