### PR TITLE
Assign well control mode directly in contrib functions

### PR DESCRIPTION
**Pull request by joakim-hove**
Micro simplification and comment update in AggregateWellData. Mainly to maintain an illusion of progress on the restart stuff.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
I don't really see how this is a simplification.  You're replacing named functions with the bodies of those functions.  If I'm being honest I think this makes the code more complicated and less redable.

**Comment by joakim-hove** [comment]
> I don't really see how this is a simplification. 

Well - that is in the mind of the beholder of course; I think it is a (extremely minor) improvement in readability. The reason I say that is that current master has structure like:
```C++
iWell[index1] = something;
iWell[index2] = something_else;
iwell[index3] = different_value;
setXXX( ..., iWell);
```
in the current structure I would expect setXXX() to do something non-trivial - when it just does exactly the same as the proceeding statements it does in my opinion miscommunicate.

**Comment by joakim-hove** [comment]
>>I don't really see how this is a simplification.

>Well - that is in the mind of the beholder of course; I think it is a (extremely minor) improvement in readability. The reason I say that is that current master has structure like:

If no further comments to this I will merge it later today.

**Comment by bska** [comment]
> > > I don't really see how this is a simplification.
> 
> > Well - that is in the mind of the beholder of course; I think it is a (extremely minor) improvement in readability. The reason I say that is that current master has structure like:
> 
> If no further comments to this I will merge it later today.

I do have further comments.  Since by your own admission this is, at best, a tiny simplification and it doesn't actually do anything I'd prefer that we simply close this and don't proceed with the change.

**Pull request closed without merging**
