### PR TITLE
Netbalan default

### PR DESCRIPTION
**Pull request by joakim-hove**
Create valid default NETBALAN object.

~~Data update is required because we now output real default values for NETBALAN - also in the case when it is not in use, compared to previously where we just output 0.~~

Update 2: For the NETBALAN keyword there are three different "states":

1. The keyword is entered in the deck - read values from deck, all good.
2. The network model is enabled, but no NETBLAN keyword in deck: One default initialization
3. The network model is not enabled: A second default initialization

The alternatives 2 & 3 are implemented in new function:
```C++
Balance::Balance(bool network_active, const Tuning& tuning)
    : calc_mode(CalcMode::TimeStepStart)
    , calc_interval(0)
    , m_thp_tolerance( NB::THP_CONVERGENCE_LIMIT::defaultValue )  
    , m_thp_max_iter( NB::MAX_ITER_THP::defaultValue )          <-- Create data update - was 0 previously
{
    if (network_active) {
        this->ptol = NB::PRESSURE_CONVERGENCE_LIMIT::defaultValue;
        this->m_pressure_max_iter = NB::MAX_ITER::defaultValue;
        this->m_min_tstep = tuning.TSMINZ;
    } else {
        this->ptol = 0;
        this->m_pressure_max_iter = 0;
        this->m_min_tstep = 0;
    }
}
```
and because of the update `thp_max_iter` value all(?) are regression tests get an updated INTEHEAD[77]

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this update_data please

**Comment by joakim-hove** [comment]
jenkins build this opm-tests=675 please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this update_data please

**Comment by joakim-hove** [comment]
jenkins build this opm-tests=676 please

**Comment by joakim-hove** [comment]
Opinions to this? There are *maaany* updates in flight (and I have more in store ...)

**Comment by bska** [comment]
> Opinions to this?

Did you verify that we actually need to output `NETBALAN` values if the network option is not active?  The size of the file update in OPM/opm-tests#676 is larger than I expected.

**Comment by joakim-hove** [comment]
> Did you verify that we actually need to output NETBALAN values if the network option is not active? The size of the file update in

I agree that the update was larger than anticipated; I did not verify this personally - but this is the conclusion I have reached together with @jalvestad in Equinor. It seems the `NETBALAN::MAX_ITER_THP` should be output with a default value (10) even when the network option is not active. I agree it is weird - and of course I might have misunderstood.

**Comment by joakim-hove** [comment]
Confirmed in Equinor

**Pull request merged**
