### PR TITLE
WIP: Python bindings for eclipe io classes

### PR DESCRIPTION
**Pull request by tskille**
I'm expecting a joint effort on python bindings in OPM. The eclipse IO classes are obvious targets for python bindings and I hope that this can be included in a joint python binding effort when this will happen. Comments are very much welcome.

### CODE REVIEW

**Comment by joakim-hove** [comment]
> and I hope that this can be included in a joint python binding effort when this will happen. 

That certainly makes sense - and we will get there; but mind that cooperation would be simpler if you could communicate a bit up front instead of just coming with a PR out of the blue.

**Comment by tskille** [comment]
> but mind that cooperation would be simpler if you could communicate a bit up front instead of just coming with a PR out of the blue.

This is far from being a finished. By sending in a PR with what I have so far, I'm trying to communicate early that there is work in progress in this area. I just wanted to show that I have something that can be used, at least parts of this.

**Comment by atgeirr** [comment]
Not a python expert, but I think it is good to make this "behave like a normal python thing" from the start, whatever that may be. About thickness of interfaces: if making a thin python interface is hard, then it is imho likely that the changes to the C++ interfaces required to make it easy are also good for the C++ code.

**Comment by joakim-hove** [comment]
> This is far from being a finished. [...]

OK - I have looked briefly into this, and I would urge you wait a bit before continuing. Very rough feedback:

1. The C++ binding code is a good start, but we should strive to make it more Pythonic in various ways:

- Use of numpy arrays.
- Hide the type information - i.e. I just want a vector, I do not want to ask for an integer or double vector.
- Should use properties were appropriate.

2. The glue layer - will not be merged in present form, here I encourage you to wait for what is coming and then adapt to that.

3. As already mentioned the tests should use standard Python unittesting, and not scripts.

**Comment by tskille** [comment]
> Hide the type information - i.e. I just want a vector

This is what I have done in the intermediate Python layer (which is "quite thick").  

   .def("getRealFromIndex", (const std::vector<float>& (Opm::EclIO::EclFile::*)(int)) &Opm::EclIO::EclFile::get<float>)   
   .def("getDoubFromIndex", (const std::vector<double>& (Opm::EclIO::EclFile::*)(int)) &Opm::EclIO::EclFile::get<double>)   
   .def("getInteFromIndex", (const std::vector<int>& (Opm::EclIO::EclFile::*)(int)) &Opm::EclIO::EclFile::get<int>)   
   .def("getLogiFromIndex", (const std::vector<bool>& (Opm::EclIO::EclFile::*)(int)) &Opm::EclIO::EclFile::get<bool>)   
  .def("getCharFromIndex", (const std::vector<std::string>& (Opm::EclIO::EclFile::*)(int)) &Opm::EclIO::EclFile::get<std::string>);

**Comment by joakim-hove** [comment]
OK - I have taken a ride in the time-machine; back roughly two hours:

Thank you for sharing this PR at an early stage. Right now we are working on integrating the cmake build system with python, I therefor ask for your understanding that this PR will languish here until the build and test infrastructure is in place.

**Comment by joakim-hove** [comment]
> The intermediate python layer is that the file eclfile_bind.py ?

I guess the lines are not entirely clear - and the concepts of intermediate and glue layer is just something I have cooked up; but with term "intermediate layer" I thought more of your `module/eclOutput.py` - the `eclfile_bind.py` is what I thought of as the "glue layer".

**Comment by joakim-hove** [comment]
> Then I'm using if statements in the python module to pick the correct function (with respect to type)

Something like that yes. But I do not think we should use `std::vector<T>` &rightarrow; Python list, but rather a numpy array.

**Comment by joakim-hove** [comment]
As mentioned already this will not get proper review before the Python + cmake machinery has been merged, this is being worked on in both opm-common and opm-simulators and will be based on fairly standard Python `setup.py`

But just one short comment regarding numpy: It is very good that you have added support for numpy, but you should take it further: numpy should be the *only* alternative. For this Api numpy is the non-trivial alternative to support, if the user wants to use Python list that conversion is trivial for her to do herself. 

It might seem to become a more powerful Api by offering both alternatives as you do now - but **simple is good**, the Api with only Api will actually be better to use, and also much simpler to maintain.

**Comment by dr-robertk** [comment]
I agree with @joakim-hove on the numpy usage. This will also be needed when extracting a simulator state without copying of values back and forth.

**Comment by dr-robertk** [comment]
@tskille: I'm thinking of testing your improvements. Do you think it makes sense already or should I wait?

**Comment by dr-robertk** [comment]
@tskille: I'm thinking of testing you improvements. Do you think it makes sense already or should I wait?

**Comment by tskille** [comment]
It is very good if you are able to test this. I don't see any reason to wait.

**Comment by joakim-hove** [comment]
@tskille: I have one more reorganisation step I would like to complete; and then we are ready to start reviewing and merging this. Will get back to you - hopefully tomorrow.

**Comment by dr-robertk** [comment]
Sounds good.

**Comment by joakim-hove** [comment]
Hello @tskille - with the merging of: https://github.com/OPM/opm-common/pull/971 I would say the organisation of the Python tree is ready for extensions[1], so I encourage you to look at that - feel free to comment/improve it[2], and then submit your code in new pull requests. When submitting your code I would very much encourage you to:

1. Start with one quite small PR.
2. Make sure to use the `opm/setup.py` script and your C++ and Python sources there.
3. The standard way of making C/C++ extensions to Python is to create a shared library "my_extension.so" (with some init code conventions expected by Python), and then import that library into the running Python process with
```Python
import my_extension
```
i.e. you must change the approach in this PR with multiple shared libraries and `importlib`based imports.

4. Do as I say and not as I do - and have done - **make small api's**. I know it is tempting to add functionality of various kinds which seem "nice to have"; but I really think that is an anti-pattern. We should *strive hard* to make the api small, and for this particular PR that implies that I think the vector part of the api should only be based on `numpy`, and furthermore reservoir related utilities should be kept out of the API. 

[1]: This has taken longer than I thought/hoped, and it is certainly not yet in any particularly nice state, but the structure should be ~ready - and not so much of a moving target for others.

[2]: It is still far from perfect!

**Pull request closed without merging**
