### PR TITLE
Degenrate cells

### PR DESCRIPTION
**Pull request by joakim-hove**
In the case of degenerate cells there was a division by zero when calculating cell coordinates, this led to cells with volume `nan` and no joy. The first commit just removes some trailing whitespace - the relavant change is in the second commit.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
Merging now as this fixes a critical problem.  Thanks a lot!

**Pull request merged**
