### PR TITLE
Avoid connection depth = 0 when segment is specified without depth in COMPSEGS

### PR DESCRIPTION
**Pull request by vkip**
Perform the connection-depth-from-segments calculations even if the segment number is specified.

### CODE REVIEW

**Comment by vkip** [comment]
jenkins build this please

**Review by GitPaean — APPROVED** [review]
Thanks for the contribution. It looks fine to me.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
Thanks for the contribution. I am merging this PR now.

**Pull request merged**
