### PR TITLE
Update ActionX.cpp with NEXTSTEP

### PR DESCRIPTION
**Pull request by OPMUSER**

### CODE REVIEW

**Comment by OPMUSER** [comment]
This does not work because the parser says:
```

NEXTSTEP: keyword not supported
In file: ACTIONX_NEXTSTEP.DATA, line 391
```
Which means the keyword is not supported, is this correct?

**Comment by joakim-hove** [comment]
> This does not work because the parser says:

The simulator says.

>Which means the keyword is not supported, is this correct?

Well - apart from the `--enable-tuning` [discussion](https://github.com/OPM/opm-simulators/pull/3721); and the general interaction with the`TUNING` keyword - it works.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by OPMUSER** [comment]
@joakim-hove and @totto82 

Well then we should not make this keyword conditional on the `--enable-tuning` parameter. We don't do it for NUPCOL so we should not do it here. This tripped me up and it is going trip up many users as well.

Can we please change this.

**Comment by OPMUSER** [comment]
@joakim-hove and @totto82 

Well then we should not make this keyword conditional on the `--enable-tuning` parameter. We don't do it for NUPCOL so we should not do it here. This tripped me up and it is going trip up many users as well.

Can we please change this.

**Comment by OPMUSER** [comment]
@joakim-hove I still cannot get this to work with -`-enable-tuning=true.` I thought the problem was with NEXTSTEP being in the:

` /OPM/GitHub/opm-simulators/opm/simulators/utils/UnsupportedFlowKeywords.cpp`

file. So I removed it locally and rebuilt, but I still get the same error meesage:

```
Error: The keyword NEXTSTEP is not supported in the ACTIONX block
In ACTIONX_NEXTSTEP.DATA line 398.

Error: Problem with keyword NEXTSTEP
In ACTIONX_NEXTSTEP.DATA line 398
The keyword {keyword} is not supported in the ACTIONX block
In {file} line {line}.

Error: Unrecoverable errors were encountered while loading input

```
Any ideas?

**Comment by OPMUSER** [comment]
Sorry, I forgot to attach the test deck
[ACTIONX_NEXTSTEP.zip](https://github.com/OPM/opm-common/files/7690363/ACTIONX_NEXTSTEP.zip)
.

**Pull request merged**
