### PR TITLE
Python subdirectory

### PR DESCRIPTION
**Pull request by stefoss23**
Python is added through add_subdirectory and connected to the make/test system of opm-common.

### CODE REVIEW

**Comment by akva2** [comment]
please add
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 20dc5168..0c137ac0 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -211,7 +211,6 @@ install(DIRECTORY cmake DESTINATION share/opm)
 install(FILES etc/opm_bash_completion.sh.in DESTINATION share/opm/etc)
 
 if (ENABLE_PYTHON)
+  set_target_properties(opmcommon PROPERTIES POSITION_INDEPENDENT_CODE ON)
   add_subdirectory(python)
 endif()
-
-
```

**Comment by stefoss23** [comment]
Why?

**Comment by akva2** [comment]
.. to turn on PIC.

**Comment by stefoss23** [comment]
Why should PIC be on?

**Comment by akva2** [comment]
again; to allow linking a static object into a shared library, you have to enable PIC.

**Pull request merged**
