### PR TITLE
WIP Make transmissibilities editable from the parser

### PR DESCRIPTION
**Pull request by totto82**
With this PR modifying TRAN[XYZ] in EDIT works for defaulted transmissibilities. 
This is tested together with upstream PRs for SPE1 with MULTIPLY, ADD and EQUALS. 

The PR is not finished. Many of the tests do not yet compile and the implementation is not yet optimal from the performance points of view. But is should sufficient as a point of discussion.

### CODE REVIEW

**Comment by bska** [comment]
> I seriously do like circular dependency

Do *not*?

**Comment by joakim-hove** [comment]
Ehhh - just to be clear - I do **not** like circular dependencies. Thank you @bska

**Comment by andlaus** [comment]
to be clear: we also dislike the approach here, but unless a better way to fix the layering violation is found this, this PR is the best thing which we can up...

> I realize my initial approach also had its flaws, most notably that it only worked with MULT. What was wrong with the approach I had taken?

as you say: it only works with MULT, but we think that it may also cause problems with BOX and partially defaulted fields. Finally, we think that it is an even bigger hack than the proposed solution.

> Ehhh - just to be clear - I do not like circular dependencies. Thank you @bska

sure. Note that technically there is no circular dependency, but rather something akin a forward declaration: the simulator can provide a callback for doing the transmissibility calculation the parser. If no callback is provided, the behavior of the parser stays the same as before, i.e. you will get NaNs.

**Comment by alfbr** [comment]
Sounds like transmissibility calculations should be moved back to opm-grid where it once belonged.

**Comment by alfbr** [comment]
Care to share what problem you have in mind?

**Comment by joakim-hove** [comment]
> it only works with MULT, 

That is a valid point; however I do think using `ADD` and in particular `EQUALS` as transmissibility modifier is a really weird thing to do. A warning - or even an exception might be in place.

> but we think that it may also cause problems with BOX and partially defaulted fields. 

That is true - but that applies all of fields which can not be safely default initialized. I have thought of creating a common solution to that - but singling out the `TRAN?` family of keywords to get special attention for this particular weakness problem does not make sense. I agree that the parser should handle it - but a partly initialized field *is* a user error after all, and we have not encountered it in the wild yet - as far as I know.

> Finally, we think that it is an even bigger hack 

Well - that is of course in the mind of the beholder; personally I strongly prefer the solution I came up with myself, but I would of course be happy to rework it after concrete suggestions.

> [...] makes failures even more obscure.

Maybe that is true - and in that case I would be happy to add stronger/stricter seatbelts. The reason I will not merge this PR in anything close to the current form is that it makes *the code* more obscure - significantly so.

The concrete things I do not like with this PR include:

1. It does things *widely dfferent* - the pattern for 3D properties like `PORO`, `PERMX` and `SATNUM` is quite well established; now suddenly `TRAN?`behves very different. That trips up people using the code.

2. Making the `Eclipse3DProperties` depend on the `EclipseState` is in my book a circular depencency; and as already mentioned I do not like that.

3. The use of a `static` member and a class based `setTrans...` method which is called *from a different module* makes the code more difficult to reason about; and letting outside mutate the state of the objects from the parser layer is really ugly. [Yes - I know only the class is mutated - but the *behaviour* of the instances changes - even more ugly.]

4. Several function signatures have become longer, we have fought hard to shorten them - and I see it as a significant complexity increase to follow this approach.

I might have misunderstood, but I am *really* surprised this has become such a large issue. *Iff* one accepts the approach outlined [here](https://github.com/OPM/opm-common/pull/462/files#diff-0fd3416aa2c7d77ddd71e317a74f80ffR242) I thought this whole thing could be solved with ~10 lines of code in ewoms? Apart from disagreement on what is the best/correct approach - is my assumption fundamentally wrong?

**Comment by andlaus** [comment]
> > it only works with MULT,
> 
> That is a valid point; however I do think using `ADD` and in particular `EQUALS` as transmissibility modifier is a really weird thing to do. A warning - or even an exception might be in place.

To me your proposal seems to be a whack-a-moley patchwork solution. given that the hacks required to implement this are IMO conceptually not significantly less bad than what's proposed by the present PR, I'd be the wrong person to code it because I would not put my best effort into it. 

> > but we think that it may also cause problems with BOX and partially defaulted fields.
>
> That is true - but that applies all of fields which can not be safely default initialized.

yes, but in contrast to you proposal (?), with the present PR the NaN behavior of TRAN[XYZ] does not change if no callback for the transmissibility initializer is set.

> I have thought of creating a common solution to that - but singling out the `TRAN?` family of keywords to get special attention for this particular weakness problem does not make sense. I agree that the parser should handle it - but a partly initialized field *is* a user error after all, and we have not encountered it in the wild yet - as far as I know.

As far as I can see, the only way to deal with the problem at hand in a relatively sane manner is to provide the parser with a way to calculate the transmissibilities itself. Since this constitutes a big fat layering violation, it could also be fixed by merging the parser, grid, simulator and assorted modules into one big monolithic monster, but even then, the layering violation would still be there -- it would just not be as plainly obvious.

> > Finally, we think that it is an even bigger hack
> 
> Well - that is of course in the mind of the beholder; personally I strongly prefer the solution I came up with myself, but I would of course be happy to rework it after concrete suggestions.

I propose that you code up a working WIP version of your suggestion so that we can leave the hypothetical realm here.

> > [...] makes failures even more obscure.
> 
> Maybe that is true - and in that case I would be happy to add stronger/stricter seatbelts. The reason I will not merge this PR in anything close to the current form is that it makes *the code* more obscure - significantly so.

yes, we don't like having to go the route outlined by the present PR either, but you have to admit that your suggestion is conceptually not much better on the obscurity front!? (because the transmissibilities would not transmissibilities anymore, but only in some cases and sometimes it will simply fail without any obvious reason.) Also, note that a solution that requires more code is not *always* worse that a smaller one if the result is better.

> The concrete things I do not like with this PR include:
> 
> 1. It does things *widely dfferent* - the pattern for 3D properties like `PORO`, `PERMX` and `SATNUM` is quite well established; now suddenly `TRAN?`behaves very different. That trips up people using the code.

why does it behave differently with the present PR? conceptually the `TRAN[XYZ]` grid properties still initialize themselves at creation just like any other. Also, everybody involved will freely admit that having to resort to a callback to the simulator layer for this is very ugly.

> 2. Making the `Eclipse3DProperties` depend on the `EclipseState` is in my book a circular depencency; and as already mentioned I do not like that.

indeed. I misunderstood what you meant: I thought you were talking of making the opm-common and eWoms modules circularly dependent.

That said, on the circular-class-dependency issue, I'm willing to bet a beer that if the `Eclipse3DProperties` class was folded into `EclipseState` none of the downstream users would notice if the API to query properties was kept identical. IOW, from a practical point of view, these two classes already are essentially the same.

> 3. The use of a `static` member and a class based `setTrans...` method which is called *from a different module* makes the code more difficult to reason about; and letting outside mutate the state of the objects from the parser layer is really ugly. [Yes - I know only the class is mutated - but the *behaviour* of the instances changes - even more ugly.]

yes. As said, everybody agrees that this is very ugly. the same applies to your transmissibility-as-multipliers proposal, though.

> 4. Several function signatures have become longer, we have fought hard to shorten them - and I see it as a significant complexity increase to follow this approach.

Did you just defect to an `Ewoms::Simulator`-style approach? ;)

> I might have misunderstood, but I am *really* surprised this has become such a large issue. *Iff* one accepts the approach outlined [here](https://github.com/OPM/opm-common/pull/462/files#diff-0fd3416aa2c7d7 7ddd71e317a74f80ffR242) I thought this whole thing could be solved with ~10 lines of code in ewoms? Apart from disagreement on what is the best/correct approach - is my assumption fundamentally wrong?

Maybe. We'd be happy to test a WIP PR from you to find out...

**Comment by totto82** [comment]
As I see it there are 3 options
1) Extend the EclGrid in opm-common and let the parser compute the transmissibilities. In my opinion this is the least hackcy way and also the most work consuming solution. 
2) The second is the approach taken in this PR. In this approach the editing of the transmissibilities is fully supported, but it violates the structure and ordering in the parser. 
3) The solution proposed in #462. This solution is not very invasive, but it will only support the usage of MULT for the transmissibilites. Not ADD or EQUALS. 

When I discussed this with @alfbr last week, I got the impression that 1) was not an option since it would require to much work right now. But that ADD and EQUALS may at some time become important, i.e. option 3 could only be a temporary solution. The current PR tries to provide a solution that supports modification of the TRANS in the EDIT section more properly, while not needing to go to the full way of computing the transmissibilities the parser. While working on this we of-course discoverer that the structure in the parser did not really support this. 

I am not against option 3, it would not be the first "Ecl compatibility" hack we have in the code, as long as it has sufficient "seatbelts". I can provide a PR.

**Comment by joakim-hove** [comment]
Here an alternative approach has been solved - closing.

**Pull request closed without merging**
