### PR TITLE
Remove grid member from FieldProps

### PR DESCRIPTION
**Pull request by joakim-hove**
Makes things safer - and a step on the way towards a meaningful default constructor.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
What is the purpose of the `distribute_toplayer()` function?  It looks to be copying property values from the top layer (i.e., `K = 1`) to all other layers.  When is that useful?

**Comment by joakim-hove** [comment]
The ability to init only the top layer.

**Comment by bska** [comment]
>> What is the purpose of the `distribute_toplayer()` function?
>
> The ability to init only the top layer.

For `PORO`, `PERMX` and others I take it.  Okay, but those are supposed to copy values from the layer above, not the top layer.  Is there code elsewhere that handles that case?

**Comment by joakim-hove** [comment]
> [...] but those are supposed to copy values from the layer above, not the top layer. Is there code elsewhere that handles that case?

No - it does explicitly check only the layer above; the implementation goes all the way to the top in one go. Small change though - I'll fix it.

**Pull request merged**
