### PR TITLE
Add support for GRUPMAST

### PR DESCRIPTION
**Pull request by hakonhagland**
See downstream https://github.com/OPM/opm-simulators/pull/5436 and https://github.com/OPM/opm-simulators/pull/5437 for more information.

### CODE REVIEW

**Comment by hakonhagland** [comment]
jenkins build this opm-simulators=5437 please

**Comment by hakonhagland** [comment]
jenkins build this opm-simulators=5437 please

**Comment by totto82** [comment]
Thanks for the work. Looks good to me. I assume this can be merged without the changes in simulators.

**Comment by totto82** [comment]
jenkins build this please

**Comment by hakonhagland** [comment]
> I assume this can be merged without the changes in simulators.

@totto82 Yes, it should not depend on opm-simulators.

**Pull request merged**
