### PR TITLE
changed: use std::regex instead of boost::regex

### PR DESCRIPTION
**Pull request by akva2**
Just preparing this for when we decide to move to gcc 4.9 as minimum.

### CODE REVIEW

**Comment by bska** [comment]
When we do decide to do so, the code to [derive the sequence number from a filename](https://github.com/OPM/opm-common/blob/d2aaff46e03688b49637ce3db7907427467a18e4/src/opm/io/eclipse/ERst.cpp#L34-L53) can be simplified to
```C++
int seqnumFromSeparateFilename(const std::string& filename)
{
    const auto re = std::regex {
        R"~(\.[FX]([0-9]{4})$)~"
    };

    auto match = std::smatch{};
    if (std::regex_search(filename, match, re)) {
        return std::stoi(match[1]);
    }

    throw std::invalid_argument {
        "Unable to Determine Report Step Sequence Number "
        "From Restart Filename \"" + filename + '"'
    };
}
```

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this opm-simulators=2014 please

**Comment by akva2** [comment]
this is green.

**Comment by akva2** [comment]
don't forget the downstream.

**Pull request merged**
