### PR TITLE
Give meaningful error for out-of-range well perforations in ACTIONX.

### PR DESCRIPTION
**Pull request by blattms**
Previously we threw an exception that was poorly handled by the logging system. The user e.g. saw:
```
Reading from: BLA.INC line 2

Error: An error occurred while creating the reservoir schedule
Internal error: input IJK index above valid range

Error: Unrecoverable errors while loading input: input IJK index above valid range
```
With this commit we use the ParseContext to give a more meaningful error message like:
```
Error: Problem with COMPDAT in ACTIONX
In BLA.INC line 19
Cell (83, 273, 47) of well EX_WA is not part of the grid (Input IJK index (83, 273, 47) not part of grid with dimensions 169x359x46.).

Error: Problem with keyword COMPDAT
In BLA.INC line 19
Problem with COMPDAT in ACTIONX
In BLA.INC line 19
Cell (83, 273, 47) of well EX_WA is not part of the grid (Input IJK index (83, 273, 47) not part of grid with dimensions 169 x 359 x 46.).

Error: Unrecoverable errors while loading input: Problem with keyword COMPDAT
In BLA.INC line 19
Problem with COMPDAT in ACTIONX
In BLA.INC line 19
Cell (83, 273, 47) of well EX_WA is not part of the grid (Input IJK index (83, 273, 47) not part of grid with dimensions 169 x 359 x 46.).
```

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Review by bska — COMMENTED** [review]
On the one hand, it's always good to give better diagnostics. On the other hand, we arguably should never throw from a function that explores the possible future connections without knowing if these connections materialise. At least I'd prefer if we made the action be [`InputErrorAction::WARN`](https://github.com/OPM/opm-common/blob/c52d807c8d8b9d98d1b5ccf231b71a1ae4c2c05e/opm/input/eclipse/Parser/InputErrorAction.hpp#L36) instead of throwing an exception in the context of prefetching potential future connections.

**Comment by blattms** [comment]
I think this something that the current users should decide.

The decision is basically between whether we should fail fast because a keyword does obviously not make sense as is or risk to run a simulation for hours in the hope that in ACTION never becomes executed to then realize the next morning the simulation was aborted....

**Comment by bska** [comment]
> If course we can warn and ignore these problems in the running simulation.

Yeah...I'm conflicted.  If the parsing mode is strict I want to know about these things, but for "normal" I think I'd prefer a warning and that connections outside the model just be ignored.  For "low" such connections might just be silently ignored altogether.

**Comment by blattms** [comment]
BTW We also have problematic behavior if such problems appear outside ACTIONX (modifying SPE1CASE2) parsing aborts prematurely with

```
Error: Problem with keyword COMPDAT
In SPE1CASE2_BAD.DATA line 394
Internal error: Input IJK index (10, 10, 4) not part of grid with dimensions 10x10x3.

Error: Problem with keyword COMPDAT
In SPE1CASE2_BAD.DATA line 394
Internal error: Input IJK index (10, 10, 4) not part of grid with dimensions 10x10x3.

Error: Unrecoverable errors while loading input: Problem with keyword COMPDAT
In SPE1CASE2_BAD.DATA line 394
Internal error: Input IJK index (10, 10, 4) not part of grid with dimensions 10x10x3.
```

Note that the error message is at least improved with this PR (previously: "Internal error: input IJK index above valid range").

**Comment by bska** [comment]
> parsing aborts prematurely with [a diagnostic]

And that's arguably a bug in `ScheduleGrid`.  `ScheduleGrid` **could** decide that those connections will never be active, issue a warning, and then just ignore them.

**Comment by blattms** [comment]
I am undrafting this as it is a real improvement to the current situations for usersand does not change the behavior of the simulator. Therefore this should be merged.
The behavior of the simulator will be discussed with others and changed accordingly if necessary.

**Comment by bska** [comment]
> I am undrafting this as it is a real improvement to the current situations for users and does not change the behavior of the simulator. Therefore this should be merged.

Okay, fair enough.

> The behavior of the simulator will be discussed with others and changed accordingly if necessary.

Cool.  I'll merge into master.

**Comment by blattms** [comment]
Thanks. Highly appreciated.

**Comment by blattms** [comment]
We are currently failing as soon as possible, i.e. when parsing the SCHEDULE for the very first time.

**Pull request merged**
