### PR TITLE
Foam module

### PR DESCRIPTION
**Pull request by atgeirr**
This is based on #814.

I have only added the last commit, to resolve some warnings generated. There is still one, but that is triggered from opm-simulators. Since we have PRs incoming soon to address foam in that module, it may be a little messy to require a separate PR for just that warning, what do you think @akva2? Should we start being really strict immediately?

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
Turns out I misread my output, thought I had compile-checked this... I have force-pushed and will retry.

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by bska** [comment]
Is the FOAMOPTS keyword intentionally deferred or was it forgotten?  This appears to only handle the default setting of
```
FOAMOPTS
  GAS TAB /
```
which is of course a fine starting point.  We should, however, be prepared to handle `WATER` and `FUNC` too. Note that using `WATER` has implications for the handling of units of measure in `FOAMADS`.

**Comment by atgeirr** [comment]
> Is the FOAMOPTS keyword intentionally deferred or was it forgotten?

While there certainly are more keywords that will come in (this is just the first PR) we do not plan to support non-default FOAMOPTS with the current development.

**Comment by joakim-hove** [comment]
Not that it matters all that much - but I am a little confused who is actually behind this PR?

**Comment by atgeirr** [comment]
> Not that it matters all that much - but I am a little confused who is actually behind this PR?

That would be @fgfuchs and me, the work is done for the SIMCO2EOR Climit Demo project.

**Comment by bska** [comment]
I'll merge into master to unblock downstream work on this feature.

**Pull request merged**
