### PR TITLE
added: add exported targets

### PR DESCRIPTION
**Pull request by akva2**
okay, @blattms, let's start at this end then since you pointed out the regression in opm-parser.

### CODE REVIEW

**Comment by akva2** [comment]
at https://github.com/OPM/opm-common/blob/master/cmake/Modules/OpmProject.cmake#L100 there is an assumption that we do not install to a subpath of the build tree. this is done on jenkins, which means the files produced there will contain extra bogus entries. the last commit addresses this. but i'm not convinced the additional complexity is worth the gain, opinion wanted @blattms . eventually all this should be replaced by target usage anyways.

**Comment by akva2** [comment]
right now it breaks due to list vs string stuff but i'll fix that if we want this.

**Comment by akva2** [comment]
because it's a much bigger job. step by step.

**Comment by blattms** [comment]
Not sure where to add this. but for the installed package configuration files we need to replace `$[PROJECT_BINARY_DIR}/include` with `${CMAKE_INSTALL_INCLUDEDIR}}`. Otherwise we have bogus paths for opm-parser

**Comment by akva2** [comment]
i have fixed that in other ways, see opm-parser PR.

**Pull request merged**
