### PR TITLE
Use tolerances from command line for restart array SWEL

### PR DESCRIPTION
**Pull request by tskille**
Some Items in SWEL array stem from the reservoir voidage rate target item of producer wells on history controls (WCONHIST). Hence not only on static input data.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by akva2** [comment]
Can one of the admins verify this patch?

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
Looks good and goes through CI check (as expected).  I'll merge this into master now.

**Pull request merged**
