### PR TITLE
Assign guide rate values to data::Wells when loading from restart

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Comments?

**Review by bska — COMMENTED** [review]
Did you check that this patch does the right thing for injectors?  Note that injector guide rates are reported/stored with a negative sign in `XWEL`, but should probably be positive when transported back to the simulator.

**Comment by joakim-hove** [comment]
> Note that injector guide rates are reported/stored with a negative sign in XWEL, but should probably be positive when transported back to the simulator.

OK - thanks; no I have not verified this.

**Review by bska — CHANGES_REQUESTED** [review]
This is wrong.  The original code correctly assigned `.rates` for both producers and injectors.  That was the point of the negative sign in the `usys.to_si()` expression.

**Comment by joakim-hove** [comment]
OK - updated

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks.  This is much better.  I'll merge into master.

**Pull request merged**
