### PR TITLE
Move material-related tests to a subdirectory.

### PR DESCRIPTION
**Pull request by atgeirr**
Note that tests for some of the more general classes from opm-material (such as Evaluation) have not been moved.

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
jenkins build this please

**Review by bska — COMMENTED** [review]
I'm not opposed to this, but other than a little bit of file system organisation, what do we gain from this work?  Is this in preparation of some other restructuring or new feature?

**Comment by atgeirr** [comment]
No, it is just to get a little less clutter in the test directory.

**Comment by bska** [comment]
>> Is this in preparation of some other restructuring or new feature?
>
> No, it is just to get a little less clutter in the test directory.

Cool.  In that case I'll merge into master.

**Pull request merged**
