### PR TITLE
Fix bug with ouf of bounds access in UDQ parser

### PR DESCRIPTION
**Pull request by joakim-hove**
See: https://github.com/OPM/opm-common/issues/682

@bska: There was clearly a bug in the code - by just looking, and I have fixed it now. But I had problems reproducing the bug - valgrind which is my usual tool for such problems was all happy even before the fix.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
> I have fixed [the underlying issue] now.

Confirmed.  I've rerun the `UDQTests` locally in the same environment where I came across #682 and I don't see the issue anymore.

> valgrind which is my usual tool for such problems was all happy even before the fix.

Valgrind plugs into `malloc()`.  If `tokens.size() < tokens.capacity()` you will be accessing an element that's perfectly good from the point of view of Valgrind.  I haven't looked into whether that is what was happening here.

**Comment by joakim-hove** [comment]
> Confirmed. 

Thank you.

> Valgrind plugs into malloc(). If tokens.size() < tokens.capacity() you will be accessing an element that's perfectly good from the point of view of Valgrind. 

That makes very much sense; it is a limitation of Valgrind I have not thought of before.

**Comment by bska** [comment]
Okay, this fixes a real problem and Jenkins approves so I'll merge into master.  Thanks a lot!

**Pull request merged**
