### PR TITLE
adding a few connection summary keywords

### PR DESCRIPTION
**Pull request by GitPaean**
COFR CWFR CGFR CWCT CGOR

### CODE REVIEW

**Comment by GitPaean** [comment]
It is something I am really not familiar with, it is good someone can take a look at it. @bska @joakim-hove

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
I tested it with the example `wtest/bhp_min/MIN_BHP_1.DATA`, 

The relevant summary output is set as follows, 
```
128 CWCT
129  'OP_1' /
130 /
131 COFR
132  'OP_1' /
133 /
134 CWFR
135  'OP_1' /
136 /
```

While when I do `summary.x` with the output, I obtain 
```
COFR:OP_1:104            COFR:OP_1:124            COFR:OP_1:144            COFR:OP_1:24             COFR:OP_1:4              
COFR:OP_1:4,1,1          COFR:OP_1:4,1,2          COFR:OP_1:4,1,3          COFR:OP_1:4,1,4          COFR:OP_1:4,1,5          
COFR:OP_1:4,1,6          COFR:OP_1:4,1,7          COFR:OP_1:4,1,8          COFR:OP_1:44             COFR:OP_1:64             
COFR:OP_1:84             CTFAC:OP_1:104           CTFAC:OP_1:124           CTFAC:OP_1:144           CTFAC:OP_1:24            
CTFAC:OP_1:4             CTFAC:OP_1:4,1,1         CTFAC:OP_1:4,1,2         CTFAC:OP_1:4,1,3         CTFAC:OP_1:4,1,4         
CTFAC:OP_1:4,1,5         CTFAC:OP_1:4,1,6         CTFAC:OP_1:4,1,7         CTFAC:OP_1:4,1,8         CTFAC:OP_1:44            
CTFAC:OP_1:64            CTFAC:OP_1:84            CTFAC:WI_1:1,5,1         CTFAC:WI_1:1,5,2         CTFAC:WI_1:1,5,3         
CTFAC:WI_1:1,5,4         CTFAC:WI_1:1,5,5         CTFAC:WI_1:1,5,6         CTFAC:WI_1:1,5,7         CTFAC:WI_1:1,5,8         
CTFAC:WI_1:117           CTFAC:WI_1:137           CTFAC:WI_1:157           CTFAC:WI_1:17            CTFAC:WI_1:37            
CTFAC:WI_1:57            CTFAC:WI_1:77            CTFAC:WI_1:97            CWCT:OP_1:104            CWCT:OP_1:124            
CWCT:OP_1:144            CWCT:OP_1:24             CWCT:OP_1:4              CWCT:OP_1:4,1,1          CWCT:OP_1:4,1,2          
CWCT:OP_1:4,1,3          CWCT:OP_1:4,1,4          CWCT:OP_1:4,1,5          CWCT:OP_1:4,1,6          CWCT:OP_1:4,1,7          
CWCT:OP_1:4,1,8          CWCT:OP_1:44             CWCT:OP_1:64             CWCT:OP_1:84             CWFR:OP_1:104            
CWFR:OP_1:124            CWFR:OP_1:144            CWFR:OP_1:24             CWFR:OP_1:4              CWFR:OP_1:4,1,1          
CWFR:OP_1:4,1,2          CWFR:OP_1:4,1,3          CWFR:OP_1:4,1,4          CWFR:OP_1:4,1,5          CWFR:OP_1:4,1,6          
CWFR:OP_1:4,1,7          CWFR:OP_1:4,1,8          CWFR:OP_1:44             CWFR:OP_1:64             CWFR:OP_1:84     
```

**Comment by GitPaean** [comment]
It looks like the generated summary keywords are in line with the E100 reference, even though I do not understand how it works. 

But most of COFR results are zero. 

image

The purple line is the E100 reference result.

**Comment by bska** [comment]
The water cut and gas/oil ratio definitions look reasonable to me, but the flow-rate quantities probably need some adjustments.  The flow rates are positive for production and negative for injection, so I would probably define them as
```C++
// production - injection
{ "CGFR", sub(crate<rt::gas, producer>, crate<rt::gas, injector>) },
{ "COFR", sub(crate<rt::oil, producer>, crate<rt::oil, injector>) },
{ "CWFR", sub(crate<rt::wat, producer>, crate<rt::wat, injector>) },
```
Note that the `crate` function returns a non-negative rate value and will pick appropriate sign depending on the second template parameter.

**Comment by GitPaean** [comment]
The jenkins failure are due to different summary keyword sets in the summary output. This will not be in the way of updating reference.

**Comment by GitPaean** [comment]
> The flow rates are positive for production and negative for injection, so I would probably define them as
```C++
// production - injection
{ "CGFR", sub(crate<rt::gas, producer>, crate<rt::gas, injector>) },
{ "COFR", sub(crate<rt::oil, producer>, crate<rt::oil, injector>) },
{ "CWFR", sub(crate<rt::wat, producer>, crate<rt::wat, injector>) },
```

Thanks @bska . I will do that.

**Comment by GitPaean** [comment]
Thanks @bska . The result is better. The difference in the later part are not due to the summary output. 

image

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by bska** [comment]
> The result is better.

Glad to hear it.  Did you mean to push an update with the revised definitions of the connection phase flow rates or is that still in local developement on your machine?

**Comment by GitPaean** [comment]
> Glad to hear it. Did you mean to push an update with the revised definitions of the connection phase flow rates or is that still in local developement on your machine?

I forgot to commit it.  Not it is pushed.

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by GitPaean** [comment]
For `CTFAC` output, it looks like we handle differently from the commercial simulator.
image

The result from the commercial simulator is the purple line. 

It looks like for closed well due to physical reason (probably also for economic limit, not sure about the SHUT well from deck), `CTFAC` remains non-zero while OPM-flow treat them as zero. 

Basically, it might give us some clues about how the commercial simulator handles closed wells. They probably still have the closed wells in the well model, which is different from OPM-flow's current way. (excuse me if I am wrong at this point. )

**Comment by GitPaean** [comment]
`wtest/bhp_min/MIN_BHP_1.DATA` is a prediction case without historical schedule.  The producer begin with oil rate production, then it gets shut due to physical cause. Through `WTEST`, the commercial simulator manages to reopen the producer for a few times, while OPM-flow does not.  The reopening behavior is something we need to investigate, here we only discuss about the summary output. 

The following (and also the above comment) is some findings about the summary output. Some are bugs, and some are different behavior from the commercial simulator. 

One is the historical mode summary values,  as stated above, this case is a prediction case,  the commercial simulator manages to provide some non-zero historical values, while the behavior is not very consistent. 

For this `FOPRH`, OPM-flow provides zero value output, while the commercial simulator provides non-zero value output. It looks like the values are the same with `FOPR`. 

image

For `WGPTH`, again, the commercial simulator produces the value of `WGPT`, however, the output of the OPM-flow is clearly a bug. 
image

Same applies to `WOPTH`, 
image

For `FGOR`, and also `FGORH`,  it is clearly both OPM and the commercial simulator are buggy at the beginning part when well OP_1 still running. Both of them gives zero output
image

image

Not sure whether the commercial simulator did some rounding off for the very small values, or some other techniques
image

image

**Comment by GitPaean** [comment]
The comments above is for providing information for further development. It should not be in the way of merging of this PR. 

This PR is ready for reviewing and merging.

**Comment by GitPaean** [comment]
jenkins build this opm-tests=266 please

**Pull request merged**
