### PR TITLE
Remove opm specific restart vectors OPM_IWEL and OPM_XWEL?

### PR DESCRIPTION
**Pull request by joakim-hove**
NB: This PR is put up for discussion - as a goal; and it is *not* ready to be merged - it even fails the tests.

It is not clear to me how much work it would be to remove the opm specific fields OPM_IWEL and OPM_XWEL, but at the time they were introduced that was as a way to save well related information which we did not know how to store in the IWEL and XWEL arrays. Since then a *heroic effort* has been undertaken to output correct `IWEL` and `XWEL` vectors, and the original motivation to introduce `OPM_IWEL` and `OPM_XWEL` should be void??

### CODE REVIEW

**Comment by bska** [comment]
I support the goal of removing `OPM_IWEL` and `OPM_XWEL`.  Most of the items in `OPM_XWEL` already have counterparts in the `XWEL` and `XCON` ECLIPSE arrays.  The only remaining item that we do not know where to put is the [well temperature](https://github.com/OPM/opm-common/blob/c3b0dab6e56e4491fa11bb5839022072b245d787/src/opm/output/eclipse/RestartIO.cpp#L131) value.  This obviously matters in thermal simulations.

Removing `OPM_IWEL` requires reworking the way we preserve active control targets for wells and so needs coordinated work between opm-common and opm-simulators.  I sort of started this discussion in OPM/opm-simiulators#1699, but it never got anywhere.  To be honest, I'd rather complete that work than taking the intermediate step proposed in PR #988.

**Comment by joakim-hove** [comment]
> To be honest, I'd rather complete that work than taking the intermediate step proposed in PR #988.

Sure - I just want to start the discussion.

> This obviously matters in thermal simulations.

And how relevant are thermal simulations? At the risk of sounding like a black-oil bigot it is *my impression* that "thermal stuff" gets relatively large attention in the infrastructure code, and as illustrated here - increases the overall complexity[1], whereas the core simulator features are less mature and less used. *Iff* thermal stuff is holdout for opm-specific complexity like `OPM_IWEL` and `OPM_XWEL` - is it worth it? An idiot can ask more than .... can answer - I don't pretend to know the answer, but f forced to give one in isolation I would let the thermal stuff suffer.


[1]: Probably not much - but still

**Comment by atgeirr** [comment]
> And how relevant are thermal simulations? At the risk of sounding like a black-oil bigot it is _my impression_ that "thermal stuff" gets relatively large attention in the infrastructure code, and as illustrated here - increases the overall complexity[1], whereas the core simulator features for thermal stuff are less mature and less used. _Iff_ thermal stuff is a holdout for opm-specific complexity like `OPM_IWEL` and `OPM_XWEL` - is it worth it? An idiot can ask more than .... can answer - I don't pretend to know the answer, but if forced to give one in isolation I would let the thermal stuff suffer.

OPM Flow has the potential to be the best simulator for geothermal simulation, if handled well, because it (as far as I know) handles wells and schedules etc. in a much more comprehensive way than most simulation codes used for such (since they have no pressure towards begin really good at this, unlike Flow). It also seems to me that thermal capabilities are growing in importance for carbon sequestration and petroleum cases, of course that is a purely subjective view. We should not dismiss that lightly.

Now storing the temperature of a well -- that might not be very important. Given the usual assumption that the volume of a well is small or negligible, the thermal energy contained in it is also small and its temperature will be totally dominated by the injected or produced fluid.

**Comment by OPMUSER** [comment]
@atgeirr 

> Now storing the temperature of a well -- that might not be very important.

Not strictly true because it is used for modeling the effect of injecting cold sea water into the reservoir to model the impact on water injectivity. This can cause some issues when injecting large volumes of cold water.

**Comment by atgeirr** [comment]
> Not strictly true because it is used for modeling the effect of injecting cold sea water into the reservoir to model the impact on water injectivity. This can cause some issues when injecting large volumes of cold water.

I agree that a) the temperature of the injected fluid is important, as well as b) the temperature of the reservoir block in which we inject. Do you mean that the temperature of the wellbore is significant enough to require separate modeling and storing, in addition to a) and b)?

**Comment by OPMUSER** [comment]
Never done that in a simulator so I cannot comment, the emphasis has always been on the subsurface impact. There are other software tools for examining the impact of thermal expansion-contraction and stress on the "pipe".

**Comment by atgeirr** [comment]
After thinking a little more on the original issue here, I think that perhaps we should abandon the line of thought that we can get "perfect restarting" or checkpointing using the Eclipse binary file formats. We could instead separate these two things, and use boost.serialize on a large scale to support checkpointing, letting any RESTART-file related work focus on and be measured only on compatibility.

This PR could be a start in that direction. The major effort would be required to implement the checkpointing, but if we agree to go *all in* on that, it should be both doable and simple (but not necessarily small) task.

**Comment by bska** [comment]
> We could instead separate [check-pointing from RESTART], letting any RESTART-file related work focus on and be measured only on compatibility.

If we do do that, then we can also get rid of the `DOUBHEAD` compatibility hack that stores "OPMEXTRA" (i.e., the suggested next stepsize) in `DOUBHEAD[1]` (introduced in bfe250718/#548).

**Pull request closed without merging**
