### PR TITLE
Fix nans in EGrid::getCellCorners

### PR DESCRIPTION
**Pull request by daavid00**
Adding missing conditional to avoid nans.

### CODE REVIEW

**Comment by daavid00** [comment]
jenkins build this please

**Comment by blattms** [comment]
I see that this prevents nans, but to judge I would need to understand the original. Could you help me with that?

**Comment by daavid00** [comment]
For example for the grid generated using [spe11c.txt](https://github.com/OPM/pyopmspe11/blob/main/examples/hello_world/spe11c.txt), then using resdata:
```
from resdata.grid import Grid
resg = Grid("SPE11C.EGRID")
corners_resdata = resg.export_corners(resg.export_index())[0]
print(corners_resdata)
[  0.           0.         155.04167175   1.           0.
 155.04167175   0.         200.         131.60166931   1.
 200.         131.60166931   0.           0.         255.04167175
   1.           0.         255.04167175   0.         200.
 231.60166931   1.         200.         231.60166931]
```
while using opm:
```
from opm.io.ecl import EGrid as OpmGrid
opmg = EGrid("SPE11C.EGRID")
corners_opm = opmg.xyz_from_ijk(0, 0, 0)
print(corners_opm)
([nan, nan, nan, nan, nan, nan, nan, nan], [nan, nan, nan, nan, nan, nan, nan, nan], 
 [155.0416717529297, 155.0416717529297, 131.60166931152344, 131.60166931152344, 255.0416717529297, 255.0416717529297, 231.60166931152344, 231.60166931152344])
```
This PR fixes these nans (also this conditional is present at the end of the file (lines 597-602)).

**Comment by blattms** [comment]
Thanks. I think I finally got it. Sometimes I do have my dense days :sweat_smile: 
Looks good.

**Pull request merged**
