### PR TITLE
 Activate WECON and WTEST for use in PYACTION, tests are in opm-tests

### PR DESCRIPTION
**Pull request by lisajulia**

### CODE REVIEW

**Comment by lisajulia** [comment]
jenkins build this opm-simulators=5365 opm-tests=1163 please

**Review by blattms — APPROVED** [review]
Looks good.

Feel free to selfmerge after the rebase and successful jenkins run
Maybe after #4069

**Comment by lisajulia** [comment]
> Looks good.
> 
> Feel free to selfmerge after the rebase and successful jenkins run Maybe after #4069

ok, I'll do that

**Comment by lisajulia** [comment]
jenkins build this opm-simulators=5365 opm-tests=1163 please

**Pull request merged**
