### PR TITLE
checking all the instances of AQUCT and AQUFETP keywords

### PR DESCRIPTION
**Pull request by GitPaean**
with master branch, only the last instance will be caught for these two keywords.

It is a followup for PR #3468

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Looks good to me.  I'll merge into master once the build check is green.

**Comment by OPMUSER** [comment]
@GitPaean  Did this make it into 2023-04-RC1?

**Comment by GitPaean** [comment]
Yes, it did.

**Pull request merged**
