### PR TITLE
Unconditionally Output Guiderates to Restart File

### PR DESCRIPTION
**Pull request by bska**
This PR ensures that we also always output guiderate values to the restart file.  Always calculating these summary quantities we leverage the restart output support added in commit 317d1ba (i.e., in PR #1792).

### CODE REVIEW

**Comment by bska** [comment]
Note: This PR depends on, and includes PR #1880, and must therefore not be merged before that PR is in master.

**Comment by bska** [comment]
Marking this as "ready for review" now since the upstream PR (#1880) was merged into master.

**Comment by bska** [comment]
Note that this will, by construction, unconditionally output additional items to the restart files which will beget an update to the reference data.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Is this ready?

**Comment by bska** [comment]
> Is this ready?

Yes it is.  I marked it [ready for review](https://github.com/OPM/opm-common/pull/1882#issuecomment-692717829) a few days ago. I also remarked that merging this will entail updating the reference data due to outputting more non-zero items to the restart files of models that use the guiderate feature.

I'll run a build check to ensure that there are no unexpected failure modes.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
> I'll run a build check to ensure that there are no unexpected failure modes.

The results are [back](https://ci.opm-project.org/job/opm-common-PR-builder/2434/testReport/) and the failures are all of the expected form&mdash;new values in [`XGRP[85]`](https://github.com/OPM/opm-common/blob/403fd09e6998a58ce3625c96fb3ab6dfa69a69dd/opm/output/eclipse/VectorItems/group.hpp#L81-L84) and possibly others.  The relative errors are all `-1`, which means that the corresponding array items go from a zero value to a non-zero value.

I'm now satisfied that it is safe to update the reference solutions for this PR, once the PR as a whole is approved.

**Comment by joakim-hove** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=381 please

**Comment by bska** [comment]
jenkins build this opm-tests=381 please

**Comment by bska** [comment]
I am going to run one last build check for this and then I'd very much like to get this PR merged (along with its accompanying reference data update, OPM/opm-tests#381).

**Comment by bska** [comment]
jenkins build this opm-tests=381 please

**Comment by joakim-hove** [comment]
I interpret [this comment] as saying that the current should go in first? Will merge later today.

**Pull request merged**
