### PR TITLE
Revert "Use input COORD and ZCORN if these are available when writing EGRID f…"

### PR DESCRIPTION
**Pull request by bska**
Reverts OPM/opm-common#3227

### CODE REVIEW

**Comment by akva2** [comment]
isn't rather the problem that the reference data was generated without the reverted PR, ie, the build test this PR was done before the tests were merged?

**Comment by bska** [comment]
> isn't rather the problem that the reference data was generated without the reverted PR, ie, the build test for that PR was done before the tests were merged?

That **may** be part of it, but to be honest I don't think that's the reason.  Instead I think that GRIDUNIT processing happens **after** #3227 stored copies of the input COORD and ZCORN arrays, but that said processing is unaware of those separate copies.

**Comment by bska** [comment]
> indeed, that's seems to be the case, pretty obvious looking into the code

Agreed.  I'll create a PR unless you want to.

**Comment by akva2** [comment]
you go right ahead, my tree is very in the middle of things atm.

**Comment by bska** [comment]
PR #3233 is a better solution than this, so I'll close as no longer needed.

**Pull request closed without merging**
