### PR TITLE
Add eff_fac for historic volumes

### PR DESCRIPTION
**Pull request by lars-petter-hauge**
Efficiency factors should also be applied for historic volumes.

### CODE REVIEW

**Comment by lars-petter-hauge** [comment]
Let me do some verifications that this is all that's necessary and I'll add a test

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
> Efficiency factors should also be applied for historic volumes.

The ways of Eclipse are mysterious - are you certain? I have no clue.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by lars-petter-hauge** [comment]
> The ways of Eclipse are mysterious - are you certain? I have no clue.
I didn't think about this when the W/G-EFAC was implemented, but it seems so. It doesn't say anything in the documentation (as I could find..).. But thinking about it, it does make sense, otherwise it would be pointless comparing historic rates whenever well efficiency factors are included.

I'll double check on Monday though.

**Comment by alfbr** [comment]
@lars-petter-hauge is right, we have verified it with simulations.

**Pull request merged**
