### PR TITLE
remove warnings in co2store with NDEBUG on

### PR DESCRIPTION
**Pull request by hnil**
remove warnings in co2store when NDEBUG is on. In CO2STORE can be slow if a lot of extrapolation is done.
In simulations one should limit the pressures by --temperature-min/max --pressure-min/max so that table is ok.

### CODE REVIEW

**Comment by totto82** [comment]
> remove warnings in co2store when NDEBUG is on

Do you mean the opposite? Only check for extrapolation and output warnings if NDEBUG is on?

**Comment by totto82** [comment]
Does it make sense to add a user defined limit like MESSAGE to reduce number of warnings if NDEBUG is on.

**Comment by bska** [comment]
> Does it make sense to add a user defined limit like MESSAGE to reduce number of warnings if NDEBUG is on.

Not really.  `NDEBUG` is "no debugging" and is typically turned on for release builds and off for debug builds.  The `assert` macro is nominally implemented as
```C++
#if defined(NDEBUG)
#define assert(x) /* nothing */
#else
#define assert(x) __builtin_assert_impl((x))
#endif
```
Of course, real implementations do something more elaborate, but the above is a useful mental model of how `NDEBUG` works.

**Comment by totto82** [comment]
> Not really. NDEBUG is "no debugging" and is typically turned on for release builds and off for debug builds

I agree, but I think we by default turn NDEBUG "on" also in release build.

**Comment by bska** [comment]
> > Not really. NDEBUG is "no debugging" and is typically turned on for release builds and off for debug builds
> 
> I agree, but I think we by default turn NDEBUG "on" also in release build.

We don't.  We explicitly turn `NDEBUG` [**off**](https://github.com/OPM/opm-common/blob/4485bdfa83f61f4663d5291365b24d91eb387304/cmake/Modules/UseOptimization.cmake#L75) in our release builds, but users can turn it back on by setting our [`WITH_NDEBUG`](https://github.com/OPM/opm-common/blob/4485bdfa83f61f4663d5291365b24d91eb387304/cmake/Modules/UseOptimization.cmake#L66-L67) option to `True` at configure time.

`NDEBUG` is a bit weird to reason about because it quickly becomes a double negation
```C++
if (! NDEBUG) {
    do_expensive_checks();
}
normal_implementation();
```

**Comment by totto82** [comment]
> a double negation
Sorry. The double negation tricked me.I am looking forward to the day  https://github.com/OPM/opm-common/pull/3427 gets merged.

**Pull request merged**
