### PR TITLE
Add size() and num_wells() methods to SummaryState

### PR DESCRIPTION
**Pull request by joakim-hove**
Small utility methods used in the UDQ sequel

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
```
Build step 'Execute shell' marked build as failure
{standard input}: Assembler messages:
{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
c++: internal compiler error: Terminated (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
CMakeFiles/flow.dir/build.make:254: recipe for target 'CMakeFiles/flow.dir/flow/flow_ebos_oilwater_polymer_injectivity.cpp.o' failed
make[2]: *** [CMakeFiles/flow.dir/flow/flow_ebos_oilwater_polymer_injectivity.cpp.o] Terminated
make[2]: *** Deleting file 'CMakeFiles/flow.dir/flow/flow_ebos_oilwater_polymer_injectivity.cpp.o'
CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/flow.dir/all' failed
make[1]: *** [CMakeFiles/flow.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
{standard input}: Assembler messages:
{standard input}:557759: Warning: end of file not at end of a line; newline inserted
c++: internal compiler error: Terminated (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
CMakeFiles/ebos_altidx.dir/build.make:62: recipe for target 'CMakeFiles/ebos_altidx.dir/ebos/ebos_altidx.cc.o' failed
make[2]: *** [CMakeFiles/ebos_altidx.dir/ebos/ebos_altidx.cc.o] Terminated
make[2]: *** Deleting file 'CMakeFiles/ebos_altidx.dir/ebos/ebos_altidx.cc.o'
CMakeFiles/Makefile2:1521: recipe for target 'CMakeFiles/ebos_altidx.dir/all' failed
make[1]: *** [CMakeFiles/ebos_altidx.dir/all] Error 2
c++: internal compiler error: Terminated (program cc1plus)
Please submit a full bug report,
```

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
> ```
> Build step 'Execute shell' marked build as failure
> {standard input}: Assembler messages:
> {standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
> c++: internal compiler error: Terminated (program cc1plus)
> ```

These days Jenkins appears to generate those if there are multiple concurrent build requests going in the same repository.

**Comment by joakim-hove** [comment]
Ehhh - was that a race condition ...?

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Pull request merged**
