### PR TITLE
Add skeleton for input simulator

### PR DESCRIPTION
**Pull request by joakim-hove**
Have just added an absolute minimum cmake skeleton for an "input simulator". For the more advanced prediction based functionality we will need tighter interaction between the simulator and the data structures from opm-common.

This is a zeroth step in creating a test-bed to work back-and-forth between opm-common datastructures (typically what is in the `Schedule` classes) and the simulator. 

Comments welcome

### CODE REVIEW

**Comment by joakim-hove** [comment]
Anyone for a review - I'll self merge soon.

**Comment by dhan16** [comment]
attempting my first review...

1. do you mean "isim.hpp" is like an interface which all simulators will implement as we flesh this out?

2. what do you mean by "input" in "input simulator"? why the simulator an "input"? or is it "input"ting something?

3. i'm guessing sim is a short form for "input sum". probably just best to call it "input_sim" everywhere instead of "isim" for readability?

4. whats the standard for defaults in cmake? i'd assume the default for non-real options is false. so default ENABLE_INPUTSIM to false? btw, if the description is ""Build the mock simulator for io testing" the option should really be "ENABLE_MOCKSIM".  by that logic, i guess isim/src/isim.cpp becomes input_sim/src/mock_sim.cpp? 

5. the opm-common license is "GNU General Public License v3.0". but the new files reference "Copyright 2013 Statoil ASA." and "Copyright 2018 Equinor ASA"

6. where is test_isim defined?

**Comment by dhan16** [comment]
7. isim/include/opm/isim/main.hpp is empty and unused.

**Comment by dhan16** [comment]
8. "report_step = 0; report_step <= this->schedule.size(); report_step++". lets just rename size() to num_report_steps()? that would be clearer maybe. "size" is a very generic name

**Comment by joakim-hove** [comment]
> attempting my first review...

Thank you ;-)

> do you mean "isim.hpp" is like an interface which all simulators will implement as we flesh this out?

The "i" was for "input" - and never meant to represent "interface" - I see that "interface" was a natural interpretation. 

The whole purpose of this is to facilitate/enable experimenting & debigging of closer back-and-forth interaction between the simulator and the input layer. So the input simulator should use cotrect input, but just pass that straight through to output - i.e. an "input" simulator. But I agree "mock" is better an have changed to `mock_sim/msim` throughout.

> whats the standard for defaults in cmake? i

I have defaulted it to off.

>  the opm-common license is "GNU General Public License v3.0". but the new files reference "Copyright 2013 Statoil ASA." and "Copyright 2018 Equinor ASA"

Should all be "Equinor 2018"

> where is test_isim defined?

`tests/msim/test_msim`

> isim/include/opm/isim/main.hpp is empty and unused.

Removed

> report_step = 0; report_step <= this->schedule.size(); report_step++". lets just rename size() to 

Done

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
> debigging

That's how I'll refer to upscaling from now on :smile:

**Comment by dhan16** [comment]
thanks for the changes

**Pull request merged**
