### PR TITLE
Remove FSIP from summary ALL

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins bulid this update_data please

**Comment by joakim-hove** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
Note: `FSIP` was added to `ALL` in #2565 and that PR also added the keyword to [SummaryConfigTests](https://github.com/OPM/opm-common/blob/0da931a7e6b0dd13e991791b7a76b8b59514b901/tests/parser/SummaryConfigTests.cpp#L458).  If we remove `FSIP` here, we should also remove it from the unit test for `ALL`.

**Comment by joakim-hove** [comment]
>If we remove FSIP here, we should also remove it from the unit test for ALL.

Sure - I am just uncertain what is correct here.

**Pull request closed without merging**
