### PR TITLE
Support SKIP/ENDSKIP, i.e., ignore everything between.

### PR DESCRIPTION
**Pull request by vkip**
Ignore everything between SKIP|SKIP100|SKIP300 and ENDSKIP

### CODE REVIEW

**Review by bska — COMMENTED** [review]
What's the performance impact of this implementation if we have something like
```
DIMENS
  100 400 300 /
GRID
SKIP
COORD
-- ...
/
ZCORN
-- ...
/
ENDSKIP
COORD
-- ...
/
ZCORN
-- ...
/
```
This is absolutely a pathological case, and in the real world it would probably be
```
GRID
SKIP
INCLUDE
  'G1.GRDECL' /
ENDSKIP
INCLUDE
  'G2.GRDECL' /
```
instead.  On the other hand, if we do end up reading "large" data keywords one line at a time, that may incur considerable cost.

**Comment by vkip** [comment]
Not sure if this is a real problem. Did a quick test now with a SKIP/ENDSKIP surrounding a grid definition of ~20 million lines, with no apparent problem (considerably faster to skip the lines than parsing them). 

I realize this may not be intended way of implementing this, so please feel free to point in the right direction.

**Review by bska — APPROVED** [review]
> Did a quick test now with a `SKIP`/`ENDSKIP` surrounding a grid definition of ~20 million lines, with no apparent problem
 
Okay, cool.  Thanks a lot for checking.

> (considerably faster to skip the lines than parsing them).

Understood.  I was worried it might be the other way around.

> I realize this may not be intended way of implementing this, so please feel free to point in the right direction.

To be honest, I haven't given any thought at all as to how we might implement this feature so since this works and there's no performance downside I'm inclined to merge this as is.

**Comment by blattms** [comment]
I just realized that these keywords are still treated as unsupported by the simulator. Maybe we should change that? See https://github.com/OPM/opm-simulators/pull/5085

**Pull request merged**
