### PR TITLE
Support for mechanical dispersion

### PR DESCRIPTION
**Pull request by daavid00**

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this opm-models=847 opm-simulators=4960 please

**Comment by totto82** [comment]
jenkins build this opm-models=847 opm-simulators=4960 please

**Comment by totto82** [comment]
jenkins build this opm-models=847 opm-simulators=4960 please

**Comment by daavid00** [comment]
After merging https://github.com/OPM/opm-simulators/pull/4959, this PR has been updated to enable dispersion for flow_gaswater_dissolution_diffuse and modified one of the added tests ([DISPERC_INJECTION.DATA](https://github.com/OPM/opm-tests/pull/1072/files#diff-3b9aa9fe1e2850d1a6ce02316b4b52ad8800f79df1d7a4991fab52c1fa14897e)) to consider GAS WATER CO2STORE (this update also enables dispersion for flow_gaswater_energy, (diffusion is disabled in current master, it is planned to enabled it as well)).

**Comment by totto82** [comment]
jenkins build this opm-models=847 opm-simulators=4960 please

**Comment by totto82** [comment]
jenkins build this opm-models=847 opm-simulators=4960 please

**Comment by totto82** [comment]
jenkins build this opm-models=847 opm-simulators=4960 please

**Review by atgeirr — APPROVED** [review]

**Comment by atgeirr** [comment]
Started reviewing the set of PRs, should not merge until all done.

**Comment by daavid00** [comment]
Many thanks @atgeirr for your comments about this PR in opm-models and simulators. I have made the requested changes and updated the PR. I would appreciate if Jenkins could be run to fix any issue. Please let me know if further corrections are needed before merging this :).

**Comment by atgeirr** [comment]
> Please let me know if further corrections are needed before merging this

The two issues remarked on in the opm-simulators PR have not been discussed.
Other than that, I only have two further comment:
 - The `convFactor` defined on opm/models/blackoil/blackoildispersionmodule.hh lines 177-198 is not explained, I would like such an explanation to be added.
 - Somewhat related to the above, the defining continuous equations have been added (good!) for the flux, but it would be great to also add the discrete equations (looks like a two-point flux to me, but good to write it out explicitly).

**Comment by akva2** [comment]
> Many thanks @atgeirr for your comments about this PR in opm-models and simulators. I have made the requested changes and updated the PR. I would appreciate if Jenkins could be run to fix any issue. Please let me know if further corrections are needed before merging this :).

You have been added to the jenkins trigger list.

**Comment by daavid00** [comment]
jenkins build this opm-models=847 opm-simulators=4960 please

**Comment by bska** [comment]
jenkins build this opm-models=847 opm-simulators=4960 please

**Comment by daavid00** [comment]
jenkins build this opm-models=847 opm-simulators=4960 please

**Comment by daavid00** [comment]
jenkins build this opm-models=847 opm-simulators=4960 please

**Comment by daavid00** [comment]
> > Please let me know if further corrections are needed before merging this
> 
> The two issues remarked on in the opm-simulators PR have not been discussed. Other than that, I only have two further comment:
> 
> * The `convFactor` defined on opm/models/blackoil/blackoildispersionmodule.hh lines 177-198 is not explained, I would like such an explanation to be added.
> * Somewhat related to the above, the defining continuous equations have been added (good!) for the flux, but it would be great to also add the discrete equations (looks like a two-point flux to me, but good to write it out explicitly).

I have added the discrete equation and also the definition of the `convFactor`. Regarding the two issues in opm-simulators, now Diffusion is enable in `flow_ebos_gaswater_energy.cpp`, and the run is abort if `DISPERC` is on the deck and `enableDispersion` is false at compile time. For aborting the run for diffusion, I talked today with @totto82 and he said he will make a different PR, since he will also add some changes in the diffusion model. Thanks again @atgeirr for your review, writing down the equations helped to fix some significant issues :).

**Comment by atgeirr** [comment]
Thanks, looks like all is as it should be (until proven otherwise...), merging!

**Pull request merged**
