### PR TITLE
Enable In-Place Element Construction in Insert()

### PR DESCRIPTION
**Pull request by bska**
It's a generally useful technique that's never slower than construct followed by move.

### CODE REVIEW

**Comment by bska** [comment]
Note: This PR depends on, and contains, #3446.  It must not be merged until that PR is installed on the master branch.  I will keep the PR in "draft" state until it is ready for review.

**Review by akva2 — APPROVED** [review]
Looks nice and idiomatic.

**Comment by bska** [comment]
Upstream PR has been merged into the master branch.  Since this is approved I'll run a build check and merge if that is successful.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
> Since this is approved I'll run a build check and merge if that is successful.

Final build check is successful.  I'll merge this into the master branch now.

**Pull request merged**
