### PR TITLE
Add Support for WPIx Summary Vectors

### PR DESCRIPTION
**Pull request by bska**
We calculate these, for now, as
```
WPIx = WOPR / (WBPx - WBHP)
```
but it is possible that we may have to revise this definition, especially for injectors.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this ignore_extra please

**Review by blattms — APPROVED** [review]
Looks good.

**Comment by bska** [comment]
jenkins build this please

**Comment by blattms** [comment]
Mmh, would have thought the tests fail with new output. I'll leave the merging to @bska

**Comment by bska** [comment]
> Mmh, would have thought the tests fail with new output.

It was absolutely supposed to, and looking at the [Jenkins run](https://ci.opm-project.org/job/opm-common-PR-builder/6186/) there is indeed a [regression failure](https://ci.opm-project.org/job/opm-common-PR-builder/6186/testReport/(root)/mpi/compareECLFiles_flow_0B_WELPI_MODEL2/) for `0B_WELPI_MODEL2`.  I don't know what that didn't show up here, but I'll rerun the build check to see if that was an intermittent condition.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
Now we did get the expected failure.  I'll update the reference solutions and merge this.

**Comment by bska** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=1053 please

**Comment by bska** [comment]
The new reference solutions have been installed on the CI system.  Merging this now to activate support for `WPIn`.

**Pull request merged**
