### PR TITLE
move some infrastructure to opm-material

### PR DESCRIPTION
**Pull request by andlaus**
These classes are only used by opm-material and its downstreams. The reason for doing moving it there is that this allows more freedom in reorganizing the lower-level OPM modules (i.e., opm-common, opm-parser, opm-output) while still avoiding a hard dependency of the thermodynamic and numerical framework modules on the ECL file parsing libraries.

this PR requires quite a few downstream mop-up PRs, mainly because of the changed location of headers.

@akva2, @atgeirr: the PRs in their current form do not preserve the git history. I am open to rebase them on raw "move the files with history" branches, but I do not really consider this to be necessary because most of these file originate from `opm-material` anyway and they were moved to `opm-common` in a non history preserving manner.

### CODE REVIEW

**Comment by andlaus** [comment]
jenkins build this with downstreams opm-material=287 ewoms=282 opm-simulators=1398 please

**Comment by atgeirr** [comment]
I am mostly open to this, but there are some things here I disagree with:
 - Exceptions.hpp is in widespread use, and belongs in opm-common in my opinion.
 - Keeping the include paths (opm/common/...) would be better in many cases I think (also it would reduce or eliminate downstream PRs).
 - resetLocale() is only used by Flow, so why move it (if moved, it should be to opm-simulators).
 - Avoiding "the hard dependency" on ECL stuff would be taken care of by the discussed build system option. I can speculate that what you meant was to (potentially) make opm-material + ewoms buildable (partially) without opm-common(+parser+output) at all, is that not correct?

**Comment by andlaus** [comment]
> `Exceptions.hpp` is in widespread use, and belongs in opm-common in my opinion.

actually it is not. it is only used by `opm-material` and `ewoms`. what *is* widely used is `ErrorMacros.hpp` but this stays where it is.

> Keeping the include paths (opm/common/...) would be better in many cases I think (also it would reduce or eliminate downstream PRs).

yes, this would eliminate the opm-simulators downstream PR, but no, it would not be better because it is a hell of a lot more confusing if the `opm/common` includes are dispersed over multiple modules. Also, once this is going to be cleaned up, the same PRs are needed anyway...

> resetLocale() is only used by Flow, so why move it (if moved, it should be to opm-simulators).

it is also used by `Ewoms::start()`. I don't mind moving it to ewoms, though.

> Avoiding "the hard dependency" on ECL stuff would be taken care of by the discussed build system option. I can speculate that what you meant was to (potentially) make opm-material + ewoms buildable (partially) without opm-common(+parser+output) at all, is that not correct?

I don't want to have support all the (probably mostly academic) people that complain about something breaking which they don't need to e.g. implement their next adaptivity paper. do you? Anyway the proposed PRs are a "clean" solution that's more fool-proof as far as I can see.

(the only workable alternative that I can see is to keep opm-common as it is now.)

**Comment by andlaus** [comment]
I forgot to mention that opm-grid, opm-upscaling, opm-parser as well as opm-output *don't* need any changes.

**Comment by atgeirr** [comment]
>> Exceptions.hpp is in widespread use, and belongs in opm-common in my opinion.

> actually it is not. it is only used by opm-material and ewoms. what is widely used is ErrorMacros.hpp but this stays where it is.

It is included by many files in opm-simulators, and used in all things related to Flow.




> it is also used by Ewoms::start().

True, I failed to notice that. Still, I think it is quite reasonable to keep it in opm-common, unless you want to be able to be 100% independent of it. That brings us to...



>> Avoiding "the hard dependency" on ECL stuff would be taken care of by the discussed build system option. I can speculate that what you meant was to (potentially) make opm-material + ewoms buildable (partially) without opm-common(+parser+output) at all, is that not correct?

> I don't want to have support all the (probably mostly academic) people that complain about something breaking which they don't need to e.g. implement their next adaptivity paper. do you? Anyway the proposed PRs are a "clean" solution that's more fool-proof as far as I can see.

As long as (for example) ErrorMacros.hpp remains in opm-common, those (not-related-to-flow-at-all) parts of ewoms we are discussing here would still depend on opm-common, so I don't see the benefit of moving (for example) Exceptions.hpp. It would subtly (or not so subtly) encourage reinventing things, rather than reusing. For instance, after combining opm-common with opm-parser the parser code could use the Valgrind support for debugging (if we don't move it). Right now it does not hurt now, but makes things less flexible.

**Comment by andlaus** [comment]
I just counted: opm-simulators includes `Exceptions.hpp` just 14 times and I strongly suspect that most of these files do not actually use anything from it..

**Comment by andlaus** [comment]
jenkins build this with downstreams opm-material=287 ewoms=282 opm-simulators=1398 please

**Comment by andlaus** [comment]
jenkins build this with downstreams opm-material=287 ewoms=282 opm-simulators=1398 please

**Comment by atgeirr** [comment]
> I just counted: opm-simulators includes Exceptions.hpp just 14 times and I strongly suspect that most of these files do not actually use anything from it..

14 times is not a few! Actually, some of the exception classes were added specifically so that Flow could use them to discriminate between failure types.

My verdict is this: Exceptions.hpp stays in opm-common. The rest of the PR is acceptable, even if I don't wholeheartedly agree with all of it... (I think general things like Evaluation for example, which right now is in opm-material, should be in opm-common in the long term for example.)

So if you change that, I am fine with the rest.

**Comment by andlaus** [comment]
> My verdict is this: Exceptions.hpp stays in opm-common

I don't agree, but way too many words about the color of this bike shed have been spend already. changed.

**Comment by andlaus** [comment]
jenkins build this with downstreams opm-material=287 ewoms=282 opm-simulators=1398 please

**Comment by atgeirr** [comment]
Fine to merge when all green.

**Comment by andlaus** [comment]
> Fine to merge when all green.

k, thx. do you want me to push green or do you prefer to do it yourself?

**Comment by atgeirr** [comment]
Looks like Jenkins did not see the downstream PRs properly, if you take a look at the output. We could just try again?

**Comment by atgeirr** [comment]
> k, thx. do you want me to push green or do you prefer to do it yourself?

Does not matter, as long as all is green and the PR is as agreed. I leave this to you.

**Comment by andlaus** [comment]
weird. the code which jenkins complained about is not in my branch. maybe it was just a timing issue...

**Comment by andlaus** [comment]
jenkins build this with downstreams opm-material=287 ewoms=282 opm-simulators=1398 please

**Comment by andlaus** [comment]
> Does not matter, as long as all is green and the PR is as agreed. I leave this to you.

okay, thanks for the clarification.

**Comment by andlaus** [comment]
jenkins build this with downstreams opm-material=287 ewoms=282 opm-simulators=1398 please

**Comment by andlaus** [comment]
*grr* jenkins only rebuilds if the HEAD of the PR branch has changed, not if just one of the up- or downstreams has changed.

**Comment by akva2** [comment]
that should not be the case.

**Comment by andlaus** [comment]
okay, this explains the symptoms. thanks!

**Comment by akva2** [comment]
cancelled as it saw my comment ;) i'll re-post the trigger.

**Comment by akva2** [comment]
jenkins build this with downstreams opm-material=287 ewoms=282 opm-simulators=1398 please

**Comment by andlaus** [comment]
that jenkins error is really weird: it actually says that the file in question is present and gets installed (github agrees), yet it likes to complain that the class is not present. On my machine locally everything works fine. I've touched all heads, so maybe Jenkins gets through now...

**Comment by andlaus** [comment]
jenkins build this with downstreams opm-material=287 ewoms=282 opm-simulators=1398 please

**Comment by andlaus** [comment]
jenkins build this with downstreams opm-material=287 ewoms=282 opm-simulators=1398 please

**Comment by andlaus** [comment]
hm, jenkins ignored previous to last trigger was ignored as well. maybe github does not always send notification emails in the same order they where written in. anyway, it went down the hole to dig in the mud, let's hope it emerges unscarred.

**Comment by andlaus** [comment]
jenkins build this with downstreams opm-material=287 ewoms=282 opm-simulators=1398 please

**Comment by andlaus** [comment]
hm, this is *really* strange: the patch where I added a few warnings to `opm/material/common/Exceptions.hpp` does not seem to get picked up by jenkins. my current theory is that jenkins has some conflicts with untracked files, but it is extremely hard debug this without ssh access to the jenkins rig. @akva2 can you have a look?

**Comment by atgeirr** [comment]
Have you checked your local setup? Perhaps there is something that has not been pushed properly? Just a sanity check.

**Comment by andlaus** [comment]
yes: git reports no untracked files and no differences to the remote branch.

**Comment by andlaus** [comment]
next try. eWoms actually had some differences.

**Comment by andlaus** [comment]
jenkins build this with downstreams opm-material=287 ewoms=282 opm-simulators=1398 please

**Comment by andlaus** [comment]
that did not cut it either. :/

I would like to verify that jenkins merges the correct PR heads, but alas this seems to be impossible with the current Jenkins logs because the git commit id printed by the build system is the head of the locally merged branches, not the id of the head of the github branch.

@akva2: can you make jenkins print the IDs of the merged heads when merging the PRs? (I'd also be very grateful if you had a more direct look what goes wrong here. in particular, why the debugging `#warning`s in the exceptions header are not produced.)

**Comment by akva2** [comment]
jenkins build this with downstreams opm-material=287 ewoms=282 opm-simulators=1398 please

**Comment by andlaus** [comment]
hm. now the debugging `#warning`s are printed. why wasn't this the case yesterday? I'm 100% sure that I've pushed *before* triggering jenkins.

**Comment by akva2** [comment]
yes, it's annoying as feck but lately github sometimes get confused when branches are rewritten. it keeps serving the old copy in the pull/xx/merge refs. it cures itself over time but it can sometimes be many hours. i have opened https://github.com/OPM/opm-common/pull/333 so this can be identified without ssh access.

**Comment by andlaus** [comment]
okay, there was another hitch: the default OPM build system does not define `HAVE_*` config.h macros for the modules it found unless it is explicitly instructed to do so. this implied that the `NumericalIssue` class does not get derived from `NumericalProblem` and thus the latter cannot be caught instead of the former. Anyway: fixed.

**Comment by andlaus** [comment]
jenkins build this with downstreams opm-material=287 ewoms=282 opm-simulators=1398 please

**Comment by andlaus** [comment]
*argh* github delivered the wrong opm-simulators head. this time it did not even receive a force push.

**Comment by andlaus** [comment]
jenkins build this with downstreams opm-material=287 ewoms=282 opm-simulators=1398 please

**Comment by andlaus** [comment]
Jenkins still fails because it still uses an incorrect version of the opm-simulators pr. @atgeirr: Let's try it one more time, but if it keeps failing because of this issue, can it be merged anyway?

**Comment by andlaus** [comment]
jenkins build this with downstreams opm-material=287 ewoms=282 opm-simulators=1398 please

**Comment by andlaus** [comment]
*yay* it worked without changing anything. let's get over this nightmare and merge.

**Pull request merged**
