### PR TITLE
Adding some keywords

### PR DESCRIPTION
**Pull request by stefoss23**
Adding some keywords missed in the first big round of keyword adding:
ACTIONS, AMALGAM, APILIM, APIVD, AQUALIST, AQUCHGAS, AQUCHWAT, BDENSITY, BGGI and BOGI.

### CODE REVIEW

**Comment by stefoss23** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
Do you want to add a downstream "MissingFeatures" PR before we merge this?

**Comment by joakim-hove** [comment]
> Do you want to add a downstream "MissingFeatures" PR before we merge this?

That has already been merged: do you want to add a downstream "MissingFeatures" PR before we merge this?

Although this typical pair of PR's should be merged together there is no technical link - i.e. from a build and test perspective they can be merged independently.

**Comment by bska** [comment]
> > Do you want to add a downstream "MissingFeatures" PR before we merge this?
> 
> That has already been merged: [OPM/opm-simulators#2237](https://github.com/OPM/opm-simulators/pull/2237)

Well, in that case there's nothing holding this back.  I'll merge into master.  Thanks a lot.

**Pull request merged**
