### PR TITLE
Added FindCwrap, add to pythonpath

### PR DESCRIPTION
**Pull request by pgdr**
Added feature for locating module `cwrap`, similar to the way we locate module `ert`.

### CODE REVIEW

**Comment by atgeirr** [comment]
Will this be another third-party library we depend on? Or will it be optional? Where and how do you intend to use it?

**Comment by pgdr** [comment]
This is a submodule of `ert` that we use in parser.  We now just make the locating of the module more robust.

It's only invoked from parser when python tests are turned on.

**Comment by atgeirr** [comment]
> submodule of ert

So it has nothing to do with this?

https://cwrap.org

**Comment by pgdr** [comment]
No, it has nothing to do with that.  Somewhat unfortunate name, it appears ...

**Comment by joakim-hove** [comment]
This is a pure addition, affecting only the *not-much-used* Python bindings - and the Python tests which are already on death row. I will merge this afternoon.

Jenkins build: http://80.240.129.131:8080/job/opm-parser-PR-builder/39/

**Pull request merged**
