### PR TITLE
improve lto support

### PR DESCRIPTION
**Pull request by akva2**
need to use the wrappers for ar and ranlib, or static
libraries are problematic.

### CODE REVIEW

**Comment by akva2** [comment]
i agree that it's probably of little effect with the unscrutinized templating going around here, but it doubt it does any harm, so i still enable in packaging.

**Comment by andlaus** [comment]
I'm happy to let you call the shots here, but I'd like to remind you that LTO was a major support hassle a few years back...

**Comment by akva2** [comment]
it has always been supported under a cmake option. there is no support burden, people need to explicitly enable it. LTO has matured a lot in later years, i don't see a reason to remove it.

**Comment by andlaus** [comment]
ah, okay. I probably misunderstood: so it stays off by default?

**Comment by akva2** [comment]
yes. no change there, i just make sure to set the associated AR and RANLIB tools if it is enabled. the need was triggered by the fact that the newly introduced static testutil library in opm-common caused nightly builds to stop working.

**Comment by joakim-hove** [comment]
This is above my paygrade in build idiosyncrasies - @akva2 merge when you see fit.

**Comment by akva2** [comment]
hrm, why did they make that gcc-ar-7 i wonder :/ i just looked at my installed compiler and figured it would be consistent (x86_64-linux-gnu-gcc-ar etc). will need some more logic then, with a fallback to gcc-ar.

**Comment by akva2** [comment]
try now.

**Comment by akva2** [comment]
i guess that's enough backing for a shameless self-merge.

**Comment by blattms** [comment]
Indeed.

**Pull request merged**
