### PR TITLE
added: tell update_data where to start branch from

### PR DESCRIPTION
**Pull request by akva2**
this to allow for update_data from opm-tests

### CODE REVIEW

**Comment by akva2** [comment]
this and the downstream https://github.com/OPM/opm-simulators/pull/3693 allows for triggering an update_data from opm-tests.

**Comment by joakim-hove** [comment]
Very good - I look forward to using this.

**Comment by joakim-hove** [comment]
Looks safe to merge this only?

**Comment by akva2** [comment]
yes as such, however it's all NOP without the other part.

**Comment by joakim-hove** [comment]
> however it's all NOP without the other part.

That I understand. Will let the other one linger a bit in case someone more qualified comes along.

**Pull request merged**
