### PR TITLE
Allow interrogating DynamicState for changes in data

### PR DESCRIPTION
**Pull request by wito**
This feature adds the method `bool DynamicState<T>::is_new_data(size_t time_step)`, which returns `true` if the data at `time_step` is changed from `time_step - 1`, or else `false`.

### CODE REVIEW

**Comment by wito** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Unfortunately this will not cut it in our situation; a large part of the `DynamicState` comparisons we need are with `std::shared_ptr` and the `operator==` for `std::shared_ptr`compares the container object and not the internal pointer.

**Comment by wito** [comment]
> Unfortunately this will not cut it in our situation; a large part of the `DynamicState` comparisons we need are with `std::shared_ptr` and the `operator==` for `std::shared_ptr`compares the container object and not the internal pointer.

Are you sure about that?

[The documentation I have says different](https://en.cppreference.com/w/cpp/memory/shared_ptr/operator_cmp):

```c++
template < class T, class U > 
bool operator==( const std::shared_ptr<T>& lhs,
                 const std::shared_ptr<U>& rhs ) noexcept {
    return lhs.get() == rhs.get();
}
```

**Comment by wito** [comment]
A simple `==` is also how equality is decided other places in  `DynamicState<T>`, such as in `find_not(const T& value)`.

**Comment by akva2** [comment]
operator== for shared pointers never compared values, it compares pointers.

**Comment by joakim-hove** [comment]
OK - I back down ;-)

**Pull request merged**
