### PR TITLE
Relocate files

### PR DESCRIPTION
**Pull request by akva2**
Move files with opm/core prefix into opm/common.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this with downstreams opm-material=283 opm-grid=305 ewoms=280 opm-simulators=1394 opm-upscaling=246 please

**Comment by andlaus** [comment]
I've got no objections to this PR per-se, but I'm wondering if this could not be used as an opportunity to get rid of unnecessary subdirectories? e.g. isn't everything in opm-common "utility" code? so far, I assumed that this was the whole purpose of the module...

**Comment by atgeirr** [comment]
This is the first of several "move things to reasonable dirs" PR chains. With this one, I think opm-common is covered, and that is of course the one with the most downstream repercussions. If you disagree with the reorganization suggested please shout out. Otherwise I hope we can quickly move downstream.

**Comment by atgeirr** [comment]
> I've got no objections to this PR per-se, but I'm wondering if this could not be used as an opportunity to get rid of unnecessary subdirectories? e.g. isn't everything in opm-common "utility" code? so far, I assumed that this was the whole purpose of the module...

The choice to retain subdirs is mostly to keep the number of files in each dir reasonably small. I think maybe the term "utility" is somewhat vague. I consider a "utility" in this context an independent feature that is not universally used (so ErrorMacros.hpp is kept at the top level as it is universally used). I hope that seems reasonable?

**Comment by andlaus** [comment]
> The choice to retain subdirs is mostly to keep the number of files in each dir reasonably small.

I see and I agree with the goal. That said, note that the point is only valid if the directories where a given file is located is somewhat can be inferred by simple rules and the result is unique: e.g. why are the `Valgrind.hpp`, the logging stuff and  the exception handling files located in `opm/common` but `ConditionalStorage.hpp` is in `opm/common/utility`. Honestly I see no logic behind this. (you can of course argue that everything should go into the `utility` subdirectory, but then your point is mood and also the `utility` folder can be ommited.)

> I think maybe the term "utility" is somewhat vague. I consider a "utility" in this context an independent feature that is not universally used (so ErrorMacros.hpp is kept at the top level as it is universally used). I hope that seems reasonable?

I see your logic, but I do not agree: In mathematics the simplest correct proof is the "best". IMO the same applies to programming: the simplest working solution is the "best".

**Comment by andlaus** [comment]
@atgeirr_ maybe you see what I mean if you explain me not the rationale of the code organization not of code that you're deeply involved in, but "foreign" one, e.g. eWoms or opm-parser...

**Comment by atgeirr** [comment]
> I see and I agree with the goal. That said, note that the point is only valid if the directories where a given file is located is somewhat can be inferred by simple rules and the result is unique: e.g. why are the Valgrind.hpp, the logging stuff and the exception handling files located in opm/common but ConditionalStorage.hpp is in opm/common/utility. Honestly I see no logic behind this. (you can of course argue that everything should go into the utility subdirectory, but then your point is mood and also the utility folder can be ommited.)

The logging stuff is a subsystem of some size, and not a simple utility. I can agree to also move Exceptions.hpp and friends currently located at opm/common/ to opm/common/utility (making opm/common contain no files, only dirs), if you think that is better. Please indicate your preference (if no strong preference I think we'll proceed as outlined).

> @atgeirr: maybe you see what I mean if you explain me not the rationale of the code organization not of code that you're deeply involved in, but "foreign" one, e.g. eWoms or opm-parser...

Not quite sure what you mean, but I think ewoms and opm-parser both have mostly reasonable directory structures (although I have admitted to not being a fan of moving the include files to a separate place), and I would not suggest any changes to those in this round.

**Comment by akva2** [comment]
jenkins build this with downstreams opm-material=283 opm-grid=305 ewoms=280 opm-simulators=1394 opm-upscaling=246 please

**Comment by andlaus** [comment]
> The logging stuff is a subsystem of some size, and not a simple utility. I can agree to also move Exceptions.hpp and friends currently located at opm/common/ to opm/common/utility (making opm/common contain no files, only dirs), if you think that is better. Please indicate your preference (if no strong preference I think we'll proceed as outlined).

I think that the size of a feature does not really matter for this discussion. To answer your question: I prefer as "flat" hierarchies as possible (not only when it comes to code, BTW ;)), but if you *really* want "deep nesting" I would argue to do it consistently and move all code into "utility".

>> @atgeirr: maybe you see what I mean if you explain me not the rationale of the code organization not of code that you're deeply involved in, but "foreign" one, e.g. eWoms or opm-parser...
>
> Not quite sure what you mean, but I think ewoms and opm-parser both have mostly reasonable directory structures (although I have admitted to not being a fan of moving the include files to a separate place), and I would not suggest any changes to those in this round.

I was not arguing that you should suggest any changes. rather, my point is that one is always more comfortable in one's "own nest" but a good structure is IMO defined by people who have only exhibit limited familiarity with a  code base being able to immediately understand. maybe I should have better asked you to explain the directory structure of the linux kernel or LibreOffice...

**Comment by akva2** [comment]
jenkins build this with downstreams opm-material=283 opm-grid=305 ewoms=280 opm-simulators=1394 opm-upscaling=246 please

**Comment by atgeirr** [comment]
> I think that the size of a feature does not really matter for this discussion. To answer your question: I prefer as "flat" hierarchies as possible (not only when it comes to code, BTW ;)), but if you really want "deep nesting" I would argue to do it consistently and move all code into "utility".

Well, I dont want "deep nesting" either, so I'll take that as a no, then.

**Comment by atgeirr** [comment]
If no further comments, I'll go with the

> I've got no objections to this PR per-se

comment and merge this in a few hours.

**Comment by andlaus** [comment]
> > I think that the size of a feature does not really matter for this discussion. To answer your question: I prefer as "flat" hierarchies as possible (not only when it comes to code, BTW ;)), but if you really want "deep nesting" I would argue to do it consistently and move all code into "utility".
>
> Well, I dont want "deep nesting" either, so I'll take that as a no, then.

Maybe there is a small misunderstanding: I intended to say that while I don't want to see any files in an arguably superfluous subdirectories, I consider consistency to be more important here, i.e. either move *all* files into subdirectories or *none*. Using inconsistent criteria of where a given piece of functionality is located is IMO worse than a consistent scheme that I don't fully agree with...

(BTW: For fun I just counted the number of header files in the opm-common module: 32, most of them are for OpmLog and the old parameter handling code. I think that even a directory with 32 files does not feel too crowded.)

**Comment by atgeirr** [comment]
> I think that even a directory with 32 files does not feel too crowded

Sure, but I want to be ready for more guests...

**Comment by andlaus** [comment]
maybe we should burn that bridge when we come to it?

**Comment by atgeirr** [comment]
> either move all files into subdirectories or none

Ok, I don't agree 100% but see your point. I suggest we save our discussion muscle for opm-simulators, where many more files will be moved!

**Comment by andlaus** [comment]
> Ok, I don't agree 100% but see your point. 

that makes two of us ;)

**Pull request merged**
