### PR TITLE
Fix typo in KRNUM json file

### PR DESCRIPTION
**Pull request by hakonhagland**
This fixes issue #3053 for me.

### CODE REVIEW

**Comment by hakonhagland** [comment]
jenkins build this please

**Review by bska — COMMENTED** [review]
Looks good to me.  For what it's worth, it appears that the same issue exists in

* [`DIFF`](https://github.com/OPM/opm-common/blob/fae7b5ccfcc1030eb80f6b24c73d3fec20e67026/src/opm/input/eclipse/share/keywords/000_Eclipse100/D/DIFF#L6)
* [`HAxxxxxx`](https://github.com/OPM/opm-common/blob/fae7b5ccfcc1030eb80f6b24c73d3fec20e67026/src/opm/input/eclipse/share/keywords/000_Eclipse100/H/HAxxxxxx#L7)
* [`HMxxxxxx`](https://github.com/OPM/opm-common/blob/fae7b5ccfcc1030eb80f6b24c73d3fec20e67026/src/opm/input/eclipse/share/keywords/000_Eclipse100/H/HMxxxxxx#L6)
* [`HMMULTxx`](https://github.com/OPM/opm-common/blob/fae7b5ccfcc1030eb80f6b24c73d3fec20e67026/src/opm/input/eclipse/share/keywords/000_Eclipse100/H/HMMULTxx#L7)

I don't think we've ever used any of these, but I think it makes sense to ensure that we at least recognise the associate keywords.  Would you like to amend this PR to address those issues too?

**Comment by hakonhagland** [comment]
jenkins build this please

**Comment by hakonhagland** [comment]
> it appears that the same issue exists in ...

@bska Good observation! I have added a new commit to address this

**Review by bska — APPROVED** [review]
Thanks a lot for the updates.  This looks good to me now and I'll merge into master.

**Pull request merged**
