### PR TITLE
Revise Phase Logic for Internal Energy

### PR DESCRIPTION
**Pull request by bska**
The `is_mixing` object indirectly detected that function `internalEnergy()` was being used only on the supported gas, oil, and water phases.  Be more explicit about this by adding a default clause to the phase switch.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Review by akva2 — APPROVED** [review]

**Comment by bska** [comment]
PR approved and build check is green.  I'll merge into master.

**Pull request merged**
