### PR TITLE
The MESSAGES keyword needs a thirteenth item

### PR DESCRIPTION
**Pull request by alfbr**
The MESSAGES keyword actually has thirteen items. This adds the last item to the keyword.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Good - with the PR @alfbr - as a side effect you also get a glimpse of the occasional moodyness of test system; I 'll try to get jenkins get it's act together for the third time:

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Hmmm - I don't really understand this; it seems to pass in Jenkins so then I must assume it passed at your place as well. But still - there *is* a syntax error in the json file, the newly added item is added outside of the `items: ` list - the diff should be something like:
```diff
-     {"name" : "BUG_STOP_LIMIT"  , "value_type" : "INT" , "default" : 1}]}
+     {"name" : "BUG_STOP_LIMIT"  , "value_type" : "INT" , "default" : 1},
+     {"name" : "GROUP_PRINT_LIMIT", "value_type" : "INT" , "default" : 10}]}
```

**Comment by alfbr** [comment]
Actually, I did compile it before sending in the PR. My apologies, things must have gone too fast for me.

**Comment by alfbr** [comment]
Should be fine now.

**Pull request merged**
