### PR TITLE
Implement TLMIXPAR as dedicated vector of struct - not table

### PR DESCRIPTION
**Pull request by joakim-hove**
Fix for: https://github.com/OPM/opm-common/issues/1855

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this opm-models=622 please

**Comment by joakim-hove** [comment]
@totto82

**Comment by joakim-hove** [comment]
jenkins build this opm-models=622 please

**Comment by joakim-hove** [comment]
Hmmm - it has been a long summer holiday; any idea why I get this failure locally:
```
21: Test command: /usr/bin/mpiexec "-n" "1" "/home/hove/work/OPM/opm-simulators/build/bin/test_ParallelRestart"
21: Test timeout computed to be: 1500
21: Running 128 test cases...
21: unknown location(0): fatal error: in "TableManager": std::logic_error: [/home/hove/work/OPM/opm-simulators/opm/simulators/utils/ParallelRestart.hpp:60] Packing not (yet) supported for this non-pod type.
21: /home/hove/work/OPM/opm-simulators/tests/test_ParallelRestart.cpp(428): last checkpoint: "TableManager" test entry
```

@akva2

**Comment by blattms** [comment]
I have not looked at the code, just judging from the description:

I guess you need to add the searialization boiler plate code for the new struct? (Was probably there for the Table)

**Comment by joakim-hove** [comment]
> I guess you need to add the searialization boiler plate code for the new struct? 

Thanks for answering; I have tried to add the serialization boilerplate - but I might have got it wrong!?

**Comment by blattms** [comment]
What is the non pod type? Maybe we need to improve the error message to include
that or fire up gdb.

The error indicates that `packSize` for that type is missing.

**Comment by joakim-hove** [comment]
jenkins build this opm-models=622 opm-simulators=2724 please

**Comment by joakim-hove** [comment]
@totto82 : cool if you take a look on this; I'll merge it tomorrow afternoon if you don't complain.

**Pull request merged**
