### PR TITLE
Improve Error Message for MULTFLT

### PR DESCRIPTION
**Pull request by OPMUSER**
Improve Error Message for MULTFLT see [#3062](/OPM/opm-common/pull/3062#issuecomment-1185473384)

### CODE REVIEW

**Comment by blattms** [comment]
Will this tell where the error is in the file?

**Comment by OPMUSER** [comment]
Not directly, but the previous message informs the user the start of the MULTFLT line, so the messages will be like this:

```
Creating grid from keywords DX, DY, DZ and TOPS
3 fluid phases are active

[Loading faults from FAULTS in MULTFLT.DATA line 220

Applying MULTFLT in MULTFLT.DATA line 237

Error:
Problem with keyword MULTFLT
Could not set fault transmissibility multiplier
MULTFLT(FLTNAME) equals FAULT01 and MULT(FLT-TRS) equals 0
Error creating reservoir properties: Key FAULT01 not found.

Error:
An error occurred while creating the reservoir properties
Internal error: Key FAULT01 not found.


Error: Unrecoverable errors while loading input: Key FAULT01 not found.

```
The reason for the multiple 

`Error: Unrecoverable errors while loading input: Key FAULT01 not found.`

type of messages is because we are in the `for` loops. I tried moving the inner loop to be inside the try/catch but I got compiler errors, so I gave up.   But  if you have suggestion, I'll improve the PR.

For reference, test case attached.

[MULTFLT.zip](https://github.com/OPM/opm-common/files/9131068/MULTFLT.zip)

**Comment by OPMUSER** [comment]
Can this be merged.

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
Yes it can.

**Pull request merged**
