### PR TITLE
Aicd deck load

### PR DESCRIPTION
**Pull request by joakim-hove**
@tskille : was this what you meant for ISEG fix?

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this serial please

**Comment by blattms** [comment]
Has been hanging in queue for quite a while. Any news? @tskille

**Comment by tskille** [comment]
This is a change that we no longer believe are correct. We are not working actively on restart at the moment, but if we later on learn that we need this, we will create a new PR. 

Hence, this PR can be closed. Can you @blattms close this ?

**Comment by blattms** [comment]
Sure, I am closing. Thanks for the heads up.

**Pull request closed without merging**
