### PR TITLE
Added pseudo unit system for untransformed input values.

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
What is the expected/intended use case for this unit convention?

**Comment by joakim-hove** [comment]
> What is the expected/intended use case for this unit convention?

The intended use case is for scripting applications[1] which read fragments of a deck, do something with and print out again. In situations like that:

1. We have generally not read the whole deck, and in particular we do not know the unit system requested by the deck.

2. The (interactive) user would probably prefer to work with "the same numbers" as found in the deck.

[1]: The python wrappers to the parser functionality is very slowly becoming something: https://github.com/Statoil/sunbeam/

**Comment by bska** [comment]
> The intended use case is for scripting applications[1] which read fragments of a deck, do something with and print out again.

Ah, I see.  Do we (meaning the parser) really support reading an arbitrary collection of keywords without sectioning information--especially `RUNSPEC`?  I seem to recall there being discussions about that topic before.

In any case, this PR seems like a reasonable way of accomplishing the stated goal.

**Comment by joakim-hove** [comment]
> Do we (meaning the parser) really support reading an arbitrary collection of keywords without sectioning information--especially RUNSPEC?

Well - formally the answer is no; but still subset of deck fragments which can be read is quite large. The application right now is reorganising a schedule section; i.e. inserting a well at an arbitrary point in time and such things.

But of course - when only working with fragments like this one can *not* generate a `EclipseState` structure - only a `Deck`.

**Comment by andlaus** [comment]
there seem to be no way to request this from a deck? maybe an OPM-specific keyword analogous to METRIC, FIELD, PVT_M and LAB should be added and wired up?

**Comment by andlaus** [comment]
as far as I can see, this new unit system should be called "SI"...

**Comment by joakim-hove** [comment]
> there seem to be no way to request this from a deck?

You are right - it is a secret feature with no linkage! 

The not-yet-implemented plan was that the low level parse method should get an optional unit system argument.

**Comment by joakim-hove** [comment]
OK - usage coming in a later PR.

**Pull request merged**
