### PR TITLE
Add WTEST to Allowed ACTIONX Keywords

### PR DESCRIPTION
**Pull request by OPMUSER**
Add WTEST to allowed ACTIONX Keywords

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
Note that #2676 also addresses the FSIP issue.  We'll also have remove this vector (i.e., FSIP) from the unit test for ALL in [SummaryConfigTests](https://github.com/OPM/opm-common/blob/0da931a7e6b0dd13e991791b7a76b8b59514b901/tests/parser/SummaryConfigTests.cpp#L458).

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=618 please

**Comment by bska** [comment]
Thanks.  I'll merge into master.

**Pull request merged**
