### PR TITLE
parameters to extend drsdtcon

### PR DESCRIPTION
**Pull request by trinemykk**
connected to opm-models (OPM/opm-models#902) and opm-simulators (OPM/opm-simulators#5418)

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this opm-models=902 opm-simulators=5418 please

**Comment by totto82** [comment]
The test failures are in the opm-models blackoil models i.e. they dont use opmcommon stuff. Adding a enableConvectiveMixing flag and make the convectiveMixingModule depent on this flag is the best way IMO to solve this. (ala what is done for the rest of the blackoilmodules)

**Comment by totto82** [comment]
jenkins build this opm-models=902 opm-simulators=5418 please

**Comment by totto82** [comment]
jenkins build this opm-models=902 opm-simulators=5418 please

**Comment by totto82** [comment]
jenkins build this opm-models=902 opm-simulators=5418 please

**Comment by totto82** [comment]
jenkins build this opm-models=902 opm-simulators=5418 please

**Comment by totto82** [comment]
jenkins build this opm-models=902 opm-simulators=5418 please

**Comment by totto82** [comment]
jenkins build this opm-models=902 opm-simulators=5418 please

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
jenkins build this opm-models=902 opm-simulators=5418 please

**Comment by totto82** [comment]
Thanks. The test failure in the DRSDTCON test is expected. I have manually checked the results and they are ok. To be on the safe side I will run a benchmark to check the performance. After that this can be merged.

**Comment by totto82** [comment]
benchmark please opm-models=902 opm-simulators=5418

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test | Configuration | Relative |
| ---- | ------------- | -------- |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *

FAILED RUNS: 
OPM Benchmark: drogon - Threads: 1 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: drogon - Threads: 8 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: punqs3 - Threads: 1 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: punqs3 - Threads: 8 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: smeaheia - Threads: 1 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: smeaheia - Threads: 8 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: spe10_model_1 - Threads: 1 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: spe10_model_1 - Threads: 8 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: flow_mpi_extra - Threads: 1 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: flow_mpi_extra - Threads: 8 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: flow_mpi_norne - Threads: 1 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: flow_mpi_norne - Threads: 8 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access

View result details @ https://www.ytelses.com/opm/?page=result&id=2524

**Comment by totto82** [comment]
Did I do something wrong when I called benchmark?

**Comment by totto82** [comment]
benchmark opm-models=902 opm-simulators=5418 please

**Comment by totto82** [comment]
benchmark please opm-models=902 opm-simulators=5418

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test | Configuration | Relative |
| ---- | ------------- | -------- |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *

FAILED RUNS: 
OPM Benchmark: drogon - Threads: 1 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: drogon - Threads: 8 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: punqs3 - Threads: 1 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: punqs3 - Threads: 8 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: smeaheia - Threads: 1 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: smeaheia - Threads: 8 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: spe10_model_1 - Threads: 1 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: spe10_model_1 - Threads: 8 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: flow_mpi_extra - Threads: 1 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: flow_mpi_extra - Threads: 8 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: flow_mpi_norne - Threads: 1 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: flow_mpi_norne - Threads: 8 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access

View result details @ https://www.ytelses.com/opm/?page=result&id=2526

**Comment by totto82** [comment]
@akva2 Do I do something wrong when calling benchmark?

**Comment by totto82** [comment]
>i'm not responsible for the benchmark support but i cannot see anything wrong as such. but the PR is also red, are you sure this actually builds?

I was unsure about the syntax to call benchmark across multiple repos.  "benchmark please opm-models=902 opm-simulators=5418" Will this work. Or do I need to add please in the end.

**Comment by akva2** [comment]
i believe your syntax is correct, although I must point out that whoever implemented it did not understand the practical role of the please in the trigger structure (ie it's there to have an end anchor). I have never seen the scripts behind the trigger so I can't really help other than my faint memory seeing that structure work before.

**Comment by totto82** [comment]
jenkins build this opm-models=902 opm-simulators=5418 please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test | Configuration | Relative |
| ---- | ------------- | -------- |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *

FAILED RUNS: 
OPM Benchmark: drogon - Threads: 1 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: drogon - Threads: 8 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: punqs3 - Threads: 1 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: punqs3 - Threads: 8 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: smeaheia - Threads: 1 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: smeaheia - Threads: 8 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: spe10_model_1 - Threads: 1 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: spe10_model_1 - Threads: 8 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: flow_mpi_extra - Threads: 1 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: flow_mpi_extra - Threads: 8 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: flow_mpi_norne - Threads: 1 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: flow_mpi_norne - Threads: 8 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 - opm-common 4097: parameters to extend drsdtcon: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access

View result details @ https://www.ytelses.com/opm/?page=result&id=2528

**Comment by totto82** [comment]
I have tested Norne and drogon and smeaheia and they all run fine (i.e. no changes in results and performance) locally.

**Comment by totto82** [comment]
I will try to merge this step by step. First opm-common.

**Comment by totto82** [comment]
jenkins build this please

**Pull request merged**
