### PR TITLE
Aquancon: don't segfault if an element's influx_coeff is a null pointer

### PR DESCRIPTION
**Pull request by andlaus**
I'm not sure when this happens, but it can definitely happen. Possibly if a cell is inactive?

### CODE REVIEW

**Comment by joakim-hove** [comment]
Have you seen it blow up in the wild; or is this a precaution?

**Comment by andlaus** [comment]
the former.

**Comment by joakim-hove** [comment]
Sorry - I will not merge this; it is too much symptom fixing; if you want to come back with a proper fix that is cool, otherwise I will give it a shot.

**Comment by andlaus** [comment]
okay, we will continue to use our own branches in the mean time. Also, I'm happy if you want to do the work, but I suspect that this happens if there is an inactive cell in thane aquifer, so I'm not sure if this can be done much differently...

**Comment by joakim-hove** [comment]
> Also, I'm happy if you want to do the work, 

I'm on it.

> [...] I suspect that this happens if there is an inactive cell in an aquifer

That was also my initial hunch - now I am leaning to think that the situation arises either due to invalid input - or that we have implemented some quirks of the relevant keywords incorrectly. Can you share the relevant keywords from the deck?

**Comment by andlaus** [comment]
> Can you share the AQUANCON keyword from the deck?

I've just asked: Unfortunately, it's not possible. If you want a direct contact, I can give you the email address...

**Comment by joakim-hove** [comment]
> I've just asked: Unfortunately, it's not possible.

Thank you for asking - I think I have found it; you could give #719 a spin.

**Pull request closed without merging**
