### PR TITLE
changed: remove unnecessary boost includes

### PR DESCRIPTION
**Pull request by akva2**
This is the first PR in a series of PRs that aim to reduce build times.

I don't know exactly how much this one is responsible for, but in a rather non-scientific test the build time on my box
with all changes was reduced from 47 min to 43 min.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by blattms** [comment]
Does that mean we can also get rid off those boost dependencies for the packages? That would a lot of time when building in clean changroots.

**Comment by akva2** [comment]
well, yes as such. we still need boost::test of course. but the real nasty ones are actually the boost::iterator_range and boost::spirit. these sit in the main libboost-dev iirc.

**Comment by atgeirr** [comment]
> boost::iterator_range

That one should not be too hard to replace with our own code, if that is a high enough priority.

**Comment by akva2** [comment]
that would not help much on its own.

**Comment by bska** [comment]
>> > `boost::iterator_range`
>> 
>> That one should not be too hard to replace with our own code,
>
> that would not help much on its own.

Besides, C++20 has `std::span` which completely supersedes that Boost library type.

**Comment by atgeirr** [comment]
> that would not help much on its own.

Since you said this was a nasty one, I just thought it could. Is the problem that it won't help unless we also remove boost::spirit?

**Comment by akva2** [comment]
yes exactly. the point would be getting rid of libboost-dev but since they both sit in that package, just one will not cut it.

**Review by bska — APPROVED** [review]
Thanks. I'll merge into master.

**Pull request merged**
