### PR TITLE
PAvgXXX: instantiate for float

### PR DESCRIPTION
**Pull request by akva2**
Extracted from #4016

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-simulators=5548 please

**Comment by akva2** [comment]
the failures here are.. concerning.

**Comment by lisajulia** [comment]
> the failures here are.. concerning.

OK - I have the same failures in another unrelated PR (#4167) - I suppose the failures come from something else?

**Comment by akva2** [comment]
yes. i'll explain in a bit i have to run to train now.

**Comment by atgeirr** [comment]
If the cause is the recent change on Jenkins to force only 1 thread for OpenBLAS, then the differences here should be identical across all PRs until fixed. I will run a data update here, which probably should fix things and be the right thing to do.

**Comment by atgeirr** [comment]
jenkins build this opm-simulators=5548 update_data please

**Comment by akva2** [comment]
Yes, I'm seeing consistent failures across all PRs. Fairly certain the thread change is the reason.

So what happened is that after the change defaults, in particular to cprw as default linear solver, I noticed slow performance and excessive cpu usage on jenkins. Tracked this to openblas using multiple threads. cprw means umfpack as coarse solver and umfpack uses blas. By pinning the number of openblas threads to 1 we now see consistent test failures. So indeed a data update should be the correct action. 

I also have hopes this will help stabilize the snow-flake MSW tests we have. In particular umfpack is used for solving the well equations. As these equations are often quite ill-conditioned the "random" summation order from using multiple threads in blas may very well be a big contributor to the instability of these tests.

**Comment by akva2** [comment]
Yeah, bulding @lisajulia PR with data update produces by this PR is now green. So I think the data update should be merged to fix the CI.

**Comment by akva2** [comment]
jenkins build this opm-simulators=5548 please

**Review by bska — APPROVED** [review]
Very good.  I'll merge this and its downstream counterpart into the master branch.

**Pull request merged**
