### PR TITLE
Use only first 8 characters as fault name when comparing/searching.

### PR DESCRIPTION
**Pull request by blattms**
Warnings about too long names need to be generated in the validation code in opm-simulators.

Needs OPM/opm-simulators#3959

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
Build failures should be fixed with https://github.com/OPM/opm-simulators/pull/3959

**Comment by bska** [comment]
jenkins build this opm-simulators=3959 please

**Review by bska — APPROVED** [review]
This is good solution that does not impact too much other code.  I'll merge this and the downstream PR into their respective master branches.

**Pull request merged**
