### PR TITLE
Rename SpiralICD -> SICD

### PR DESCRIPTION
**Pull request by joakim-hove**
This PR is a preparation for implementing AICD support in opm-common. Turns out that AICD is a perfect superset of SICD  - the plan is therefor to have one `ICD` with some extra optional `AICD`settings. The very first step - which is this PR - is to rename the `SpiralICD` class to the more generic `ICD`.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2640

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2640

**Comment by GitPaean** [comment]
WSEGLABY, it is also a ICD, and WSEGVALV is also a ICD. Not sure there are others. 

Only WSEGAICD is a superset of WSEGSICD.

**Comment by joakim-hove** [comment]
> WSEGLABY, it is also a ICD, and WSEGVALV is also a ICD. Not sure there are others.
Only WSEGAICD is a superset of WSEGSICD.

OK; I'll see

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2640

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2640 please

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2640 please

**Comment by joakim-hove** [comment]
This has been discussed offline - merging

**Pull request merged**
