### PR TITLE
Add missing <array> include.

### PR DESCRIPTION
**Pull request by atgeirr**
Compile fix for clang. Will self-merge when green, unless beat to it.

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by bska** [comment]
Shouldn't really need to "build please".  This is obviously correct and should go in, but I'll let the build check go through anyway.

**Comment by atgeirr** [comment]
> This is obviously correct and should go in

I agree, but I have experienced "obvious" fixed being wrong before. Better to always follow the rule.

**Comment by bska** [comment]
>> This is obviously correct and should go in
> 
> I agree, but I have experienced "obvious" fixes being wrong before. Better to always follow the rule.

The build check was green.  I'll merge this into master.  Thanks for the fix.

**Pull request merged**
