### PR TITLE
Use Early Return for Runtime WELPI Handling

### PR DESCRIPTION
**Pull request by bska**
That way we can remove one level of nesting.  While here, also ensure that we have a new 'scalingApplicable' object for each well lest we potentially run into conflicting definitions of the eligible connections.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Review by akva2 — APPROVED** [review]
I was itching to change to early return when I moved the code around but resisted the temptation ;)

**Comment by bska** [comment]
> I was itching to change to early return when I moved the code around but resisted the temptation ;)

:grin: 

I've had this particular change in the pipeline on my local machine for a long time, but it never seemed important enough.  With the current restructuring work I decided it was better to do it now than wait for another opportunity.

**Comment by bska** [comment]
Merging per prior approval.

**Pull request merged**
