### PR TITLE
fixed: avoid use of uninitialized SummaryNode::number_

### LINKED ISSUE #3090: Uninitialized usage in Summary.cpp
Uninitialized memory use runnng ACTIONX_GCONPROD.DATA

```
==1840963== Conditional jump or move depends on uninitialised value(s)
==1840963==    at 0x239426: int const& std::max<int>(int const&, int const&) (stl_algobase.h:227)
==1840963==    by 0x30C7795: (anonymous namespace)::Evaluator::FunctionRelation::update(unsigned long, double, (anonymous namespace)::Evaluator::InputData const&, (anonymous namespace)::Evaluator::SimulatorResults const&, Opm::SummaryState&) const (Summary.cpp:2650)
==1840963==    by 0x30CD3A9: Opm::out::Summary::SummaryImplementation::eval(int, double, Opm::data::Wells const&, Opm::data::GroupAndNetworkValues const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, double> > >&, Opm::Inplace const&, Opm::Inplace const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<double, std::allocator<double> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<double, std::allocator<double> > > > > const&, std::map<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int>, double, std::less<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int> >, std::allocator<std::pair<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int> const, double> > > const&, std::map<int, Opm::data::AquiferData, std::less<int>, std::allocator<std::pair<int const, Opm::data::AquiferData> > > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Opm::data::InterRegFlowMap, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Opm::data::InterRegFlowMap> > > const&, Opm::SummaryState&) const (Summary.cpp:3908)
==1840963==    by 0x30D109D: Opm::out::Summary::eval(Opm::SummaryState&, int, double, Opm::data::Wells const&, Opm::data::GroupAndNetworkValues const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, double> > >, Opm::Inplace const&, Opm::Inplace const&, Opm::PAvgCalculatorCollection const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<double, std::allocator<double> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<double, std::allocator<double> > > > > const&, std::map<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int>, double, std::less<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int> >, std::allocator<std::pair<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int> const, double> > > const&, std::map<int, Opm::data::AquiferData, std::less<int>, std::allocator<std::pair<int const, Opm::data::AquiferData> > > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Opm::data::InterRegFlowMap, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Opm::data::InterRegFlowMap> > > const&) const (Summary.cpp:4352)
==1840963==    by 0x1D45E63: Opm::EclGenericWriter<Dune::CpGrid, Dune::CpGrid, Dune::GridView<Dune::DefaultLeafGridViewTraits<Dune::CpGrid> >, Dune::MultipleCodimMultipleGeomTypeMapper<Dune::GridView<Dune::DefaultLeafGridViewTraits<Dune::CpGrid> >, Dune::Impl::MCMGFailLayout>, double>::evalSummary(int, double, std::map<unsigned long, double, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, double> > > const&, Opm::data::Wells const&, Opm::data::GroupAndNetworkValues const&, std::map<int, Opm::data::AquiferData, std::less<int>, std::allocator<std::pair<int const, Opm::data::AquiferData> > > const&, std::map<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int>, double, std::less<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int> >, std::allocator<std::pair<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int> const, double> > > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, double> > > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<double, std::allocator<double> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<double, std::allocator<double> > > > > const&, Opm::Inplace const&, Opm::Inplace const&, Opm::EclInterRegFlowMap const&, Opm::SummaryState&, Opm::UDQState&) (eclgenericwriter.cc:512)
==1840963==    by 0x33700B: Opm::EclWriter<Opm::Properties::TTag::EclFlowProblem>::evalSummaryState(bool) (eclwriter.hh:258)
==1840963==    by 0x30458A: Opm::EclProblem<Opm::Properties::TTag::EclFlowProblem>::endTimeStep() (eclproblem.hh:1159)
==1840963==    by 0x2DEC58: Opm::BlackoilModelEbos<Opm::Properties::TTag::EclFlowProblem>::afterStep(Opm::SimulatorTimerInterface const&) (BlackoilModelEbos.hpp:429)
==1840963==    by 0x2BB8B5: Opm::NonlinearSolverEbos<Opm::Properties::TTag::EclFlowProblem, Opm::BlackoilModelEbos<Opm::Properties::TTag::EclFlowProblem> >::step(Opm::SimulatorTimerInterface const&) (NonlinearSolverEbos.hpp:228)
==1840963==    by 0x2B98F8: Opm::SimulatorReport Opm::AdaptiveTimeSteppingEbos<Opm::Properties::TTag::EclFlowProblem>::step<Opm::NonlinearSolverEbos<Opm::Properties::TTag::EclFlowProblem, Opm::BlackoilModelEbos<Opm::Properties::TTag::EclFlowProblem> > >(Opm::SimulatorTimer const&, Opm::NonlinearSolverEbos<Opm::Properties::TTag::EclFlowProblem, Opm::BlackoilModelEbos<Opm::Properties::TTag::EclFlowProblem> >&, bool, std::vector<int, std::allocator<int> > const*) (AdaptiveTimeSteppingEbos.hpp:413)
==1840963==    by 0x29792D: Opm::SimulatorFullyImplicitBlackoilEbos<Opm::Properties::TTag::EclFlowProblem>::runStep(Opm::SimulatorTimer&) (SimulatorFullyImplicitBlackoilEbos.hpp:260)
==1840963==    by 0x27E584: Opm::SimulatorFullyImplicitBlackoilEbos<Opm::Properties::TTag::EclFlowProblem>::run(Opm::SimulatorTimer&) (SimulatorFullyImplicitBlackoilEbos.hpp:153)
==1840963== 
```
@bska i guess you might be knowledgable here. SummaryNode::number is uninitialized and seems to miss an assignment here. i'm not sure what is the correct fix.

_Originally posted by @akva2 in https://github.com/OPM/opm-common/pull/3088#discussion_r933552527_

@bska let's continue here, the issue is in current master..

### PR DESCRIPTION
**Pull request by akva2**
`SummaryNode::number_` does not have a value for all summary keywords.

closes #3090

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
missing an entry in the whitelist @bska?

**Comment by blattms** [comment]
@akva2 Will you investigate failing jenkins?

**Comment by akva2** [comment]
I am not really knowledgeable but both failures are the same keyword(s) so i assume the whitelist bska gave me miss a few entries. Waiting for confirmation..

**Comment by bska** [comment]
I will look into this tomorrow morning CEST. I'm traveling today.

**Comment by bska** [comment]
> missing an entry in the whitelist @bska?

Effectively yes.  I'd forgotten about the completion-related summary keywords which associate a completion number&mdash;defined in keyword `COMPLUMP`&mdash;with a summary keyword and a well name.  Common examples are `WOPRL` or `CGPTL`.  The current master sources do not actually have a category for completion-related keywords, but I've just created PR #3094 which corrects that problem and **should**, in theory, make this PR work correctly too.  In that case we don't need any further changes here once #3094 is merged.

**Comment by bska** [comment]
@akva2 : The downstream PR #3094 has been merged into the master branch.  Would you mind rebasing this on top of master and recheck if the current PR is sufficient to avoid accessing uninitialised memory?

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
i can confirm that 
- the fix is still needed
- it is now green.

**Comment by bska** [comment]
> i can confirm that
> 
> * the fix is still needed
> * it is now green.

Great news.  I'll merge into master.

**Pull request merged**
