### PR TITLE
Fix check for opm grid with dune 2.5

### PR DESCRIPTION
**Pull request by blattms**
This make the check for opm-grid and its compilation work with DUNE 2.5. Probably the second commit would probably have been sufficient. Without it dune-grid was trying to include old headers from dune-geometry that do not exist in version 2.5 any more.

Note that opm-simulators will not work with DUNE 2.5 as ewoms does not support it as it still relies on EntityPointers.

### CODE REVIEW

**Comment by akva2** [comment]
this looks fine to me. i'm going away on vacation tmrw (2 weeks) but i trust @blattms to test this sufficiently before merge. please remember to test 2.4 somewhere in addition (jenkins holds 2.3.1 so it covers that part).

**Comment by blattms** [comment]
Will do that check! Have a lovely vacation!

**Comment by bska** [comment]
jenkins build this with downstreams please

**Comment by blattms** [comment]
tested with dune 2.4 and comilation works.

**Comment by blattms** [comment]
For the record.

This PR fixes the problem that opm-core does not find opm-grid if DUNE 2.5 is used. Introspection of the CMakeError.log reveals:
```
Performing C++ SOURCE FILE Test HAVE_OPM_GRID failed with the following output:
Change Dir: /home/mblatt/DUNE-2.5/opm-core/opm-parallel/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTryCompileExec2536472088/fast"
/usr/bin/make -f CMakeFiles/cmTryCompileExec2536472088.dir/build.make CMakeFiles/cmTryCompileExec2536472088.dir/build
make[1]: Entering directory '/home/mblatt/DUNE-2.5/opm-core/opm-parallel/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/mblatt/DUNE-2.5/opm-core/opm-parallel/CMakeFiles/CMakeTmp/CMakeFiles 1
Building CXX object CMakeFiles/cmTryCompileExec2536472088.dir/src.cxx.o
/usr/bin/c++   -DDUNE_COMMON_FIELDVECTOR_SIZE_IS_METHOD=1 -DDUNE_COMMON_VERSION_MAJOR=2 -DDUNE_COMMON_VERSION_MINOR=5 -DDUNE_COMMON_VERSION_REVISION=1 -DDUNE_GRID_EXPERIMENTAL_GRID_EXTENSIONS=1 -DDUNE_GRID_VERSION_MAJOR=2 -DDUNE_GRID_VERSION_MINOR=5 -DDUNE_GRID_VERSION_REVISION=1 -DHAS_ATTRIBUTE_DEPRECATED=1 -DHAS_ATTRIBUTE_DEPRECATED_MSG=1 -DHAS_ATTRIBUTE_UNUSED=1 -DHAVE_ARRAY=1 -DHAVE_BOOST=1 -DHAVE_CXA_DEMANGLE=1 -DHAVE_DUNE_ISTL=1 -DHAVE_ERT=1 -DHAVE_MAKE_SHARED=1 -DHAVE_MPI=1 -DHAVE_NULLPTR=1 -DHAVE_OPM_GRID -DHAVE_OPM_PARSER=1 -DHAVE_SHARED_PTR=1 -DHAVE_STATIC_ASSERT=1 -DHAVE_TR1_TUPLE=1 -DHAVE_TUPLE=1 -DHAVE_TYPE_TRAITS=1 -DHAVE_ZOLTAN=1 -DMPI_2=1 -DSHARED_PTR_HEADER="<memory>" -DSHARED_PTR_NAMESPACE=std -pipe -Wall -Wno-unknown-pragmas -pthread -std=c++14 -DHAVE_OPM_GRID -I/home/mblatt/DUNE-2.5/opm-grid -I/usr/lib/openmpi/include -I/usr/lib/openmpi/include/openmpi -I/home/mblatt/DUNE-2.5/dune-common -I/home/mblatt/DUNE-2.5/dune-grid -I/home/mblatt/DUNE-2.5/dune-geometry -I/home/mblatt/DUNE-2.5/dune-istl -I/home/mblatt/DUNE-2.5/opm-common -I/home/mblatt/opt/include -isystem /home/mblatt/DUNE-2.5/opm-parser/lib/eclipse/include -isystem /home/mblatt/DUNE-2.5/opm-parser/opm-parallel/lib/eclipse/include -isystem /home/mblatt/DUNE-2.5/opm-parser/lib/json/include -isystem /home/mblatt/opt/libecl/include    -o CMakeFiles/cmTryCompileExec2536472088.dir/src.cxx.o -c /home/mblatt/DUNE-2.5/opm-core/opm-parallel/CMakeFiles/CMakeTmp/src.cxx
In file included from /usr/lib/openmpi/include/mpi.h:253:0,
                 from /home/mblatt/DUNE-2.5/dune-common/dune/common/parallel/variablesizecommunicator.hh:8,
                 from /home/mblatt/DUNE-2.5/opm-grid/dune/grid/CpGrid.hpp:53,
                 from /home/mblatt/DUNE-2.5/opm-core/opm-parallel/CMakeFiles/CMakeTmp/src.cxx:1:
/usr/lib/openmpi/include/mpi_portable_platform.h:374:34: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
              _STRINGIFY(__GNUC__)"."_STRINGIFY(__GNUC_MINOR__)"."_STRINGIFY(__GNUC_PATCHLEVEL__)
                                  ^
/usr/lib/openmpi/include/mpi_portable_platform.h:374:63: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
              _STRINGIFY(__GNUC__)"."_STRINGIFY(__GNUC_MINOR__)"."_STRINGIFY(__GNUC_PATCHLEVEL__)
                                                               ^
In file included from /usr/include/dune/geometry/genericgeometry/matrixhelper.hh:10:0,
                 from /usr/include/dune/geometry/genericgeometry/geometrytraits.hh:7,
                 from /home/mblatt/DUNE-2.5/opm-grid/dune/grid/cpgrid/Geometry.hpp:48,
                 from /home/mblatt/DUNE-2.5/opm-grid/dune/grid/cpgrid/Intersection.hpp:52,
                 from /home/mblatt/DUNE-2.5/opm-grid/dune/grid/CpGrid.hpp:62,
                 from /home/mblatt/DUNE-2.5/opm-core/opm-parallel/CMakeFiles/CMakeTmp/src.cxx:1:
/usr/include/dune/common/static_assert.hh:127:10: error: redefinition of ‘struct Dune::AlwaysFalse<T>’
   struct AlwaysFalse {
          ^
In file included from /home/mblatt/DUNE-2.5/dune-common/dune/common/iteratorfacades.hh:9:0,
                 from /home/mblatt/DUNE-2.5/dune-common/dune/common/arraylist.hh:11,
                 from /home/mblatt/DUNE-2.5/dune-common/dune/common/parallel/indexset.hh:7,
                 from /home/mblatt/DUNE-2.5/dune-common/dune/common/parallel/remoteindices.hh:6,
                 from /home/mblatt/DUNE-2.5/dune-common/dune/common/parallel/interface.hh:8,
                 from /home/mblatt/DUNE-2.5/dune-common/dune/common/parallel/variablesizecommunicator.hh:13,
                 from /home/mblatt/DUNE-2.5/opm-grid/dune/grid/CpGrid.hpp:53,
                 from /home/mblatt/DUNE-2.5/opm-core/opm-parallel/CMakeFiles/CMakeTmp/src.cxx:1:
/home/mblatt/DUNE-2.5/dune-common/dune/common/typetraits.hh:277:10: error: previous definition of ‘struct Dune::AlwaysFalse<T>’
   struct AlwaysFalse {
          ^
In file included from /usr/include/dune/geometry/genericgeometry/matrixhelper.hh:10:0,
                 from /usr/include/dune/geometry/genericgeometry/geometrytraits.hh:7,
                 from /home/mblatt/DUNE-2.5/opm-grid/dune/grid/cpgrid/Geometry.hpp:48,
                 from /home/mblatt/DUNE-2.5/opm-grid/dune/grid/cpgrid/Intersection.hpp:52,
                 from /home/mblatt/DUNE-2.5/opm-grid/dune/grid/CpGrid.hpp:62,
                 from /home/mblatt/DUNE-2.5/opm-core/opm-parallel/CMakeFiles/CMakeTmp/src.cxx:1:
/usr/include/dune/common/static_assert.hh:140:10: error: redefinition of ‘struct Dune::AlwaysTrue<T>’
   struct AlwaysTrue {
          ^
In file included from /home/mblatt/DUNE-2.5/dune-common/dune/common/iteratorfacades.hh:9:0,
                 from /home/mblatt/DUNE-2.5/dune-common/dune/common/arraylist.hh:11,
                 from /home/mblatt/DUNE-2.5/dune-common/dune/common/parallel/indexset.hh:7,
                 from /home/mblatt/DUNE-2.5/dune-common/dune/common/parallel/remoteindices.hh:6,
                 from /home/mblatt/DUNE-2.5/dune-common/dune/common/parallel/interface.hh:8,
                 from /home/mblatt/DUNE-2.5/dune-common/dune/common/parallel/variablesizecommunicator.hh:13,
                 from /home/mblatt/DUNE-2.5/opm-grid/dune/grid/CpGrid.hpp:53,
                 from /home/mblatt/DUNE-2.5/opm-core/opm-parallel/CMakeFiles/CMakeTmp/src.cxx:1:
/home/mblatt/DUNE-2.5/dune-common/dune/common/typetraits.hh:290:10: error: previous definition of ‘struct Dune::AlwaysTrue<T>’
   struct AlwaysTrue {
          ^
In file included from /usr/include/dune/geometry/genericgeometry/referencedomain.hh:15:0,
                 from /usr/include/dune/geometry/genericgeometry/referenceelements.hh:16,
                 from /usr/include/dune/geometry/genericgeometry/cornermapping.hh:7,
                 from /usr/include/dune/geometry/genericgeometry/geometrytraits.hh:8,
                 from /home/mblatt/DUNE-2.5/opm-grid/dune/grid/cpgrid/Geometry.hpp:48,
                 from /home/mblatt/DUNE-2.5/opm-grid/dune/grid/cpgrid/Intersection.hpp:52,
                 from /home/mblatt/DUNE-2.5/opm-grid/dune/grid/CpGrid.hpp:62,
                 from /home/mblatt/DUNE-2.5/opm-core/opm-parallel/CMakeFiles/CMakeTmp/src.cxx:1:
/usr/include/dune/geometry/genericgeometry/subtopologies.hh:598:46: error: ‘GenericForLoop’ was not declared in this scope
       static const unsigned int staticSize = GenericForLoop< StaticSum, Size, 0, dimension >::value;
                                              ^
/usr/include/dune/geometry/genericgeometry/subtopologies.hh:598:71: error: missing template arguments before ‘,’ token
       static const unsigned int staticSize = GenericForLoop< StaticSum, Size, 0, dimension >::value;
                                                                       ^
/usr/include/dune/geometry/genericgeometry/subtopologies.hh:598:77: error: ‘const unsigned int Dune::GenericGeometry::SubTopologyMapper<Topology>::Size’ conflicts with a previous declaration
       static const unsigned int staticSize = GenericForLoop< StaticSum, Size, 0, dimension >::value;
                                                                             ^
/usr/include/dune/geometry/genericgeometry/subtopologies.hh:583:14: note: previous declaration ‘template<class Topology> template<int codim> struct Dune::GenericGeometry::SubTopologyMapper<Topology>::Size’
       struct Size
              ^
/usr/include/dune/geometry/genericgeometry/subtopologies.hh:598:79: error: expected unqualified-id before numeric constant
       static const unsigned int staticSize = GenericForLoop< StaticSum, Size, 0, dimension >::value;
                                                                               ^
CMakeFiles/cmTryCompileExec2536472088.dir/build.make:57: recipe for target 'CMakeFiles/cmTryCompileExec2536472088.dir/src.cxx.o' failed
make[1]: *** [CMakeFiles/cmTryCompileExec2536472088.dir/src.cxx.o] Error 1
make[1]: Leaving directory '/home/mblatt/DUNE-2.5/opm-core/opm-parallel/CMakeFiles/CMakeTmp'
Makefile:118: recipe for target 'cmTryCompileExec2536472088/fast' failed
make: *** [cmTryCompileExec2536472088/fast] Error 2

Source file was:
#include <dune/grid/CpGrid.hpp>
int main (void) {
  Dune::CpGrid g;
  return 0;
}
```
Note that this happened with DUNE 2.3 installed under the default system path.

**Comment by blattms** [comment]
Without DUNE 2.3 the error log is more self explanators:
```
Performing C++ SOURCE FILE Test HAVE_OPM_GRID failed with the following output:
Change Dir: /home/mblatt/DUNE-2.5/opm-core/opm-parallel/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTryCompileExec3965660428/fast"
/usr/bin/make -f CMakeFiles/cmTryCompileExec3965660428.dir/build.make CMakeFiles/cmTryCompileExec3965660428.dir/build
make[1]: Entering directory '/home/mblatt/DUNE-2.5/opm-core/opm-parallel/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/mblatt/DUNE-2.5/opm-core/opm-parallel/CMakeFiles/CMakeTmp/CMakeFiles 1
Building CXX object CMakeFiles/cmTryCompileExec3965660428.dir/src.cxx.o
/usr/bin/c++   -DDUNE_COMMON_FIELDVECTOR_SIZE_IS_METHOD=1 -DDUNE_COMMON_VERSION_MAJOR=2 -DDUNE_COMMON_VERSION_MINOR=5 -DDUNE_COMMON_VERSION_REVISION=1 -DDUNE_GRID_EXPERIMENTAL_GRID_EXTENSIONS=1 -DDUNE_GRID_VERSION_MAJOR=2 -DDUNE_GRID_VERSION_MINOR=5 -DDUNE_GRID_VERSION_REVISION=1 -DHAS_ATTRIBUTE_DEPRECATED=1 -DHAS_ATTRIBUTE_DEPRECATED_MSG=1 -DHAS_ATTRIBUTE_UNUSED=1 -DHAVE_ARRAY=1 -DHAVE_BOOST=1 -DHAVE_CXA_DEMANGLE=1 -DHAVE_DUNE_ISTL=1 -DHAVE_ERT=1 -DHAVE_MAKE_SHARED=1 -DHAVE_MPI=1 -DHAVE_NULLPTR=1 -DHAVE_OPM_GRID -DHAVE_OPM_PARSER=1 -DHAVE_SHARED_PTR=1 -DHAVE_STATIC_ASSERT=1 -DHAVE_TR1_TUPLE=1 -DHAVE_TUPLE=1 -DHAVE_TYPE_TRAITS=1 -DHAVE_ZOLTAN=1 -DMPI_2=1 -DSHARED_PTR_HEADER="<memory>" -DSHARED_PTR_NAMESPACE=std -pipe -Wall -Wno-unknown-pragmas -pthread -std=c++14 -DHAVE_OPM_GRID -I/home/mblatt/DUNE-2.5/opm-grid -I/usr/lib/openmpi/include -I/usr/lib/openmpi/include/openmpi -I/home/mblatt/DUNE-2.5/dune-common -I/home/mblatt/DUNE-2.5/dune-grid -I/home/mblatt/DUNE-2.5/dune-geometry -I/home/mblatt/DUNE-2.5/dune-istl -I/home/mblatt/DUNE-2.5/opm-common -I/home/mblatt/opt/include -isystem /home/mblatt/DUNE-2.5/opm-parser/lib/eclipse/include -isystem /home/mblatt/DUNE-2.5/opm-parser/opm-parallel/lib/eclipse/include -isystem /home/mblatt/DUNE-2.5/opm-parser/lib/json/include -isystem /home/mblatt/opt/libecl/include    -o CMakeFiles/cmTryCompileExec3965660428.dir/src.cxx.o -c /home/mblatt/DUNE-2.5/opm-core/opm-parallel/CMakeFiles/CMakeTmp/src.cxx
In file included from /usr/lib/openmpi/include/mpi.h:253:0,
                 from /home/mblatt/DUNE-2.5/dune-common/dune/common/parallel/variablesizecommunicator.hh:8,
                 from /home/mblatt/DUNE-2.5/opm-grid/dune/grid/CpGrid.hpp:53,
                 from /home/mblatt/DUNE-2.5/opm-core/opm-parallel/CMakeFiles/CMakeTmp/src.cxx:1:
/usr/lib/openmpi/include/mpi_portable_platform.h:374:34: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
              _STRINGIFY(__GNUC__)"."_STRINGIFY(__GNUC_MINOR__)"."_STRINGIFY(__GNUC_PATCHLEVEL__)
                                  ^
/usr/lib/openmpi/include/mpi_portable_platform.h:374:63: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
              _STRINGIFY(__GNUC__)"."_STRINGIFY(__GNUC_MINOR__)"."_STRINGIFY(__GNUC_PATCHLEVEL__)
                                                               ^
In file included from /home/mblatt/DUNE-2.5/opm-grid/dune/grid/cpgrid/Intersection.hpp:52:0,
                 from /home/mblatt/DUNE-2.5/opm-grid/dune/grid/CpGrid.hpp:62,
                 from /home/mblatt/DUNE-2.5/opm-core/opm-parallel/CMakeFiles/CMakeTmp/src.cxx:1:
/home/mblatt/DUNE-2.5/opm-grid/dune/grid/cpgrid/Geometry.hpp:48:59: fatal error: dune/geometry/genericgeometry/geometrytraits.hh: No such file or directory
 #include <dune/geometry/genericgeometry/geometrytraits.hh>
                                                           ^
compilation terminated.
CMakeFiles/cmTryCompileExec3965660428.dir/build.make:57: recipe for target 'CMakeFiles/cmTryCompileExec3965660428.dir/src.cxx.o' failed
make[1]: *** [CMakeFiles/cmTryCompileExec3965660428.dir/src.cxx.o] Error 1
make[1]: Leaving directory '/home/mblatt/DUNE-2.5/opm-core/opm-parallel/CMakeFiles/CMakeTmp'
Makefile:118: recipe for target 'cmTryCompileExec3965660428/fast' failed
make: *** [cmTryCompileExec3965660428/fast] Error 2

Source file was:
#include <dune/grid/CpGrid.hpp>
int main (void) {
  Dune::CpGrid g;
  return 0;
}
```

**Comment by dr-robertk** [comment]
@blattms: With this patch everything works also in opm-simulators once 

opm_need_version_of ("dune-geometry")
opm_need_version_of ("dune-grid") 

is added to CMakeLists.txt in opm-simulators. 
There is one more problem when UMFPACK is found. dune-istl needs HAVE_SUITESPARSE_UMFPACK but the check in opm-common defines HAVE_SUITESPARSE_UMFPACK_H for some reasons. Once this is fixed then everything seems to compile.

**Comment by blattms** [comment]
@dr-robertk That should not be needed as the definitions get passed to downstream modules. I even recall having problems/warnings before if theses statements are repeated downstream.

**Comment by bska** [comment]
@dr-robertk said:

> There is one more problem when UMFPACK is found. dune-istl needs `HAVE_SUITESPARSE_UMFPACK` but the check in opm-common defines `HAVE_SUITESPARSE_UMFPACK_H` for some reasons. Once this is fixed then everything seems to compile.

The Dune ISTL started referencing `HAVE_SUITESPARSE_UMFPACK` [about one year ago]( https://gitlab.dune-project.org/core/dune-istl/commit/b335fd2e3cac3b30a5d7f04ac41f175f08be3d89) Until then, the symbol used to be called `HAVE_UMFPACK`.  OPM's symbol `HAVE_SUITESPARSE_UMFPACK_H` has been in place since [at least 2012](https://github.com/OPM/opm-core/commit/abab8dd711296989cc5af9f69d10590f45264067#diff-2ff18ed2f1d4c84f930ed91b10d1937fR44).

In any case, we have a mechanism in place for dealing with this.  It may not be entirely obvious, but we can define preprocesor symbol aliases in [`OpmAliases.cmake`](https://github.com/OPM/opm-common/blob/master/cmake/Modules/OpmAliases.cmake), included through `OpmLibMain.cmake`, that ensure that we define the symbol that the ISTL expects in terms of the symbol that we check for.  The change below, in addition to the current patch (PR #259) is sufficient for me to build the `master` branch of everything up to and including opm-simulators when targeting Dune 2.5.0.

Module opm-upscaling fails to build against Dune 2.5.0 however.  At minimum we need to do something about [`GridInterfaceEuler`](https://github.com/OPM/opm-upscaling/blob/master/opm/porsol/common/GridInterfaceEuler.hpp#L106) referencing `EntityPointer`s, but there may be other changes that are needed as well.

---

```diff
diff --git a/cmake/Modules/Finddune-istl.cmake b/cmake/Modules/Finddune-istl.cmake
index 9927e6f..1cb60a0 100644
--- a/cmake/Modules/Finddune-istl.cmake
+++ b/cmake/Modules/Finddune-istl.cmake
@@ -52,6 +52,7 @@ int main (void) {
   HAVE_PARMETIS;
   HAVE_SUPERLU;
   HAVE_UMFPACK;
+  HAVE_SUITESPARSE_UMFPACK;
   SUPERLU_MIN_VERSION_4_3;
   SUPERLU_POST_2005_VERSION
   ")
diff --git a/cmake/Modules/OpmAliases.cmake b/cmake/Modules/OpmAliases.cmake
index 392749b..48611b8 100644
--- a/cmake/Modules/OpmAliases.cmake
+++ b/cmake/Modules/OpmAliases.cmake
@@ -9,6 +9,7 @@ function (set_aliases)
   # are separated by space
   set (aliases
        "HAVE_UMFPACK             HAVE_SUITESPARSE_UMFPACK_H"
+       "HAVE_SUITESPARSE_UMFPACK HAVE_SUITESPARSE_UMFPACK_H"
        "HAVE_DUNE_BOOST          HAVE_BOOST"
        )
   foreach (alias IN LISTS aliases)
```

**Comment by akva2** [comment]
hopefully nobody will kill me. i need this to restore CI.

**Pull request merged**
