### PR TITLE
add field volumes in place to summary

### PR DESCRIPTION
**Pull request by goncalvesmachadoc**
Output FOIPR, FWIPR, FGIPR, FRPV

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Looks good to me and I'll merge into master.  Thanks a lot for hooking these vectors up to the summary system.

**Comment by OPMUSER** [comment]
@goncalvesmachadoc Just to confirm that the FOIPR, FWIPR, FGIPR (E300) vectors are reported at reservoir conditions, correct?

**Comment by goncalvesmachadoc** [comment]
> @goncalvesmachadoc Just to confirm that the FOIPR, FWIPR, FGIPR (E300) vectors are reported at reservoir conditions, correct?

Yes, they are the reservoir volumes vectors that we just created for the reservoir volumes table in the PRT files.

**Comment by OPMUSER** [comment]
Thanks for the confirmation, I have updated the manual accordingly.

**Pull request merged**
