### PR TITLE
Internalize tracers

### PR DESCRIPTION
**Pull request by joakim-hove**
Add some dimension trickery on top of #1627 

My blood sugar is dangerously low at the moment - if someone wants to point out that I have got the dimsensions wrong they are most probably right.

Is this this tracer stuff in use? Someone want's to step up with a real example?

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2496 please

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2496 please

**Comment by akva2** [comment]
There are TRACERS in norne. You have to give
``` 
--enable-tracer-model=true
```
to enable it. I used the vtk output for inspection; you have to use 
```
--enable-vtk-output=true --vtk-write-tracer-concentration=true --output-dir=somewhere
```
to see the results.

I have no basis to judge whether they work or not; but it seems to look the same before and after PR.

**Comment by joakim-hove** [comment]
> but it seems to look the same before and after PR.

That'll fly in my book - thanks for the testing.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this opm-simulators=2496 please

**Pull request merged**
