### PR TITLE
Renames header tests/WorkArea.cpp to tests/WorkArea.hpp

### PR DESCRIPTION
**Pull request by blattms**
If it walks like a duck why not call it one.

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by bska** [comment]
> If it walks like a duck why not call it one.

Sure, but I'd really prefer that this facility go into a tests-only library instead.

**Comment by blattms** [comment]
... Which would make my workflow of testing a Debian package a bit harder. 

Currently I assume that I can simply create a new dune module by copying a few test files and trying to compile the module.
But of course I can copy source files, too. will give it a try.

**Comment by blattms** [comment]
Well we also need to change our buildsystem for that and that will be even more work.  Probably not worth it for such a simple file. Undrafting.

**Pull request merged**
