### PR TITLE
Fix for connection D factors 

### PR DESCRIPTION
**Pull request by totto82**

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this opm-simulators=4996 please

**Comment by totto82** [comment]
jenkins build this opm-simulators=4996 please

**Comment by totto82** [comment]
jenkins build this opm-simulators=4996 please

**Comment by totto82** [comment]
jenkins build this opm-simulators=4996 please

**Comment by totto82** [comment]
jenkins build this opm-simulators=4996 please

**Comment by akva2** [comment]
jenkins build this opm-simulators=4996 please

**Comment by totto82** [comment]
jenkins build this opm-simulators=4996 please

**Comment by totto82** [comment]
jenkins build this opm-simulators=4996 please

**Review by bska — APPROVED** [review]
Thanks.  This looks good to me and I'll merge into master.

**Pull request merged**
