### PR TITLE
support for federated builds

### PR DESCRIPTION
**Pull request by andlaus**
i.e., with this the CMake modules do not need to be "centrally
collected" anymore, but can be shipped with the OPM modules which need
them.

This works by adding each existing "${MODULE_ROOT}/cmake/Modules"
directory for each specified variable that ends with "_ROOT" to the
CMake search path.

with this PR, the opm-cmake repository becomes basically obsolete because the general build system infrastructure can be placed in a "common" OPM source module whilst the higher level repositories can provide the CMake modules which they depend on. Note that this would require to introduce something an "opm-common" repository for such very basic stuff (e.g., stuff which does not depend on any libraries).

Also note that, in my opinion, we should still seriously consider to switch to an externally maintained build system because the build system is only seen as "neccessary evil" (at best) by basically anyone in OPM I'm aware of.

### CODE REVIEW

**Comment by joakim-hove** [comment]
I'm sorry I have not responded to this - it fell completely below the radar. I still feel this is related to build system *improvements*, which I would like to consider after the initial big merge.

**Comment by andlaus** [comment]
okay, I've rebased this on top of the current master and as a demonstration removed the Find modules of opm-material and ewoms here and added them to their main repositories. Using dunecontrol or when specifying -D${MODULE}_ROOT="$FOO" everything works smoothly, but the sibling build will most likely fail. (I haven't tested this, though.)

If you merge this PR, please also merge the corresponding PRs for opm-material and eWoms.

**Comment by atgeirr** [comment]
Has this been reviewed? Should it go in before we rename opm-cmake -> opm-common?

**Comment by akva2** [comment]
i don't think we want this now. we went with the opm-cmake / opm-common approach instead.

**Comment by andlaus** [comment]
> i don't think we want this now. we went with the opm-cmake / opm-common approach instead.

IMO it is only acceptable for external projects to use the OPM build system if they can fix the build of their module without bothering to open a PR for opm-$MODULE_WITH_BUILDSYSTEM. IMO this means that the the question of having a federated build system or not comes down to whether the build system is supposed to be used by external projects or not. (and if it is not supposed to be used by them, the question if/how usage of OPM code by external projects should be supported arises.)

**Comment by atgeirr** [comment]
Eventually the prereqs files and find macros should be hosted with the individual modules and not here. But is that what this PR set out to achieve? If so: did it achieve it? I think from comments above that the answer is not "yes" but "almost" (fails to consider the sibling build for example). However I think it is a very worthwhile goal.

**Comment by andlaus** [comment]
> Eventually the prereqs files and find macros should be hosted with the individual modules and not here. But is that what this PR set out to achieve? If so: did it achieve it? 

yes, that's at least what this PR wants to achieve with minimal effort: it does so by searching for module files in all directories specified by some ${FOO}_ROOT variable. the only disadvantage we discovered with it is that this does not work with sibling builds because these do not require to explicitly specify these locations. 

> I think from comments above that the answer is not "yes" but "almost" (fails to consider the sibling build for example

indeed. Be aware that "automatic" support for sibling builds should be removed for other reasons in (not only) my humble opinion. (it seems to me that even experienced developers who are new to OPM spend at least one working day hunting down issues which were in the end caused by the sibling build feature.)

**Comment by atgeirr** [comment]
> Be aware that "automatic" support for sibling builds should be removed for other reasons in (not only) my humble opinion.

Could we make everyone happy by using a single variable to specify the location for the sibling build (something_ROOT) and only use it if that variable is set?

**Comment by andlaus** [comment]
> Could we make everyone happy by using a single variable to specify the location for the sibling build (something_ROOT) and only use it if that variable is set?

for the approach to federated builds which taken in this PR here, no: In that world you still don't know what a module can possibly depend on. (there probably some ways to hack around this, but they will be not very easy to discover and probably some work to implement.)

regarding the work time lost to sibling builds, it would help if they would need to be explicitly created as you suggest.

instead of the sibling build feature, why are you not using a meta build tool or a shell script?

**Comment by atgeirr** [comment]
> instead of the sibling build feature, why are you not using a meta build tool or a shell script?

I have been promised such things, but no-one has made them available to the general public yet as far as I can tell. I may have forgotten some attempts though, sorry if I did. If you would put your build instructions/scripts/meta tools on opm-utilities that would be nice.

**Comment by atgeirr** [comment]
It looks like we still are not able to agree on the issues touched on by this PR. I would like the prerequisite files etc. for each module to be located in that module and not in opm-common, but I do not think this PR did that, at least not without taking away capabilities (such as sibling build?).

So should we close this, or keep it open as a reminder that we are not done yet with this discussion?

**Comment by andlaus** [comment]
let's revisit this when/if the time is ready for it...

**Pull request closed without merging**
