### PR TITLE
Explicitly define and specialize the static template variables in BlackOilFluidSystem.cpp

### PR DESCRIPTION
**Pull request by hakonhagland**
This should solve https://github.com/OPM/opm-simulators/issues/5390.

Move the template definitions of static variables from the header to the .cpp file and provide explicit specialiations for them there. This will make the static variables defined in the opmcommon.so shared library.

### CODE REVIEW

**Comment by hakonhagland** [comment]
I tested this PR with the issue https://github.com/OPM/opm-simulators/issues/5390 and it solved it on my laptop (all Python tests now passes when using shared libraries)

@akva How can we test with shared libraries with Jenkins?

**Comment by hakonhagland** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this mpi-shared please

**Comment by hakonhagland** [comment]
> jenkins build this mpi-shared please

@akva2 Did that trigger build libopmcommon.so (shared library) ? In the jenkins log:

https://ci.opm-project.org/job/opm-common-PR-builder/7131/consoleFull

I see this:
```
[799/1080] Linking CXX static library lib/libopmcommon.a
```
so it appears it created the static version (libopmcommon.a) instead?

**Comment by akva2** [comment]
jenkins build this mpi-shared please

**Comment by hakonhagland** [comment]
Thanks, it seems to use the shared libraries now. The link failure reported in [the last build](https://ci.opm-project.org/job/opm-common-PR-builder/7133/consoleFull):
```
[347/472] Linking CXX executable bin/test_cuda_safe_call
FAILED: bin/test_cuda_safe_call
```
seems unrelated to this PR as far as I can see.

**Comment by akva2** [comment]
please pick https://github.com/akva2/opm-simulators/tree/fix_cuda_shared_linking

**Comment by hakonhagland** [comment]
@akva2 That fix is in opm-simulators, right? Why not create a PR there for the fix?

**Comment by akva2** [comment]
because that build will fail running the tests, right?

**Comment by hakonhagland** [comment]
Hmm.. Can we run "jenkins build  mpi-shared please opm-simulators="https://github.com/akva2/opm-simulators/tree/fix_cuda_shared_linking" ?

**Comment by akva2** [comment]
right, this PR is in opm-common. i'm being stupid. PR opened.

**Comment by hakonhagland** [comment]
jenkins build this opm-simulators=4087 mpi-shared please

**Comment by akva2** [comment]
4087 ?

**Comment by hakonhagland** [comment]
jenkins build this opm-simulators=5401 mpi-shared please

**Comment by hakonhagland** [comment]
I now see from [the jenkins log](https://ci.opm-project.org/job/opm-common-PR-builder/7135/testReport/junit/(root)/mpi-shared/compareSeparateECLFiles_flow_pyaction_mult__insert_kw/) for one of the failed test cases `compareSeparateECLFiles_flow_pyaction_mult__insert_kw`:

```
/var/lib/jenkins/post-builder/workspace/opm-common-PR-builder/mpi-shared/install/bin/compareECL: error while loading shared libraries: libopmcommon.so.2024.10: cannot open shared object file: No such file or directory
```
Maybe we need to set LD_LIBRARY_PATH somewhere?

**Comment by akva2** [comment]
yes we do, i'll look into it.

**Comment by akva2** [comment]
it's fixed now but you won't get a green build because of failing tests (for other reasons). but let's see if the python tests pass now at least..

**Comment by hakonhagland** [comment]
> let's see if the python tests pass now at least..

@akva2 Yes, the Python tests now pass :)

```
        Start 371: python_basic
297/358 Test #370: flow__version .....................................................   Passed    0.63 sec
        Start 372: python_fluidstate_variables
298/358 Test #317: NORNE_RESTART .....................................................   Passed    7.35 sec
        Start 373: python_mpi
299/358 Test #372: python_fluidstate_variables .......................................   Passed    1.22 sec
        Start 374: python_primary_variables
300/358 Test #371: python_basic ......................................................   Passed    1.48 sec
        Start 375: python_schedule
301/358 Test #373: python_mpi ........................................................   Passed    1.12 sec
        Start 376: python_throw
302/358 Test #376: python_throw ......................................................   Passed    0.32 sec
303/358 Test #374: python_primary_variables ..........................................   Passed    1.64 sec
```

The other test failures seems related MSW test cases? Since you observed the same test failures in https://github.com/OPM/opm-simulators/pull/5401 I assume they are not related to this PR?

**Comment by akva2** [comment]
indeed.

**Comment by akva2** [comment]
this does it's job. it's unfortunate that we have to merge it in red but the failures are not caused by this PR and as it fixes what it aims to fix, i will merge it now.

**Pull request merged**
