### PR TITLE
Internal serialization in EclipseState - part 3

### PR DESCRIPTION
**Pull request by akva2**
Sits on top of https://github.com/OPM/opm-common/pull/1573

### CODE REVIEW

**Comment by blattms** [comment]
"Sits on top" means "includes"? Many of these code changes look very familiar. In that case rereviewing them might be a bit unproductive?

**Comment by akva2** [comment]
yes it means includes. just let me flush the others before you continue reviewing, i will rebase to get rid of the shared stuff as i go.

**Comment by blattms** [comment]
Cool, thanks.

**Comment by akva2** [comment]
jenkins build this opm-simulators=2468 please

**Pull request merged**
