### PR TITLE
Some janitoring

### PR DESCRIPTION
**Pull request by akva2**
First commit is strictly code style related, the second is an actual bug fix.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this opm-grid=387 dune2.5 please

**Comment by akva2** [comment]
jenkins build this opm-grid=387 dune2.5 please

**Comment by akva2** [comment]
jenkins build this opm-grid=387 dune2.5 please

**Comment by akva2** [comment]
jenkins build this opm-grid=387 please

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=387 please

**Comment by akva2** [comment]
opm-grid 387 is merged.

**Comment by akva2** [comment]
jenkins build this please

**Pull request merged**
