### PR TITLE
[WIP] Strip ecl word from ecl libraries

### LINKED ISSUE #456: Bug in generated opm-common-config.cmake?
The situation here is that I want to compile the `sunbeam` python wrapper/extension to the parser functionality in opm: https://github.com/Statoil/sunbeam/

This previously linked to the opm-parser project; I now want to bring it into 2018 and link to the opm-common project: https://github.com/Statoil/sunbeam/pull/85

The opm-common project has been built and installed, and in sunbeam I am looking for an installed version of opm-common:

```cmake
find_package(opm-common REQUIRED)
```
This configures and compiles nicely, but at link time the project fails with:
```
Linking CXX shared module ../python/sunbeam/libsunbeam.so
/usr/bin/ld: cannot find -lecl
```

Looking at the installed `opm-common-config.cmake` it contains this line:
```cmake
set (opm-common_LIBRARIES ${opm-common_LIBRARY} "ecl;/private/joaho/work/ERT/install/lib64/libecl.so.2.3;m;dl;-lpthread;/usr/lib64/libz.so;/usr/lib64/libboost_system-mt.so;/usr/lib64/libboost_filesystem-mt.so;/usr/lib64/libboost_regex-mt.so")
  mark_as_advanced (opm-common_LIBRARY)
```
i.e. the ecl library is mentioned twice - first as just `ecl` and then subsequently with full path. If I remove the `ecl` element from the list the linking of sunbeam succeeds. The multiple mention of `ecl` looked a bit suspicious to me - is it a bug?

### PR DESCRIPTION
**Pull request by blattms**
We already have the path of the ecl library in that variable
and the word ecl causes trouble like:

Linking CXX shared module ../python/sunbeam/libsunbeam.so
/usr/bin/ld: cannot find -lecl

Closes #456

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by akva2** [comment]
you added this in 0e25c9f2e985963fac59a2dee570e1c8e67663a5

**Comment by blattms** [comment]
@akva2 Thanks for the hint. I do not recall what situations I was talking about. Let us see what jenkins says.

**Comment by joakim-hove** [comment]
> if users do not do a find_package(ecl) before.

I tried that and it worked: https://github.com/Statoil/sunbeam/pull/85 but that is not how thing should be?

**Comment by joakim-hove** [comment]
For me the immediate problem is solved by adding `find_package(ecl REQUIRED)` in the Sunbeam cmake file, but I think this should be merged?

**Comment by blattms** [comment]
Closing as there is a better alternative.

**Pull request closed without merging**
