### PR TITLE
some white space cleaning up

### PR DESCRIPTION
**Pull request by GitPaean**
Created to test the master branch.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
The master branch is broken for the following test on Jenkins. 
```
Test Result (3 failures / ±0)
mpi.compareECLFiles_flow+3D_MSW
mpi.compareECLFiles_flow+MSW_MODEL_1
mpi.compareECLFiles_flow+FAULTS_MODEL_1
```

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
> update_data please

I'm a little hesitant to update the reference data without knowing the underlying cause.  As far as I can tell, there hasn't been a change to any of the modules recently that would cause the reference data to become out of data.  The fact that master doesn't run through unconditionally suggests that there might be uninitialized data somewhere.

**Comment by GitPaean** [comment]
> I'm a little hesitant to update the reference data without knowing the underlying cause

It is part of the procedure to check the cause. I will not suggest to merge it at all if we have not got some extent of knowledge about the issue.

**Comment by GitPaean** [comment]
jenkins build this opm-tests=125 please

**Comment by GitPaean** [comment]
All the cases (four of them) that update reference result are related to multisegment wells. See OPM/opm-tests#125.

**Comment by GitPaean** [comment]
jenkins build this opm-tests=125 please

**Comment by joakim-hove** [comment]
Is this situation (i.e. tests in master broken) being addressed?

**Comment by atgeirr** [comment]
I cannot find any clear cause of the breakage. I will merge this PR (although it is only very limited...) and more importantly its generated opm-tests PR to restore master testing on Jenkins.

**Comment by GitPaean** [comment]
With more tests, it is likely that some setup in Jenkins causes the broken test of master.  

Before (one week ago?), jenkins passed, my local tests passed
Before we merged the update produced with this PR yesterday, jenkins failed, my local test failed
After we merge the update yesterday, jenkins passed, my local test failed

Basically, it means, my local tests has been consistent with the jenkins test before. Then suddenly jenkins showed test failures that were difficult to figure out the cause, my local tests still worked well. 
Then we updated the reference result for jenkins, which failed my local tests.  Nothing changed for my machine, and also jenkins is the one failed first.

**Comment by atgeirr** [comment]
Could this be caused by libecl changing? Not very likely, though.

**Comment by GitPaean** [comment]
> Could this be caused by libecl changing? Not very likely, though.

Testing shows no. The version of dune is not related either.

**Comment by tskille** [comment]
The test fails for me as well and I will have a look at these.

**Comment by GitPaean** [comment]
It is a pity that we can not have the consistency between the local test and the jenkins test, which can be the source of some problems in the future. It is much easier to check the data locally than checking the things in Jenkins.

**Comment by tskille** [comment]
I have looked more into the test 'flow+FAULTS_MODEL_1':  

Egrid and Init is ok

test of summary file goes through if I change relative tolerance from 1e-5 to 1e-3. 
test of restart file, fails for report nr 5, keyword SWEL and XCON. 

SWEL are floating point data for wells. SWEL array is set to use strict tolerances since (1e-6) this is not solutions from the simulation. This is typically data which is processed from input (production targets, datum depths and so on). @bska is the best to help us with this. 

[tskille@tr-lx100028 flow+faults_model_1]$ ../../../../../opm-common/build/bin/compareECL FAULTS_MODEL_1 ../../../../../opm-tests/model1/opm-simulation-reference/flow/FAULTS_MODEL_1 2e-2 1e-3 -t UNRST -r 5 -a

2 keywords exhibit failures
        SWEL: Restart, sequence 5
                Fails for 1 entries
                Largest absolute error: 3.6621094e-03
                Largest relative error: 1.4521551e-06
        XCON: Restart, sequence 5
                Fails for 2 entries
                Largest absolute error: 5.6404848e-01
                Largest relative error: 1.3150459e-03


Is this the same as you see ?

**Comment by tskille** [comment]
Test: low+msw_3d_hfa: fails on summary (FGIPG) and restart (XCON), goes through if relative tolerance is increased from 1e-5 to 1e-4. 

Test: flow+msw_model_1: fails on summary. (need to increase relative tolerance to 5e-3). Restart report step 2, second value in DOUBHEAD. Doubhead require strict tolerances

**Comment by GitPaean** [comment]
> Is this the same as you see ?

They are the same.

**Comment by bska** [comment]
Just for the record, I too am unable to run those tests locally.  On the other hand, I wasn't able to run them before merging OPM/opm-tests#125 either.  Here is what I see when comparing `SWEL` in `FAULTS_MODEL_1`
```
46:     SWEL: Restart, sequence 11
46:             Fails for 1 entries
46:             Largest absolute error: 2.9296875e-03
46:             Largest relative error: 1.0610703e-06
46:     SWEL: Restart, sequence 12
46:             Fails for 1 entries
46:             Largest absolute error: 4.1503906e-03
46:             Largest relative error: 1.4912139e-06
46:     SWEL: Restart, sequence 6
46:             Fails for 1 entries
46:             Largest absolute error: 2.6855469e-03
46:             Largest relative error: 1.0152363e-06
46:     SWEL: Restart, sequence 7
46:             Fails for 1 entries
46:             Largest absolute error: 2.6855469e-03
46:             Largest relative error: 1.0052896e-06
```

---
Here are the differences I get in `XCON` when running `FAULTS_MODEL_1`
```
46:     XCON: Restart, sequence 10
46:             Fails for 14 entries
46:             Largest absolute error: 4.1454239e+00
46:             Largest relative error: 8.8320568e-04
46:     XCON: Restart, sequence 11
46:             Fails for 14 entries
46:             Largest absolute error: 1.0325147e+01
46:             Largest relative error: 6.1959193e-04
46:     XCON: Restart, sequence 12
46:             Fails for 17 entries
46:             Largest absolute error: 1.0151102e+01
46:             Largest relative error: 1.3247956e-04
46:     XCON: Restart, sequence 5
46:             Fails for 11 entries
46:             Largest absolute error: 7.0487409e+00
46:             Largest relative error: 5.9606708e-04
46:     XCON: Restart, sequence 6
46:             Fails for 6 entries
46:             Largest absolute error: 8.4248074e+00
46:             Largest relative error: 3.8878357e-05
46:     XCON: Restart, sequence 7
46:             Fails for 6 entries
46:             Largest absolute error: 6.9108859e+00
46:             Largest relative error: 7.2055737e-05
46:     XCON: Restart, sequence 8
46:             Fails for 24 entries
46:             Largest absolute error: 2.1183028e+01
46:             Largest relative error: 1.1370086e-02
46:     XCON: Restart, sequence 9
46:             Fails for 15 entries
46:             Largest absolute error: 7.6627355e+00
46:             Largest relative error: 7.0750996e-04
```

For completeness, the `SWEL` differences almost certainly stem from the [reservoir voidage rate target](https://github.com/OPM/opm-common/blob/71c046bef40840b7e7dff0c716363d0f1f4fdc9e/src/opm/output/eclipse/AggregateWellData.cpp#L496-L503) item of producer wells on history controls (WCONHIST).  We fill in those values based on simulation results.  In the case of prediction controls (WCONPROD), the target is set based on values read directly from the input deck and should not vary between simulation runs.

The `XCON` array generated by Flow contains [five](https://github.com/OPM/opm-common/blob/71c046bef40840b7e7dff0c716363d0f1f4fdc9e/opm/output/eclipse/VectorItems/connection.hpp#L63-L72) items (out of a total of [58](https://github.com/OPM/opm-common/blob/71c046bef40840b7e7dff0c716363d0f1f4fdc9e/src/opm/output/eclipse/CreateInteHead.cpp#L268)), all of which are defined in terms of [simulation results](https://github.com/OPM/opm-common/blob/71c046bef40840b7e7dff0c716363d0f1f4fdc9e/src/opm/output/eclipse/AggregateConnectionData.cpp#L237-L240).  Finally, item 2 (zero based index 1) of `DOUBHEAD` is an OPM-Flow [extension/hack](https://github.com/OPM/opm-common/blob/71c046bef40840b7e7dff0c716363d0f1f4fdc9e/src/opm/output/eclipse/DoubHEAD.cpp#L594-L602) to the regular restart protocol.  It was introduced in commit bfe25071 (PR #548) as a  means of communicating the suggested next step size when restarting a simulation from mostly ECLIPSE-compatible restart files (i.e., no OPM extended vectors such as `OPM_XWEL` or `OPMEXTRA`).  I haven't tried to remove that extension yet, but I would like to drop it.

**Comment by tskille** [comment]
> For completeness, the SWEL differences almost certainly stem from the reservoir voidage rate target item of producer wells on history controls (WCONHIST).

I was not aware of this. Then SWEL should then not use strict tolerances. Hence I will remove this from the list of arrays that should use strict tolerances.  I will update [EclRegressionTest.hpp](https://github.com/OPM/opm-common/blob/master/test_util/EclRegressionTest.hpp).

**Pull request merged**
