### PR TITLE
Add active_size() method to FieldPropsManager

### PR DESCRIPTION
**Pull request by joakim-hove**
Minor functionality

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
Just to be clear: active size is number of active cells?

**Comment by joakim-hove** [comment]
> Just to be clear: active size is number of active cells?

yes - it now even has a comment.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by blattms** [comment]
> yes - it now even has a comment.
:birthday: :tada:

**Pull request merged**
