### PR TITLE
fixed: sneaky ; was supposed to be :

### PR DESCRIPTION
**Pull request by akva2**
stupid fingers.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by bska** [comment]
Does this address the [recent opm-simulators integration failure](https://ci.opm-project.org/job/opm-simulators/1012/testReport/)?

**Comment by akva2** [comment]
it should. it took me a while but i now finally understand what's going on, so i want to do another change.

**Comment by akva2** [comment]
the problem was that we added to the PYTHONPATH. so on a second build configuration, we got into trouble. as PYTHONPATH should be empty on system level for jenkins (anything else is evil), i'll just make that assumption to avoid this problem.

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this serial please

**Comment by bska** [comment]
Thanks for the analysis.  Please merge if you're happy with the current version of this patch.

**Pull request merged**
