### PR TITLE
Implements OpmInputError in TableManager

### PR DESCRIPTION
**Pull request by wito**
This feature updates `TableManager` to throw `OpmInputError` where context permits.

### CODE REVIEW

**Comment by wito** [comment]
This feature now resolves #1975.

**Comment by wito** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by wito** [comment]
jenkins build this please

**Comment by wito** [comment]
jenkins build this please

**Comment by wito** [comment]
jenkins build this please

**Pull request merged**
