### PR TITLE
Add support for OPERATER keyword

### PR DESCRIPTION
**Pull request by joakim-hove**
This PR will add support for the OPERATER keyword. The OPERATER implementation as such works; however when applying this to the `PORV` keyword - which is *very-much-autogenerated-thanky-you-very-much* - it becomes very clear that the `GridProperty` system is in dire need for a refactor.

That refactor should not be too far into the future.

**Update**: OK - I have done some immediate refactoring; I feel slightly better now. Although the need for a refactor of the `GridProperty` system is certainly still warranted.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Anyone for a review? I'll merge tomorrow.

**Comment by GitPaean** [comment]
A question here, with this PR, the keyword `OPERATER` will work with simulation properly, right?

I just need a confirmation here.

**Comment by joakim-hove** [comment]
I think so - do you have experience of the contrary?

**Comment by GitPaean** [comment]
nope. I am debugging, and what to be sure this is not the problem, since it is something I saw for the first time.

**Comment by alfbr** [comment]
> I am debugging, and want to be sure this is not the problem

It is not the problem, we checked out the support a couple of months back.

**Pull request merged**
