### PR TITLE
Properly Distinguish Empty from Not Applicable Match Set

### PR DESCRIPTION
**Pull request by bska**
The result set intersection logic in commit c2a9d2f9d (PR #4340) failed to properly separate the cases of a match set not being applicable&ndash;e.g., in the case of a field level scalar condition&ndash;and a match set being empty.  This matters when there are multiple clauses being combined with the conjunction `AND`.  In that case the overall condition may be satisfied, but there may be no single well (or group) that satisfies all clauses whence the resulting match set should be empty.  The initial "empty set" handling might then, erroneously, pick the match set of the last clause.

This commit amends the empty set logic by marking the `wells_` as `optional<>`.  We now treat `nullopt` as "not applicable" and a non-null, but empty, match set as a true empty set the intersection by which also yields an empty set.

Add two unit tests to exercise this logic.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Review by akva2 — APPROVED** [review]
Looks good to me

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
PR approved and build check is green.  I'll merge into master.

**Pull request merged**
