### PR TITLE
changed: only keep keywords in sched_deck if there are actions

### PR DESCRIPTION
**Pull request by akva2**
This becomes very significant with large schedules. This is probably too naive but I want to check fallout.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this opm-simulators=5635 please

**Review by bska — COMMENTED** [review]
I haven't looked at the details here yet, I'll do that later, but I just want to point out that in a restarted simulation run (`rst != nullptr`) it is **possible**, though unlikely, that all of the `ACTIONX` data has been entered prior to the restart step.  If we're going with this approach then you might want to add something like
```C++
if (!keepKeywords) {
    keepKeywords = !rst->actions.empty();
}
```
to the [`if (rst)` branch](https://github.com/OPM/opm-common/blob/27a6e80523b7cfa5997befed3323c4afced1ac81/opm/input/eclipse/Schedule/Schedule.cpp#L149).  This includes  [`RstState::actions`](https://github.com/OPM/opm-common/blob/27a6e80523b7cfa5997befed3323c4afced1ac81/opm/io/eclipse/rst/state.hpp#L76) as one more source of information on whether to keep the input keywords.

**Comment by akva2** [comment]
done.

**Comment by akva2** [comment]
jenkins build this opm-simulators=5635 please

**Comment by akva2** [comment]
jenkins build this opm-simulators=5635 please

**Comment by blattms** [comment]
I have no overview here, so my question might make no sense.

How does this behave with MULT* in the schedule? We do have tests for this (opm-tests/mult/MULT2D_SCHD?.DATA), but even there the changes are still at the start of the simulation.

**Comment by akva2** [comment]
It would not affect it. The normal way the schedule operate is that we

1) list/copy all the keywords into the ScheduleDeck class.
2) iterate over the schedule and parse into appropriate classes (well instances with new multipliers applied as we go) for each step. this is done once, before the simulation starts.

Then we can throw away the keywords as everything has been stored in those classes. The exception for this is if there is an action. It will then, once an action triggers, replay the deck keywords starting with the step the action happened.

Thus we only need these keywords IF there are actions that need the replaying when triggered.

**Comment by bska** [comment]
Does the API change here mean that this must be merged together with the companion PR (i.e., OPM/opm-simulators#5635)?

**Review by bska — COMMENTED** [review]
This looks good to me and should be merged.  I'll defer merging, however, until I know if the downstream PR must be merged alongside this PR.

**Comment by akva2** [comment]
There is an api change, but as there is a default value corresponding to old behavior it should in theory build separate of the downstream. I did not test that however.

**Comment by bska** [comment]
> there is a default value corresponding to old behavior it should in theory build separate of the downstream

I saw the new default value, but I'm always uneasy when adding new defaulted parameters in the middle of the parameter list.

> I did not test that however

Okay, I'll run a build check now to see.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
>> I did not test [if this PR could be merged in isolation] however
>
> Okay, I'll run a build check now to see.

That experiment failed so the two PRs must be merged in concert.  Very well, I'll have a look at the other PR as well.

**Comment by akva2** [comment]
yeah, i can't resolve that one as it passed values for parameters after the added parameter.

**Review by bska — APPROVED** [review]
I've reviewed the downstream PR and everything looks good.  I'm open to discussing what the default value of `keepKeywords` should be at the simulator level, but that's a separate issue to having the feature.  I'll merge this and its downstream companion PR into the master branch now.

**Pull request merged**
