### PR TITLE
Segments updates2

### PR DESCRIPTION
**Pull request by joakim-hove**
More small updates to the segment model.

Part of the https://github.com/OPM/opm-common/issues/1396 sequel

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
Why did you switch back to using a raw pointer (commit 7829895)?  Do we no longer see the problems of commit 50460ec8d (PR #11170)?

**Comment by joakim-hove** [comment]
> Why did you switch back to using a raw pointer (commit 7829895)? Do we no longer see the problems of commit 50460ec (PR #1170)?

Allright - I was expecting to get flack for that one; I can revert it. I just felt the whole construction of creating a `std::unique_ptr` for five lines of code looked kind of funny - and a bit over engineered in my opinion; but anyway I can change it. How about:
```
WellConnections new_connections = input_connections;
// update new_connections
return new WellConnections( std::move(new_connections) );
```

**Comment by bska** [comment]
> I just felt the whole construction of creating a std::unique_ptr for [was] a bit over engineered in my opinion

It did fix a real problem however, although admittedly one that only happened in a unit test.

> How about [alternative]

That's better.  Better still would be to slightly restructure the implementation to not construct the new `WellConnections` object  until it's actually needed (after [`Compsegs::processCOMPSEGS`](https://github.com/OPM/opm-common/blob/4f63172dc9b5bb621ce320de95da9bded6385a49/src/opm/parser/eclipse/EclipseState/Schedule/MSW/updatingConnectionsWithSegments.cpp#L35)) because then we'd not be as vulnerable to the `ErrorGuard` throwing exceptions.

Ultimately, however, the real solution is to have `newConnectionsWithSegments()` actually return a `uniqe_ptr<WellConnections>`.  The primary caller&mdash;[`Well::handleCOMPSEGS()`](https://github.com/OPM/opm-common/blob/4f63172dc9b5bb621ce320de95da9bded6385a49/src/opm/parser/eclipse/EclipseState/Schedule/Well/Well.cpp#L488)&mdash;just hands the return value off to a `shared_ptr<>` and `shared_ptr<>` has a [constructor](https://en.cppreference.com/w/cpp/memory/shared_ptr/shared_ptr) from `unique_ptr<>`.  If `newConnectionsWithSegments()` were to return a `unique_ptr<>`, then the implementation of `Well::handle COMPSEGS()` wouldn't need to change at all.

**Comment by joakim-hove** [comment]
OK - I have added a fix to #1468 : 1205e8c 

When it comes to the other improvements you mention I am sure you are right; but I am all over this code right now and would like let things stabilize before the improvements you mention are addressed.

**Pull request merged**
