### PR TITLE
Removed well property total number of connections

### PR DESCRIPTION
**Pull request by joakim-hove**
The Well had a property total number of connections - this has been removed in favor of quering the connections object when it is needed.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
I think this may have unintended consequences.  Please talk to @jalvestad before merging this.  There are at least some parts of the output code that need to know the number of records in `COMPDAT`, not merely the number of active connections that a well happens to have at any given moment.

With the well objects being relocated recently, the history isn't easily available from Github any longer, but I do recall this property being introduced for a reason.

**Comment by joakim-hove** [comment]
>I think this may have unintended consequences. Please talk to @jalvestad before merging this. 

I will not merge right away. As I understood the functionality - which is now removed - was that it just summed up the total number of connections for a particular well; and that is the same as the size of the final connection set.

**Comment by bska** [comment]
> it just summed up the total number of connections for a particular well;

It didn't just do that.  Please see the bit in [Compsegs.cpp](https://github.com/OPM/opm-common/blob/fa77187871398185079ad59635aa6e94948bdd96/src/opm/parser/eclipse/EclipseState/Schedule/MSW/Compsegs.cpp#L129-L130) that you just removed.  Here, the `totNC` is `compsegs.size()` not `connections.size()`.

**Comment by joakim-hove** [comment]
> It didn't just do that. [...] Here, the totNC is compsegs.size() not connections.size().

Well - the more reason to remove it; it can count can segments and it can count connections. The result is applied to a variable called `number_of_connections` - with no further ado; it is only in this assignment: https://github.com/OPM/opm-common/blob/master/src/opm/output/eclipse/AggregateConnectionData.cpp#L92 - which at least name-wise is again about connections. I think the coupling to segments is purely accidental - because it has been used and tested in a situation where the number of segments and connections agree.

I would also like to point to that all tests pass; when all tests pass, it should be safe to merge such a refactoring - otherwise the tests have limited value. I'll be "quite offline" until Monday, will continue the task when I get back - but current inclination is to merge this.

**Comment by bska** [comment]
> but current inclination is to merge this.

Please don't!  There may well be work to do here, for instance in the variable naming and in making the roles more clear, but the current proposal is moving in the wrong direction.  All of this has to do with the ordering of connections in the restart file.  It matters deeply for multi-segmented wells.

> I think the coupling to segments is purely accidental

It is not.  That's the only thing that actually matters here.

> it should be safe to merge such a refactoring - otherwise the tests have limited value

The current tests do have limited value, but it's only because we have so few tests that activate the connection reordering for multi-segmented wells.

**Comment by joakim-hove** [comment]
Ok - I will not merge it for now, but this particular code is complicating other ongoing refactoring so I would really like you to make an effort so it is more comprehensible - and also tested. 

Well - I think this works as it does because it has only been tested/used on models where the number of segments and the number of connections is identical. Due to the naming I have assumed that it the connection conniction (pun intended) is the right and relevant one, if it is actually all about segments it really needs to change name.

**Comment by joakim-hove** [comment]
OK - @jalvestad - I have a minor update where the number of connections removed due to inactive cells is retained, and the `Well::getTotNoConn()` takes the removed connections also into account.

**Comment by jalvestad** [comment]
I have tested the latest version and it works OK!

**Comment by joakim-hove** [comment]
>I have tested the latest version and it works OK!

Thank you!

**Pull request merged**
