### PR TITLE
Allow for WELL as group limit action

### PR DESCRIPTION
**Pull request by totto82**

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this opm-simulators=5172 please

**Comment by totto82** [comment]
jenkins build this opm-simulators=5172 please

**Comment by totto82** [comment]
jenkins build this opm-simulators=5172 please

**Comment by totto82** [comment]
jenkins build this opm-simulators=5172 please

**Comment by akva2** [comment]
jenkins build this opm-simulators=5172 please

**Review by bska — CHANGES_REQUESTED** [review]
I suppose, in isolation, this could be passable.  In practice though, this PR needs a better description and a set of unit tests.  In its current form there are too many pitfalls in this area to just enable this change.

**Comment by totto82** [comment]
> I suppose, in isolation, this could be passable. In practice though, this PR needs a better description and a set of unit tests. In its current form there are too many pitfalls in this area to just enable this change.

Could you elaborate a bit. What pitfalls? It is unclear to me how we should handle cases where for instance item 7 is "NONE" and constrains are given (like item 3 - item 6).  From the simulator side a message telling the user that the limit is violated is given but no action is triggered.

https://github.com/OPM/opm-simulators/blob/2fcefbd743b23b7cedb9acaf9451e85c8c9db590/opm/simulators/wells/BlackoilWellModelConstraints.cpp#L426

But based on the code in question here. The parser will ignore item3-item6  if "none" is used for item7 both in the current code and with this PR. Wouldn't it be better to actually set the constrain (i.e. remove the check for "RATE" and "NONE"). Or have I misunderstood something?

**Comment by bska** [comment]
> What pitfalls?

That we don't know what the current (or proposed) code does.  I want unit tests that clearly delineate what we know works and what we know does not work.  The combinations here are too manifold to avoid introducing subtle problems during maintenance if we don't have proper test coverage so I want tests that demonstrate

1. Known good combinations
2. Known unsupported combinations
3. Exceptions for anything else

> The parser will ignore item3-item6 if "none" is used for item7 both in the current code and with this PR. Wouldn't it be better to actually set the constrain (i.e. remove the check for "RATE" and "NONE")

I don't know what's best here, and that's why I want much better test coverage in this area.

**Comment by totto82** [comment]
> I don't know what's best here, and that's why I want much better test coverage in this area.

I see. I will add a couple of tests that mimics my understanding as a starting point. Hopefully, I get a better understanding while testing.

**Comment by totto82** [comment]
@bska  Are we happy with the added tests?

**Comment by totto82** [comment]
jenkins build this opm-simulators=5172 please

**Review by bska — COMMENTED** [review]
The more I look at this, the more I become uneasy that this is not quite correct.  I also believe that the current master is not correct either.  Items [11&ndash;13](https://github.com/OPM/opm-common/blob/bd588c1f0091851a49d50c227e0372077d60dc86/opm/input/eclipse/share/keywords/000_Eclipse100/G/GCONPROD#L64-L81) hold **overriding** procedures for the water, gas, and liquid targets, meaning the resulting phase-specific action procedures should be along the lines of

Base | p = `1*` | p = `NONE` | p = y
----- | ---- | ---- | ---- 
`NONE` | `NONE` | `NONE` | y
x | x | `NONE` | y

in which "Base" is the procedure from `GCONPROD(7)` and "p" is one of the phase-specific procedures in items 11&ndash;13.  Moreover "x" and "y" signify specific procedure values other than `NONE`.  Finally, the value p = `1*` signifies a defaulted item.

Unless I'm missing something I think we should amend the construction of the [phase-specific procedures](https://github.com/OPM/opm-common/blob/bd588c1f0091851a49d50c227e0372077d60dc86/opm/input/eclipse/Schedule/Group/GroupKeywordHandlers.cpp#L182-L185) to also inspect the `Item::defaultApplied()` flag, meaning we do something along the lines of
```C++
action.water = record.getItem("WATER_EXCEED_PROCEDURE").defaultApplied(0)
    ? action.allRates
    : Group::ExceedActionFromString(record.getItem("WATER_EXCEED_PROCEDURE").getTrimmedString(0));
```
(and similar for gas and liquid).  If constructed this way&ndash;and we might want to push that logic to a separate helper function&ndash;then I believe it'll be sufficient to check conditions of the form
```C++
production.cmode == WRAT || ((action.water != NONE) && !apply_default_water_target)
```
for whether or not to incldude one of the phase-specific targets in `GroupProductionProperties::production_control`.

**Comment by totto82** [comment]
jenkins build this opm-simulators=5172 please

**Comment by totto82** [comment]
Thanks @bska. I think I have implemented what you suggested. The tests, both in opm-common and opm-simulators are still ok.

**Comment by bska** [comment]
jenkins build this opm-simulators=5172 please

**Comment by bska** [comment]
jenkins build this opm-simulators=5172 please

**Review by bska — APPROVED** [review]
Thanks a lot for the updates.  This looks good to me now and I'll merge into master.

**Pull request merged**
