### PR TITLE
Add hybrid LINRAD (linear-radial) filter cake model

### PR DESCRIPTION
**Pull request by vkip**

### CODE REVIEW

**Comment by GitPaean** [comment]
The PR is looking fine. Please let us know whether the development is done so we can get it in. @vkip

**Comment by vkip** [comment]
> The PR is looking fine. Please let us know whether the development is done so we can get it in. @vkip

Thanks, and sorry for the lack of information. I'll add a short background to the counterpart in opm-simulators. 
I believe this is done, so please proceed to merge at will.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
>  I'll add a short background to the counterpart in opm-simulators.

Maybe you should add some description here for the people to update the manual for this keyword option.  @vkip 

I am merging the PR in now.

**Comment by vkip** [comment]
Information for manual update: 
This PR (+ https://github.com/OPM/opm-simulators/pull/5717) adds 'LINRAD' as a valid option for item 2 (GEOMETRY) in keyword WINJDAM. The filter cake model will then be a hybrid where the cake thickness is computed assuming linear geometry (as with item 2 = LINEAR). This thickness is then used to compute a damage skin in radial geometry (as with item 2 = RADIAL).

**Pull request merged**
