### PR TITLE
DeckKeyword: constr. with records takes unitsystem args.

### PR DESCRIPTION
**Pull request by stefoss23**
Deckkeyword constr w/ records also takes 2 unit_systems args active and default. 

Functionality is also added in Python.

### CODE REVIEW

**Comment by stefoss23** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
This needs a rebase and then it will be merged.

**Comment by joakim-hove** [comment]
rebase?!

**Comment by stefoss23** [comment]
jenkins build this please

**Pull request closed without merging**
