### PR TITLE
Abort parser if COMPSEGS is missing for multisegment well.

### PR DESCRIPTION
**Pull request by blattms**
This might not be 100% perfect but it will detect completely missing COMPSEGS keywords for multisegment wells already during file parsing instead of during the simulation at the report step where the problem occurs (could be rather late). Hence it improves  OPM/opm-simulators#4329.

We keep track of all the wells that appear in WELSEGS and COMPSEGS and at the end of each report step parsed, we check that there is entry using COMPSEGS for each well that was in WELSEGS.

Note that the keyword used for the error is the first WELSEGS with missing COMPSEGS. Error message looks like:

```
Error: Problem with keyword WELSEGS
In MSW-3D-03.DATA line 2391
Missing COMPSEGS keyword for the following multisegment well:
   PROD01 in MSW-3D-03.DATA at line 2391.

Error: Unrecoverable errors while loading input: Problem with keyword WELSEGS
In MSW-3D-03.DATA line 2391
Missing COMPSEGS keyword for the following multisegment well:
   PROD01 in MSW-3D-03.DATA at line 2391.
````

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
This is a good start.  I can imagine a slightly different  though more invasive design that would allow us to detect the situation only when the wells change, but we can do that if the need arises.

I'll merge this for now.

**Comment by bska** [comment]
> I'll merge this for now.

Actually, scratch that.  I didn't notice that one of the existing tests [started failing](https://ci.opm-project.org/job/opm-common-PR-builder/5296/) with this PR.

**Comment by GitPaean** [comment]
Should we check all the connections that `connection.attachedToSegment()` is `true`?

Then it is slightly more general approach?

**Comment by blattms** [comment]
> Should we check all the connections that connection.attachedToSegment() is true?

Luckily, that is already checked when handling COMPSEGS keyword, (hopefully for ages)

> Actually, scratch that. I didn't notice that one of the existing tests [started failing](https://ci.opm-project.org/job/opm-common-PR-builder/5296/) with this PR.

Yep, because they rely on allowing missing COMPSEGS keyword.

I will also try to improve the error message and use the location of the corresponding WELSEGS keyword instead of the range. Seems to make more sense to me.

**Comment by bska** [comment]
> > Actually, scratch that. I didn't notice that one of the existing tests [started failing](https://ci.opm-project.org/job/opm-common-PR-builder/5296/) with this PR.
> 
> Yep, because they rely on allowing missing COMPSEGS keyword.

More like they don't actually care about the connections, just the topological structure of the well segments.

**Comment by GitPaean** [comment]
> Luckily, that is already checked when handling COMPSEGS keyword, (hopefully for ages)

I saw the code now. It was there from the very beginning of the multisegment wells model.  

That code might fail if multiple COMPSEGSs are used to complete for a multisegment well, but it might be out of scope for this PR.

**Comment by blattms** [comment]
Test should be fixed now.

Improved error message for missing COMPSEGS keyword: Instead of listing a range where the errors are we now list the
location of each corresponding WELSEGS keyword to give the user all the information that he may need.

Error looks like:

```
unknown location(0): fatal error: in "MissingCOMPSEGS": Opm::OpmInputError: Problem with keyword WELSEGS
In <memory string> line 38
Missing COMPSEGS keyword for the following multisegment well:
    PROD01 in <memory string> at line 38.
```

**Comment by blattms** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks for the updates.  I'll merge into master.

**Pull request merged**
