### PR TITLE
Run pyaction

### PR DESCRIPTION
**Pull request by joakim-hove**
This code is getting very close to "complete and usable" - up until now the Python code has been just a module, and the context from the simulator has been injected into the model prior to running. I.e. as part of this PR there is a test module `action2.py` which looks like:

```Python
wells_shut = False
sim = context.sim
schedule = context.schedule
report_step = context.report_step

for well in sim.wells:
    if sim.well_var(well, "WWCT") > 0.50:
        schedule.shut_well(well, report_step)
        wells_shut = True

context.result = wells_shut
```
this works - but in particular it is difficult to check the syntax up front. I have considered the alternative where the script must have a function `run()`:

```Python
def run(schedule, sim, report_step):
    wells_shut = False
    for well in sim.wells:
    if sim.well_var(well, "WWCT") > 0.50:
        schedule.shut_well(well, report_step)
        wells_shut = True
    return wells_shut
```
and the context is supplied as arguments to this function. I am leaning in the direction of the `run()` function.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
**Manual**

The `PYACTION` keyword is opm only keyword which can be used to run Python code during the simulation. As the name indicates the initial inspiration was to facilitate writing `ACTIONX` statements in Python, but the keyword can be used to run code for any type of purpose, in particular as a way to assign values to `UDQ`.

The `PYACTION` keyword consists of two records, the first record contains the name of the action - that is an arbitrary string, and a string indicating the number of times the action should be run. For the latter there are three possible values:

   SINGLE: The action is run exactly once
   UNLIMITED: The action is run at the end of *every* timestep
   FIRST_TRUE: The action is run at the end of every timestep - until it returns True

The second record is the path to a Python module which will be run as the action.

*Example 1:*

```
PYACTION
    'WELL_CHECK'  'UNLIMITED' /
   'path/to/well_check.py' /
```

*About the Python module*
The Python module is 100% normal Python - but it must have a function `run( )` with a certain signature:
```Python
def run(ecl_state, schedule, report_step, summary_state):
      if summary_state.get_well_var("OP1", "WWCT") > 0.80:
            schedule.shut_well("OP1", report_step)
```

The Python module is imported during the parse phase - this implies that:
1. Basic syntax is checked during import
2. It is verified that the module has a run function
3. Code which is at module level is run at import time - you probably don't want that.

*Context from the simulator*

*Example 2:*

*Used to evaluate UDQ/UDQ*

*Experimental feature*

*Safety precautions*

**Comment by joakim-hove** [comment]
jenkins build this opm-test=283 opm-simulators=2536 please

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2536 please

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2536 update_data please

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2536 update_data please

**Comment by joakim-hove** [comment]
OK - I know consider this code "complete and ready" and intend to merge it in the near future. The current code works - and is IMHO an interesting capability. Current code is a "framework" with a quite limited number of ready callable functions; hopefully it will be quite simple to add more callable functions when we get user testing.

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2536 opm-tests=289 please

**Comment by joakim-hove** [comment]
There are some new warnings: 
```
PyRunModule.hpp:41:8: warning: ‘Opm::PyRunModule’ declared with greater visibility than the type of its field ‘Opm::PyRunModule::storage’ [-Wattributes]
```
which I don't know how to handle.

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2536 opm-tests=289 please

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2536 update_data please

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2536 opm-tests=289 please

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2536 update_data please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by akva2** [comment]
wrong trigger.

**Comment by joakim-hove** [comment]
jenkins build this opm-simulators=2536 opm-tests=289 please

**Pull request merged**
