### PR TITLE
EclMaterialLawManager: move most code to separate compile unit

### PR DESCRIPTION
**Pull request by akva2**
To encapsulate various types.

Waiting for https://github.com/OPM/opm-common/pull/3246

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
benchmark please

**Review by bska — APPROVED** [review]
Thanks, this looks good to me.  Please merge when you're satisfied that there's no appreciable performance reduction.

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                              | Relative |
| ------- | ------------------------------------------ | -------- |
| opm-git | OPM Benchmark: drogon - Threads: 1         | 1.05     |
| opm-git | OPM Benchmark: drogon - Threads: 8         | 1.003    |
| opm-git | OPM Benchmark: smeaheia - Threads: 1       | 1.003    |
| opm-git | OPM Benchmark: smeaheia - Threads: 8       | 1.01     |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 | 1.01     |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 | 1.005    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 | 1.003    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 | 1.001    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1886

**Comment by akva2** [comment]
jenkins build this please

**Pull request merged**
