### PR TITLE
Add Group constructor based on RstGroup

### PR DESCRIPTION
**Pull request by joakim-hove**
Small step in restart sequel

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Comments?

**Comment by akva2** [comment]
new warning.

**Comment by joakim-hove** [comment]
> new warning.

Fixed

**Comment by joakim-hove** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
This looks good to me.  Unless you intend to make additional changes here I suggest we merge this as is.

**Pull request merged**
