### PR TITLE
Add SummaryState class to hold on to summary state.

### PR DESCRIPTION
**Pull request by joakim-hove**
Preparation to check/look up summary variables run-time for e.g. UDQ / WTEST / ACTION and other niceties.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
> Preparation to check/look up summary variables run-time for e.g. UDQ / WTEST / ACTION and other niceties.

One of those niceties is being able to output well and group-related quantities to restart files.

**Comment by joakim-hove** [comment]
review?

**Comment by bska** [comment]
> review?

I'll try to get it done later tonight but no promises.

**Comment by joakim-hove** [comment]
jenkins build this libecl=411 please

**Comment by bska** [comment]
Overall I think this is a good start.  The `SummaryState` protocol is a bit too tightly coupled to the internals of the output code in my opinion&mdash;clients are essentially expected to pass `gen_key1` values from libecl as the lookup keys&mdash;but we can perhaps loosen this coupling at a later time.

I also think it is needlessly verbose to implement predicate functions as
```C++
bool pred(args)
{
    if (condition(args)) {
        return true;
    } else {
        return false;
    }
}
```
and I moreover notice that the `SummaryState::length` data member appears to be unused.  Is that intentional?

Other than that I think this should go into master.

**Comment by joakim-hove** [comment]
> lients are essentially expected to pass gen_key1 values from libecl as the lookup keys—but we can perhaps loosen this coupling at a later time.

yes - that is right. It can certainly be changed at a later stage, but it has been my experience oer seval years, that the `gen_key1`- i.e. `VAR:QUALIFIER1:QUALFIER2` syntax has been very convenient. More well/field/group/... specific apis provide more type safety and context, and can of course be provided, but my experience has been that these feel more klunky, and the simple gen_key based approach has been the most comfortable to use.

> I also think it is needlessly verbose to implement predicate functions as

Fixed

> I moreover notice that the SummaryState::length data member appears to be unused

Removed

**Comment by joakim-hove** [comment]
jenkins build this libecl=411 please

**Comment by bska** [comment]
Thanks for the updates.  I approve of the PR in its current form.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
This used to fly in jenkins, now it fails. Is master good?

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this libecl=411 please

**Comment by joakim-hove** [comment]
Thank you for review - merging.

**Pull request merged**
