### PR TITLE
Aquifer grid order

### PR DESCRIPTION
**Pull request by joakim-hove**
Partial fix to: https://github.com/OPM/opm-simulators/issues/3126

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
It looks it conflicts with numerical aquifers. I would like to help, but today I am out of the office. Maybe this evening or tomorrow if you can wait.

**Comment by joakim-hove** [comment]
> It looks it conflicts with numerical aquifers. I would like to help, but today I am out of the office. Maybe this evening or tomorrow if you can wait. You are free to go ahead though.

Yes - I have just discovered that; will take a brief look - but otherwise your offer of assistance is appreciated; we'll stay in touch.

**Comment by joakim-hove** [comment]
@bska : I think this should also fix the problem mentioned [here](https://github.com/OPM/opm-simulators/issues/3126#issuecomment-805268082)

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
It looks good to me.

**Review by bska — APPROVED** [review]
Looks good to me.  I think this is will solve all known issues with aquifers and inactive cells.  I'll merge into master.

**Pull request merged**
