### PR TITLE
New kw PVTSOL to accomodate an extension of the black oil model.

### PR DESCRIPTION
**Pull request by osae**
Table of PVT data for an alternative solvent extension of the black oil model.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
I guess this can be merged; but first of all it must be fixed to be green in the build system.

The `PVTX` tables are *quite complex* - since this keyword is something implement ourselves it might(?) be possible to model the `PVTSOL` keyword after one of the simpler tables/keywords - or do you really need the full complexity of the `PVTX` tables?

**Comment by osae** [comment]
To my understanding, the building issue is as follows:

/var/lib/jenkins/workspace/opm-common-PR-builder@2/mpi/install/include/opm/parser/eclipse/EclipseState/Tables/TableManager.hpp:39:10: fatal error: opm/parser/eclipse/EclipseState/Tables/PvtsolTable.hpp: No such file or directory
 #include <opm/parser/eclipse/EclipseState/Tables/PvtsolTable.hpp>
 
However, as far as I can see, the pr contains the file at the given location. Can there be any configuration issues that I've missed?

The new table is very similar to the PVTO table (also derived from PVTX). There is an outer table of solvent fractions (similar to PVTO:RS), and for each outer table entry there is an inner table of properties as function of pressure (the # rows and pressure values might vary across different inner tables). Compared to PVTO with 4 columns, the PVTSOL has 10 columns.

**Comment by totto82** [comment]
I think you need to add the filename it to CMakeLists_files.cmake

**Comment by joakim-hove** [comment]
> However, as far as I can see, the pr contains the file at the given location. Can there be any configuration issues that I've missed?

Yes. Jenkins installs the modules as it goes, and downstream builds against the installed upstream packages. So - to ensure thus you must add the new `.hpp` file to the `CMakeLists_files.cmake`

**Comment by osae** [comment]
Thank you for advising.  `CMakeLists_files.cmake` has now been fixed.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by osae** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Review by joakim-hove — APPROVED** [review]
This can be merged; please indicate if you consider it ready.

**Pull request merged**
