### PR TITLE
Fix install mode

### PR DESCRIPTION
**Pull request by akva2**
- install cmake rules
- properly generate cmake config file

### CODE REVIEW

**Comment by akva2** [comment]
@joakim-hove please confirm

**Comment by joakim-hove** [comment]
> please confirm

I'm on it.

**Comment by joakim-hove** [comment]
I don't understand this - the install seems to work, whereas finding the cmake modules based on sibling search for opm-common does not seem to work? Assume opm-common and opm-parser checked out as sibling directories:

__Installed cmake modules:__

```bash
cd opm-common
mkdir build ; cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/tmp/opm/install
make install

cd ../../opm-parser
mkdir build ; cd build
cmake .. -DOPM_COMMON_ROOT=/tmp/opm/install/share/opm 
make
```
I.e. this is roughly[1] the way I hoped it should work. 

__Finding opm-common / cmake modules using sibling search:__
If I do not tell the parser where the opm-common module is located I was expecting it to find that using sibling search - but that does not work for me:

```bash
# Remove all traces of installed opm-common; including the opm-common/build directory

cd opm-parser
mkdir build ; cd build
cmake ../    
```

Where the last `cmake ../` command fails because the OPM specific build modules can not be found.

When trying to debug this I have stared and long and hard at this code: https://github.com/OPM/opm-parser/blob/master/CMakeLists.txt#L14. I would *assume* that:
```
15:  find_package(opm-common QUIET)
```
 should fail as the native `find_package()`should have no clue as to where to find `opm-common`? However the `opm-common_FOUND` variable is set to 1, and the block on lines 18-43 is never entered; consequently the `OPM_CMAKE_PATH` variable is never modified and then
 ```
72:  include(UseMultiArch)
```
fails.

[1]: This is still a detail - but it anticipating the day when `opm-common` gets code as well, it would be very convenient to distinguish between the code part of opm-command and the cmake configuration part - by configuring the installation of the `cmake/` part and the code part of opm-common separately; and also if the downstream modules could use `-DOPM_CMAKE_ROOT=` in the configure step.

**Comment by atgeirr** [comment]
You need to specify OPM_COMMON_ROOT I think, even for a sibling build (unless the cmake macros were installed to a standard directory). At least that is how it used to work for me. If I forgot to specify it I would get the message about needing to set it etc. What is wrong in your case seems to be that it claims to have opm-common, when it has not really found it.

**Comment by joakim-hove** [comment]
> You need to specify OPM_COMMON_ROOT

Thanks - that worked; I have never been known to be a big fan of the sibling build - but I thought the sibling build feature *should* have found the opm-common module automagically in my case?

>What is wrong in your case seems to be that it claims to have opm-common, when it has not really found it.

Yes - that I agree; I have tried hard to clear all caches to avoid false positives - but there might still be something like that.

**Comment by atgeirr** [comment]
>> You need to specify OPM_COMMON_ROOT

> Thanks - that worked; I have never been known to be a big fan of the sibling build - but I thought the sibling build feature should have found the opm-common module automagically in my case?

Apparently it should. I was mistaken earlier, it looks like each CMakeLists.txt has the SIBLING_SEARCH option. Perhaps @akva2 understands why this apparently failed?

I'd like to merge this though to fix the install mode. I assume it has been sufficiently tested for that @joakim-hove?

**Comment by joakim-hove** [comment]
Yes - INSTALL has been sufficiently tested.
14. sep. 2015 08:08 skrev "Atgeirr Flø Rasmussen" <notifications@github.com>
følgende:

**Pull request merged**
