### PR TITLE
Minor refactor to monkey-patching

### PR DESCRIPTION
**Pull request by joakim-hove**
Minor refactor - to simplify additional monkey patching.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by akva2** [comment]
build was green. using this to test requested ability to build without downstreams.

**Comment by akva2** [comment]
jenkins build this no downstreams please

**Comment by akva2** [comment]
as promised @joakim-hove

**Comment by joakim-hove** [comment]
> as promised @joakim-hove

On time and budget - thank you @akva2 !

**Pull request merged**
